### ISSUE TITLE
How to distinguish which architecture a new network has?

### ISSUE THREAD

**Issue by kris-computer-go** [leela-zero/leela-zero#1066]
Do we have any other networks except 10x128, 10x192 & 20x128?
Until now it was the rule that 10x128 network's size was around 36MB, 20x128 around 79MB and 10x192 around 88MB. At the same time each next in a given architecture had a larger size than the previous one.

But 0aa3a463 network which appeared recently has a 76MB.
So which kind of network it is?

**Comment by kris-computer-go** [comment]
Maybe it would be nice if each kind of network 10x128, 10x192, 20x128 and so on has its own colour in the table on zero.sjeng.org

**Comment by jkiliani** [comment]
I would also like a way to see the net size without downloading it and loading it into leelaz... at the moment I often can only guess whether a bootstrap net is 192x10 or 128x20.

**Comment by kris-computer-go** [comment]
Oh indeed 0aa3a463 is a 10x192 as well as 0d66c88e . But how about the size?

**Comment by grolich** [comment]
It has indeed become increasingly difficult to read the graph/network list with several different architectures appearing without anything to differentiate them from one another.

Many things can help here - color coding, adding a column in the test matches table for it, or even both.

**Comment by jkiliani** [comment]
I think a column in the test match table, or in the tool tip should work. Skeptical about color coding since that is essentially already used for the SPRT result.

**Comment by Cabu** [comment]
It is true that the current graph is a complete mess from a networks point of view but does its job for the project point of view. 
In the graph, we could have multiple colored lines, one for each network size with lighter colored triangles for its fails and darker colored dots for its pass. That way we will be able to see when a network generation started and ended, which ones overlapped. And we can use thet same colors in the networks lists (best and lasts) to help see where we are in the tests...

**Comment by gcp** [comment]
Maybe just marking tests in another color would already solve a lot of confusion. If they are using a flag, I could even test against the current best betwork.

**Comment by tychota** [comment]
Would it be possible to see the architecture when hovering on top of a network, in the toolbax that show up?

**Comment by roy7** [comment]
We'd have to start storing info on the network in the database. Presently the server has no such info to show.

@gcp Want me to support a 'testonly' flag and if set to true, it'll not promote even after an SPRT pass vs best-network?

**Comment by gcp** [comment]
>@gcp Want me to support a 'testonly' flag and if set to true, it'll not promote even after an SPRT pass vs best-network?

Sounds good, especially if you can show these in a less confusing manner on the webpage.

**Comment by gcp** [comment]
>Would it be possible to see the architecture when hovering on top of a network, in the toolbax that show up?

The problem is that the server doesn't know this, and it would have to be able to parse the weights format to determine it. This isn't implemented.

**Comment by rchs819** [comment]
Just walk pass and found this old issue

- Displaying network architecture has been implemented a while ago
- Server now support test only match

Any feedback or suggestions feel free to report at gcp/leela-zero-server

**Comment by roy7** [comment]
Yeah this issue can be closed.

**Comment by sethtroisi** [comment]
This is now listed on home page
