### ISSUE TITLE
Optimisation suggestion for UCTNode

### ISSUE THREAD

**Issue by lycium** [leela-zero/leela-zero#1116]
C.f. https://github.com/gcp/leela-zero/blob/master/src/UCTNode.h#L116

I see the nodes have std::vector of pointers to child nodes, this can definitely be optimised, both for performance and storage: if you wrap the tree structure in a class (along with the base node ptr), then it has a std::vector of nodes and child indices for the whole tree, and the node's children list becomes a single index to the child-list vector.

So when you make a new node, you get the current size() of the nodes vector, then push_back on the vector with the new node. Similarly when you want to create the child nodes vector, you get the current size() of the child-nodes-list vector, and push_back N times for each child node index.

This helps in several ways:

1. Cache locality, since all the nodes will be contiguous in memory

2. Reduced storage, since child refs are 32bit instead of 64bit (also reduces cache pressure a lot)

3. Much better runtime speed, since allocating new nodes doesn't go through a system call (malloc) most of the time. (Meltdown/Spectre mitigation patches have made that extra expensive these days.) You can reserve() a bunch of nodes so that it basically never does a realloc.

**Comment by gcp** [comment]
(3) isn't much of an argument. Either you preallocate a lot of ahead, and you waste memory (which is a concern), or you don't, and you lose the benefit. Memory allocation is also not something that is showing up in profiles AFAIK.

(2) May or may not be an advantage, see current issues about optimizing the tree.

There are also problems with having raw UCTNodes in a vector, because it contains atomics.

**Comment by lycium** [comment]
Thanks for your reply, and sorry for the duplicate. Something can be done about the atomics access (eg keeping a fixed bunch of atomics and using modulo), but overall I understand it would be a major change and it's difficult to motivate.

I still think there are some big gains to be had with this approach, but will have to do some MCTS experiments first to get some numbers.

Thanks for your work on Leela Zero!

**Comment by gcp** [comment]
>sorry for the duplicate

It wasn't, I hadn't read correctly what you proposed.

>eg keeping a fixed bunch of atomics and using modulo on the node index, because the number of locks should be proportional to parallel threads not number of nodes

Someone wrote code for this already, but it had the same problem that it added a ton of complexity for unclear gain.
