### ISSUE TITLE
AutoGTP doesn't show used network on connection failure

### ISSUE THREAD

**Issue by l1t1** [leela-zero/leela-zero#1122]
Got new job: selfplay
Network connection to server failed.
NetworkException: Curl returned non-zero exit code 18
Retrying in 45 s.
{
    "cmd": "selfplay",
    "hash": "e9c2c70b9346f18d9cbaa2bc2a6000556723d9b42ef4c8461d4b909e63d38f67",
    "leelaz_version": "0.12",
    "options": {
        "noise": "true",
        "playouts": "0",
        "randomcnt": "30",
        "resignation_percent": "10",
        "visits": "3200"
    },
    "options_hash": "a4325b",
    "random_seed": "8639753463589418967",
    "required_client_version": "14"
}

Got new job: selfplay
Network connection to server failed.
NetworkException: Curl returned non-zero exit code 18
Retrying in 67 s.
Maximum number of retries exceeded. Falling back to previous network.
Engine has started.
Infinite thinking time set.
1 (B C16) 2 (W R4) 3 (B C4) 4 (W Q16) 5 (B R17) 6 (W Q17) 7 (B R16) 8 (W R15) 9 (B S15) 10 (W S14) 11 (B R14)

**Comment by alreadydone** [comment]
@marcocalignano It could be better for autogtp to show the leelaz command. (I remember it did so some time ago...)

**Comment by l1t1** [comment]
finished.
 562 (W D17) 563 (B P18) 564 (W F5) 565 (B B17) 566 (W pass) 567 (B Q19) 568 (W pass) 569 (B pass) Game has ended.
Score: W+78.5
Winner: white
Uploading game: e39e34b4b5d44814a48321a9b3bdff99.sgf for network [b]4c7dd084662bfe356e572d2dca033a8e0dd30d1542bb252083ffc89
9cdbcb52e[/b]
Game data 502de7f89290b5721b52f9adad3e82dc3a5c937d4ea828be4e7b29dfb3546e37 stored in database
63 game(s) (63 self played and 0 matches) played in 5952 minutes = 5669 seconds/game, 23148 ms/move, last game took 5026
8 seconds.

**Comment by rchs819** [comment]
The task assigned was selfplay for network hash 
```
e9c2c70b9346f18d9cbaa2bc2a6000556723d9b42ef4c8461d4b909e63d38f67
```

However,
```
Network connection to server failed.
NetworkException: Curl returned non-zero exit code 18
Retrying in 67 s.
Maximum number of retries exceeded. Falling back to previous network.
```
It looks like you had trouble fetching the network, so it falls back to previous network
which is
```
4c7dd084662bfe356e572d2dca033a8e0dd30d1542bb252083ffc89
```

**Comment by l1t1** [comment]
but training an  older network is useless.

**Comment by d7urban** [comment]
Why would it be useless? It is still used.

**Comment by alreadydone** [comment]
It's unlikely but possible that the OP also failed to download the previous network ...

**Comment by sethtroisi** [comment]
closing, no active discussion for ~1year
