### ISSUE TITLE
Adaptive resign threshold

### ISSUE THREAD

**Issue by Dorus** [leela-zero/leela-zero#1139]
The current 92 move limit for resigns doesn't work. 1) it works terrible on games that are lost early (like ladder games), many self play and match games are extended unnecessary. 2) it works terrible on handicap games, if LeelaZ doesn't make a huge profit the first 92 moves it will resign, even while people that play handicap games often give away points later in the game, those that play high handicap often give points early game but also all the way in the endgame.

I propose adaptive resign threshold:

Set a resign threshold as normal (like 30%)
Set a adaptive threshold (like 10%)

During the game, track the win %. Auto set the resign threshold to (max win%-adaptive threshold).

For example, a handicap game might start at 2% winrate and will not resign. But after 50 moves the winrate is 12%, and resign will be 2%. Some time later, winrate is up to 35% and adaptive resign will be 25%. Now a few moves later winrate drops back down again to 26% and adaptive resign will stay at 25%, one more move, winrate goes below 25% and LeelaZ resigns.

On the other hand, if winrate goes up to 41%, it swill stick to the 30% normal resign threshold and not increase it future.

It might be required to add another safeguard so games do not go on forever. The adaptive resign threshold could be scaled with game length, so not only do you set a % but also a number (like 300), and every move the adaptive resign threshold is decreased by 1/300th and eventually disabled at move 300.

This should probably be a command line argument, but with adaptive resign, it might be possible to remove the 92 move limit for resigns on self play and match games, so that will be a small profit too.

**Comment by Mardak** [comment]
Pretty sure @gcp has previously questioned if the 92 move threshold should be around anymore for leelaz and that it was mainly added for leela to avoid some bugs / complaints:
https://github.com/gcp/leela-zero/blob/97c2f8137a3ea24938116bfbb2b0ff05c83903f0/src/UCTSearch.cpp#L251-L257

There does seem to be existing code to adjust the resign threshold with handicap:
https://github.com/gcp/leela-zero/blob/97c2f8137a3ea24938116bfbb2b0ff05c83903f0/src/UCTSearch.cpp#L270-L283

Although those handicaps incremented with `set_free_handicap <position>`. @Dorus how are the handicap games started?

**Comment by gcp** [comment]
>Pretty sure @gcp has previously questioned if the 92 move threshold should be around anymore for leelaz and that it was mainly added for leela to avoid some bugs / complaints

It was added to avoid resigning in handicap games, and it may not be necessary in LZ any more because *it already has adaptive resigning*.

Almost everything @Dorus asks for is already implemented, as far as I know? Do you have any specific handicap games that show issues with the current adaptive resignation system?

**Comment by gcp** [comment]
See pull request #626 which was based on issue #622.

**Comment by Dorus** [comment]
@gcp Oh this is already in? Well i tried a 9h handicap game vs a LeelaZ bot on KGS and it resigned at i think 92 moves.

Do the bot authors need to do anything special to activate this? Or is it only in the dev version?

I believe the bot i played was heavily modified so it might not have all patches etc.

**Comment by WhiteHalmos** [comment]
This has been in a long time. Look under the code for the 92 threshold.

**Comment by Dorus** [comment]
I checked back, my handicap game started with 9 stones placed by kgs. It resigned at move 82 where winrate just wend up to 1% (or 0.01%, that's what the bot owner said but idk if that's even possible).

The way i read the code, it already has the second safe guard where it slowly increase the resign threshold for 215 moves, but i do not see the part where it will not surrender as long as win % is increasing over multiple moves.

My idea was to let LeelaZ not resign unless win% drops.

**Comment by Mardak** [comment]
I found this OGS game https://online-go.com/game/12275021 where there's 4 handicap, and RoyalZero resigns after move 92 with `Variation: 0.1% 751/3041 visits`. It's using the default 10% threshold, and with 4 handicap, the minimum handicap threshold is 2%, and the blended threshold for this move is around 5%.

At least from RoyalZero's comment history, the highest eval was ever 0.4%, so removing the 92 limit won't quite work by itself as it would try to resign for an eval under 2%. Even if RoyalZero was run with `--resignpct 1`, with 4 handicap, the minimum handicap threshold is 0.2%, which looks to happen before move 20 in this game.

@Dorus you're right that the code does not implement your proposed "adaptive resign threshold" but it does have a "dynamic handicap-adjusted resign threshold." Although I'm not sure how useful it will be if implemented as your example has win rate going up to 41%, but with such a high handicap, quite likely eval will be close to 0.00% all game, e.g., https://online-go.com/game/12276810 and your game with 0.01%.

**Comment by roy7** [comment]
It occurs to me from https://github.com/online-go/gtp2ogs/issues/65 that since I don't use set_free_handicap on games at OGS usually, LZ might never know the correct handicap when doing the adaptive resign calculations?

Since set_free_handicap needs a full list of all stones to place, but stones in Chinese are placed one at a time anywhere on the board, I'm unclear on how to handle that on the gtp2ogs level. I think the way it currently operators for bots at OGS is they get move info as moves are placed, and gtp2ogs just does a 'play' command to place that stone with the bot. When handicap placements are done, 'genmove' is asked for for bot's move.

set_free_handicap is used when setting a game back up though after handicap placements are completed when resuming an old game.

**Comment by gcp** [comment]
>Since set_free_handicap needs a full list of all stones to place, but stones in Chinese are placed one at a time anywhere on the board, I'm unclear on how to handle that on the gtp2ogs level.

Cache the stones, and when the first move for LZ arrives, do the set_free_handicap at that point?
