### ISSUE TITLE
Impact of amount of graphics memory

### ISSUE THREAD

**Issue by d7urban** [leela-zero/leela-zero#1141]
My graphics card has a relatively small memory at 3Gb. What, if any, effects does that have on running self plays? I'm thinking of upgrading soonish, would there be any advantage to having more graphics memory with regard to running LeelaZero? Would perhaps larger, future networks be affected?

**Comment by bastiaf** [comment]
I use these arguments:
`--gtp --threads 8 --noponder --weights networks/2e3863edbb0e18f198e2e76d50529931c17f17f01c7468c992afd9b33f4d5379`

For the threads parameter the number of CPU cores works fine for me. You can also test which number of threads give you the best result by calling leelaz with the benchmark option:
./leelaz.exe --benchmark --weights networks/2e3863edbb0e18f198e2e76d50529931c17f17f01c7468c992afd9b33f4d5379 --threads 8

Additionally you can add an initial GPG command in Sabaki, for example to define some time settings:
`time_settings 0 30 1`
(0 seconds main time, 30 seconds byoyomi, 1 period)

**Comment by Friday9i** [comment]
If you don't want to slow down your PC too much, take the number of cores minus 1 for the --threads (ie "--threads 3" if you have a quad-core PC). Otherwise, it's quite painful...

**Comment by d7urban** [comment]
These are both fine advices, but not exactly what I was after. What I wondered was if, when I upgrade my graphics card, I should go for more memory or if the amount of memory doesn't matter much with regards to running autogtp/leelaz with large NNs.

**Comment by bastiaf** [comment]
The graphic memory should not be a problem. I just tested it, the 20x256 network needs about 1GB, so even for an engine vs engine game 2GB are enough.

(Firefox takes another GB, but maybe it is more restrained if the graphic memory is smaller.)

**Comment by gcp** [comment]
The networks are fairly small (compared to game textures) and you're unlikely to run into problems there with any modern discrete card.

**Comment by sethtroisi** [comment]
closing, no active discussion for ~1year with answer from gcp
