### ISSUE TITLE
Compile and run on RedHat

### ISSUE THREAD

**Issue by panda0307** [leela-zero/leela-zero#1181]
I have a simple question.

There are some differences between Ubuntu and RedHat.
How to compile and run LZ on RedHat systems?

Thanks.

**Comment by thynson** [comment]
I've successfully compiled leela-zero on my Fedora workstation; for RHEL7 and before it should be the same, I'm not sure whether it works on RHEL 6 or older version.
You just need to install cmake, qt5-base-devel, boost-devel, openblas-devel, and opencl-headers. And then follow the instructions in README.
