### ISSUE TITLE
Next branch with Lizzie support and thread-safe fix

### ISSUE THREAD

**Issue by Ka-zam** [leela-zero/leela-zero#1207]
I have merged @ihavnoid 's thread-safe fix and my own Lizzie fix here:
https://github.com/Ka-zam/leela-zero/tree/next_lizzie

I would be interested to have someone test this on Windows since I'm only on Linux myself.

**Comment by sbf2000** [comment]
Good！ I tested on Windows10, It won't crash like it was and support Lizzie well 。

**Comment by isty2e** [comment]
Could you make a PR with the lizzie fix? It will be much easier to use the next branch with lizzie in the future.

**Comment by Ka-zam** [comment]
No, can't really do that since it changes the ponder method and that's not helpful for general use. It could be a special command that enables that functionality though.

**Comment by afalturki** [comment]
Yeah seems like adding the change as a togglable option in LZ is the way to go.

**Comment by Ka-zam** [comment]
I've noticed instability with Lizzie as well when doing undo/redo in quick succession. Seems to be something wrong in the UCTNodePointer class. But this is being investigated right now and we should wait for a stable atomic pointer class until getting more functionality in.

**Comment by Ka-zam** [comment]
Resolved, it seems. My branch has been updated.
