### ISSUE TITLE
PUCT + FPU tuning run

### ISSUE THREAD

**Issue by gcp** [leela-zero/leela-zero#1211]
I was on holidays and let one of my machines do a new PUCT + FPU optimization run with CLOP. I think @Eddh raised the question earlier whether FPU was tuned before the sqrt_totalvp algorithm was merged. It might've been before the merge, so I ran this just in case.

PUCT optimal is between 0.55 and 1.1, estimated max = 0.75
FPU reduction optimal is between 0.2 and 0.4, estimated max = 0.3

Estimated Elo gain from tuning << 10 Elo.

This is extremely close to our current values and it seems unlikely that any improvement could be measurable, so I'll leave the current values be.

**Comment by samecos** [comment]
Eum,Interesting,I think other size nn should be different hyper parameters. Let me try with 256fx20B network.

**Comment by gcp** [comment]
>I think other size nn should be different hyper parameters

These parameters have been optimal as long ago as several size increases, so evidence is strongly against your claim.

**Comment by sethtroisi** [comment]
closing, no active discussion for ~1year
