### ISSUE TITLE
A New GUI for Leelaz with Alphago Master's opening library

### ISSUE THREAD

**Issue by MingWR** [leela-zero/leela-zero#1219]
I made a GUI for Leela Zero. Only Wiindows version is available now.<br>
I know everyone loves sabaki, but it doesn't support opening book. If you want to change the time setting during a game, you have to do it with gtp command. I feel this isn't very convenient, so I made a gui specifically for Leela Zero.<br>
Here is the link of my app: https://github.com/MingWR/iceelz<br>
I hope you like it.

**Comment by l1t1** [comment]
good job

**Comment by l1t1** [comment]
300M, why the exe file is so big.

**Comment by hydrogenpi** [comment]
Can your gui do tournament games like what Gomill ringmaster does? (on Windows, since that other tool is only on Linux)

**Comment by pcengine** [comment]
Could you please tell us how to use opening book? I can't find any instructions related to opening book in your readme file.  Is there a command or something to tell the app to use opening book?

**Comment by pcengine** [comment]
@MingWR Do we need to download the alphago opening book and put it under the same directory? Or the alphago opening book is already built in this app?

**Comment by MingWR** [comment]
@pcengine No, you don't need. The gui come with the opening book. I give link of the sgf just to show where I get the data.

**Comment by sethtroisi** [comment]
closing, no active discussion for ~1year
