### ISSUE TITLE
Weird results 128x10 vs 192x15 (1x1080Ti)

### ISSUE THREAD

**Issue by StanTraykov** [leela-zero/leela-zero#1222]
I got some interesting test results from LZ 0.13 (win64 binary) that may hopefully be of some use for debugging. May be related to the race condition in #1161 and/or the time management issues.

The nets I tested are:
* **LZ39** — the last (promoted) 128x10 net (**number 116**, 39d46507)
* **LZba** — the first 192x15 net (**number 117**, ba748d40)
* **LZc0** — the sixth (promoted) 192x15 net (**number 122**, c0cb605b)

### 1st test: 4s, no ``--timemanage`` switch supplied

At first, I just wanted to run a time-based (4s/move) test to see how the last 10-block and the first 15-block compare, and also how much the sixth 15-block had progressed.

LZba (1st 15b) beat LZ39 (last 10b) handily (65.0% from 160 games). I didn't have any particular expectations for this match, but what surprised me was the next result in relation to it: LZc0 (6th 15b) beat LZ39 by approx. the same amount--65.9% from 132 games. I also ran another match using the same parameters, LZc0 vs LZba (6th vs 1st 15b), which LZc0 won with 66.3% from 202 games.

<details>

```
LZba vs LZ39 -- 4s/m -- with time mgmt (--timemanage omitted)
                   160 games, total moves   33680, avg 210.5, min  96, max 355
          W   B  total wins   wins as W   wins as B  avg t/mv  max t/mv  viols
LZba74:  80  80 104 [65.0%]  56 [70.0%]  48 [60.0%]    1.766s    3.111s  0/  0
LZ39d4:  80  80  56 [35.0%]  32 [40.0%]  24 [30.0%]    1.706s    4.693s  1/  1
bad wins, being the first to violate time: LZba74  0; LZ39d4  0
total time thunk: LZba74: 8:17:39; LZ39d4: 8:01:30

LZba74 vs LZc0 -- 4s/m ---- with time mgmt (--timemanage omitted)
                   202 games, total moves   45417, avg 224.8, min  92, max 351
          W   B  total wins   wins as W   wins as B  avg t/mv  max t/mv  viols
LZba74: 101 101  68 [33.7%]  37 [36.6%]  31 [30.7%]    1.717s    5.132s  1/  2
LZc0cb: 101 101 134 [66.3%]  70 [69.3%]  64 [63.4%]    1.705s    3.147s  0/  0
bad wins, being the first to violate time: LZba74  0; LZc0cb  0
total time thunk: LZba74: 10:53:18; LZc0cb: 10:47:36

LZc0 vs LZ39 -- 4s/m -- with time mgmt (--timemanage omitted)
                   132 games, total moves   27549, avg 208.7, min  92, max 371
          W   B  total wins   wins as W   wins as B  avg t/mv  max t/mv  viols
LZc0cb:  66  66  87 [65.9%]  45 [68.2%]  42 [63.6%]    1.779s    3.288s  0/  0
LZ39d4:  66  66  45 [34.1%]  24 [36.4%]  21 [31.8%]    1.698s    3.913s  0/  0
bad wins, being the first to violate time: LZc0cb  0; LZ39d4  0
total time thunk: LZc0cb: 6:50:09; LZ39d4: 6:32:05
```
</details>

### 2nd test: fixed visits (3201)

I wanted to investigate this further--why didn't LZc0 win by a much larger margin against LZ39? I ran two matches with fixed visits (3201) just to make sure I agree with the results on zero.sjeng.org and to see that the newer 15b net does indeed much better. The results were LZba vs LZ39: 81.5% from 146 games (cf. result on zero.sjeng.org, 86.7%) and LZc0 vs LZ39: 92.2% from 140 games.

<details>

```
LZba vs LZ39 -- 3201 visits --
                    146 games, total moves   27947, avg 191.4, min  92, max 332
           W   B  total wins   wins as W   wins as B  avg t/mv  max t/mv  viols
LZbaV32:  72  74 119 [81.5%]  62 [86.1%]  57 [77.0%]    1.095s    3.138s  0/  0
LZ39V32:  74  72  27 [18.5%]  17 [23.0%]  10 [13.9%]    0.459s    1.396s  0/  0
bad wins, being the first to violate time: LZ39V32  0; LZbaV32  0
total time thunk: LZ39V32: 1:47:43; LZbaV32: 4:15:50

LZc0 vs LZ39 -- 3201 visits --
                    140 games, total moves   27222, avg 194.4, min  99, max 389
           W   B  total wins   wins as W   wins as B  avg t/mv  max t/mv  viols
LZc0V32:  70  70 130 [92.9%]  67 [95.7%]  63 [90.0%]    1.125s    3.339s  0/  0
LZ39V32:  70  70  10 [ 7.1%]   7 [10.0%]   3 [ 4.3%]    0.467s    1.469s  0/  0
bad wins, being the first to violate time: LZ39V32  0; LZc0V32  0
total time thunk: LZ39V32: 1:46:39; LZc0V32: 4:16:02
```
</details>

### 3rd test: 4s, with ``--timemanage=off``

Wondering what was going on, I decided to test with the same 4s/move time controls but with time management turned off (as bugs with it were recently discussed) and, lo and behold, things studdenly looked very different. LZba won 60.9% against LZ39, while LZc0 got a <del>whopping 96.2%</del> better result with 82.5%!

<details>

```
LZba vs LZ39 --  4s/m -- without time mgmt (--timemanage=off)
                     128 games, total moves   26592, avg 207.8, min 108, max 380
            W   B  total wins   wins as W   wins as B  avg t/mv  max t/mv  viols
LZba-TMO:  64  64  78 [60.9%]  41 [64.1%]  37 [57.8%]    3.072s    3.495s  0/  0
LZ39-TMO:  64  64  50 [39.1%]  27 [42.2%]  23 [35.9%]    3.180s    7.200s 35/ 49
bad wins, being the first to violate time: LZ39-TMO 14; LZba-TMO  0
total time thunk: LZ39-TMO: 11:48:29; LZba-TMO: 11:23:39

LZc0 vs LZ39 -- 4s/m -- without time mgmt (--timemanage=off)
                     154 games, total moves   31566, avg 205.0, min  92, max 622
            W   B  total wins   wins as W   wins as B  avg t/mv  max t/mv  viols
LZc0-TMO:  77  77 127 [82.5%]  65 [84.4%]  62 [80.5%]    3.073s    4.300s  0/  1
LZ39-TMO:  77  77  27 [17.5%]  15 [19.5%]  12 [15.6%]    3.184s    8.292s 53/ 88
bad wins, being the first to violate time: LZ39-TMO  7; LZc0-TMO  0
total time thunk: LZ39-TMO: 14:02:50; LZc0-TMO: 13:30:55
```
</details>

### Time violations

But there's also another anomaly you may have noticed in the third test above. The 10b net exceeded time controls a large number of times. My guess is that this is due to some bug(s) in the engine, which coincidentally cause more harm with 128x10 than 192x15 (and may be related to the total number of playouts per move).

I also calculated the winrates for the 3rd test with all the games with time violations removed, but the winrate didn't change much (winrate normalized = (W winrate + B winrate)/2).

<details>

```
LZ39 vs LZba --  4s/m -- without time mgmt (--timemanage=off) -- TIME VIOL'S REMOVED
                      93 games, total moves   18866, avg 202.9, min 109, max 380 WR NORMALIZED
            W   B  total wins   wins as W   wins as B  avg t/mv  max t/mv  viols ------------- 
LZba-TMO:  41  52  57 [61.3%]  27 [65.9%]  30 [57.7%]    3.071s    3.366s  0/  0   [61.8%]
LZ39-TMO:  52  41  36 [38.7%]  22 [42.3%]  14 [34.1%]    3.173s    3.986s  0/  0
bad wins, being the first to violate time: LZ39-TMO  0; LZba-TMO  0
total time thunk: LZ39-TMO: 8:21:30; LZba-TMO: 8:05:03

LZ39 vs LZc0 -- 4s/m -- without time mgmt (--timemanage=off) -- TIME VIOL'S REMOVED
                     101 games, total moves   20007, avg 198.1, min 104, max 321 WR NORMALIZED
            W   B  total wins   wins as W   wins as B  avg t/mv  max t/mv  viols -------------
LZc0-TMO:  46  55  81 [80.2%]  37 [80.4%]  44 [80.0%]    3.072s    3.483s  0/  0   [80.2%]
LZ39-TMO:  55  46  20 [19.8%]  11 [20.0%]   9 [19.6%]    3.175s    3.999s  0/  0
bad wins, being the first to violate time: LZ39-TMO  0; LZc0-TMO  0
total time thunk: LZ39-TMO: 8:52:46; LZc0-TMO: 8:34:01

```
</details>

### Command lines

Here are the command lines I used (I have also time/stderr/SGF logs, available on request).

<details>

```
[LZc0cb]
wkDir=C:\Users\Stan\LZ\fulltune-c0cb60
cmd=leelaz -g -t11 --noponder -w c0cb60.txt -l lz-c0cb60.log
quiet=on

[LZ39d4]
wkDir=C:\Users\Stan\LZ\fulltune-39d465
cmd=leelaz -g -t11 --noponder -w 39d465.txt -l lz-39d465.log
quiet=on

[LZba74]
wkDir=C:\Users\Stan\LZ\fulltune-ba748d
cmd=leelaz -g -t11 --noponder -w ba748d.txt -l lz-ba748d.log
quiet=on

[LZc0V32]
wkDir=C:\Users\Stan\LZ\fulltune-c0cb60
cmd=leelaz -v3201 -g -t11 --noponder -w c0cb60.txt -l lz-c0cb60.log
quiet=on

[LZ39V32]
wkDir=C:\Users\Stan\LZ\fulltune-39d465
cmd=leelaz -v3201 -g -t11 --noponder -w 39d465.txt -l lz-39d465.log
quiet=on

[LZbaV32]
wkDir=C:\Users\Stan\LZ\fulltune-ba748d
cmd=leelaz -v3201 -g -t11 --noponder -w ba748d.txt -l lz-ba748d.log
quiet=on

[LZc0-TMO]
wkDir=C:\Users\Stan\LZ\fulltune-c0cb60
cmd=leelaz --timemanage off -g -t11 --noponder -w c0cb60.txt -l lz-c0cb60.log
quiet=on

[LZ39-TMO]
wkDir=C:\Users\Stan\LZ\fulltune-39d465
cmd=leelaz --timemanage off -g -t11 --noponder -w 39d465.txt -l lz-39d465.log
quiet=on

[LZba-TMO]
wkDir=C:\Users\Stan\LZ\fulltune-ba748d
cmd=leelaz --timemanage off -g -t11 --noponder -w ba748d.txt -l lz-ba748d.log
quiet=on

```
</details>
<p></p>

**Edit: The 3rd test, second run (LZ39 vs LZc0), initially contained wrong results which have now been corrected in place.**

**Comment by Friday9i** [comment]
Just a suggestion to follow you more easily:
LZ39 — the last (promoted) 128x10 net (39d46507) : it's LZ116 (ie network #116)
LZba — the first 192x15 net (ba748d40): it's LZ117
LZc0 — the sixth (promoted) 192x15 net (c0cb605b): it's LZ122
Simple and easy to follow ; -)

**Comment by StanTraykov** [comment]
Ah, thx, good idea, will add them when the test correction is complete (overnight).

**Comment by StanTraykov** [comment]
Updated with corrected results for the last run. In summary:
* **with time management on**, the 1st and 6th 192x15 promoted nets perform similarly well against the last 128x10 net (win rate around 65%). This is surprising, as the 6th net should be stronger.
* **with time management off**, the WRs are much further apart: 82.5% and 60.9%.
* There are a lot of time violations for the 128x10 net (but not so many for 192x15). (This is probably related to the race condition?)

**Comment by MaxMaki** [comment]
@roy7 @gcp If timemanage is causing an effect where it's making the new networks weaker than against the old ones maybe it should be disabled at least temporarily in match games?

**Comment by gcp** [comment]
Given that OP is saying he's getting losses on time I would conclude absolutely nothing from this.

**Comment by StanTraykov** [comment]
> Given that OP is saying he's getting losses on time I would conclude absolutely nothing from this. (The matches are fixed visit, not fixed time).

While nothing can be concluded for fixed-visit strength, I think the results do show that ``--timemanage on`` (which we already know to cause strength drop) is more negatively affecting larger networks than smaller ones. (Unless, of course, all results in my setup are skewed due to the bug.) Also, just a clarification: the engines were monitored but not penalized for exceeding time, so there were no wins by time.

**Comment by gcp** [comment]
>--timemanage on (which we already know to cause strength drop)

No, we do not?

**Comment by StanTraykov** [comment]
Initially, I was just testing two 192x15 nets (nos. 1 and 6) vs the last 128x10 with fixed time per move[1]. This was out of curiosity, but then I got the weird result of no. 6 not performing better against the 10b. Removing time management "fixed" this. If there are some other tests that would be of better use--I'd be happy to run some. (Right now trying to see if #1224 fixes the bug.)

[1] "time_settings 0 4 1" = 4 seconds for 1 stone Canadian, equivalent to 1x4s Japanese.

**Comment by gcp** [comment]
4 seconds for 1 stone is will cause the same problem as for Japense byo yomi. You can never save time by moving quickly, so time management will indeed strictly make things worse.

**Comment by gcp** [comment]
>In the first post

Probably better to read the last ones!

**Comment by gcp** [comment]
>match games are fixed visits, so if it indeed makes it weaker at 3200 visits, then shouldn't it be off for matches?

It makes it stronger:
https://github.com/gcp/leela-zero/pull/968#issuecomment-370189810

**Comment by sethtroisi** [comment]
closing, no active discussion for ~1year
