### ISSUE TITLE
Example on how to compile autogtp on macOS

### ISSUE THREAD

**Issue by agugglez** [leela-zero/leela-zero#1227]
autogtp README shows Ubuntu and Windows/Visual Studio examples on how to install qt packages and compile the autogtp tool. A similar macOS version would be appreciated.

**Comment by gcp** [comment]
The README already has an example for macOS as well: https://github.com/gcp/leela-zero#example-of-compiling-and-running---macos

**Comment by agugglez** [comment]
I mean the autogtp part which uses qt.

**Comment by gcp** [comment]
Probably brew install qt5 and then the same as for Unix?

**Comment by bood** [comment]
Yes, I can confirm.

`brew install qt5` will install qt5 in `/usr/local/opt/qt/bin` directory.

**Comment by agugglez** [comment]
I tried that without success. Maybe because my xcode (8.3.3) is outdated??

**Comment by gcp** [comment]
"without success" is a bit vague to find out what is wrong.

**Comment by agugglez** [comment]
I tried with "brew install qt" the first time which I don't think makes any difference with "qt5". It started to download a "bottle" from "homebrew.bintray.com" and at some point it gave a "SSL connection error" and the download stopped (maybe this was related to a slow internet connection). Then brew tried to install it from source (downloading some "qt-everywhere" package) and then it hangs when running a "./configure" script to finish the installation. In "Monitor" I could see there were lots of "clang" processes running and consuming a lot of CPU so I suspected it had something to do with Xcode. I tried again with "brew install qt5" and thankfully the "bottle download" continued from where it stopped at over 90% and it worked perfectly.

**Comment by zinwalin** [comment]
Just to elaborate for anyone who finds that after installing qt5, can't access qmake in the terminal.

Install QT5 using:

brew install qt5
Then to allow access qmake from the terminal you'll need to run:

brew link qt5 --force


then go to autoatp folder, and

qmake

make

**Comment by sethtroisi** [comment]
closing, no active discussion with newer instructions in README
