### ISSUE TITLE
Lizzie (Leela Zero Interface) version 0.4 is released

### ISSUE THREAD

**Issue by featurecat** [leela-zero/leela-zero#1239]
I'm not sure if it's fine for me to advertise it here, but I just released version 0.4 of Lizzie. It's a really useful tool to analyze / play games with Leela Zero. It's also open source if anyone would like to contribute :)

https://www.reddit.com/r/baduk/comments/8e9b9q/lizzie_leela_zero_interface_04_is_released/

**Comment by Marcin1960** [comment]
Is it possible to build 32bit version?

**Comment by featurecat** [comment]
I need someone to help me figure out how to compile 32 bit version. if you know how, just add my branch's UCTSearch.cpp file to Leela release and compile. it will work.

**Comment by Marcin1960** [comment]
Open clean sources separately In Visual Studio, Change solution/project to Win32 everywhere. Remove autogtp project. In leela-zero project menu use NuGet packages, get zlib-msvc-x86, (remove 64 zlib) etc ...

Here is my thread on Win32 version:
https://github.com/gcp/leela-zero/issues/1103

**Comment by d7urban** [comment]
How do I use the ELF weights in Lizzie? 0.4 won't open if I specify that weight file.

**Comment by featurecat** [comment]
For now, just use Ka-zam's version until I make an official release of Lizzie 0.5 github.com/Ka-zam/leela-zero

**Comment by sethtroisi** [comment]
closing, no active discussion
