### ISSUE TITLE
autogtp crashes

### ISSUE THREAD

**Issue by Manslay** [leela-zero/leela-zero#125]
It just crashes, telling me it has played 1 game which took about 5-10 seconds or so.

**Comment by gcp** [comment]
What does "it just crashes" mean exactly?

**Comment by Manslay** [comment]
Running it on Win10

**Comment by Manslay** [comment]
Win10 says that autogtp has stopped working and then that leelaz.exe doesn't work

**Comment by Manslay** [comment]
Exception c0000409 at offset 000788c2

**Comment by Manslay** [comment]
leelaz.exe crashes when I type "genmove b", providing weights file of course

**Comment by leehiufung911** [comment]
Having same problem

**Comment by damonmaster** [comment]
I use win10,  It shows that ”Engine has started” and then crashed

**Comment by SuJinpei** [comment]
seems same problem, here is my output:
```
>autogtp.exe
autogtp v2
Best network hash: 1ac2638de9d4d3f9eef43f2afb6b1b4c090a7c350fde4d2d77e00e39eba6fde0
Required client version: 2 (OK)
curl.exe -s -O -J -w %{filename_effective} http://zero.sjeng.org/best-network
Curl filename: 1ac2638de9d4d3f9eef43f2afb6b1b4c090a7c350fde4d2d77e00e39eba6fde0.gz

gzip: 1ac2638de9d4d3f9eef43f2afb6b1b4c090a7c350fde4d2d77e00e39eba6fde0.gz: unexpected end of file
Net filename: 1ac2638de9d4d3f9eef43f2afb6b1b4c090a7c350fde4d2d77e00e39eba6fde0
Engine has started.
*ERROR*: The 'leelaz' process died unexpected.
Infinite thinking time set.
1 games played.
```

**Comment by gcp** [comment]
>unexpected end of file

The download failed. Delete that file and try again. (I believe the next update will be able to recover automatically from this)

**Comment by SuJinpei** [comment]
latest release(Leela Zero 0.6 + AutoGTP v4) runs good.

**Comment by Phelanpt** [comment]
Just had a crash in the middle of playing a game:
![autogtp crash](https://user-images.githubusercontent.com/33914906/33236438-70ba2094-d24b-11e7-8281-b1936b2fa761.png)

Didn't get anything else besides a sudden crash. Seems to be running fine after relaunching it.

**Comment by Phelanpt** [comment]
Another crash in a similar way. Does anyone know how to get more information from autogtp, something I could upload here when it crashes?
![autogtp crash 2](https://user-images.githubusercontent.com/33914906/33568578-d546f206-d91e-11e7-8151-78b0fc2fb134.png)

**Comment by HenryHo2006** [comment]
Another Crash, Win7 64bit
![crashv7](https://user-images.githubusercontent.com/14534015/33752999-0aafa268-dc20-11e7-8200-294c91427083.png)

**Comment by HenryHo2006** [comment]
![crash2](https://user-images.githubusercontent.com/14534015/33753034-304ac6ec-dc20-11e7-953d-7fd5bc1b9ee4.png)

**Comment by bood** [comment]
Integrating with some crash report tool could be helpful,  e.g. https://github.com/google/breakpad

@gcp @marcocalignano Any experience with this?

**Comment by gcp** [comment]
No interest from my side. Majority of crashes are going to be bad drivers & bad or overclocked hardware.
