### ISSUE TITLE
how does autogtp server to identify a client

### ISSUE THREAD

**Issue by l1t1** [leela-zero/leela-zero#1250]
if many client bebinds a proxy server, can  each  one be identifid?

**Comment by Cabu** [comment]
Should autogp send the computer name with the results? That way we will have one more datapoint to sort the bad from the good results.

**Comment by gcp** [comment]
No, absolutely not. I don't want anything remotely resembling personal information in the database.

**Comment by hydrogenpi** [comment]
@Cabu the problem imo is open source there is nothing stopping someone to compile a client that strips that ID info before sending to server unless of course server side mandated and enforced secured authentication and credentials etc. Though a compromise would be a dual tier system and trusted and untrusted contribution pools. 

Computer name wouldn't be enough, also would like to have IP address, MAC address of the NIC, and other detailed specs like OS, driver info, hardware arch, etc etc etc

**Comment by nathanloop** [comment]
When seti@home introduced leaderboards cheating immediately followed. They then had to implement work verification to combat cheating. It wouldn't be trivial to do and the benefits would be questionable at best.

**Comment by eaglgenes101** [comment]
AFAIK with machine learning, getting a small amount of bad data is a fact of life when it comes to collecting data from the open to train on. Unless there's a systematic pattern to the bad data, there's too much of it, or there's overfitting, the learning system generally just implicitly writes the bad data off as exceptions to the general rule. 

If worse came to worst we could start requiring contributors to digitally sign their contributions, and scrutinize contributors for bad play, but with >99% of contributors to Leela Zero being honest, I don't think that's something that needs to be considered anytime soon.

**Comment by rchs819** [comment]
To really answer the question:

## how does autogtp server identify a client
The server identifies a client by its IP address.

## if many clients behind a proxy server, can each one be identified?
No, not at all. 
They will be treated as one client, because all of them would have the same IP address.

**Comment by sethtroisi** [comment]
closing, no active discussion for ~1year
