### ISSUE TITLE
Leelaz win 3rd Place at 2018 AI  Go Competition 

### ISSUE THREAD

**Issue by l1t1** [leela-zero/leela-zero#1271]
but I upload failed.
see
game1 http://duiyi.sina.com.cn/gibo_new/live/viewer.asp?sno=6
game2 http://duiyi.sina.com.cn/gibo_new/live/viewer.asp?sno=12

https://www.twitch.tv/jroy7/

does anybody know why https://github.com/gcp/leela-zero/issues/1270 post is disapear?
there was more live links

**Comment by higherdim** [comment]
LZ > Golios
LZ >  DolBaram 
LZ vs TBD

**Comment by higherdim** [comment]
LZ(left) vs Golios
[http://n.sinaimg.cn/sports/2_img/upload/58ce4c36/783/w950h633/20180427/NeJq-fztkpip0341099.jpg](url)

**Comment by l1t1** [comment]
leelaz lost round3

**Comment by herazul** [comment]
What ai was it against on round 3? Is there a place where we can find all match results ?

**Comment by Mezoka** [comment]
"Is there a place where we can find all match results?"

http://duiyi.sina.com.cn/gibo/new_gibo.asp

http://foxwq.com/qipu

**Comment by l1t1** [comment]
game4 http://duiyi.sina.com.cn/gibo_new/live/viewer.asp?sno=18

**Comment by alreadydone** [comment]
lost to Fine Art in game 3 and playing with Phoenix Go (aka BensonDarr) now.

**Comment by l1t1** [comment]
leelaz win in round 4

**Comment by l1t1** [comment]
sgf of game4 http://foxwq.com/qipu/newlist/id/2018042757476800.html
-------------------------

(;GM[1]FF[4]
SZ[19]
GN[2018围棋AI大赛预赛第4轮 ]
DT[2018-04-27]
PB[PhoenixGo]
PW[LeelaZero]
BR[P9段]
WR[P1段]
KM[750]HA[0]RU[Japanese]AP[GNU Go:3.8]RE[B+R]TM[1800]TC[3]TT[60]AP[foxwq]
;B[dc];W[pq];B[cp];W[qd];B[oc];W[eq];B[pe];W[qe];B[pf];W[qg];B[gq];W[do];B[dp];W[ep];B[eo];W[fo];B[en];W[gp];B[dm];W[de];B[hp];W[fn];B[iq];W[fm];B[dk];W[ec];B[eb];W[dl];B[cl];W[el];B[cm];W[ed];B[fb];W[cc];B[cb];W[dd];B[db];W[ci];B[gd];W[kq];B[dg];W[cg];B[hn];W[ko];B[pp];W[qp];B[oq];W[op];B[po];W[nq];B[or];W[pr];B[qo];W[rp];B[hl];W[im];B[hm];W[hr];B[gr];W[ir];B[hq];W[ej];B[cf];W[df];B[ch];W[bg];B[di];W[bh];B[dj];W[dh];B[ei];W[io];B[ho];W[fj];B[lp];W[np];B[kp];W[lq];B[jp];W[hj];B[eg];W[bc];B[gi];W[gj];B[ik];W[ij];B[jj];W[ji];B[ki];W[jh];B[je];W[kh];B[kj];W[mh];B[pg];W[qh];B[ph];W[nn];B[hh];W[gg];B[fi];W[hi];B[ih];W[ii];B[mj];W[nj];B[mi];W[ig];B[kf];W[ni];B[nh];W[mg];B[nk];W[ng];B[oh];W[md];B[me];W[ie];B[id];W[he];B[hd];W[ne];B[le];W[nc];B[od];W[nd];B[lc];W[ob];B[qf];W[rf];B[pb];W[mb];B[oa];W[nb];B[gh];W[kc];B[ld];W[lb];B[jc];W[kd];B[jd];W[oe];B[pd];W[qc];B[pc];W[oj];B[qi];W[ri];B[pj];W[ok];B[rj];W[rh];B[pk];W[nl];B[ek];W[rk];B[si];W[qk];B[sh];W[rg];B[qj];W[pl];B[ql];W[qm];B[rb];W[qb];B[qa];W[rc];B[sc];W[re];B[sd];W[na];B[pa];W[sb];B[sa];W[rl];B[sg];W[fk];B[gl];W[fl];B[kl];W[jb];B[ib];W[km];B[cr];W[sk];B[sj];W[ia];B[hb];W[of];B[lm];W[ln];B[jm];W[mk];B[pi];W[kn];B[kg];W[lh];B[er];W[dq];B[fq];W[jk];B[kk];W[jg];B[hg];W[il];B[jn];W[kb];B[jf];W[if];B[fe];W[fg];B[eh];W[bj];B[bk];W[cj];B[ck];W[em];B[dn];W[fp];B[br];W[dr];B[ds];W[bp];B[co];W[ef];B[ff];W[es];B[fs];W[fc];B[mf];W[ge];B[gc];W[bq];B[cq];W[ll];B[jl]C[黑中盘胜])

**Comment by l1t1** [comment]
game 5 live http://duiyi.sina.com.cn/gibo_new/live/viewer.asp?sno=27

**Comment by herazul** [comment]
Who is the bot she is facing game 5 ?

**Comment by l1t1** [comment]
game 5 leelaz win sgf

------

(;GM[1]FF[4]
SZ[19]
GN[2018围棋AI大赛预赛第5轮]
DT[2018-04-27]
PB[LeelaZero]
PW[英雄王]
BR[P1段]
WR[P1段]
KM[750]HA[0]RU[Japanese]AP[GNU Go:3.8]RE[B+R]TM[1800]TC[3]TT[60]AP[foxwq]
;B[pd];W[dd];B[pq];W[dp];B[pn];W[jq];B[fc];W[cf];B[nc];W[cn];B[qj];W[hc];B[dc];W[cc];B[cb];W[ec];B[db];W[ed];B[cd];W[bc];B[bd];W[bb];B[ba];W[eb];B[ab];W[ql];B[mq];W[qp];B[qq];W[lp];B[ip];W[fq];B[dq];W[ep];B[ln];W[mp];B[nq];W[in];B[pl];W[jp];B[cp];W[cq];B[bq];W[cr];B[co];W[bn];B[do];W[em];B[dn];W[cl];B[hn];W[hm];B[fn];W[gl];B[io];W[jn];B[gm];W[hl];B[gp];W[fm];B[gn];W[br];B[gr];W[jo];B[ir];W[md];B[er];W[fr];B[fs];W[bp];B[bo];W[aq];B[eq];W[dr];B[es];W[mc];B[if];W[qf];B[id];W[ic];B[kd];W[ds];B[gs];W[kc];B[pf];W[pg];B[of];W[lg];B[qe];W[ih];B[gf];W[fg];B[ef];W[eg];B[gg];W[qk];B[pk];W[rj];B[pj];W[qi];B[qm];W[rm];B[rn];W[om];B[pi];W[qh];B[rf];W[rl];B[on];W[gh];B[fh];W[eh];B[hh];W[fi];B[hi];W[ii];B[kh];W[ig];B[jg];W[hg];B[lh];W[rg];B[qg];W[mh];B[mg];W[qf];B[kk];W[sn];B[so];W[sm];B[ro];W[pm];B[qn];W[ng];B[mf];W[nf];B[nh];W[mi];B[og];W[ne];B[lf];W[ke];B[sk];W[kf];B[kg];W[oh];B[ni];W[sj];B[jl];W[jm];B[qg];W[ph];B[nj];W[qf];B[jc];W[jb];B[jd];W[lb];B[qg];W[sg];B[rh];W[qf];B[il];W[im];B[qg];W[ri];B[nb];W[le];B[jf];W[me];B[lg];W[rd];B[qc];W[rc];B[re];W[qb];B[pb];W[rb];B[sd];W[sc];B[od];W[qd];B[pc];W[se];B[sf];W[qf];B[pe];W[pa];B[qg];W[sh];B[sa];W[oi];B[nk];W[qa];B[ob];W[mb];B[bf];W[bg];B[ao];W[ll];B[lk];W[np];B[op];W[iq];B[gd];W[hp];B[gq];W[en];B[eo];W[fo];B[fp];W[ho];B[fb];W[ff];B[oa];W[ge];B[hd];W[nn];B[nm];W[mm];B[nl];W[ki];B[li];W[oo];B[po];W[or];B[oq];W[gb];B[ce];W[af];B[go];W[dm];B[df];W[be];B[de];W[dg];B[ea];W[kl];B[ik];W[da];B[ca];W[ga];B[mn];W[km];B[no];W[lr];B[fe];W[fa];B[ac];W[mr];B[nr];W[ns];B[hf];W[ij];B[hk];W[hj];B[gk];W[fk];B[gj];W[fj];B[jk];W[gi];B[da];W[gc];B[fd];W[jr];B[pr];W[os];B[ps];W[ms];B[lq];W[kq];B[an];W[bl]C[黑中盘胜])

**Comment by l1t1** [comment]
http://sports.sina.com.cn/go/2018-04-27/doc-ifztkpip0627145.shtml

Preliminaries final ranking:

First: Fina Art China

Second: Phoenix Go China

Third: Leela Zero Belgium

Fourth: TS Go China

Fifth (Parallel): DolBaram Korea

Fifth (Parallel): Little Love Go (BADUKi) Korea

Seventh: HEROZ Kishin Japan

Eighth: Golois France

**Comment by gcp** [comment]
This means Leela qualified for the semi-finals tomorrow, so we'll get a few more games.

**Comment by jkiliani** [comment]
I think this is a fantastic performance, especially considering that FineArt and Phoenix Go are closed source and have the resources of a big company (Tencent) behind them.

**Comment by gcp** [comment]
Tomorrow Leela Zero plays Phoenix Go again.

**Comment by Friday9i** [comment]
And I'll get the curve of scalability of 20Bv9 vs LZ118 by tonight hopefully, my PC run full-time on it: so we should get a better view of which one of the 2 is best at high number of visits. Unfortunately, I don't get access to 20Bv11, so not in a position to test it (and not enough time anyway).
However, if someone with access to v11 has a big configuration (eg 4xGTX1080) and want to test by tomorrow morning, I can give some advices on how to test it efficiently, please ask me.

**Comment by yenw** [comment]
"Is there a place where we can find all match results?"

https://github.com/yenw/computer-go-dataset/tree/master/AI/Berry%20Genomics%20Cup%202018%20World%20AI%20Weiqi%20Competition

**Comment by roy7** [comment]
@l1t1 got a link for the LZ / Phoenix rematch?

**Comment by Mezoka** [comment]
![1953153](https://user-images.githubusercontent.com/17486912/39390292-fe1d3830-4ac4-11e8-86b3-eae638727cdb.jpg)

**Comment by l1t1** [comment]
sgf http://foxwq.com/qipu/newlist/id/2018042839232251.html

-----

(;GM[1]FF[4]
SZ[19]
GN[贝瑞基因杯世界人工智能赛半决赛]
DT[2018-04-28]
PB[PhoenixGo]
PW[LeelaZero]
BR[P9段]
WR[P9段]
KM[750]HA[0]RU[Japanese]AP[GNU Go:3.8]RE[B+R]TM[1800]TC[1]TT[10]AP[foxwq]
;B[cp];W[pc];B[pp];W[dd];B[qe];W[eq];B[dn];W[od];B[iq];W[qq];B[pq];W[qp];B[po];W[qo];B[pn];W[qn];B[cf];W[pm];B[om];W[ol];B[nm];W[nl];B[ml];W[mm];B[pl];W[qm];B[mk];W[nj];B[mn];W[lm];B[ln];W[km];B[kn];W[jm];B[jn];W[im];B[nk];W[ok];B[oj];W[pk];B[pj];W[qk];B[ni];W[in];B[io];W[nn];B[on];W[jo];B[kp];W[no];B[np];W[mo];B[lp];W[nq];B[or];W[mp];B[mr];W[lq];B[mq];W[jp];B[kq];W[jq];B[kr];W[ho];B[qj];W[ce];B[rk];W[ql];B[df];W[fd];B[hc];W[di];B[ck];W[hd];B[id];W[he];B[ie];W[ic];B[jc];W[ib];B[if];W[hf];B[ec];W[ed];B[hb];W[jb];B[kc];W[kb];B[lb];W[lc];B[ld];W[mc];B[mb];W[cj];B[nc];W[md];B[nd];W[me];B[ig];W[gc];B[gb];W[ne];B[ob];W[pf];B[pe];W[oc];B[nb];W[jd];B[kd];W[oe];B[qf];W[pg];B[qg];W[ri];B[qh];W[mj];B[mh];W[rd];B[pb];W[lj];B[ke];W[lg];B[lh];W[qb];B[ng];W[dc];B[fc];W[kf];B[kh];W[qa];B[re];W[sd];B[sb];W[rb];B[sa];W[rj];B[ph];W[og];B[oh];W[jh];B[je];W[cl];B[gd];W[cr];B[ji];W[bk];B[gh];W[hq];B[ir];W[ip];B[ff];W[gj];B[eh];W[fi];B[ge];W[ko];B[lo];W[jr];B[js];W[hr];B[qr];W[jj];B[ii];W[ij];B[hi];W[qd];B[pd];W[qc];B[sc];W[mg];B[nf];W[pa];B[ia]C[黑中盘胜
/"huaix其实……接着走下去，还是可以2目半的吧])

**Comment by l1t1** [comment]
fine art vs tsgo http://foxwq.com/qipu/newlist/id/2018042839545849.html
[ft1sgf.txt](https://github.com/gcp/leela-zero/files/1957239/ft1sgf.txt)

**Comment by roy7** [comment]
Well LZ got beat down by Phoenix, but looking at the TS vs Fine Art game, TS lost by move 30. So I'm hopeful LZ can beat TS and secure 3rd place.

**Comment by hydrogenpi** [comment]
Lets hope five out of the six gtx1080Ti don't suddenly detached during the game. After the golaxy thing I'm not too suprised by anything anymore.

**Comment by l1t1** [comment]
3-4 final http://foxwq.com/qipu/newlist/id/2018042851264148.html

-----

(;GM[1]FF[4]
SZ[19]
GN[贝瑞基因杯世界人工智能赛3/4名决赛]
DT[2018-04-28]
PB[LeelaZero]
PW[天算]
BR[P9段]
WR[P9段]
KM[750]HA[0]RU[Japanese]AP[GNU Go:3.8]RE[B+R]TM[1800]TC[5]TT[60]AP[foxwq]
;B[pc];W[pp];B[cd];W[dp];B[qf];W[ed];B[ec];W[dd];B[dc];W[ce];B[bd];W[fd];B[fc];W[gd];B[hb];W[cc];B[be];W[cf];B[bf];W[cg];B[bg];W[ch];B[ic];W[fq];B[qn];W[nq];B[on];W[qo];B[rn];W[mo];B[gp];W[gq];B[ip];W[pj];B[op];W[oq];B[qq];W[qp];B[mn];W[ln];B[mm];W[lo];B[ph];W[nj];B[lm];W[km];B[kl];W[jm];B[lk];W[oh];B[og];W[nh];B[pi];W[dn];B[lh];W[jl];B[jk];W[kj];B[kk];W[ik];B[ij];W[hk];B[jj];W[pb];B[pd];W[hj];B[hq];W[jq];B[kq];W[hr];B[ie];W[ii];B[co];W[cp];B[bp];W[bq];B[do];W[eo];B[ep];W[bo];B[cn];W[en];B[fp];W[iq];B[bn];W[ap];B[cl];W[bk];B[ck];W[cj];B[bl];W[el];B[bj];W[jd];B[eq];W[cr];B[id];W[oc];B[od];W[nb];B[nc];W[ob];B[qb];W[mc];B[nd];W[lb];B[kc];W[rb];B[qa];W[pa];B[qc];W[bi];B[ak];W[kb];B[hp];W[gr];B[jp];W[kr];B[hi];W[ih];B[hh];W[hg];B[fi];W[gg];B[fh];W[jg];B[fk];W[ek];B[ej];W[dj];B[fm];W[fl];B[gl];W[gk];B[em];W[gm];B[gn];W[hl];B[dm];W[qj];B[ql];W[pl];B[oj];W[nm];B[ok];W[nn];B[om];W[ml];B[ol];W[cb];B[ll];W[gc];B[gb];W[db];B[ea];W[bc];B[da];W[no];B[mk];W[pg];B[qg];W[ab];B[ba];W[ro];B[ca];W[sn];B[sm];W[so];B[rm];W[lg];B[kp]C[黑中盘胜])

**Comment by WesleyDeng** [comment]
Congratulations to the Leela team!

**Comment by gcp** [comment]
>Lets hope five out of the six gtx1080Ti don't suddenly detached during the game. After the golaxy thing I'm not too suprised by anything anymore.

Always this negativity 🙄 I'm sure the Golaxy match was a good learning experience. Without our volunteer operators, Leela Zero wouldn't even have been in this tournament. Great performance and many thanks!

**Comment by billyswong** [comment]
@Friday9i Do you know if the 20Bv11 net in competiton be submitted to public test match like those older 20-blocks nets for benchmark in near future?

**Comment by Friday9i** [comment]
I'll update my benchmark of scalability with the v12 in the coming days (finishing the test with v9 currently)

**Comment by Splee99** [comment]
I don't know if you guys noticed the sequence around the 3-3 points in the game of LZ vs fineart. It revealed exactly the disadvantage of 3-3 invasion. Maybe LZ has to go thru 20 block self play training to understand this, because it is related to the broader board situation.

**Comment by l1t1** [comment]
from the test match of v11 and v12, their winrate are similar to  best 192*15

**Comment by sethtroisi** [comment]
https://github.com/leela-zero/leela-zero/issues/1272
