### ISSUE TITLE
Live streaming for AI semi final LZ vs Phoenix Go (Chinese) at 10:00 UTC+8

### ISSUE THREAD

**Issue by fell111** [leela-zero/leela-zero#1276]
Here is the live streaming and live match for the semi final.
stream https://www.panda.tv/389578

semi final  LZ vs Phoenix 
http://portal.yikeweiqi.com/online/golive/detail?id=8586

match for the 3rd LZ vs TS Go
http://portal.yikeweiqi.com/online/golive/detail?id=8598

**Comment by l1t1** [comment]
http://duiyi.sina.com.cn/gibo_new/live/viewer.asp?sno=7

**Comment by diadorak** [comment]
LZ lost. Will play TS Go for the 3rd place.

**Comment by higherdim** [comment]
Phoenix is a 40 block Zero.  FineArt is a 80 block Master. 
No surprise LZ lost. Good chance to get third this time.

**Comment by diadorak** [comment]
@higherdim source??

**Comment by higherdim** [comment]
From live stream caster.

**Comment by higherdim** [comment]
Some say FineArt is a 40 block Master.

**Comment by higherdim** [comment]
I heard 3rd is 40000 Yuan (～USD 6500)

**Comment by fell111** [comment]
It is said that the playouts for Phoenix Go is several million. That's crazy. LZ only have 200 k playouts for 20 blocks.

**Comment by godmoves** [comment]
FYI, Phoenix is 40 blocks zero and Fine art is 60 blocks master .
