### ISSUE TITLE
Next game to get the Zero treatment?

### ISSUE THREAD

**Issue by TFiFiE** [leela-zero/leela-zero#1290]
After Go and chess (#369), does anyone think there is a game left for which likewise an effective amount of support for a distributed DL effort could be attracted? The only one for which I could seriously see this happen is shogi (and even that would probably require significant awareness among Japanese people who know little English). I'm not getting the idea computer xiangqi is a big thing in China.

**Comment by Marcin1960** [comment]
"On a sidenote, one of the downsides of LZ so quickly becoming superhuman is that people now are saying "good enough" and pulling back contributions"

I don't think this is the reason.

**Comment by l1t1** [comment]
there are so many new born bots  after few months!

**Comment by ihavnoid** [comment]
> On a sidenote, one of the downsides of LZ so quickly becoming superhuman is that people now are saying "good enough" and pulling back contributions

The net size increase is making it look like there are less contributions - but we also have to keep in mind that the net size increase is making us have less games for the same amount of compute, so maybe it's less worse than what we imagined?

> 658 clients in past 24 hours, 173 in past hour.
> 7133294 total selfplay games. (16586 in past 24 hours, 777 in past hour.)
> 339331 total match games. (1744 match games in past 24 hours, 0 in past hour.)

**Comment by gcp** [comment]
I don't think the amount of contribution is going down, but indeed the network upgrades decrease the amount of games a lot (and hence, the rate of new networks). Also, the statistics display drop every time I do maintenance on the server (removing old games from the DB to make room on its SSD)

**Comment by hydrogenpi** [comment]
whats the specs for ssd

**Comment by thalessa** [comment]
OpenAI has produced a 1v1 DOTA bot that almost always beats humans. They claim to be working on 5v5.

**Comment by gcp** [comment]
The problem with Dota2 and stuff to me always seemed that there was no complete, standalone implementation of the game (might not be true anymore for original SC).

So if you want to have a Monte Carlo bot simulate playing out the game, that's not something you can actually do.

>Personally I'd like to see contract bridge. The best programs are not superhuman

Really? I thought that programs like Jack were superhuman for quite a long time already.

**Comment by nathanloop** [comment]
> Really? I thought that programs like Jack were superhuman for quite a long time already.

Last I knew Jack and WBridge5 were very good and could play competitively with top players but Jack still lost the last official Man vs. Machine tournament that I'm aware of. Maybe humans just play at the best possible level for the game?

**Comment by thalessa** [comment]
Dota 2 (Moba) has a bot AI team now

https://youtu.be/eHipy_j29Xw

**Comment by alreadydone** [comment]
Impressive cooperation among five agents without explicit means of communication ...

**Comment by alreadydone** [comment]
Teamwork: https://twitter.com/Smerity/status/1011340815682056192

LSTM architecture: https://twitter.com/hardmaru/status/1011300202622226432 from https://d4mucfpksywv.cloudfront.net/research-covers/openai-five/network-architecture.pdf

Resource: https://twitter.com/hardmaru/status/1011509177699594240

**Comment by thalessa** [comment]
For those interested, the OpenAI bot match for Dota 2 takes place on August 5th and will be professionally cast on twitch.

They're playing a team of 5 machine learning bots with no explicit communication, in a continuous hidden information game vs a human semi-pro team. 

Many of the game restrictions on the match have been lifted.

**Comment by thalessa** [comment]
OpenAI results and technical blog with network architecture

https://blog.openai.com/openai-five-benchmark-results/

Given how much they had to simplify the game and draft I doubt they will get full rules working by TI 8, but they might well beat a professional team in their current ruleset.

**Comment by sethtroisi** [comment]
Looks like the answer was Starcraft / Dota

closing
