### ISSUE TITLE
How strong is raw network (without visits/playouts)

### ISSUE THREAD

**Issue by kris-computer-go** [leela-zero/leela-zero#1294]
It may be useful for weak hardware (slow CPU & no GPU) to create as strongest raw network as possible.
What would be the biggest weight file trained with net2net? I mean how many blocks / filters?
Because bigger the network = stronger, maybe we could have a 9D player for laptops or even smartphones.

**Comment by Eddh** [comment]
It seems like someone tried on cgos : http://www.yss-aya.com/cgos/19x19/cross/LZ_20x256v12_p1.html

**Comment by Friday9i** [comment]
From a few games I played, I'd say the raw LZ128 network is at least 2D or 3D KGS: it beat me a few times with 3 handi, and I'm around 1 kyu KGS... Good news for LZ, sad for me ; -(

**Comment by Eddh** [comment]
Deepmind reported an elo of about 3000 for their raw 40x512 net. Slightly below Alphago Fan. So yeah it does help. But of course it's not as strong without the tree search, the huge gap is quite justified.

**Comment by jkiliani** [comment]
The largest net used by Deepmind was 256x40. As far as I know (their publications and conference presentations) they never went beyond 256 filters, even with the very deep net for Alphago Zero.

**Comment by hydrogenpi** [comment]
@Friday9i Nick Sibicky is a 4dan, so is SundayGoLesson's Jonathan Hop. Dywrin is a 5Dan and "Go instructor" is a 6Dan.

**Comment by hydrogenpi** [comment]
@ kris-computer-go  test have shown that latest net on 100 playouts is the same as Leela 11 on unlimited. Bigger weight files only slow it down exponentially esp on smaller form factor devices.

**Comment by gcp** [comment]
>Bigger weight files only slow it down exponentially esp on smaller form factor devices.

But even something like 4 playouts give a huge Elo gain over 1 playout, and that is very feasible on phones. I tested this. It's literally only 1-2 that does not give 200 Elo.

**Comment by LetterRip** [comment]
@hydrogenpi 

>The only way to get a pro level on smart phone is when a single playout is basically already approaching pro level.

Not necessarily so.  Weight compression, quantization, pruning, etc. might allow for a really strong net that runs on the tensorflow for phone GPUs with reasonable performance.

**Comment by l1t1** [comment]
maybe someday lz will be the standard benchmark software on phone

**Comment by MartinDevelopment** [comment]
If it is possible to get 120 visits a moves in less than 10 seconds on a phone, that would be more than enough, since that is enough to beat leela 0.11 on a desktop.

**Comment by kris-computer-go** [comment]
I've just played another 4 games against different 3dan players using my old laptop and this time 20x256 v12 net (CPU only).
--benchmark showed 0 n/s (zero!!!). Result was 4 : 0 for Leela0.
Even though result was better then with 15x192 net - I felt that Leela was uncertain. Some moves was good some was bad. If I have to choose again I would prefer to play with 15x192 net.

**Comment by MartinDevelopment** [comment]
@kris-computer-go This is a test I ran some time ago, it shows that doubling the visit amount at even such a low amount increases the strenght alot. I will run another test with the latest network, but now all the way up to 128 visits.

Network: 158603eb61a1e5e9dcd1aee157d813063292ae68fbc8fcd24502ae7daf4d7948
LZ-1v v LZ-2v (600/600 games)
board size: 19   komi: 7.5
        wins              black          white        avg cpu
LZ-1v    297 49.50%       151 50.33%     146 48.67%      4.48
LZ-2v    303 50.50%       154 51.33%     149 49.67%      4.46
                          305 50.83%     295 49.17%

LZ-2v v LZ-4v (600/600 games)
board size: 19   komi: 7.5
        wins              black          white        avg cpu
LZ-2v    255 42.50%       131 43.67%     124 41.33%      4.59
LZ-4v    345 57.50%       176 58.67%     169 56.33%      4.67
                          307 51.17%     293 48.83%

LZ-4v v LZ-8v (600/600 games)
board size: 19   komi: 7.5
        wins              black          white        avg cpu
LZ-4v    197 32.83%       99  33.00%     98  32.67%      4.60
LZ-8v    403 67.17%       202 67.33%     201 67.00%      5.12
                          301 50.17%     299 49.83%

**Comment by l1t1** [comment]
leelaz just like DroidFish for chess, is not only the best chess game, it can also be used to detect hardware performance.

**Comment by Friday9i** [comment]
I also did tests with n visits vs 2n visits with a recent network (LZ126 I think): results on my home computer, I'll paste them tonight.
But from memory, 2 visits is NOT stronger than 1 visit (around 50/50 result for 400 games), 4 vs 2 visits gives a small boost (around 30 Elo points), then the Elo boost from doubling visits increases, which surprised me: each doubling gives a boost, and that boost is increasing!
The boost for doubling visits increase and goes up to almost ~150/200 Elo points at 500 visits and more (ie 1024 visits is almost 200 Elo points stronger than 512 visits!).
I did not test above 2K vs 1K visits, as it becomes very time consuming to generate 100s of games to get statistically significant results.
As said, I'll post detailed results tonight.

**Comment by gcp** [comment]
Doubling visits does not double the amount of computation done, so that's why you are not seeing the expected scaling.

It's better to do such tests with fixed playouts, and either use "next" or disable time management.

**Comment by Friday9i** [comment]
@gcp: ok thanks a lot, I'll test with playouts and no time mangement then (not "next", as I'm not expert enough to compile it myself, pity...).
I'll show results here for both visits and playouts.

**Comment by sethtroisi** [comment]
closing older issue with no active discussion
