### ISSUE TITLE
Using NN for time-management and board-counting?!

### ISSUE THREAD

**Issue by hydrogenpi** [leela-zero/leela-zero#1295]
Using NN for time-management settings and accurate boardstate counting with the 'zero' philosophy. 

===== begin tldr =====

**We know that a human player that is othewsie WEAKER than LZ, (cannot win against LZ in a normal game) but when managing time on behalf of LZ, will make LZ's play stronger than its default time management.... So if that higher order intuition can itself somehow be trained into a NN, then it would improve the overall playing strength of whatever engine that used it for its time management.**

===== end tldr ===== 

How feasible would it be to envision one NN (as a holistic monolith) by adding extra/more layers/blocks so that it uses the NN when playing to not only select moves but also set time-settings as well. Instead of outputting just (X,Y) coordinates, we now have a temporal aspect of (X,Y,Z), the move in conjunction with how much time to spend rendering the move itself.... Specifically to train a nueral network to optimize time-usage in a manner that would be more robust and efficent than even a top-pro could manage in terms of best combinations of time allocations. It seems like LZ is already top pro in raw playing strength but its time management is still lacking. Namely, I'm willing to bet and my theory is that if allowing a pro to management LZ's time, LZ could play stronger than LZ managing its own time. This can be tested by giving a pro (or even any other relatively strong but less than professional player) the exact same LZ network and hardware, playing vs against the same LZ network and hardware but using its Rudimentary time management. Its pretty obvious in the long run which side would score more wins. However it doesnt have to be this way . There is nothing inherently better in this regard that humans can do that an AI can't be self-learned to do even better and I believe when it comes to optimal time-management that this is no different and certainly no exception!. If we can train an NN to manage time better than even a pro can do, imagine the extra strength boost it can have when used in conjunction with an already superhuman AI! If we can encode the "intuition" of Go into a NN, there is no reason why the higher-order intuition of managing its time during play could not also be encoded into NN as well.....

What is one real world example or application of this? _Recently baduk1 played many top level pros using Lizzie and won against these pros. Had something like Roy's more automated bot been used even when network and hardware are identical, its likely that baduk1's managing of the time on the behalf of LZ made it stronger vs an automated bot playing with its more simple time management. But this is human intervention. So if a NN can be trained to manage time BETTER than any human can do, then it would be "zero" and the "best of all worlds"._ 

But Would it be better to train an external NN in isolation just for the task of time-management (and hence possibly make it engine independent so that this time-management AI/NN could be used on any engine or even used in human games to suggest to the humans how much is the optimal time to spend per move depending on all the other factors and details of the game as it unfolds in real-time etc) ...or... would it be better to train one holistic NN so as to incorporate and embed the time management aspect as merely a component (or rather one more deminsion or additional element) within the larger NN itself, i.e. a single all-encompassing network that both plays the moves and also sets its own time when playing said moves, all without human intervention and all within the guidelines of the 'zero' philosophy.?

Another related thing is the possibility of using NN to also train a mechanism for very accurate board-counting. Since counting really comes down to the board state at any static moment in time and is not influenced by the strength of the engines and/or the relative strengths of the players (be they human or AI) nor the time settings used, etc then if a tool could be trained using NN to produce accurate counts (not only in the end-game but also during each and every possible state-of-play and stage-of-the-game) then it would be useful not only in outputting count states in AI vs AI, AI vs human games, but also as a robust autocounting mechanisms even in human vs human games. Since "counting" should be entirely independent of engine strength or any other parameters or factors, if a well enough NN was trained for the specific task of counting, it could be incorporated in all engines and used widely for many different things. 

What is one real world example or application of this? Recently in Haylee's first of eight games (re)match against LZ there were many chat comments debating whether or not LZ does "counting" (be it internally somehow or otherwise) and hence also whether or not that count info can be displayed as an output in addition to the roy's variation WR% etc... It seems this would add an eelement of interest, since basically the WR% for LZ went to almost 100 within a short number of moves and stayed there for the rest of the game, then a metric more interesting in addition to WR% would be something like a total count of how many points white/black has at any given moment in time. (not just at the end game but during all stages of the game) Given OGS has counting issues, and OGS has scoring issues, and counting is still somewhat of an art and imperfect science at best, if an NN could be trained to count at a level more accurate than even the best human could do, then for all intents and purposes it would further give Go players and viewers alike additional value in facilitating the automation of what is basically a tedious and mechanic and somewhat inaccurate aspect of the game. 

What would be required to train the NN for time-management? Would the inputs be merely the total 'boardstate' (which by definition includes the WR% and also the "count") at any given moment as a sort of time-slice snapshot AND plus in conjunction the "historial WR graph/chart/trend" (basically all the previous boardstates that were used to arrive/derive at the current-most boardstate)? So basically pick a strong LZ network, have it play self-playing games against itself. Add noise by randomly increasing /decreasing each move by x fraction/amount and then train on the winners, promote the best nets after testing, rinse and repeat just like the same process used to train the Go AI engine from zero in the first place? In this case the "playing" network never gets promoted and in fact is frozen and stays the same, it is the "time managment" meta network that is changed and promoted as the ones that are better in creating more wins on the same network rise to the top and compete against themselves? 

What would be required to train the counting aspect with NN from 'zero'? I don't think there are millions of sgf of games with total counts that can be used as raw data for training. And plus that would be supervised training anyhow and at least somewhat deviate from the spirit of the zero method.... so what? MCTS to fill in the games and extrapolate a final score from any intermediate position? Wouldn't this be like the value/policy network that was trained in earlier versions of AG? One possibility could be to have it learn within itself within the same game. For example say during move 50 it predicts a large group as being dead or alive and incorporates that within its calculation of scoring in counting points, but later on in the game in much later moves it realizes its earlier prediction was correct/wrong, then if it can be trained to learn from that within the /each game, that could help train its nueral network intution as to what/where sketchy/early frameworks should be counted as how many points given so much is unknown etc. Instead of viewing each game by the ultimate loss/won result, it views and trains on each game as a temporal aspect, seeing each moment in time and comparing its earlier estimates to how the game actually plays/played out (which is much more accurate than merely a MCTS estimation of final scoring)

**Comment by alreadydone** [comment]
Just my two cents:
for time management, use the winrate fluctuation (say during the latest 10% playouts) to decide whether to extend search further. This requires no change to NN, you just need to keep some statistics (maybe just max and min winrate) during MCTS.
For score estimation: #1013 seems to work and people seem to have implemented score estimation in lizzie or mylizzie. I would suggest replacing the binary 0/1 loss/win results by tanh(score) or something alike, and maybe play every game with resignation disabled. The NN will still play aggressively when it's behind, but will not play self-atari when there's no hope; it also won't play moves that provably lose points in endgames when it's winning, and the final result may be good enough to train value heads with different komi.

**Comment by hydrogenpi** [comment]
In a real game when LZ falls for a ladder by the time it realizes it is too late, there is no going back. But Training an NN to manage time could also have the effect of steering it away from potentially losing moves/sequences before it even goes down that route. For example as a strong human player managing time for the AI, if the human sees the current move is going to result in a bad ladder he will try to wait a while until the selection moves on to something else before committing the move to the board. So there is no reason why an NN can't be trained to do the same. Essentially giving it a "temporal" advantage that otherwise it wouldn't have.

**Comment by hydrogenpi** [comment]
We know that a human player that is othewsie WEAKER than LZ, but when managing time on behalf of LZ, will make LZ's play strong than its default time management. So if that higher order intuition can be trained into a NN, then it would improve the overplay strength of whatever engine that used it for its time management.

**Comment by bittsitt** [comment]
@alreadydone : Lizzie does not include score est, and from what I can tell, mylizzie score est is based on having either Zen or gnugo installed to do the estimation. Do you know of somebody that has a fork on one of these two that uses Lizzie?

**Comment by alreadydone** [comment]
Two references for time management for MCTS: 
https://pdfs.semanticscholar.org/c88a/df13845554bd5b27c351d723fc76fb717786.pdf
MCTS is *unstable* if the move with the highest win rate differs from the move with the highest visit count. MoHex moves are frequently unstable, so we implement a search extension policy similar to that of [25]: extend an unstable search by half of its original search time. We extend a search at most once.

[25] Huang, S.-C., Coulom, R., Lin, S.-S.: Time management for Monte-Carlo tree search applied to the game of go. In: 2010 International Conference on Technologies and Applications of Artificial Intelligence (TAAI), pp. 462–466, November 2010

(Shih-Chieh Huang = Aja Huang)

**Comment by sethtroisi** [comment]
closing older issue with other active discussions
