### ISSUE TITLE
How to store winrate/playouts in sgf file

### ISSUE THREAD

**Issue by bittsitt** [leela-zero/leela-zero#1297]
Lizzie contributer here with a question a bit on the side. I think it would be very useful to store winrate (and play outs, and maybe even top alternatives) in a sgf so that if you spend a lot of time processing a file, you don’t have to redo it if you want to look at again. On chess servers, you can also get your file analysed by a computer for a fee, and something similar is likely to happen with go.

Are there any sgf experts here that knows how this could be done (or is it already being done in LZ)? One easy solution would be to add it in the comments, but it makes it harder to find actual comments (from a review eg). There is also a value property, but for go it says specifically that it refers to score estimate, also you wouldn’t be able to store play outs which would be very relevant if you start analysing a game on  a stronger computer e.g.

Is the best option to add some tags to the sgf format? Which tags would be best to add in that case? Winrate and playouts? I assume most clients are robust enough that they will skip tags they don't know and not choke.

**Comment by roy7** [comment]
Not disagreeing with your suggestion, but I did want to recommend GoReviewPartner to you. There's also an analysis site called CrazySensei that does what you mention, and a free alternative whose web site I can never remember.

**Comment by bittsitt** [comment]
I see GoReviewPartner has made a rsgf format that includes review information which is interesting.

I mostly concerned with coming up with a format that can become a standard that would work across all tools.

**Comment by sethtroisi** [comment]
newer discussion in https://github.com/leela-zero/leela-zero/issues/2205
also see PR https://github.com/leela-zero/leela-zero/pull/2174
