### ISSUE TITLE
Proposed change to Tuner.cpp

### ISSUE THREAD

**Issue by Marcin1960** [leela-zero/leela-zero#1300]
It would be nice, when tuning takes long time, to provide some assurance to the user.

if (max_error < MAX_ERROR && (best_time == 0 || sum < best_time)) {
            auto param_str = parameters_to_string(p);
            auto kernel_ms = 1e-6f * (sum / runs);
            // Timing is in nanoseconds (10^-9), Giga = 10^9, so this works out
            auto kernel_gflops = total_flops / (sum / runs);
            myprintf("(%u/%u) %s %.4f ms (%.1f GFLOPS)\n",
               param_counter, valid_params.size(), param_str.c_str(),
               kernel_ms, kernel_gflops);
            best_time = sum;
            best_params = defines;
        }
		**else {
			if ((param_counter % 100) == 0) {
				auto kernel_ms = 1e-6f * (sum / runs);
				myprintf("%u %.4f ms \n", param_counter, kernel_ms);
			}
		}**

**Comment by gcp** [comment]
Sounds reasonable to at least output a ```.``` regularly.

**Comment by Marcin1960** [comment]
ms is just for fun, looks more interesting and instructive :)
