### ISSUE TITLE
OpenCL not working

### ISSUE THREAD

**Issue by Valdorigamiciano** [leela-zero/leela-zero#1301]
Hi, I've been trying to make it work for a while, but haven't managed to succeed apparently due to OpenCL not working properly. Hope someone can help me solve this issue, it's damn annoying, and forgive me if I formulated the request somewhat improperly, I'm just a normal user so I am not really sure what to look for. I've installed all the available packages that satisfy the requisites for the software to run on my distribution, Solus.My specifics are CPU i5-4690k and GPU R9 280X. 

**When I try to run ./tests included in the repository, I get this**: 

Running main() from gtest_main.cc
[==========] Running 11 tests from 2 test cases.
[----------] Global test environment set-up.
Detecting residual layers...v1...8 channels...1 blocks.
Initializing OpenCL.
DRM_IOCTL_I915_GEM_APERTURE failed: Invalid argument
Assuming 131072kB available aperture size.
May lead to reduced performance or incorrect rendering.
get chip id failed: -1 [2]
param: 4, val: 0
Detected 1 OpenCL platforms.
Platform version: OpenCL 2.0 beignet 1.3
Platform profile: FULL_PROFILE
Platform name:    Intel Gen OCL Driver
Platform vendor:  Intel
DRM_IOCTL_I915_GEM_APERTURE failed: Invalid argument
Assuming 131072kB available aperture size.
May lead to reduced performance or incorrect rendering.
get chip id failed: -1 [2]
param: 4, val: 0
cl_get_gt_device(): error, unknown device: 0
Error getting device(s): clGetDeviceIDs: -1
unknown file: Failure
C++ exception with description "No suitable OpenCL device found." thrown in auxiliary test code (environments or event listeners).

**This is what I get from clinfo:**

DRM_IOCTL_I915_GEM_APERTURE failed: Invalid argument
Assuming 131072kB available aperture size.
May lead to reduced performance or incorrect rendering.
get chip id failed: -1 [2]
param: 4, val: 0
Number of platforms                               1
  Platform Name                                   Intel Gen OCL Driver
  Platform Vendor                                 Intel
  Platform Version                                OpenCL 2.0 beignet 1.3
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_byte_addressable_store cl_khr_3d_image_writes cl_khr_image2d_from_buffer cl_khr_depth_images cl_khr_spir cl_khr_icd cl_intel_accelerator cl_intel_subgroups cl_intel_subgroups_short cl_khr_gl_sharing
  Platform Extensions function suffix             Intel
DRM_IOCTL_I915_GEM_APERTURE failed: Invalid argument
Assuming 131072kB available aperture size.
May lead to reduced performance or incorrect rendering.
get chip id failed: -1 [2]
param: 4, val: 0
cl_get_gt_device(): error, unknown device: 0

  Platform Name                                   Intel Gen OCL Driver
Number of devices                                 0

NULL platform behavior
  clGetPlatformInfo(NULL, CL_PLATFORM_NAME, ...)  Intel Gen OCL Driver

DRM_IOCTL_I915_GEM_APERTURE failed: Invalid argument
Assuming 131072kB available aperture size.
May lead to reduced performance or incorrect rendering.
get chip id failed: -1 [2]
param: 4, val: 0
cl_get_gt_device(): error, unknown device: 0
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ALL)  No devices found in platform

ICD loader properties
  ICD loader Name                                 OpenCL ICD Loader
  ICD loader Vendor                               OCL Icd free software
  ICD loader Version                              2.2.12
  ICD loader Profile                              OpenCL 2.2

**Comment by Ka-zam** [comment]
Beignet apparently requires a kernel patch on 4th gen Core CPUs:

`There are several little caveats which need to be discussed up front. Foremost, the Beignet project supports the following hardware:

3rd Generation Intel Core Processors
Intel “Bay Trail” platforms with Intel HD Graphics
4th Generation Intel Core Processors (requires a kernel patch be applied for shared memory!)
5th Generation Intel Core Processors "Broadwell".`

Do you have this kernel patch applied?

**Comment by alphaladder** [comment]
https://github.com/pytorch/ELF/issues/24

**Comment by Marcin1960** [comment]
The last AMD driver that is not broken is Catalyst 15.7.1

You might need to clean thoroughly the remains of later versions.

**Comment by Valdorigamiciano** [comment]
@Ka-zam My CPU should not be affected.
@gcp Thanks, perhaps I should try an Ubuntu-based distro.
@Marcin1960 why so?

**Comment by sethtroisi** [comment]
closing older issue with no active discussion and many code changes since
