### ISSUE TITLE
Performance comparison for LZ vs ELF

### ISSUE THREAD

**Issue by bood** [leela-zero/leela-zero#1320]
I did some test on GTX1060:

```
./leelaz_elf --benchmark -w elfv0.gz -v3000 -t2
3001 visits, 1038172 nodes, 3000 playouts, 232 n/s
```

```
echo -e "play b d16\ngenmove w\n" | ./elf.run 10000
MCTS: 64804.3ms. Total: 64804.3ms.
```
acutal command used is `./gtp.sh ~/elf/pretrained-go-19x19-v0.bin --verbose --gpu 0 --num_block 20 --dim 224 --mcts_puct 1.50 --batchsize 16 --mcts_rollout_per_batch 16 --mcts_threads 2 --mcts_rollout_per_thread $1 --resign_thres 0.05 --mcts_virtual_loss 1`

so `10000*2/64.8=~308n/s`

Appears to be a `308/232=~1.32x` improve for ELF vs LZ, looks not bad for LZ?

Please paste your performance data here if you have a different card and compiled ELF successfully.

**Comment by gcp** [comment]
Note:
https://github.com/gcp/leela-zero/pull/1312#issuecomment-386497295

**Comment by bood** [comment]
Tried reducing batch size to 8, it does become worse on GTX 1060:
`MCTS: 94762.6ms. Total: 94762.6ms.`

**Comment by l1t1** [comment]
@bood how to trim the verbose output when run benchmark

C:\leela_lizzie_elf>leelaz_elf --benchmark -w elf_converted_weights.txt -v3000 -t2
Thinking at most 2678400.0 seconds...
NN eval=0.500597
Playouts: 1, Win: 20.20%, PV: D16
Playouts: 36, Win: 47.15%, PV: Q4 D16 C4 E3 D3 E4 C6 O3 R6 Q3 R3 R2
Playouts: 72, Win: 49.11%, PV: Q4 D16 C4 E3 D3 E4 C6 O3 R6 Q3 R3 R2 P3 Q2 P4 R4 P2 R5 Q6
Playouts: 111, Win: 49.80%, PV: Q4 D16 C4 E3 D3 E4 C6 O3 R6 Q3 R3 R2 P3 Q2 P4 R4 P2 R5 Q6
Playouts: 148, Win: 50.13%, PV: D16 Q4 D3 C5 C4 D5 F3 C14 F17 C16 C17 B17 C15 B16 D15 D17 B15 E17 F16 D10 O17
Playouts: 187, Win: 50.22%, PV: D16 Q4 D3 C5 C4 D5 F3 C14 F17 C16 C17 B17 C15 B16 D15 D17 B15 E17 F16 C10 O17 M17
Playouts: 228, Win: 50.27%, PV: D16 Q4 D3 C5 C4 D5 F3 C14 F17 C16 C17 B17 C15 B16 D15 D17 B15 E17 F16 D10 O17 M17
Playouts: 271, Win: 50.32%, PV: Q4 D16 C4 E3 D3 E4 C6 O3 R6 Q3 R3 R2 P3 Q2 P4 R4 P2 R5 Q6 K3 R14 R12
Playouts: 314, Win: 50.38%, PV: Q4 D16 C4 E3 D3 E4 C6 O3 R6 Q3 R3 R2 P3 Q2 P4 R4 P2 R5 Q6 K3 R14 R12
Playouts: 352, Win: 50.45%, PV: D16 Q4 D3 C5 C4 D5 F3 C14 F17 C16 C17 B17 C15 B16 D15 D17 B15 E17 F16 C10 O17 M17 R3

**Comment by fell111** [comment]
@bood did you set USE_HALF=1 with LZ when compile? I think that will bring some speedup for 1060.

**Comment by l1t1** [comment]
my card
Device driver: 376.62
Device speed:  901 MHz
Device cores:  2 CU
Device score:  1112
Selected platform: NVIDIA CUDA
Selected device: GeForce GT 730
with OpenCL 1.2 capability.
Loaded existing SGEMM tuning.
Wavefront/Warp size: 32
Max workgroup size: 1024
Max workgroup dimensions: 1024 1024 64
BLAS Core: Prescott

C:\leela_lizzie_elf>leelaz_elf --benchmark -w elf_converted_weights.txt -v30 -t2
Thinking at most 2678400.0 seconds...
NN eval=0.500597
Playouts: 1, Win: 20.20%, PV: D16

  Q4 ->      14 (V: 51.10%) (N: 42.93%) PV: Q4 D16 C4 E3 D3 E4 C6 O3 R6 Q3 R3
 D16 ->      13 (V: 50.88%) (N: 43.31%) PV: D16 Q4 D3 C5 C4 D5 F3 C14 F17 C16
  D4 ->       4 (V: 50.54%) (N: 12.65%) PV: D4 Q4 D17
5.6 average depth, 12 max depth
26 non leaf nodes, 1.19 average children
32 visits, 11405 nodes, 31 playouts, 6 n/s

**Comment by fell111** [comment]
>  do I need to re-tune?

There is no need to re-tune. You need to re-compile the source code.
run cmake and add -DUSE_HALF=1.

**Comment by seopsx** [comment]
On GTX 1070:

./leelaz --benchmark -w elf_converted_weights.txt -v3000 -t 2
370 n/s

USE_HALF was enabled.

and ELF:
455 n/s

So on GTX 1070 ELF is 19% more efficient.

**Comment by Hersmunch** [comment]
Is there a way to convert LZ weights to ELF format? These could be used to double check the earlier comparison test using only the ELF code (maybe with some help from FB?)

**Comment by l1t1** [comment]
@Hersmunch you can read the source code in convert.py and exchanhe read and exchange

**Comment by l1t1** [comment]
@Hersmunch you can read the source code in convert.py and exchange read and write

**Comment by sethtroisi** [comment]
A number eval pairings have been queued so this is mostly out of date
