### ISSUE TITLE
ELF's bin file

### ISSUE THREAD

**Issue by d7urban** [leela-zero/leela-zero#1329]
I'd like to test this too. How can I use the pretrained-go-19x19-v0.bin with LZ 0.14? It says the weights file is the wrong version. Do I need to convert it somehow?

**Comment by gcp** [comment]
http://zero.sjeng.org/networks/62b5417b64c46976795d10a6741801f15f857e5029681a42d02c9852097df4b9.gz

**Comment by l1t1** [comment]
there is a link in https://github.com/gcp/leela-zero/issues/1311
could @gcp add the link at the webpage?

**Comment by d7urban** [comment]
Yeah, I found it right after posting the question. But maybe other's are equally slow :)

**Comment by l1t1** [comment]
btw, the 20*256 weights link is removed from webpage too, suggest to add it too

**Comment by gcp** [comment]
>btw, the 20*256 weights link is removed from webpage too, suggest to add it too

Which one? There's been a ton of those networks tested.

**Comment by l1t1** [comment]
my idea is place each arch's current strongest weight (neednot the best ones,eg,a 10*128 network whose winrate is 0.54 to current best 10*128)on webpage to ease people 's different need.

**Comment by l1t1** [comment]
those need may merge them into a phone app as beginer ,midium and expert

**Comment by Marcin1960** [comment]
Is there a version of ELF net, that I can run on KGS using leelaz.exe?

**Comment by roy7** [comment]
@Marcin1960 http://zero.sjeng.org/networks/62b5417b64c46976795d10a6741801f15f857e5029681a42d02c9852097df4b9.gz

**Comment by Marcin1960** [comment]
Than you for an answer. What do I wrong?

leela.exe --tune-only -w elf_62b5
Using 2 thread(s).
RNG seed: 11676533119581502935
Leela Zero 0.13mod  Copyright (C) 2017-2018  Gian-Carlo Pascutto and contributors
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; see the COPYING file for details.

Weights file is the wrong version.

**Comment by roy7** [comment]
Use Leela Zero 0.14.

**Comment by Marcin1960** [comment]
Thanx

**Comment by chilin99999** [comment]
@gcp Excuse me, where is the conversion script to convert ELF Open Go weight file into Leela Zero weight file?
Is there any guide to use it?

**Comment by l1t1** [comment]
i think you want https://github.com/gcp/leela-zero/blob/master/training/elf/elf_convert.py
