### ISSUE TITLE
NetworkException: JSON parse error

### ISSUE THREAD

**Issue by afalturki** [leela-zero/leela-zero#1334]
I got this after running autogtp for the first time. I compiled master myself using VS17 with the sole addition of /DUSE_HALF=1

> AutoGTP v16
Using 1 thread(s) for GPU(s).
Starting tuning process, please wait...
Network connection to server failed.
NetworkException: JSON parse error: illegal value
Retrying in 30 s.
Network connection to server failed.
NetworkException: JSON parse error: illegal value
Retrying in 45 s.

**Comment by roy7** [comment]
@Mardak No idea if this is related to us or not...

**Comment by Mardak** [comment]
This looks like the initial get-task/0 request:
https://github.com/gcp/leela-zero/blob/e1284477eb0c66d41af8c80088cbb488caf20341/autogtp/Management.cpp#L314-L316

 Network connection to server failed.

Maybe the server was down, but I suppose as a sanity check, is this machine the same one you're using now to post to github? Are there other network issues? Retry now?

**Comment by Mardak** [comment]
Although a normal network error would have output more like this:
```
AutoGTP v16
Using 1 thread(s) for GPU(s).
Starting tuning process, please wait...
Network connection to server failed.
NetworkException: Curl returned non-zero exit code 7
Retrying in 30 s.
```

**Comment by roy7** [comment]
Could you share part of your IP address so I can try and locate you in the logs?

**Comment by hydrogenpi** [comment]
and check your bgp routing table

**Comment by afalturki** [comment]
Sorry. I had to leave and just came back. Trying the official executable, autogtp is working correctly. This could be a problem with my autogtp.exe
I'll try compiling again with or without /DUSE_HALF=1 and check if the problem still persists.

**Comment by roy7** [comment]
The only log hits for his IP other than the front page are:

> got task: selfplay {"cmd":"selfplay","hash":"ecab83bb611574a6a3139ae0f9734c172167997a843fbb034dac88246cfd7199","required_client_version":"15","random_seed":"2623174223222226033","leelaz_version":"0.13","options_hash":"df715e","options":{"playouts":"0","visits":"3201","resignation_percent":"5","noise":"true","randomcnt":"999"}}
> got task: selfplay {"cmd":"selfplay","hash":"ecab83bb611574a6a3139ae0f9734c172167997a843fbb034dac88246cfd7199","required_client_version":"15","random_seed":"4411382634033331968","leelaz_version":"0.13","options_hash":"df715e","options":{"playouts":"0","visits":"3201","resignation_percent":"5","noise":"true","randomcnt":"999"}}

**Comment by afalturki** [comment]
This is from using the new official release which was working. Does that mean that my compiled version doesn't even contact the server?

**Comment by Mardak** [comment]
Turns out the output from "curl" was no error and no data, so parsing empty string fails.

**Comment by afalturki** [comment]
Sorry. Forgot to copy gzip and curl to the folder before building.
