### ISSUE TITLE
a method to build a offline training system

### ISSUE THREAD

**Issue by l1t1** [leela-zero/leela-zero#1340]
1. download the binary and source code of Leela Zero 0.14 + AutoGTP v16. and best (or other)network file from http://zero.sjeng.org/, for exmple , ae205d8b 128x10 , copy it to LZbest
2. run   validation -n LZbest.gz -n LZbest.gz -k sgf  again and again to collect self-play games
3. use python srcipt in leela zero source code to build new networks (see reply comment)
4.  run   validation -n new.gz -n LZbest.gz and validation  -n LZbest.gz -n new.gz
if one new is PASSed(what shall I do if only one color is PASSed?), copy it to LZbest, then goto step 2.

did I omit something?

**Comment by l1t1** [comment]
a Chinese document of step 3 can be found at
https://github.com/gcp/leela-zero/issues/1168
,whose name is How_to_Training_Yourself_Weight(CN).docx

**Comment by l1t1** [comment]
**some questions**
1.from the CN document, it seems not only self-play games, but also match games, or sgf from other source can be used for training, it it safe to got a stronger network? eg, if I download raw sgf file from https://sjeng.org/zero/, can I traning a better 128x10 network?
2.can above step be put into a loop sript, so that wo just run it, it would produces better network automaticlly.

**Comment by gcp** [comment]
>match games, or sgf from other source can be used for training

You can, but you lose the distribution of the MCTS search, you will just get 100% on the best move. It will work but perhaps not be optimal.

If you use self-play games, using only the SGF is worse because the moved played will not always be the best.

**Comment by l1t1** [comment]
thanks @gcp

**Comment by sethtroisi** [comment]
closing older issue with no active discussion with many code changes since
