### ISSUE TITLE
Self play leelaz crashed ('Error in OpenCL calculation' with 62b5 net)

### ISSUE THREAD

**Issue by d7urban** [leela-zero/leela-zero#1342]
On Windows 10, with a GTX 1080ti

As usual I run autogtp.exe -g 2, but after about 8 hours of this on leelaz 14 I got this error:

> *ERROR*: Error in GTP response.
> Error read 82 'Error in OpenCL calculation: expected -0.001105 got -0.000890 (error=10.501710%)
> '
> *ERROR*: Error in GTP response.
> Error read 78 'Update your GPU drivers or reduce the amount of games played simultaneously.
> '
>
A little more than an hour later the second leelaz crashes too, but with a "leelaz.exe has stopped working" prompt from windows, and nothing else.

Is it really too much with -g 2 for a 1080ti? I do have the latest drivers (23.21.13.9135), can it be a driver problem? My other machine, with GTX 1060, is happily chugging along at 15+ hours with the same command and no errors.

**Comment by Mardak** [comment]
Does it crash without `-g 2`? The printed error says to try 2 things to maybe avoid the error.

**Comment by jillybob** [comment]
I have run autogtp with -g 2 and my instance crashed overnight. I am not sure what caused the error, it was a prompt from Windows.

**Comment by Hersmunch** [comment]
Are the crashes only with the larger ELF network? Perhaps the accumulation of more small errors is crossing our error threshold?
I imagine it would be pretty awkward to check the error only for one block rather than the entire lot though.

**Comment by gcp** [comment]
>Perhaps the accumulation of more small errors is crossing our error threshold?

It's possible. The failure was right at the threshold.

**Comment by gcp** [comment]
I'll mark this a bug and let's try to see if we have more instances where this happens but only with the ELF network. If so I'll bump the error margin, as it's completely ad-hock.

**Comment by jillybob** [comment]
> Does it crash without -g 2? The printed error says to try 2 things to maybe avoid the error.


It does not crash without -g 2. It only happened with the ELF network self-play.

**Comment by Ttl** [comment]
One difference between ELF network and regular LZ networks is that ELF network has much smaller values for the convolution weights. For example ELF network L2 norm of the input convolution is 0.33 when ecab net's input convolution has L2 norm of 5.9. During inference values in the ELF network are much closer to zero. This could decrease the numerical accuracy in Winograd transformations.

**Comment by jillybob** [comment]
I was running at -t 1 and got the crash in both the latest 15x net and the 20b ELF net.

Microsoft Visual Studio 2017  debug output: Unhandled exception at 0x00007FF63F2BFAD5 in leelaz.exe: Fatal program exit requested. 

Call stack here: https://i.imgur.com/QNVvgSM.png

**Comment by sethtroisi** [comment]
closing older issue with no active discussion with many code changes since
