### ISSUE TITLE
A possible methodology for supporting other value of komi

### ISSUE THREAD

**Issue by bixbyr** [leela-zero/leela-zero#1344]
Although global balance issues depend heavily on komi, most of the knowledge in the lower layers of Leela's network does not depend on komi. Instead of trying to support multiple values with one network, it seems more reasonable to me to fork the network at some advanced state of training and retrain only the upper layers.

The inputs to the top blocks of Leela's network are very rich features for judging how the game is going. Instead of relearning all of these features and starting from scratch to support a new value of komi, we could start with a trained network and freeze the lower layers (probably by marking them as trainable=False in TF). With only the upper 3/15 blocks having learnable weights and the lower 12/15 providing strong features which won't get overridden during the "random" phase of training, I would expect the forked network to be random at first but converge very quickly. Once the network is playing sane recognizable go again, we could unfreeze the lower section of the network and resume normal updates. The portion of the network to freeze would need to be learned, I suspect that relearning 2-3 blocks and the two heads would be enough to bootstrap to a high level of play.

This would require all weight files to specify the komi that they are using in the file, and the server to have separate ratings, etc. It would still obviously take a lot of self play games, but since most of the knowledge is transferable between different komi we could avoid a great deal of redundant work.

**Comment by Ka-zam** [comment]
I think this seems a very reasonable approach.

**Comment by Ishinoshita** [comment]
Agree that once the dust has settle down, this might a very reasonable way to implement this. But we are still climbing the hill, so constantly retraining mutiple networks for multiple komi might not be attractive right now.
BTW, when I first read the paper 'Multi-labelled value network....' , I thought that such architecture might be a must for learning speed, since it seems to allow to make more information flow in the value network. Indeed, if the value network has to learn opposite results for different komi output, it has a priori to refine its evaluation of the board more than a fixed komi NN. Cannot be lazzy ('it's a win game anyway'), has to say it is still a win with komi+1, +2, etc....  I regarded this as possible way to go beyond AG-Lee level. Then came AGZ/AZ with super-human level and the dual head architecture....But I still would be very curious to see this plugged on current LZ.

**Comment by sbf2000** [comment]
In the 9x9 board, I have trained two different komi (6.5 and 7.5) leelaz weights,which is not difficult, as long as it is based on the original weight, It will be possible to change komi to continue training for about 500K selfplay data sets without locking  lower blocks of weight.

**Comment by barrtgt** [comment]
I was just thinking of using alternating komi at two extremes, say half the games use 0 komi and the other half use 14 komi for 19x19. 9x9 should probably use something less extreme like 5 and 9? Would the style be as if it were 7 komi or would you see the network play differently? Maybe it would play for points and not play too conservative when ahead or aggressive when behind?

**Comment by sbf2000** [comment]
The weight of different komi, the style are very diffent.
It is a simple way to think through AI and train komi as an input feature of the network. As long as the Leelazero code can do some improvements on dynamic komi.

**Comment by bixbyr** [comment]
@sbf2000 Most of the feedback that the network gets is it's own judgement of who is winning or losing at the end of a play out. Remember that most games don't even go to count right now. Not the mention that the results of the MCTS will be wrong because the final value network output will be based on what it knew from before. Basically it will be a huge mess.

**Comment by sbf2000** [comment]
@bixbyr As an input feature of the network, komi is fixed at the beginning of a game, and the output of value heads and strategy heads under different komi, the network will learn by itself, without programming solutions.

**Comment by bixbyr** [comment]
@sbf2000 The network might eventually learn yes. But I'd expect to see a very big reversion in it's level of play because most of it's learning it dependent on knowing how to judge who wins (with some probability) at the end of exploring a variation. If you change the rules on it, the value head will have the wrong answers and thus the MCTS will collapse. With millions of games it can figure it out, but that's still a huge regression.

Also, how are you going to add a new feature to the existing network? net2net does some very careful tinkering to keep the existing structure while expanding the size of a network, but it has nothing to say about adding new features part way through training.

**Comment by sbf2000** [comment]
@bixbyr The training a network of adds komi features(assuming V3), which can first use the v2 network to generate enough training data of contain komi feature value, and then start the training again. I guess we can't use the net2net method anymore.

**Comment by gcp** [comment]
I think you can use net2net as long as the additional komi input planes you add are all 0's for a 7.5 komi game.

**Comment by sethtroisi** [comment]
closing older issues, no active discussion for >6 months.
