### ISSUE TITLE
Leela being "conflicted"

### ISSUE THREAD

**Issue by TFiFiE** [leela-zero/leela-zero#1347]
What am I to make of situations in which the most visited child persistently differs from the one with the best win rate, even with lots of thinking time? Example SGF: `(;B[pd];W[dp];B[pp];W[dd];B[cf];W[fc])`

**Comment by gcp** [comment]
Very typical for MCTS search, especially as Leela has no way to extend time for such situations. The best win rate will never be chosen until it accumulates enough visits, because it could be based on a too shallow tree.

**Comment by gcp** [comment]
Going to dupe this to #1307.

**Comment by TFiFiE** [comment]
I intended this issue to be a place to discuss this general phenomenon and must object to it being closed as a duplicate of a more narrow one concerning how time management could take it into account. For one thing, in the example above, I can't get Leela to settle on an unambiguously best move even after giving it much more time than any dynamic time management would have. If anything, this issue is more related to #883.

**Comment by sethtroisi** [comment]
closing older issue with no active discussion with many code changes since
