### ISSUE TITLE
Sharp Increase in ms/move

### ISSUE THREAD

**Issue by jonlave** [leela-zero/leela-zero#1348]
In the last day, I've seen my average ms/move jump from 1500 ms/move to 2500 ms/move (using a 1080 Ti) and we haven't increased the network size. The only thing that's changed from what I can see is the self play parameters, specifically "randomcnt": "999" (I believe this number was much smaller).

**Comment by l1t1** [comment]
check if network used was 62b5417b64c46976795d10a6741801f15f857e5029681a42d02c9852097df4b9.gz?

**Comment by jonlave** [comment]
All of my self-plays are using "hash": "ecab83bb611574a6a3139ae0f9734c172167997a843fbb034dac88246cfd7199" . The ELF network is hash 62b5417b64c46976795d10a6741801f15f857e5029681a42d02c9852097df4b9, right? I'm not seeing that in my history.

**Comment by l1t1** [comment]
could you paste the logs here?

**Comment by Splee99** [comment]
For me it is 10sec per move for the 15 block and 12 sec per move for 20 block (ELF). Leelaz 0.13 uses 7 sec per move before.

**Comment by Hersmunch** [comment]
Since we are limiting visits it makes sense that increasing random count will increase the time to play another move after picking a move with a low visit count.

**Comment by Mardak** [comment]
@Ttl related to the value head and bad moves: what's the behavior of the training data evaluating the win rate one way only to have the final outcome of the game be the opposite because of a completely unrelated random later move leading to a resign?

**Comment by jonlave** [comment]
I did a lz vs lz in Sabaki using similar parameters as the selfplay games. Attempting to the attach the logs here (log3 is black and log4 is white...i think).

[log3.txt](https://github.com/gcp/leela-zero/files/1977861/log3.txt)
[log4.txt](https://github.com/gcp/leela-zero/files/1977862/log4.txt)
[lz_vs_lz_1.sgf.txt](https://github.com/gcp/leela-zero/files/1977863/lz_vs_lz_1.sgf.txt)

**Comment by l1t1** [comment]
leela 0.14 
1 game(s) (1 self played and 0 matches) played in 309 minutes = 18591 seconds/game, 62385 ms/move, last game took 18516
leela 0.13
1 game(s) (1 self played and 0 matches) played in 41 minutes = 2485 seconds/game, 31858 ms/move, last game took 2483 sec

**Comment by sethtroisi** [comment]
closing older issue with no active discussion with many code changes since
