### ISSUE TITLE
Abnormal game information and result

### ISSUE THREAD

**Issue by ohseong** [leela-zero/leela-zero#1350]
This elfgo's match game is abnormal.
http://zero.sjeng.org/viewmatch/81aff1f0a0587d2a90e85067b942542b997b0e1e9207c709f64d307b3decf2ad?viewer=wgo

**Comment by Mardak** [comment]
What part of the result is abnormal? The sgf does look a little different from the other sgf from the same client. I would guess it's because autogtp was stopped then resumed.
```sgf
(;GM[1]FF[4]RU[Chinese]DT[2018-05-06]SZ[19]KM[7.5]TM[3600]PB[Leela Zero 0.14 73a12e72]PW[Human]RE[W+Resign]C[Leela Zero options: -p 0 -v 3200 -r 5 -m 0 -t 1 -d --noponder -s 14722774367143322853 -g -q -w networks/73a12e721c668db435794b38304e686550974d2cb2895280bfdc69699afc10d5];
```

Compared to an earlier submitted game from client 18:
http://zero.sjeng.org/viewmatch/a207cb944bb56f07077f93d61015b217009368413d162cf5ede6c86a1d74b6c0?viewer=wgo
```sgf
(;GM[1]FF[4]RU[Chinese]DT[2018-05-05]SZ[19]KM[7.5]PB[Leela Zero 0.14 62b5417b]PW[Leela Zero 0.14 73a12e72]RE[B+Resign] C[Leela Zero options: -p 0 -v 3200 -r 5 -m 0 -t 1 -d --noponder -s 12086142049257655345 -g -q -w networks/62b5417b64c46976795d10a6741801f15f857e5029681a42d02c9852097df4b9]
```

In particular, the potentially resumed game has `TM[3600]` and the default `PW[Human]`

**Comment by ohseong** [comment]
It was also reported as a Black'win.

**Comment by rchs819** [comment]
My observation:
B stopped playing after move 209 (not even playing pass)
W just continued to play till move 240

**Comment by Mardak** [comment]
Oh indeed, this is the tail end of the broken game:
```sgf
B[og];W[oh];W[ia];W[ka];W[qg];W[er];W[rg];W[nr];W[dq];W[jr];W[cq];W[la];W[bp];W[na];W[co];W[pa];W[ks];W[sa];W[lr];W[lg];W[ms];W[mg];W[le];W[mh];W[ld];W[li];W[ke];W[ki];W[jd];W[jf];W[id];W[kf])
```

**Comment by roy7** [comment]
Well that seems very very broken. If the bot playing black flat out died, autogtp would detect that somehow? I don't know how white keeps playing with no black moves at all.

**Comment by marcocalignano** [comment]
@roy7 can you have a look in the database and see if other matches have the second player "Human"?

**Comment by roy7** [comment]
I can't easily do that, it'd take a full collection scan/regex match and the server might kill me if I try. :) Perhaps @gcp could do it on his local machine after moving the data off the server, or just grep it from his raw game SGF dump files once the next batch are made?

**Comment by sethtroisi** [comment]
closing older issue
