### ISSUE TITLE
if a sgf was uploaded fail, could it be upload again? how to do so if can?

### ISSUE THREAD

**Issue by l1t1** [leela-zero/leela-zero#1359]
I have a game played more than 5 hours.
https://github.com/gcp/leela-zero/issues/1348#issuecomment-386960870

**Comment by hydrogenpi** [comment]
it says 41 minutes. where you get 5 hours from?

**Comment by l1t1** [comment]
@hydrogenpi 41m for leela0.13 with network LZ130
5h for leela0.14 with  network LZ132
