### ISSUE TITLE
could you save the played games in local and retry upload when is ok?

### ISSUE THREAD

**Issue by l1t1** [leela-zero/leela-zero#136]
the game time became longer, but server some time down. all works are wasted.

<FONT face="Helvetica">
The Web Server may be down, too busy, or experiencing other problems preventing it from responding to requests. You may
wish to try again at a later time.
</FONT>
</TD></TR>
<TR><TD>
<FONT face="Helvetica" SIZE=2>
<BR>
For assistance, contact your network support team.
</FONT>
</TD></TR>
</TABLE>
</blockquote>
</FONT>
</BODY></HTML>
2 game(s) played in 372 minutes = 11180 seconds/game, last game took 10780 seconds.

**Comment by gcp** [comment]
See pull request #130.

**Comment by FransFaase** [comment]
Could it be possible to introduce an option to keep the sgf files after they are submitted? I would like to see the games that were played on my machine.

**Comment by marcocalignano** [comment]
Use the ption -k --keep and add the name of a directory after it.

**Comment by l1t1** [comment]
fail upload did not retry yet in v0.8，
<pre>
5 game(s) played in 322 minutes = 3865 seconds/game, 10104 ms/move, last game took 4321 seconds.
curl.exe -F networkhash=2184b7500795533b97a40cc83bdfd51d1f18183c6e76d7cca3053237e0f18c7c -F clientversion=7 -F sgf=@7739
e6b645b945b0aa5cd6cf2753bd8f.sgf.gz -F trainingdata=@7739e6b645b945b0aa5cd6cf2753bd8f.txt.0.gz http://zero.sjeng.org/sub
mit
Upload failed. Curl Exit code: 52
Continuing...
</pre>

**Comment by sethtroisi** [comment]
This is now supported.
