### ISSUE TITLE
leelaz 0.13 abnormal exit when installing latest nivida driver

### ISSUE THREAD

**Issue by l1t1** [leela-zero/leela-zero#1360]
are  they conflict?

**Comment by l1t1** [comment]
from
Initializing OpenCL.
Detected 1 OpenCL platforms.
Platform version: OpenCL 1.2 CUDA 8.0.0
Platform profile: FULL_PROFILE
Platform name:    NVIDIA CUDA
Platform vendor:  NVIDIA Corporation
Device ID:     0
Device name:   GeForce GT 730
Device type:   GPU
Device vendor: NVIDIA Corporation
Device driver: 376.62
Device speed:  901 MHz
Device cores:  2 CU
Device score:  1112
Selected platform: NVIDIA CUDA
Selected device: GeForce GT 730
with OpenCL 1.2 capability.

---

to
Initializing OpenCL.
Detected 1 OpenCL platforms.
Platform version: OpenCL 1.2 CUDA 9.1.84
Platform profile: FULL_PROFILE
Platform name:    NVIDIA CUDA
Platform vendor:  NVIDIA Corporation
Device ID:     0
Device name:   GeForce GT 730
Device type:   GPU
Device vendor: NVIDIA Corporation
Device driver: 391.35
Device speed:  901 MHz
Device cores:  2 CU
Device score:  1112
Selected platform: NVIDIA CUDA
Selected device: GeForce GT 730
with OpenCL 1.2 capability.

**Comment by tterava** [comment]
I've also had some issues with NVidia's latest drivers. Sometimes the computer is left in a state where clGetPlatformIDs() fails and basically the entire GPU is unable to do anything else but normal 2D operation. It doesn't seem to be a hardware issue because logging out & back in fixes the issue.

**Comment by bastiaf** [comment]
@tterava: 
I have the same problem, and after that a reboot is necessary. Or is there a more simple solution?

But in that case the output of Leela is »OpenCl: clGetPlatformIDs()«.

**Comment by tterava** [comment]
Just logging out of Windows and back in seems to fix the issue for me. I've only tested it once though.

**Comment by gcp** [comment]
NVIDIA has issued a hotfix for their drivers now.
