### ISSUE TITLE
terminate called after throwing an instance of 'cl::Error'

### ISSUE THREAD

**Issue by JDJoe** [leela-zero/leela-zero#1363]
`genmove w
Thinking at most 3599.9 seconds...
NN eval=0.297472
terminate called after throwing an instance of 'cl::Error'
  what():  clFinish
`
For some reason I keep getting this error. 

03:00.0 VGA compatible controller: NVIDIA Corporation GP102 [GeForce GTX 1080 Ti]
nvidia-driver etc are all 390

**Comment by gcp** [comment]
Did you recently update drivers? See #1360. But 390 is the "stable" Linux series, I think.

**Comment by Ka-zam** [comment]
Distro?

What does clinfo show?
