### ISSUE TITLE
Ke Jie said pros in CHINA already use leelazero to self training

### ISSUE THREAD

**Issue by l1t1** [leela-zero/leela-zero#1364]
https://m.weibo.cn/status/4237111198527346

**Comment by l1t1** [comment]
When I was training in the training room today, I had a difficult part to explain. A certain professional player seconds to say local winning percentage... I asked how he knew [laugh cry] he said he used his own computer The leela zero swings... After learning more about it, I realized that a lot of professional players have started training like this! [Let's] The AI used for training is also varied... For example, Facebook recently opened up an AI, and its strength is far beyond professional players! [Laughing cry] How do you know if you're unfamiliar? I don't want to start spending money to buy a supercomputer to run AI training. [Tolerable sadness] Do you still learn programming now? [ Disappointed]

**Comment by Alderi-Tokori** [comment]
@AlexanderMisel LZ is already beating pros consistently, I don't see why it's "not strong enough".

**Comment by john45678** [comment]
Even a most conservative estimate says LZ is well able to beat pros on good hardware.

**Comment by Yakago** [comment]
Also one of the biggest strengths of these is evaluation. AIs sometimes lose due to tactical mistakes, but when that doesn't happen they're very difficult to beat

**Comment by Eddh** [comment]
I don't think he's not saying it's not strong enough to beat pros, but not strong enough to be a reference. Because of the known weaknesses in ladder and sometimes tactical weakness or blindspots, he's kind of right about that.

**Comment by tterava** [comment]
I think people are reading way too much into those weaknesses than they should. LZ doesn't have a problem with ladders if you give it enough playouts and you're not playing a handicap fuseki. Also the "blindspots" are not what humans typically mean with the term. A blindspot for LZ means that it misses a good move 15 moves down the line, a move that many humans can't make even if they are in that situation. Let alone see it from 15 moves before.

If pros use each others' games for reference, as they have done for thousands of years, then there's no reason why they wouldn't be able to use LZ's games as reference too. I would even argue they are the highest level games currently available, apart from games generated by ELF and those released by AGZ. LZ is by far the best analyzing tool they have at their arsenal and like Ke Jie said, anyone not using them will surely get left behind by those who do.

**Comment by gcp** [comment]
>not strong enough to be a reference for pros. At least it should grow to the level Facebook OpenGo
...
>Because of the known weaknesses in ladder

🙄

Not sure pro's are that a good an objective reference for program strength, see also https://github.com/gcp/leela-zero/issues/1346#issuecomment-386989521

**Comment by Eddh** [comment]
When it was 6 block and high dan level, I could still see games in which it made game-changing mistakes most double digit kyu could avoid, I saw it lose because of a square four on a large dragon for which I assume it couldn't count the liberties. There was also still self-atari happening when it was 10 block, and If I remember right there was also a game-losing self atari in a match game with a 15 block net. 

It is far, far stronger than a double digit kyu like me, even on 1 playout, but still, there are particular positions which it fails to understand sometimes. As the size of the net and the training progress, they have become more and more rare, but essentially, it means that you can't just look at an evaluation by LZ and just accept it as truth without thinking just because it's LZ, and I think that's what being a reference mean. It's superhuman but not 1000 elo higher superhuman like in Chess.

**Comment by dfannius** [comment]
> you can't just look at an evaluation by LZ and just accept it as truth without thinking just because it's LZ, and I think that's what being a reference mean

For what it's worth, this is true with chess engines too, particularly in endgames where one player has a material advantage but has no concrete way to make progress. You are pretty safe in the middlegame, though.

**Comment by ChinChangYang** [comment]
@l1t1 The translation is slightly wrong. I would like to translate the post later.

**Comment by ChinChangYang** [comment]
Ke Jie:
Yesterday 18:38 from iPhone X
Today, when I was training in a training room, there was a go game that had a local part which was difficult to be solved. A professional player could tell the win rate of the local variation very fast. I asked him how do you know that. He said he used leela zero to play the game on his own computer. After deeply understanding that, I realized many profession players have already started this kind of training methods. There are many variant AI that are used for training. For example, facebook recently open-sourced an AI. The strength is far beyond professional players. How'd I be behind the times unconsciously? Should I begin to make money to buy a super-computer to run AI training? Is it not too late to learn programming?

**Comment by WesleyDeng** [comment]
"During today's training I encountered a very complicated local position. Another professional pointed out the winrate change right away. I asked him how he knew and he said he had checked this position with Leela Zero on his computer. Then, I found out many professional players had already started using various AI's in their training. For example, FB recently released an open source AI which is way stronger than professional players. I feel like I am behind. Should I start saving money to buy a super computer for AI training? Is it too late for me to start learning programming?" --- Ke Jie

**Comment by hydrogenpi** [comment]
Tell Ke Jie he doesnt need to learn programming. And a gtx 970 should suffice. No need for supercomputer, not even a V100. Even TitanV is a waste. 1080ti max is all thats needed now

**Comment by hydrogenpi** [comment]
In the age of UBI and AGI the real question is if its too late for aspiring devs to learning programming, laughable the question for a Go professional to learn programming.

**Comment by AlexanderMisel** [comment]
Leela Zero is a nice analyzing tool, and we could learn some strong moves and variations. So it's helpful. 

What I want to say is, whether a specific move played by LZ is stronger than human or not may be hard for a human player to tell, even for pros.

A reference go program I mean, should keep playing strongly, and has state-of-the-art evaluation system. For recent test experiences, for example ladders, more playouts do prevent continuing playing ladders, but stronger network prevents ladders from a fairly early move, and that's the way of play, pros need to learn.

**Comment by ChinChangYang** [comment]
@WesleyDeng Thanks, there is always a better translation.

**Comment by l1t1** [comment]
@WesleyDeng Thanks, i used google translation :(. it seems a fileld that AI is weaker than human, off topic

**Comment by hydrogenpi** [comment]
http://archive.is/a3b4I

**Comment by sethtroisi** [comment]
closing older issues
