### ISSUE TITLE
LINK : fatal error when I Define "USE_TUNER"

### ISSUE THREAD

**Issue by zliu1022** [leela-zero/leela-zero#1369]
Hi, All
It's a Technical support issue.

By using **MSVC 2017**, **leela-zero 0.14 master** branch.
When I define USE_TUNER, the LINK error will happen, the log is quoted below.
I found if change `("puct", po::value<float>())` to `("puct", po::value<int>())`, everything will be ok.
So , can anyone can help me ?

Thank you.

> 1>LINK : fatal error C1001: An internal error has occurred in the compiler.
> 1>(compiler file 'f:\dd\vctools\compiler\utc\src\p2\main.c', line 258)
> 1> To work around this problem, try simplifying or changing the program near the locations listed above.
> 1>Please choose the Technical Support command on the Visual C++
> 1> Help menu, or open the Technical Support help file for more information
> 1>  link!InvokeCompilerPass()+0x1f1b9
> 1>  link!InvokeCompilerPass()+0x1ebd3
> 1>  link!DllGetC2Telemetry()+0x10769b
> 1>
> 1>LINK : fatal error C1001: An internal error has occurred in the compiler.
> 1>(compiler file 'f:\dd\vctools\compiler\utc\src\p2\main.c', line 258)
> 1> To work around this problem, try simplifying or changing the program near the locations listed above.
> 1>Please choose the Technical Support command on the Visual C++
> 1> Help menu, or open the Technical Support help file for more information
> 1>  link!InvokeCompilerPass()+0x1f1b9
> 1>  link!InvokeCompilerPass()+0x1f1b9
> 1>  link!InvokeCompilerPass()+0x1ebd3
> 1>  link!DllGetC2Telemetry()+0x10769b
> 1>
> 1>LINK : fatal error LNK1000: Internal error during IMAGE::BuildImage
> 1>
> 1>
> 1>  Version 14.12.25831.0
> 1>
> 1>  ExceptionCode            = C0000005
> 1>  ExceptionFlags           = 00000000
> 1>  ExceptionAddress         = 5F4736E6 (5F040000) "d:\vs\2017\Community\VC\Tools\MSVC\14.12.25827\bin\HostX86\x64\c2.dll"
> 1>  NumberParameters         = 00000002
> 1>  ExceptionInformation[ 0] = 00000000
> 1>  ExceptionInformation[ 1] = 1855F5FC
> 1>
> 1>CONTEXT:
> 1>  Eax    = 1855F5FC  Esp    = 0025E830
> 1>  Ebx    = 0E140483  Ebp    = 0025E860
> 1>  Ecx    = 00000005  Esi    = 1855F5FC
> 1>  Edx    = 05B4002C  Edi    = 0025E840
> 1>  Eip    = 5F4736E6  EFlags = 00010206
> 1>  SegCs  = 00000023  SegDs  = 0000002B
> 1>  SegSs  = 0000002B  SegEs  = 0000002B
> 1>  SegFs  = 00000053  SegGs  = 0000002B
> 1>  Dr0    = 00000000  Dr3    = 00000000
> 1>  Dr1    = 00000000  Dr6    = 00000000
> 1>  Dr2    = 00000000  Dr7    = 00000000
> 1>Done building project "leela-zero.vcxproj" -- FAILED.
> ========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by gcp** [comment]
>LINK : fatal error C1001: An internal error has occurred in the compiler.

It's a compiler bug. Is this the very latest MSVC 2017 update?

**Comment by gcp** [comment]
>LINK : fatal error C1001: An internal error has occurred in the compiler.

It's a compiler bug. Is this the very latest MSVC 2017 update?
