### ISSUE TITLE
Could you support https for zero.sjeng.org

### ISSUE THREAD

**Issue by ivysrono** [leela-zero/leela-zero#1373]
https://zero.sjeng.org/
Mismatched now.

**Comment by gcp** [comment]
Probably. I didn't want to mess around with this too much while the project is running.

**Comment by updatede** [comment]
@gcp
You should apply a wildcard certificate if you use many subdomains. Letsencrypt support wildcard certs now.

**Comment by gcp** [comment]
Certificates aren't a problem.
