### ISSUE TITLE
Note: Old (failed) networks archive moved

### ISSUE THREAD

**Issue by gcp** [leela-zero/leela-zero#1381]
I'm going to clean out:
http://zero.sjeng.org/networks/

and move old, not-promoted networks to:
http://storage.sjeng.org/networks/

**Comment by l1t1** [comment]
nice job

**Comment by l1t1** [comment]
could you keep the timestamp info of each file for easy find useful networks. for exmaple, the last tested 6x128 file?

**Comment by gcp** [comment]
The timestamps are preserved.

**Comment by l1t1** [comment]
@gcp I notice it, so i changed the reply and paste pictures

**Comment by gcp** [comment]
No, it requires an extra nginx module and that makes security updates problematic. It's already a huge nuisance on zero.sjeng.org.

**Comment by l1t1** [comment]
solved, I saved both webpages, and use first one find the file names, then look up it in second, but for newer files, I must use tool such as excel to sort them

**Comment by l1t1** [comment]
could you also supply a list of network names with whose final winrate? I want to get the strongest file of each architecture.

**Comment by gcp** [comment]
I don't have anything like this. I guess the match results could be dumped from the server in JSON format or something.

**Comment by gcp** [comment]
By the way, retraining with new data likely will produce stronger small networks.

**Comment by Mardak** [comment]
Do you want the win rate or just elo? The graph on the home page uses http://zero.sjeng.org/data/elograph.json to plot points.

**Comment by fohristiwhirl** [comment]
Here's a simple minded Python script to sort, view and download files...

<details><summary>Click to expand</summary>

```python
import os, re, requests

pattern = re.compile(r"<a href=\"(.+)\">.+<\/a>(.+)\s{2,}(\d+)")

months = {
	"Jan" : "01",
	"Feb" : "02",
	"Mar" : "03",
	"Apr" : "04",
	"May" : "05",
	"Jun" : "06",
	"Jul" : "07",
	"Aug" : "08",
	"Sep" : "09",
	"Oct" : "10",
	"Nov" : "11",
	"Dec" : "12",
}

nets = []

r = requests.get("http://storage.sjeng.org/networks/")
lines = r.text.split("\n")

for line in lines:

	try:
		filename, dt_raw, size = re.search(pattern, line).group(1, 2, 3)
		dt = dt_raw.strip().split()
		date = dt[0].split("-")
		time = dt[1]
		date_fixed = date[2] + months[date[1]] + date[0] + time[0:2] + time[3:5]
		nets.append([filename, date_fixed, size])

	except AttributeError:
		pass

nets.sort(key = lambda x : x[1])

for i, net in enumerate(nets):
	print("{0:>3}:  {1:>67}  {2}  {3}".format(i, net[0], net[1], net[2]))

while 1:

	s = input("Download item index? (0-{}) ".format(len(nets) - 1))

	if len(s) == 0:
		continue

	try:
		n = int(s)
	except:
		continue

	if n < 0 or n >= len(nets):
		continue

	filename = nets[n][0]

	if not os.path.exists(filename):
		url = "http://storage.sjeng.org/networks/{}".format(nets[n][0])
		f = requests.get(url)
		with open(filename, "wb") as output:
			output.write(f.content)
```

</details>

**Comment by l1t1** [comment]
thanks
