### ISSUE TITLE
question about 1 playout match between facebook weight(62b5417b)

### ISSUE THREAD

**Issue by zliu1022** [leela-zero/leela-zero#1393]
I test elf weight 1 po match because it's fast, maybe it's meanless I am not sure. 
1. 0.13 vs 0.14 1000 match
2. 0.13 vs 0.14 5000 match
*Note: This 0.13 is only modified elf weight support.*

### Wish to use the result to do fast verification
1. Verify different network evaluation engine's strength, like 0.13 and 0.14
2. Just guess because not so much test, under less playouts, like 3200 visits, using in lz's weight match, 1 playouts match result will be very similar to v3200 match results(I can paste the 1po match between elf and other lz-weight latter). If this is ok, maybe we don't need v3200 match , **1 po match is enough to find the better weight**.
Let the loss in training to balance value between policy. Once 1po is stronger, so weight can promote.
3. When a specific network (? block x ? filter) is fully learned (include self play and network train), the policy head should have very small difference with value head, only the enough big playout will show the difference and improve the strength. So also **1po match maybe a good benchmark to check the network whether it's fully learned**
Judge a network is fully-learned is more efficient to save community's power and find the stronger weight in the future.

All match is using gogui-twogtp to make it run:
```
gogui-twogtp.exe 
-black "d:\go\leela-zero-0.13-win64\leelaz.exe -g -d -r1 -t2 -p1 --noponder --timemanage off -w d:\go\weight\62b5417b64c46976795d10a6741801f15f857e5029681a42d02c9852097df4b9" 
-white "d:\go\leela-zero-0.14-win64\leelaz.exe -g -d -r1 -t2 -p1 --noponder --timemanage off -w d:\go\weight\62b5417b64c46976795d10a6741801f15f857e5029681a42d02c9852097df4b9.gz" 
-size 19 -komi 7.5 -alternate -games 1000 -sgffile elf-p1_vs_elf-p1-1000 -auto -time 7200m
```

The result is:

result  | total | b | w | win | bwin | wwin | rate | brate | wrate
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- |
1 | 1000 | 500 | 500 | 399 | 299 | 100 | 39.9% | 59.8% | 20.0%
2 | 5000 | 2500 | 2500 | 3022 | 1426 | 1596 | 60.4% | 57.0% | 63.8%

It looked strange, when 0.13 take white, it has only 20% win rate.
Already test 0.13_elf_vs_0.13_elf and 0.14_elf_vs_0.14_elf, 1 playout 1000 match, the result looks more balanced, 45%~50%.
After check the result, find gogui-twogtp will mark the duplicate match.

GAME | RES_B | RES_W | RES_R | ALT | DUP | LEN | TIME_B | TIME_W 
-- | -- | -- | -- | -- | -- | -- | -- | -- |
12 | W+R | W+R | W+R | 0 | 4? | 136 | 1.5 | 1.7 | 0 | 0 | 0	
14 | W+R | W+R | W+R | 0 | 12 | 136 | 0.1 | 0.4 | 0 | 0 | 0	

which means match No.14 is duplicate as No.12

So **after removed all duplicate match** and get another result:

no dup  | total | b | w | win | bwin | wwin | rate | brate | wrate
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- |
1  |  264 | 147 | 117 | 127 | 77 | 50 | 48.1% | 52.4% | 42.7%
2  |  1587 | 752 | 835 | 803 | 382 | 421 | 50.6% | 50.8% | 50.4%

### Before to do fast verification , some question appears
1. During SPRT match , if some match is duplicated, is it need to be thrown away?
2. Is it any difference between 0.13 and 0.14 's network evaluation for 1 playout?

**Comment by jkiliani** [comment]
I don't think 1 playout matches are meaningless, since they do measure the evaluate the quality of the highest policy move and should be strongly correlated to test accuracy for that reason. Of course, they do not accurately reflect the playing strength under normal conditions, i.e. with tree search. I did some experiments testing nets at low playouts a while ago, in https://github.com/gcp/leela-zero/issues/667 in the hope that low playouts could predict match results at high playouts. It turned out this was not feasible however.

There's nothing wrong with testing the strength of different nets at 1 playout though, it may be interesting for people who want to play against Leela Zero without being Go professionals.

I would however recommend that when posting test results, you bracket your results with ``` to format them so other people can better read them, and put the column at the top with the same formatting.

**Comment by roy7** [comment]
I do want to remind everyone the policy network isn't learning the best moves, it's learning the moves that need to get the most research to win the game. This is slightly different than a policy network predicting pro moves in something like Leela v11.

Take ladders for instance, the policy network masters ladders by using a high prior to search them.

**Comment by Ishinoshita** [comment]
Policy and value head share most ofy nn layers, so I would expect progresses of both head to be somewhat correlated. While reading AGZ paper, I was awestruck by the fact that the policy head itself (greedy play, i.e. 1 po) was rated as ~3000 Elo ~ Fan Hui level (2p). So, to me, it's a way to gauge the overall nn. I was frustrated that AZ paper did not provide similar evaluation for chess. Would have been even more striking for computer chess/ chess players community to realize that 'something' doing no search at all can reach such or such Elo.

**Comment by Ishinoshita** [comment]
@roy7: Fully remind it, but my point here above still stands, even more regarding a nn that has not been optimised for winning but for feeding the search with good prior.

**Comment by roy7** [comment]
An experiment one could run is to pull a nn_eval on every child node, and select the move with the highest value head.

**Comment by Ishinoshita** [comment]
Initial AG paper did it. Both would be  interesting metrics.

**Comment by zliu1022** [comment]
Though I wish to use 1 playout match to do something big, but I am stuck at the first :-). I need to check the different version engine's strength. So I do 1 playout match 1000 match using only 0.13 and only 0.14 and then 0.13 vs 0.14. 

0.13-elf-1po_vs_0.13-elf-1po-1000
0.14-elf-1po_vs_0.14-elf-1po-1000
These result looks normal, the winrate is about 45%~50%.

But when I do 0.13-elf-1po_vs_0.14-elf-1po-1000, the 0.13-white-winrate is 20%.
So then I do 5000 match and remove the duplicate match. The result looks normal.

I update the first post , for easy to read and also put the question here:
1. During SPRT match , if some match is duplicated, is it need to be thrown away?
2. Is it any difference between 0.13 and 0.14 's network evaluation for 1 playout?

**Comment by zliu1022** [comment]
Also paste the 1 po, 1000 matchs result between elf and 73a12 , b6337, all match is used 0.13 engine with only elf support.

```
elf_vs_73a12: 87.9% (83.5%)
elf_vs_b6337: 95.5% (84.4%)
```
*Note: The rate inside bracket is after removing duplicate match.*

Not so much comparsion, but the trend looks right, elf is more stronger during match between 73a12 and b6337.

**Comment by zliu1022** [comment]
1 po, 1000 match between elf and 90560, v13(75654) and recent weight by using 0.13 engine with only elf support.
```
	nodup	all
90560	73.0%	67.1%
v13	77.1%	80.7%
b6337	80.3%	86.9%
05b72	79.2%	70.2%
2fb02	81.6%	83.2%
4be6f	81.3%	88.6%
3737d	80.4%	87.0%
v12	81.4%	82.4%
73a12	83.5%	87.9%
ecab8	83.9%	83.8%
18e6a	84.8%	84.5%
cfb2c	83.1%	91.9%
15860	81.6%	84.0%
```
Note: nodup means after removing duplicate match.
The trend looks well with v3200 match.

**Comment by zliu1022** [comment]
I make a mistake that some more match is removed as duplicated. The new result list below:

  | rate(nodup) | rate
-- | -- | --
elf_v_elf | 49.6% | 43.3%
  |   |  
b6915-0.13 | 83.0% | 82.6%
9e882-0.13 | 83.5% | 84.1%
057ad-0.13 | 84.4% | 87.0%
7c658-0.13 | 85.2% | 84.0%
11057-0.13 | 82.1% | 81.1%
521b0-0.13 | 87.5% | 89.9%
a39b6-0.13 | 86.5% | 91.2%
d8214-0.13 | 85.7% | 87.6%
90560-0.13 | 79.9% | 68.5%
v13-0.13 | 81.2% | 81.9%
b6337-0.13 | 86.4% | 90.8%
05b72 | 89.1% | 80.0%
2fb02 | 88.4% | 84.2%
4be6f | 84.7% | 89.3%
3737d | 84.7% | 88.4%
v12 | 82.2% | 82.8%
73a12 | 89.0% | 90.9%
ecab8 | 87.1% | 84.3%
18e6a | 89.6% | 86.5%
cfb2c | 87.4% | 92.9%
15860 | 89.7% | 84.8%

**Comment by zliu1022** [comment]
Update again.
Each match is 1000 games, but some weights looks like duplicate move.


  | games(nodup) | total-rate(nodup)
-- | -- | --
elf | 682 | 49.6%
e1d46-0.13 | 769 | 76.6%
8ca0e-0.13 | 819 | 77.3%
67234-0.13 | 789 | 81.1%
v16-c010f-0.13 | 695 | 69.6%
12692-0.13 | 679 | 82.2%
2b80a-0.13 | 899 | 76.6%
c6e15-0.13 | 912 | 74.9%
5839e-0.13 | 646 | 81.9%
V15-fee68-0.13 | 811 | 73.9%
d0187-0.13 | 652 | 76.5%
5b59a-0.13 | 751 | 81.4%
10bc1-0.13 | 901 | 77.5%
0cb74-0.13 | 877 | 76.3%
b6915-0.13 | 875 | 83.0%
9e882-0.13 | 757 | 83.5%
057ad-0.13 | 507 | 84.4%
7c658-0.13 | 732 | 85.2%
11057-0.13 | 491 | 82.1%
521b0-0.13 | 465 | 87.5%
a39b6-0.13 | 547 | 86.5%
d8214-0.13 | 420 | 85.7%
90560-0.13 | 393 | 79.9%
v13-0.13 | 393 | 81.2%
b6337-0.13 | 535 | 86.4%
05b72 | 322 | 89.1%
2fb02 | 181 | 88.4%
4be6f | 295 | 84.7%
3737d | 367 | 84.7%
v12 | 766 | 82.2%
73a12 | 661 | 89.0%
ecab8 | 263 | 87.1%
18e6a | 589 | 89.6%
cfb2c | 238 | 87.4%
15860 | 117 | 89.7%

**Comment by sethtroisi** [comment]
closing older issue with no active discussion and many models since
