### ISSUE TITLE
Leela-analyser

### ISSUE THREAD

**Issue by aviczhl2** [leela-zero/leela-zero#1394]
Is there an analysis code which , given an sgf file, automatically returns the level of players based on leela-zero network winrate change? 
Does anyone need this?
 I wonder if there already is one, or if l make one and add it into the leela-zero system, will it be welcomed?

**Comment by bjiyxo** [comment]
How to define "the players' level based on leela-zero network win rate change"? Is there any function describing it?

**Comment by Ishinoshita** [comment]
@aviczhl2:  I had imagine something similar a while ago, using Leela not LZ: for each position encountered in the sgf, let Leela analyse the position with some sufficient playouts and record visit counts (or win rate or average accumulated value) of Leela best move and sgf actual move. After the game bas been reviewed, for each side in the sgf (B&W) calculate an indicator of some sort to evaluate the gap between what has been played and what Leela thinks should have been played. Like average difference or log likelyhood, KL div., etc....Don't know if that would be meaningful in the end.

**Comment by ThorAvaTahr** [comment]
It will become necessary to find ways of detecting human/robot play to prevent cheating. The first cases of Go-cheating with engines have appeared already.

In chess I believe there is a good engine detection possible, I am not sure this works with go as well.

**Comment by MichaelMarkefka** [comment]
It would also be interesting to have a rank-related move choice probability distribution over move winning rate probabilities to calibrate LZ as a very human-like opponent at different ranks.

**Comment by sethtroisi** [comment]
closing older issues, no discussion for >6 months

This is best handled by lizzie or Minigo's minigui
