### ISSUE TITLE
networks directory name is hardcoded and not gitignored

### ISSUE THREAD

**Issue by arnaudgo** [leela-zero/leela-zero#1399]
Hello,

networks directory shows up with git status command.

`main.cpp:138:    if (!QDir().mkpath("networks")) {`

Arnaud

**Comment by marcocalignano** [comment]
You need to ignore it only if you decide to run autogtp from inside the same tree where your git repository is and not from another 'installation' path

**Comment by arnaudgo** [comment]
Indeed @marcocalignano you're right :) The point is that if you follow step by step the README.md of autogtp you're invited somehow to proceed that way.

```
Copy the compiled leelaz binary into the autogtp directory, and run
autogtp.

    cp ../src/leelaz .
```

Arnaud
