### ISSUE TITLE
Recommend opening Wiki now to allow for community-managed documentation of LZ's status, FAQs, past and future milestones, plans, and more.

### ISSUE THREAD

**Issue by AncalagonX** [leela-zero/leela-zero#1404]
With the continued growth of the Leela Zero community, it's become apparent to me that our user-facing documentation is a bit sparse, not least of which because the project is demonstrating its flexibility and willingness to quickly adapt to new proposals on a weekly basis. This makes it hard not just for newcomers but for regulars as well to keep track of the current status of any number of aspects of the network, training process, and so on.

Thereofre, in order to address a variety of repeated questions, misconceptions, and other spurious non-development posts, as well as to provide a collective area for the community document the current status, developments, decisions, and milestones of the Leela Zero project, could we please begin to parcel out access to the Wiki so that the community can eagerly begin the group project of populating it with useful and relevant information to everyone's benefit?

Access may be best handled on a "request first, and get approved" basis and limited to a select (but large enough) group in order to ensure both the quality and content of the Wiki are always appropriate, accurate, and when need be back by the relevant expertise need to address some of the more esoteric aspects of LZ that frequently arise.

I truly hope the gcp and other community heads come to agree with how beneficially a collective Wiki would be in organizing the widespread information scattered across numerous PRs as well as over 1000 individual issue threads, becoming more and more difficult by the day to find the relevant information one might be searching.

Thanks for your sincere consideration. This small change could very quickly greatly benefit the Leela Zero community for the better, over both the short and long run of the project. Thank you.

**Comment by gcp** [comment]
It seems github doesn't have any granularity between "allow access to people with push access" and "allow anyone access".

**Comment by sethtroisi** [comment]
closing older issues, no discussion for >6 months
