### ISSUE TITLE
Anyone know how to play a match between LeelaZeros on two PC 

### ISSUE THREAD

**Issue by kris-computer-go** [leela-zero/leela-zero#1407]
What is the easy way to make a  match within two PC on same network or through internet.
I would like to autoplay many games to compare two LZ weights.

**Comment by MartinDevelopment** [comment]
You can run them on KGS using GTP and keep letting them play against eachother. http://files.gokgs.com/javaBin/kgsGtp-3.5.22.zip

**Comment by kris-computer-go** [comment]
Is it using the tournament mode? How to configure both sides?

**Comment by MartinDevelopment** [comment]
If using KGS you can specify in the config file for Player 1: mode=custom opponent=[Player2]
and in the config file for Player 2: mode= wait opponent=[Player1]

This should keep running games without a problem.

**Comment by Friday9i** [comment]
2 different computer or just a tournament between 2 networks on the same computer? To compare 2 networks on a single pc i’m using gogui, not very user friendly but it works well

**Comment by MartinDevelopment** [comment]
@Friday9i He is talking about using 2 computers, since otherwise he could use something as simple as gomill.

**Comment by Friday9i** [comment]
Not sure as he says he wants to compare different networks...

**Comment by kris-computer-go** [comment]
Yes I'm also using gogui and gogui-twogtp but I've never managed to get
gogui-server and gogui-client to work

**Comment by Friday9i** [comment]
You don’t need the server and client! Just generate games and then use analyze to get a html file to present the results (badly, but understandable anyway)

**Comment by kris-computer-go** [comment]
Can gomill be used with Windows? It would perfect suit for me

**Comment by kris-computer-go** [comment]
Thats what I'm doing. But my intention is to speed up the games because I
have 2 PC with GTX cards

**Comment by MartinDevelopment** [comment]
Gomill is runnable on Windows, as far as I know atleast. I don't know if you can use 2 different computers with it though.

**Comment by Friday9i** [comment]
Not at home so I don’t have access to my computer, but from memory you just launch gogui with an instruction precising the 2 instances ‘ - -black leelaz.exe -w LZ135 -v 1000 - - white leelaz.exe -w LZ130 -v 1000 -games 100 -alternate´ and some precisions (folder, ...), and when finished you run analyze

**Comment by kris-computer-go** [comment]
By the way. Isn't is strange that nobody has created something similar for
go that chess players have since many years like Arena?

**Comment by MartinDevelopment** [comment]
On Linux it is quite easy, you set up a CGOS server and just connect the 2 clients to it.

**Comment by zliu1022** [comment]
gogui-server and gogui-client will be good for you. I used it.

**Comment by kris-computer-go** [comment]
Any help how exactly may command for client and server look like?

**Comment by zliu1022** [comment]
**PC-A (IP address: 192.168.1.136)**:
```
gogui-server.exe -port 8765 -loop leela-0.15.bat
```
And leela-0.15.bat has this content:
```
c:\go\leela-zero-0.15-win64\leelaz.exe -g -w c:\go\weight\62b54.gz
```

**PC-B**:
```
gogui-client.exe 192.168.1.136 8765
```
You can use this in command line or put it into sabaki, gogui, anywhere you like.

Enjoy!

**Comment by sethtroisi** [comment]
closing older issues, no discussion for >6 months and propossed solution
