### ISSUE TITLE
a python tool use leela or leelazero to analysis sgf file

### ISSUE THREAD

**Issue by l1t1** [leela-zero/leela-zero#1436]
https://bitbucket.org/mkmatlock/sgftools

**Comment by l1t1** [comment]
FROM nvidia/opencl
RUN apt-get update && apt-get install -y build-essential wget unzip git libboost-dev libboost-program-options-dev libopenblas-dev opencl-headers ocl-icd-libopencl1 ocl-icd-opencl-dev zlib1g-dev cmake clinfo qtbase5-dev qt5-default
RUN mkdir leela && cd leela && \
    wget --quiet https://www.sjeng.org/dl/Leela0110GTP.zip -O Leela0110GTP.zip && \
    unzip Leela0110GTP.zip && \
    cp leela_0110_linux_x64_opencl /usr/bin/leela-gpu && \
    cp leela_0110_linux_x64 /usr/bin/leela && \
    cd .. && rm -r leela &&\
    chmod +x /usr/bin/leela-gpu /usr/bin/leela
RUN git clone https://github.com/gcp/leela-zero && \
    cd leela-zero && \
    git submodule update --init --recursive && \
    mkdir build && cd build && \
    cmake .. && \
    make leelaz && \
    make tests && \
    cp leelaz /usr/bin/leelaz-gtp
RUN mkdir /etc/leelaz && \
    wget http://zero.sjeng.org/best-network -O best_network.gz && \
    gunzip -c best_network.gz > /etc/leelaz/weights.txt
RUN echo "#!/bin/bash" > /usr/bin/leelaz && \
    echo "/usr/bin/leelaz-gtp --weights /etc/leelaz/weights.txt" >> /usr/bin/leelaz && \
    chmod +x /usr/bin/leelaz

**Comment by l1t1** [comment]
GoReviewPartner, batch mode

**Comment by l1t1** [comment]
a fixed version
https://github.com/lightvector/leela-analysis

**Comment by rexl2018** [comment]
It has.
You need python, and run the .py directly.
> GoReviewPartner has no batch mode

**Comment by l1t1** [comment]
@rexl2018 thanks
find it at http://ns1297.imingo.net/grp-documentation/doc.htm
python r2sgf.py game1.sgf
python r2sgf.py *.sgf

Those commands can be ran from the terminal, or from a bash script or batch script.

**Comment by tamubun** [comment]
I modified [Leela_zero_K80.ipynb](https://drive.google.com/file/d/1WQfPOFhkahIJSxdIjeSQqK4q30j3T1qF/view?usp=sharing) and made Google colab notebook which analyze SGF file using GoReviewPartner.
https://colab.research.google.com/drive/1zKvcGpQidJlQjGZ0H-tlI6IFIQk2ECsn

**Comment by alreadydone** [comment]
> https://colab.research.google.com/drive/1zKvcGpQidJlQjGZ0H-tlI6IFIQk2ECsn

needs permission, it seems.

**Comment by tamubun** [comment]
Sorry, I didn't understand the drive API. Maybe you need to copy the notebook to your own drive. I do not sure that works, so at first, please try fast analyze setting like playout = 100 and restricted moves.

**Comment by alreadydone** [comment]
I can't even see the content. I clicked on the "request access" button last time, so did you see a request?

**Comment by tamubun** [comment]
I made another copy. Can you see this?
https://colab.research.google.com/drive/108CYW1ZWJ7_XymHanQxHyKxlbhDrlA-G

**Comment by tamubun** [comment]
I changed access permission and now checked from another account to be used. Above two links are both valid and they are same.

**Comment by 5525345551** [comment]
It might be an idea to include this bits of code to upload and download a sgf within colab.

Upload

from google.colab import files
files.upload()

Download

files.download('filename')

List directory

files.os.listdir()

**Comment by tamubun** [comment]
Updated using files.upload() and files.download().
https://colab.research.google.com/drive/1zKvcGpQidJlQjGZ0H-tlI6IFIQk2ECsn

Since on my environment, files.download() sometimes fails, I kept Google drive code.

**Comment by Jaafarw** [comment]
Hi, 
I had to change this line: 
`!sed -i -e '78,88d' $config`
to make it work, but I still have another error

> Bot starting procedure started with profile = slow
	bot name: LeelaZero
	bot gtp name Leela Zero
Starting LeelaZero...
Leela Zero working directory: /content/leela-zero/src/
Checking Leela Zero stderr to check for OpenCL SGEMM tuner running
leaving consume_stderr thread
Could not find out, abandoning
LeelaZero started
LeelaZero identification through GTP...
Error while writting to stdin
[Errno 32] Broken pipe
converting GRPException error message from unicode to str
ERROR: LeelaZero did not identify itself as expected:
'Leela Zero' != ''
'bool' object has no attribute 'bot_name'

**Comment by tamubun** [comment]
Thank you. I'll check this weekend.

2018年7月18日(水) 12:40 Jaafarw <notifications@github.com>:

**Comment by Jaafarw** [comment]
Thanks,

I think there is a problem witj leela zero since I couldn't benchmark it.

I added your goreviewpartner addition to a copy of Leela_zero_K80.ipynb and it worked.

There was still a problem with the sed command, I had to upload my own config.ini because I am no good with sed :)

Thanks a lot for your work,

**Comment by tamubun** [comment]
I fixed two problems.
1. Update 1st cell to copy latest Leela_zero_K80.ipynb
2. Changed sed command to fit latest goreviewpartner's config.ini.
 (This sed command erases [LeelaZero] settings which are from line 84 to line 94.)

**Comment by sethtroisi** [comment]
closing older issues, no discussion for >6 months

**Comment by TuringJest** [comment]
Does this still work? 
I get the same error as Jaafarw 


> checking Leela Zero stderr to check for OpenCL SGEMM tuner running
> leaving consume_stderr thread
> Could not find out, abandoning
> LeelaZero started
> LeelaZero identification through GTP...
> Error while writting to stdin
> [Errno 32] Broken pipe
> converting GRPException error message from unicode to str
> ERROR: LeelaZero did not identify itself as expected:
> 'Leela Zero' != ''
> 'bool' object has no attribute 'bot_name'

**Comment by tasuki** [comment]
@Flothus I get that error when my LeelaZero is misconfigured (in my case trying to access an inexistent weights file). Can you try running the LeelaZero command separately and see why it'd crash?
