### ISSUE TITLE
A win rate evaluation between network No.141(11057dd7) and No.131(ecab83bb)

### ISSUE THREAD

**Issue by genleung** [leela-zero/leela-zero#1464]
I ran a test between network No.141(11057dd7) and No.131(ecab83bb) to evaluate their relative win rate. The result is as follows:

> LeelaZero 0.15
> 200 games, 400 playouts.
> No.141 as black wins:  62% (62 of 100)
> No.141 as white wins:  75% (75 of 100)
> No.141 totally wins:  68.5% (137 of 200)
> ELO gains: 135
 
[No.141-vs-No.131.zip](https://github.com/gcp/leela-zero/files/2021547/No.141-vs-No.131.zip)

**Comment by l1t1** [comment]
the gpu and command line info

**Comment by genleung** [comment]
GPU and command line info do not matter, 400 playouts is the key. Maybe 400 po is not enough, but it is convincing that the ELO is not that different as it looks like.

**Comment by genleung** [comment]
@l1t1 I use gogui-twogtp like this:
> $ TWOGTP="gogui-twogtp -force -black \"$BLACK\" -white \"$WHITE\" -games $GAMES_COUNT -komi 7.5 -size 19 -sgffile $MATCH_PREFIX"
$ gogui -size 19 -komi 7.5 -program "$TWOGTP" -computer-both -auto

**Comment by l1t1** [comment]
i use the following tool
[rtsgf4.zip](https://github.com/gcp/leela-zero/files/2021853/rtsgf4.zip)
 to rotate the board, and easily find first 10 moves are identical
```
for  %a in (*.sgf) do @echo @rtsgf4 %a >>temp.cmd
temp
```
ref https://github.com/gcp/leela-zero/issues/1453

**Comment by l1t1** [comment]
conside use validation to compare
https://github.com/gcp/leela-zero/issues/1380

**Comment by Vargooo** [comment]
First Header | Second Header
------------ | -------------
Content from cell 1 | Content from cell 2
Content in the first column | Content in the second column

**Comment by Vargooo** [comment]
networks | first run | second run
------------ | -------------
Content from cell 1 | Content from cell 2 | Content from cell 2
Content from cell 1 | Content from cell 2 | Content from cell 2
Content in the first column | Content in the second column | Content in the second column

**Comment by Vargooo** [comment]
[Networks.docx](https://github.com/gcp/leela-zero/files/2025959/Networks.docx)

**Comment by Vargooo** [comment]
![pas de nom](https://user-images.githubusercontent.com/33191125/40354898-4a100030-5db5-11e8-8988-4903c08154d9.jpg)

**Comment by Vargooo** [comment]
Here is something similar  :
I've selected networks #0, #10, #20, #30, ..., #140.
For each network, I've run two 100 games matches against network #70, which is the reference point.
For example, #0 never wins against #70, and #140 almost always wins against #70.
I've used  twogtp, with LZ015, --visits=51 --noponder

We can see that networks up to #50 play very poorly, and #100, 110, ... have more than 90% winrate.
For the two batches, results are consistent, but for two odd things : 
#20 won 1 game against #70 !
For #60, the two results vary a lot (29 and 17)

![pas de nom](https://user-images.githubusercontent.com/33191125/40356306-ee79877e-5db8-11e8-8f94-3985767a1a3d.jpg)

**Comment by zhanzhenzhen** [comment]
Only 20 behind, that's very good news!

**Comment by jokkebk** [comment]
@zhanzhenzhen Haha, 20 promotions might be optimism, I'm rather sure the ELO gap will not be closed in a linear manner, it might be more of a logarithmic approach, and even stall completely if 192x15 performance saturates (IIRC the ELF network is larger). But if we get to say 30-70 score within a month or two, I'd be quite happy already!

**Comment by l1t1** [comment]
@genleung
I play with gogui for windows using following command
```
gogui -program "gogui-twogtp.exe -black \"D:\tool\valid14\leelaz.exe -g -w D:\tool\valid14\3ef8\" -white \"D:\tool\valid14\leelaz.exe -g -w D:\tool\valid14\3ef8\"" -computer-both
```
could you help me to save the sgf file?

**Comment by sethtroisi** [comment]
more analysis like this on cloudygo

https://cloudygo.com/leela-zero-v3/eval-graphs

closing older issues, no discussion for >6 months
