### ISSUE TITLE
can leelazero add a function to publish book about joseki and opening mode?

### ISSUE THREAD

**Issue by l1t1** [leela-zero/leela-zero#1483]
like http://waterfire.us/joseki.htm did
I rotate some match of LZ144 and found their opening are very different than 140 and 141's.
for example, https://github.com/gcp/leela-zero/issues/1453 's mode disapear.
and the black(4,4)*2 to white(4,4+4,3) mode occur

**Comment by l1t1** [comment]
[144.rar.zip](https://github.com/gcp/leela-zero/files/2041607/144.rar.zip)
the _min.sgf shows the mode in same direction

**Comment by DonMathi** [comment]
I had an different idea about looking at the moves of LZ. Look at all the different 5x5 sections where a new stone is placed in the center. Rank them and show those who are played the most. This would give a good idea about how to make good shape

**Comment by l1t1** [comment]
i saw the match games of lz148 vs lz147, it seems they still allways play (4,4)-(4,4)-(4,4)-(4,3) opening,
but 23 days ago, 
9887ff0e VS 90560d92 (http://zero.sjeng.org/match-games/5afa8e0bea1463439f8546c0), they don't play that way.
so we can image lz learn that mode in the latest 0.5M games,

**Comment by l1t1** [comment]
someone has done it
https://lifein19x19.com/viewtopic.php?f=18&t=15498
http://361points.com/media/top1patterns/patterns.html

**Comment by jillybob** [comment]
I have noticed this joseki analysis web page hasn't been updated since July
http://zero.sjeng.org/opening/44

What would be needed to update it?

**Comment by sethtroisi** [comment]
closing older issues, no active discussion
