### ISSUE TITLE
Suggestion for suppressing network unfavorate moves

### ISSUE THREAD

**Issue by Splee99** [leela-zero/leela-zero#1514]
As we discussed in #1417, LZ tends to consider many weird moves when winrate is low and the number of visits is high with powerful GPUs. These moves have one thing in common, a low N value which I suppose is not favored by the neural network. I have tried the following modified Nodecomp function in UCTNode.cpp:
```text
        if (a.get_visits() != b.get_visits()) {
        	if (a.get_score() < 0.005) return true;
        	if (b.get_score() < 0.005) return false;
            return a.get_visits() < b.get_visits();
        }
```
where two lines are added to push the nodes with N value less than 0.5% to the end of all children. I have run several handicap games and the result is promising and no weird moves were played.

Whether this modification is useful in even games I'm not sure, but it indeed helps to avoid the weird moves.

**Comment by gcp** [comment]
You need more concrete data than "result is promising".

**Comment by petgo3** [comment]
I had a try on KGS (petgo3) with your suggestion. Weird moves appeared as well.

**Comment by Splee99** [comment]
My test is based on move by move analysis. Here is the complete log of a 4 handicap with Hiratuka which is set with 20000 playouts. 
[4h1.log](https://github.com/gcp/leela-zero/files/2070267/4h1.log)

It is easy to see that all move candidates have N value bigger than 0.5% and LZ also got a game win. I have also run several similar games and LZ won all of them. Before the modification it was very hard to win for LZ with similar settings. I know I have to do more testing. 

Here is the sgf file.
[lz-vc-nohalf-hira-4h-30s14.sgf.txt](https://github.com/gcp/leela-zero/files/2070277/lz-vc-nohalf-hira-4h-30s14.sgf.txt)

@petgo3 Would you please post the sgf file with those weird moves, so I can take a closer look?

**Comment by Splee99** [comment]
@petgo3 If you were referring to the 4 handi game just played on KGS, I couldn't repeat the move O1 on my computer. It is not even on the list.

**Comment by sethtroisi** [comment]
closing older issues, no discussion for >6 months
