### ISSUE TITLE
Adding Global Pooled Properties to LZ network

### ISSUE THREAD

**Issue by afalturki** [leela-zero/leela-zero#1521]
https://github.com/lightvector/GoNN#global-pooled-properties-dec-2017

Someone posted the link on Discord and I wanted to put this here for those interested. This seems like a very promising idea that could give LZ a good strength boost while having a negligible performance cost. 

According to @lightvector ,
> For a 12-block net, augmenting two of the residual blocks this way resulted in a major 0.02 nats of improvement persisting at about 60 million training steps, while slightly decreasing the number of parameters and having no cost to performance.

More importantly, they could provide important insights on the reasons why the moves LZ chooses are good as they can tell us about some global features of the game that correspond to human-understandable concepts.

I'm not knowledgeable enough to comment but could it also be possible that adding global pooled  properties might help with strength in handicap play or in multiple komi solutions?

I'm sure if this was implemented, there would be people willing to train such a network from scratch. I myself am planning on buying a new PC when the new 1180/2080 gpu comes and would be willing to train it myself then.

**Comment by john45678** [comment]
This seems very interesting, I'm totally unqualified to judge the usefullness, but the 'Current Results' for his trial net looks very good.

**Comment by roy7** [comment]
Thanks for sharing the link and info. "Global pooling is by far the most successful architectural idea I"ve tried so far."

**Comment by TFiFiE** [comment]
See also https://github.com/gcp/leela-zero/issues/1129#issuecomment-377708501.

**Comment by sethtroisi** [comment]
closing older issues, no discussion for >6 months
