### ISSUE TITLE
can leelaz source code compile by mingw on windows 2008 or 2003

### ISSUE THREAD

**Issue by l1t1** [leela-zero/leela-zero#1525]
I run the binary file on these version.
the system reports somthing in kenrel.dll are missing

**Comment by pnprog** [comment]
Hi!
Quite note the answer you need, but at least somebody was able to compile it (but not with mingw) and run it under Windows XP:

> Tested . Need XP SP3 and Microsfot Visual C++ 2015 Redistributable (x86) package.
>When I close Sleep mode (display/harddisk), the GRP in XP Sp3 on a Virtualbox have succeeded in analysising a SGF file:)

https://github.com/pnprog/goreviewpartner/issues/68

**Comment by l1t1** [comment]
@pnprog thanks, i will try it

**Comment by sethtroisi** [comment]
closing older issues, no discussion for >6 months
