### ISSUE TITLE
Games ended with consecutive same color moves without pass

### ISSUE THREAD

**Issue by rchs819** [leela-zero/leela-zero#1536]
@gcp / @marcocalignano 

Occasionally, we get strange self-play and match games submitted to the server, where at the end of the game, LZ played same color consecutively without pass.

### Recent self-play games

- 2018-06-07 [11b678fb7b41d074a349a08a2978f90be4f455374495bee4b913b6d16794ff5b](http://zero.sjeng.org/view/11b678fb7b41d074a349a08a2978f90be4f455374495bee4b913b6d16794ff5b?viewer=wgo)
- 2018-06-07 [b9eb8de8af241f0184fb8ec5bc43458af2176fa097ea12227bc94523918858a7](http://zero.sjeng.org/view/b9eb8de8af241f0184fb8ec5bc43458af2176fa097ea12227bc94523918858a7?viewer=wgo)
- 2018-06-08 [119bc9c0000e6b277aefddcd9cfce8d3ab6ace116d05198ee67293e982a9978f](http://zero.sjeng.org/view/119bc9c0000e6b277aefddcd9cfce8d3ab6ace116d05198ee67293e982a9978f?viewer=wgo)
- 2018-06-08 [044bbdc4b51d5e02eb36b2d19127548c4021a7e47e754c03e734ac131e9e0906](http://zero.sjeng.org/view/044bbdc4b51d5e02eb36b2d19127548c4021a7e47e754c03e734ac131e9e0906?viewer=wgo)

@roy7 has confirmed the IPs from above games
> 3 are big red and 1 is someone else

### Recent match games
- 2018-03-07 [2075ab27fb47994a41ceee24dbdb6c794ea28be06c0a432f8ab7b25dc29c4ede](http://zero.sjeng.org/viewmatch/2075ab27fb47994a41ceee24dbdb6c794ea28be06c0a432f8ab7b25dc29c4ede?viewer=wgo)
- 2018-04-03 [e1187cc46e4cc48d08139a7008b6edad1fc4d212ed095cb9a40a4d856de5c7e0](http://zero.sjeng.org/viewmatch/e1187cc46e4cc48d08139a7008b6edad1fc4d212ed095cb9a40a4d856de5c7e0?viewer=wgo)
- 2018-04-17 [4d20fb1581184ef1836e443cf583defe8c2710561392367d46a0b292b8dbc82d](http://zero.sjeng.org/viewmatch/4d20fb1581184ef1836e443cf583defe8c2710561392367d46a0b292b8dbc82d?viewer=wgo)
- 2018-04-30 [d39e17d3e2b67899e8ffbc25eeee67db48aa4404f21a7d54169cd7b39c9742e1](http://zero.sjeng.org/viewmatch/d39e17d3e2b67899e8ffbc25eeee67db48aa4404f21a7d54169cd7b39c9742e1?viewer=wgo)
- 2018-05-06 [81aff1f0a0587d2a90e85067b942542b997b0e1e9207c709f64d307b3decf2ad](http://zero.sjeng.org/viewmatch/81aff1f0a0587d2a90e85067b942542b997b0e1e9207c709f64d307b3decf2ad?viewer=wgo)

@roy7 has confirmed the IPs from above games
> all 5 are different IPs

### Past games on http://storage.sjeng.org/zero
```
all.sgf.xz       contains 7,230,561 games, 2949 games were invalid
all_match.sgf.xz contains   361,908 games,   41 games were invalid
```
[all_sgf.invalid.zip](https://github.com/gcp/leela-zero/files/2084876/all_sgf.invalid.zip) (2949 games)
[all_match_sgf.invalid.zip](https://github.com/gcp/leela-zero/files/2084875/all_match_sgf.invalid.zip) (41 games)

### Potential rare bugs
Something must happened at the end of the game, that one side resigned or exited but the other side does 1 more move ?

**Comment by gcp** [comment]
Problem must be in either AutoGTP or the SGF writing as the engine just generates a move for the color it's asked to generate for.

I assume the implication that some are from Big Red means that it can't be due to local modifications?

**Comment by alreadydone** [comment]
AutoGTP running on Big Red II was compiled off https://github.com/alreadydone/lz/tree/br2gpu/, and I can't think of any modification that could be connected to such behavior.

**Comment by alreadydone** [comment]
@marcocalignano I find that all the three self-play games that were played by BRII are resumed games, and in each game the missing move is "resign". So I guess what happened was
+ time limit reached, autogtp prepared to save the game (waiting for the next move)
+ the next move was produced, and it happened to be "resign"
+ the game was still saved instead of uploaded, the side to play was switched, but nothing was added to the sgf (I guess "resign" isn't a valid move for sgf format?)
+ another autogtp was executed and it picked up the game to resume, and the side which didn't resign played another move; the other side immediately resigned, and the game was uploaded

Since the probability that a move is "resign" is about 1/200 (i.e. the typical length of a game is about 200), and since there were 300+ autogtp instances running for 12 hours each time, 3 bug games in 2 days seems about right.

**Comment by alreadydone** [comment]
Example:
2018-06-07 b9eb8de8af241f0184fb8ec5bc43458af2176fa097ea12227bc94523918858a7
Saved/Loaded e571a02139034a03ae80637ab312aaff.sgf
After resuming: [lz.o2284280.txt](https://github.com/gcp/leela-zero/files/2087457/lz.o2284280.txt)
Before resuming: [lz.o2282131.txt](https://github.com/gcp/leela-zero/files/2087458/lz.o2282131.txt)

**Comment by marcocalignano** [comment]
THis could be the very reason for it. There are two solution. 
- Workaroun: if the move the last move is resign do not increase the number of move when the game is resumed it is the turn of the color that resigned (in this case you recalculate the resign move.
- Proper fix: the game is saved as resigned and when it is resumed it will only be sent.

**Comment by sethtroisi** [comment]
closing older issues, no discussion for >6 months
