### ISSUE TITLE
Found a position that cheats all engines (including ELF). Why?

### ISSUE THREAD

**Issue by zhanzhenzhen** [leela-zero/leela-zero#1537]
Black to play.

Black should win a lot. In the end, black will have 205 stones and white will only have 156. But all engines said black would lose.

![ultimatesgf](https://user-images.githubusercontent.com/731796/41176955-e538eae4-6b94-11e8-999a-44acdefc475a.png)

Here's the SGF:

```
(;GM[1]FF[4]CA[UTF-8]KM[7.5]SZ[19]
AW[aa][ab][ac][ad][ae][af][ag][ah][ai][aj][ak][al][am][an][ao][ap][aq][ar][bi][bm][bs][ca][ci][cm][dg][di][dk][dm][do][ds][ea][eg][ei][ek][em][eo][fg][fi][fk][fm][fo][fs][ga][gg][gi][gk][gm][go][hg][hi][hk][hm][ho][hs][ia][ig][ii][ik][im][io][jg][ji][jk][jm][jo][js][ka][kg][ki][kk][km][ko][lg][li][lk][lm][lo][ls][ma][mg][mi][mk][mm][mo][ng][ni][nk][nm][no][ns][oa][og][oi][ok][om][oo][pg][pi][pk][pm][po][ps][qa][qg][qk][qo][rg][rk][ro][rs][sa][sb][sc][sd][se][sf][sg][sh][si][sj][sk][sl][sm][sn][so][sp][sq][sr]
AB[bc][bd][be][bf][bg][bh][bj][bk][bl][bn][bo][bp][bq][br][cc][cd][cf][cg][ch][cj][cl][cn][cp][cq][dc][dd][df][dh][dj][dl][dn][dp][dq][ec][ed][ef][eh][ej][el][en][ep][eq][fc][fd][ff][fh][fj][fl][fn][fp][fq][gc][gd][gf][gh][gj][gl][gn][gp][gq][hc][hd][hf][hh][hj][hl][hn][hp][hq][ic][id][if][ih][ij][il][in][ip][iq][jc][jd][jf][jh][jj][jl][jn][jp][jq][kc][kd][kf][kh][kj][kl][kn][kp][kq][lc][ld][lf][lh][lj][ll][ln][lp][lq][mc][md][mf][mh][mj][ml][mn][mp][mq][nc][nf][nh][nj][nl][nn][np][nq][oc][od][of][oh][oj][ol][on][op][oq][pc][pf][ph][pj][pl][pn][pp][pq][qc][qf][qh][qj][ql][qn][qp][qq][rc][rd][re][rf][rh][ri][rj][rl][rm][rn][rp][rq][rr][qe][pe][oe][ne][me][le][ke][je][ie][he][ge][fe][ee][de][ce]AE[qd][pd][be])
```

**Comment by gcp** [comment]
These snake-like figures are probably worst-case scenarios for a neural network trying to propagate string information. The network's filters are 3x3, so propagating that, say, S2 is connected to B17, would take about 100 or so layers (50 blocks).

**Comment by barrtgt** [comment]
I have also created similar board positions and used them to test various engines. Leela 0.11 does a much better job analyzing positions like this probably due to the additional input features.

**Comment by higherdim** [comment]
The chance of this rare case happening is something like one in 3^300, far from statistically significant anyway.

**Comment by Marcin1960** [comment]
@higherdim "The chance of this rare case happening is something like one in 3^300,"

@higherdim 

Did you tested it? Just kidding, or maybe not. I think randomness is a superstition, covering up a higher dimension ;)

@gcp 

BTW, it would be nice to have a long thread, that almost any topic would be allowed. Once a week it would closed to replaced by a new one.

**Comment by Tsun-hung** [comment]
The current atgorithm is bad at these odd contrived positions. Maybe the similar games are not included in the self-play data

**Comment by pnprog** [comment]
```
gnugo --score estimate --chinese-rules -l snake.sgf 
Black wins by 353.5 points
```
:D

**Comment by lightvector** [comment]
Gnugo probably doesn't understand https://senseis.xmp.net/?TwoHeadedDragon and believes that both of white's eyes are false, causing it to evaluate white as dead. :)

**Comment by Eddh** [comment]
@lightvector  how does your net using dilated filter and global pooling deal with the position ?

**Comment by lightvector** [comment]
I haven't actually trained any value net yet, I'm working on that now. I doubt dilated convolutions will help much here, the chain is too long. The policy part of a neural net probably does fine here.

**Comment by Nazgand** [comment]
This problem could be solved by having, for each pair of vertices, a bit input to the neural net about whether a pair of vertices contains stones of the same group. A 19 by 19 board has 361*360/2=64980 pairs of vertices.

**Comment by lightvector** [comment]
Probably just adding a chain pooling layer solves this easily, and would be better than dectupling the size of the input and attempting to modify the architecture of the convolutional layers to be able to use this input. Chain pooling already is a bit too costly to be promising though.

And neither chain pooling nor telling the neural net about connectivity pairs will work the moment you add some bamboo joints into the shape, so this doesn't seem like a great solution.

**Comment by sethtroisi** [comment]
closing older issues, no discussion for >6 months
