### ISSUE TITLE
Should we change the resignation ratio to 0 in our 62b self play

### ISSUE THREAD

**Issue by alphaladder** [leela-zero/leela-zero#1540]
@gcp I think 15b Lz could learn more from 62b self play if we change its resignation percentage from 5 to 0 or 1  . I had studied the most 62b vs 15b matchs and found that 15b is very weak in the yose stage compare with 62b. 15b can learn more from 62b if we decrease resignation percentage to 0, at least 1%.

**Comment by jkiliani** [comment]
We had no-resign games with ELF-net very early after the network was converted. The quality of the endgames was terrible, since ELF has a much more stratified value head than regular LZ networks, and plays very poorly when it's certain it's losing. This suggestion has already been tried and discarded for good reason.

**Comment by alphaladder** [comment]
thanks for your explanation

**Comment by jkiliani** [comment]
> thanks for your explanation。 however,shall we just change the resignation percentage to 1 ,if you think 0 results in long step self -play.

Resignation percentage is just fine at 5%. The real contribution of ELF is in balanced situations, for imbalanced situations the training from Leela Zero nets is sufficient. Lowering the threshold would just make the ELF games longer, not better.

**Comment by alreadydone** [comment]
It is proposed but not adopted that the game be continued with a lower number of visits after the winrate drops below a threshold; that could speed up the endgame as well.

**Comment by sethtroisi** [comment]
closing >6 month old issue with no follow up.
