### ISSUE TITLE
Code restructuring proposal

### ISSUE THREAD

**Issue by ihavnoid** [leela-zero/leela-zero#1547]
There were some proposals on using multiple nets concurrently so we probably would want to restructure code so that we can support them with more ease.  This is what I propose:
- No thread_local types on OpenCL : this is because there may be cases one thread accessing multiple different nets
- No static methods, no global variables on Network, NNCache, OpenCL, OpenCLScheduler : this is so that we can have multiple implementations of these classes (with different parameters)
- OpenCLScheduler will be abstracted by a class ForwardPipe (or something comparable) which simply has a forward() pure virtual method
- forward_cpu() will be in a separate class (CPUPipe) and be a child class of ForwardPipe
-- Later on if we implement other net types (e.g., CUDA or Vulkan or Metal) they can simply implement the ForwardPipe abstract class instead of wrapping itself around ifdefs 

Probably should be broken down into multiple smaller PRs but this is just to get a consensus whether this is the right direction.

Any thoughts?

**Comment by killerducky** [comment]
LZChess made extensive changes to support multiple backends, including CUDA. Could be worth a look. It would be a major change though.

**Comment by gcp** [comment]
They didn't make those changes to the Leela Zero code though, AFAIK the multiple backends are in lc0. Which makes it completely not interesting.

**Comment by sethtroisi** [comment]
closing >6 month old issue with no follow up.
