### ISSUE TITLE
A new front page is being tested，includes opening analysis

### ISSUE THREAD

**Issue by l1t1** [leela-zero/leela-zero#1555]
A new front page is being tested at http://zero.sjeng.org/home. Please review and provide feedback here ( https://github.com/gcp/leela-zero-server/issues/170 ).
![2018-06-14_152122](https://user-images.githubusercontent.com/23301704/41397406-b26b9b10-6fe6-11e8-9654-1cb288c454f9.png)

**Comment by Cabu** [comment]
Well, that's very good ! But here some remarks:
- On the network tab, 'we' lost the ELO rating of the networks
- If we put the 10 last matches on the homepage, why not: 
  - the 5 lasts best networks also on the homepage?
  - ALL the matches on the matches pages?
- In the joseki list why not the [4-4 point low approach low extension, slide, 3-3](https://senseis.xmp.net/?44PointLowApproachLowExtensionSlide33)?

**Comment by roy7** [comment]
I'll link your post over to the official discussion thread at https://github.com/gcp/leela-zero-server/issues/170 :)

**Comment by sethtroisi** [comment]
Looks really good 💯

**Comment by john45678** [comment]
A training progress (countdown) bar like on leela chess page (http://lczero.org/) would be really cool.

**Comment by thalessa** [comment]
Does not work on phone.

The matches list is too narrow, and the menu bar doesn't change to hamburger menu.

**Comment by godmoves** [comment]
![image](https://user-images.githubusercontent.com/25997471/41696773-6618f5b6-7548-11e8-9ca2-15a807493d0d.png)
Anyone has the same issue？

**Comment by Marcin1960** [comment]
"Recent 10 Matches" What if more than 10 matches were won by the reigning net?

I know, it is obvious for the people who know the project that to access this net one can click
on any match line, containing its name. But this page is also for the curious who came to have a look.

 I find it inelegant and awkward.

**Comment by jkiliani** [comment]
I just noticed that while the match list on the regular site shows passed matches that later drop below 55% still as passed, the new page formal does not.
