### ISSUE TITLE
why leelazero(alphagozero etc) cannot learn from match games

### ISSUE THREAD

**Issue by l1t1** [leela-zero/leela-zero#1561]
as those games also played only by bots, they haven't human knowledge.
btw, i can't read the papers, as I haven't enough AI knowledge, please explain this in a brief way.

**Comment by TFiFiE** [comment]
My guess is they would just make up too insignificant a part of the total number of training games to make it worth complicating the training process for them.

**Comment by gcp** [comment]
1) Very deterministic
2) Low percentage of games so not worth bothering with

In our case learning data isn't even recorded FWIW.
