### ISSUE TITLE
2018 Chinese weiqi congress 

### ISSUE THREAD

**Issue by Tsun-hung** [leela-zero/leela-zero#1573]
2018 second CITIC Securities Cup World intelligent  Open Go Tournament will be held from 13rd Aug to 15th Aug. More detail is given in the link.
http://sports.sina.com.cn/go/2018-06-19/doc-iheauxvz7250271.shtml
http://www.chinaweiqi.net/

**Comment by l1t1** [comment]
too many match now, this is very similar with tencent's.

**Comment by xss801** [comment]
Welcome GCP to China, there's a lot of your fans here

**Comment by Tsun-hung** [comment]
Tomorrow is the application dealine.

**Comment by l1t1** [comment]
I saw it from https://tieba.baidu.com/p/5815827604
leela zero was renamed to super leela
and
Harry8985: Reply r6144: @gcp denies authorization for this Competition? ( harry8985: 回复 r6144 :gcp否认授权这次比赛)  is that true?

**Comment by l1t1** [comment]
https://portal.chinaweiqi.net/intelligence?tid=16218
![2018-07-30_123222](https://user-images.githubusercontent.com/23301704/43377660-6c91af6c-93f4-11e8-9dcd-242e82de2cde.png)

**Comment by l1t1** [comment]
gtp connector https://github.com/chinagocon/gtplinker

**Comment by l1t1** [comment]
13日上午AI预赛1轮

Elf Open Go（美国） win  BADUKi（韩国）

AQ（日本）win Raynz（日本） 

星阵围棋（中国） win Og-go（韩国）

章鱼围棋（中国） win DolBaram（韩国）

**Comment by l1t1** [comment]
1.星阵
2.AQ
3.章鱼
4.ELF
5.og-go
6.DolBaram
7.小爱
8.Rayn
半决赛
1.星阵-ELF
2.AQ-章鱼

**Comment by l1t1** [comment]
final, golaxy vs aq
https://sports.sina.cn/others/qipai/2018-08-14/detail-ihhtfwqq7671306.d.html?from=wap

**Comment by l1t1** [comment]
Octopus bronze
http://foxwq.com/qipu/newlist/id/2018081458832923.html

**Comment by l1t1** [comment]
golaxy 4:1 aq
http://weiqi.qq.com/qipu.html
