### ISSUE TITLE
ELF OpenGo on Fox and World AI Competition

### ISSUE THREAD

**Issue by l1t1** [leela-zero/leela-zero#1595]
https://github.com/pytorch/ELF/issues/66

**Comment by l1t1** [comment]
http://www.yikeweiqi.com/news/topline/46864/

ashamed

**Comment by l1t1** [comment]
https://github.com/yenw/LeelaZero_PhoenixGo
says Please don't use it to take part in AI competitions

**Comment by Splee99** [comment]
The original Phoenixgo knows ladder perfectly. So there is more in Pheonixgo than its "weight".

**Comment by l1t1** [comment]
http://www.tcga.tw/icga-computer-olympiad-2018/en/#tsignup
Program Details

    Game Type
        Go 19x19
    Program Name
        Aurora
    Author(s)
        Qi Zhang
        Dongbin Zhao
    Operator
        Qi Zhang
    Organization
        Institute of Automation, Chinese Academy of Science
    Country
        China
    Introduction
        A not very faithful re-implementation of Master. 1. Training a residual tower by supervised learning, mini-batches of data were sampled at random from the Fox, Baduk, Tygem data sets that beyond 9d level including professional games. 2. Deep reinforcement learning based on supervised-learning starting point. Playing millions of self-play games using a large number of GPUs from National Supercomputer Center and CASIA. 3. Playing a move based on heuristic MCTS with fast rollout policy combined with policy and value.

**Comment by sethtroisi** [comment]
more coverage in other threads
