### ISSUE TITLE
Batching

### ISSUE THREAD

**Issue by Ttl** [leela-zero/leela-zero#1601]
Continued from #410. I have implemented batching support for OpenCL a while ago (https://github.com/Ttl/leela-zero/tree/batching_test). It didn't really help with a laptop's integrated GPU, but now I got to test it on GTX 1080 Ti and performance looks quite different. Here are some netbench results with different networks:

192x15 network:

| Batch size | n/s  |
|------------|------|
| 1          | 923  |
| 4          | 1060 |
| 8          | 1128 |

64x5 network:

| Batch size | n/s   |
|------------|-------|
| 1          | 3883  |
| 4          | 9992  |
| 8          | 10160 |

20x128 network for 9x9 board:

| Batch size | n/s  |
|------------|------|
| 1          | 1403 |
| 4          | 4168 |
| 8          | 4688 |
| 16         | 4992 |
| 128        | 4992 |

I also tried tuning the SGEMM for larger batch size. It didn't change the results for 192x15 network, but with SGEMM tuned for larger batch 64x5 got 11920 n/s at batch size of 8 and 20x128 network for 9x9 board got 5840 n/s at batch size of 16 and 6520 n/s at batch size of 128.

Tree search part is still missing so this can't be used in play right now. I'm not sure if 20% performance increase using large network is large enough, but with smaller networks or smaller board sizes batching is so much faster that it doesn't matter if tree search part is little inefficient.

I would guess that with 20x256 network the performance difference is even smaller and on weaker GPUs there is even less difference. Does anyone care about 9x9 board or smaller networks?

**Comment by alreadydone** [comment]
In addition to the CGOS 9x9 champion https://github.com/gcp/leela-zero/issues/1291, there's also a recent [strong 64x5 network](https://drive.google.com/open?id=1tfGcoNJ9Mh8wqHk1anHc0_dIFbxfGmLm) trained by @NhanHo on Discord that achieved 95%+ winrate against official best # 57 with -v3200.

**Comment by 5525345551** [comment]
The 10x128 network is still strong to play against for amateur player. So I would welcome any speed up.
I use an iGPU.

**Comment by Ttl** [comment]
This won't give similar speedup on weak GPUs. I got no speed increase with 192x15 network using Intel integrated GPU and only 30% speedup on 64x5 network. I wouldn't expect this to give any speedup for 128 channels networks on integrated GPU.

**Comment by Tsun-hung** [comment]
@alreadydone Is the network that he comment at #1311?
![default](https://user-images.githubusercontent.com/33803485/42270588-d71a849e-7fb3-11e8-9ff2-0d0f20173363.JPG)

**Comment by alreadydone** [comment]
@Tsun-hung This one is released on June 20, so likely an improved version. @l1t1 mentioned it at https://github.com/gcp/leela-zero/issues/1557#issuecomment-402413482.

**Comment by gcp** [comment]
>Does anyone care about 9x9 board or smaller networks?

The Leela Chess Zero people do. @frpays ported Leela Zero's OpenCL backend to lc0.

**Comment by gcp** [comment]
It would make sense anyway to implement batching in our search, as I suspect it may give a higher speedup with cuDNN. I remember you tested it and it was not impressive, but I think that was without batching.

**Comment by Tsun-hung** [comment]
@NhanHo Outstanding job! it is kind to many people who don't have fine GPU and want to match with LZ at mobile phone.

**Comment by l1t1** [comment]
same as https://github.com/pytorch/ELF/issues/25 batch?

**Comment by gcp** [comment]
Self-play batching would require a larger refactoring, I guess.

**Comment by sethtroisi** [comment]
this is being implemented and discussed in other issues / PRs no need for duplicates
