### ISSUE TITLE
some one trained a 160x10b weight

### ISSUE THREAD

**Issue by l1t1** [leela-zero/leela-zero#1611]
I download it from a qq group, it is said the strength is similar as the first 192x15b( lz117 )

```
D:\tool\leela15>leelaz -w "weights hzy-160x10.txt.gz"
Using 2 thread(s).
RNG seed: 17407140588138866925
Leela Zero 0.15  Copyright (C) 2017-2018  Gian-Carlo Pascutto and contributors
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; see the COPYING file for details.

Detecting residual layers...v1...160 channels...10 blocks.

```
the size of file is 21.7 MB, much smaller than 192x15b,

**Comment by gcp** [comment]
If there's a link we can test it. Might be good for mobile devices. Although the difference between the first 192x15 and 128x10 was ~300 self-play Elo, so given that this is bigger than 128x10, it looks not so exceptional.

**Comment by alphaladder** [comment]
it is a junk

**Comment by l1t1** [comment]
upload to https://userscloud.com/etb84gl5ucue

**Comment by ryouiki** [comment]
A quick test shows it's winrate against LZ#116(128x10 best) is 62% (200 games, -v400)
But it failed to defeat early 192x15 nets.

**Comment by l1t1** [comment]
@ryouiki  thanks

**Comment by Tsun-hung** [comment]
4 blocks?

**Comment by l1t1** [comment]
the trainer says 256x4 's  strength is similar to lz 116

**Comment by hzyhhzy** [comment]
You upload my weights without permittion😂

**Comment by hzyhhzy** [comment]
I only trained them to play.If they are trained longer,they may be much stonger.

**Comment by hzyhhzy** [comment]
I only trained them for fun.If they are trained longer,they may be much stonger.

**Comment by sethtroisi** [comment]
closing >6 month old issue, we have larger stronger models now.
