### ISSUE TITLE
The Building Blocks of Interpretability

### ISSUE THREAD

**Issue by Hersmunch** [leela-zero/leela-zero#1626]
Has anyone else seen this interactive paper about interpreting the decisions made by NNs?
https://distill.pub/2018/building-blocks/

So applying this to LZ analysing positions from an sgf would be pretty cool. I, however, have no idea where to start.
They link to a load of colab notebooks that seem like they could be adapted "fairly straightforwardly".

What do people think of this?
If you have any idea of the sorts of steps that would have to be done, I'd be very interested in learning (I've never used colab before either).

**Comment by Splee99** [comment]
It seems to be more complex than decoding the 23 chromosomes.

**Comment by peko19** [comment]
https://www.youtube.com/watch?v=-O01G3tSYpU

**Comment by sethtroisi** [comment]
closing older issue with no clear owner
