### ISSUE TITLE
fp16 vs. fp32

### ISSUE THREAD

**Issue by ihavnoid** [leela-zero/leela-zero#1662]
This is to record experiment results on the strength of fp16 and fp32 - using net d351f06e (192x15)

1) When equal number of visits

 visits | fp16 wins | fp32 wins
------- | ------------ | --------------
| 500 | 18 | 22 |
| 2000 | 19 | 21 |
| 4000 | 20 | 20 |
| 8000 | 18 | 22 |

2) when 5% more visits are given to fp16

visits | fp16 wins | fp32 wins
------- | ------------ | --------------
| 525/500 | 19 | 21 |
| 2100/2000 | 22 | 18 |
| 4200/4000 | 24 | 16 |
| 8400/8000 | 26 | 14 |

This suggests that the fp16 inaccuracy can be overcome by ~5% more visits when visit counts are high.  On low visits, NN accuracy is still crucial.

**Comment by Friday9i** [comment]
In line with @jkiliani: we would need more games to get a significant result, it seems to be within noise and the difference due to 5% additionnal visits is too big to be reasonable (hence it is noise).

How many games are needed? Not easy, "it depends" ; -).
If there is a difference (eg 40% vs 60%) in winrate between fp16 and fp32, the number of games needed depends on the amplitude of the difference: with 60/40, around 200 games should be enough but if it is only 55/45, we need at least around 500 games. If it is 52/48, we need at least 2000 games, a pain...

Should the number of visits impact the result of fp16 vs fp32 tests? I assume it should not. Hence, to get significant results, I'd be tempted to get a lot of games (eg 1000 games) and to play them with a relatively low playouts/visits (maybe 200, to limit the time to get these games).
And if you are motivated, you can test the same at 50 visits: if results are the same, it would confirm the result does not depend on visits.

**Comment by Friday9i** [comment]
Cool (but maybe you could begin with 400 games with the same number of visits: if it is is equivalent, no need to test +5% ; -).

**Comment by ihavnoid** [comment]
Ran it overnight, message didn't change a whole lot though.

playoff | fp16 wins | fp32 wins | winrate(fp16)
------- | ----------- | ----------- | -----
525/500 | 208 | 192 | 52
2100/2000 | 134 | 112 | 54
4200/4000 | 80 | 63 |  56
8400/8000 | 74 | 53 | 58

Weather is getting too hot, shutting down machines.

**Comment by tterava** [comment]
I'm getting much lower performance with the new build which has FP16 as command line option, compared to the old build which had to be compiled with DUSE_HALF -flag. I ran validation with 60 seconds main time and no limit on vists. The new build failed with 30% winrate.

**Comment by tterava** [comment]
I used the latest Next-branch with gcp's latest libopenblas.dll. Everything else is standard.

When running full-tune with --use-half it reaches significantly lower peak numbers on a gtx 1080 than the previous build, only about 2.3 GFLOPS when previous build gets about 3 GFLOPS. On average i get about 975 n/s using previous build while the new build gets about 650 n/s.

I ran validation with standard SPRT target and I think it played about 70 games until it failed. The winrate might be higher if more games were played, but the n/s difference quite significant so it's definitely weaker.

I noticed it uses different tuning than the previous version as well. Is this intended?
This is from the tuning file:

`0;XgemmBatchedHalf;192;25;192;36; -DKWG=16 -DKWI=8 -DMDIMA=8 -DMDIMC=16 -DMWG=64 -DNDIMB=8 -DNDIMC=8 -DNWG=32 -DSA=1 -DSB=1 -DSTRM=0 -DSTRN=1 -DVWM=4 -DVWN=4;OpenCL: NVIDIA Corporation GeForce GTX 1080 @ 1847MHz`


Previous version uses this tuning line:
`0;XgemmBatchedHalf;192;100;192;16; -DKWG=16 -DKWI=2 -DMDIMA=16 -DMDIMC=8 -DMWG=64 -DNDIMB=8 -DNDIMC=8 -DNWG=64 -DSA=1 -DSB=1 -DSTRM=1 -DSTRN=1 -DVWM=4 -DVWN=8;OpenCL: NVIDIA Corporation GeForce GTX 1080 @ 1847MHz`

**Comment by SebastienFaurite** [comment]
@tterava if you ran the full tuner before, you should run it again.

**Comment by ihavnoid** [comment]
The problem is that 'latest next branch' doesn't really mean much as I have no idea what it was when you were running it.  There were a lot of commits that may made things go wrong.  What is the last commit look like, for "old" and "new"?

Here are some changes that were made recently:
- A new winograd transformation algorithm was put in which should improve performance for everybody.  Hence you are seeing a new tuning line.
- Single/half precision runtime selection has been put in.


FYI, I ran 4b20a12 with the same option (./leelaz -t 7 --use-half --benchmark -w d35.txt) ad got 1035n/s


Here is the tuning:
```
0;XgemmBatchedHalf;192;25;192;36; -DKWG=16 -DKWI=8 -DMDIMA=16 -DMDIMC=16 -DMWG=64 -DNDIMB=8 -DNDIMC=8 -DNWG=32 -DSA=1 -DSB=1 -DSTRM=0 -DSTRN=0 -DVWM=4 -DVWN=4;OpenCL: NVIDIA Corporation GeForce GTX 1080 @ 1771MHz
```

**Comment by tterava** [comment]
It was commit d5bf982, it is still the latest. Are you on linux or windows? Which drivers?

Im on W10 and using latest drivers. I will test on linux later today.

**Comment by tterava** [comment]
On linux I get over 1000 n/s, which is highest I've ever got with any build. Seems it's either a problem with my setup or something with W10.

**Comment by roy7** [comment]
@tterava Can you set your git head back a few commits and see if you can find which commit broke it for you?

**Comment by tterava** [comment]
@roy7 
It seems there's something in commit 6ec5c58 that makes my system lose ~30% performance when using fp16.

Here's what I did:
- Download commit from next
- Build it with MSVC2017 using Release-profile and flag /DUSE_HALF
- Delete opencl tuning
- Run leelaz.exe -t 7 --tune-only -w d351f...
- Run leelaz.exe -t 7 --benchmark -w d351f...

Result from commit d0fd3e9:
`3207 visits, 1100773 nodes, 3206 playouts, 913 n/s`

Result from commit 6ec5c58:
`3207 visits, 1099663 nodes, 3206 playouts, 635 n/s`

**Comment by roy7** [comment]
Perfect, thanks. This isn't something I can help do anything about but I'm hoping maybe it'll lead someone like @ihavnoid in the right direction.

**Comment by ihavnoid** [comment]
6ec5c58 had autodetect broken and required explicitly specifying gpu.  Was fixed in a couple of more commits.  Can you look at the logs to see if it is done correctly?

Anyway it feels wierd because that commit had nothing to do with opencl, but we never know...

**Comment by ihavnoid** [comment]
Further experiments on my setup also seems to show that yes there is a small performance drop on 6ec5c58 but not so dramatic as what you saw (775n/s, was 843n/s).  There were some multi GPU related code changes there but that shouldn't be something related to fp16.  Will have a bit of look...

**Comment by ihavnoid** [comment]
@tterava I am doing some experiments and I need you to test something.

Can you edit OpenCLScheduler.cpp and find a code that does something like:
```constexpr auto num_threads = 2;```

and change it to something much bigger (e.g., 10) and see if that changes anything?

**Comment by tterava** [comment]
@ihavnoid Manually specifying gpu didn't seem to change anything, but changing `constexpr auto num_threads = 10;` seemed to work.

Result with 6ec5c58 after changing the line:
`3212 visits, 1102133 nodes, 3211 playouts, 931 n/s`

**Comment by ihavnoid** [comment]
- How long did it take?
- Logs will definitely help.  Additionally please let me know how many threads and how many GPUs you used.

**Comment by tterava** [comment]
It took quite long, 15 minutes+. I'm using -t 7 as before and I have a single GPU. I will try and get more data tonight.

**Comment by tterava** [comment]
-t 1 seems stable, but -t 7 or -t 16 usually crash within 1-2 games. I used time_settings 600 0 0 for both engines. I will run one more test to rule out GPU issues.

**Comment by gcp** [comment]
>only about 2.3 GFLOPS when previous build gets about 3 GFLOPS

Note that the new Winograd code potentially leads to less GFLOPS in the tuner, but this is meaningless for the overall performance.

**Comment by ihavnoid** [comment]
Hmm it seems that you fail due to too much error.  What weight param is this using?  Can you also try without the 6f8c873 commit?

**Comment by tterava** [comment]
@ihavnoid The games I tested with were ELF vs d351f. What do you mean without 6f8c873?

**Comment by ihavnoid** [comment]
You said you 'combined 6f8c873 with the PR referenced here'.  I mean, what happen if you don't combine it with 6f8c873.

**Comment by tterava** [comment]
Same error using e39ba8f

**Comment by 22nsuk** [comment]
@tterava Maybe gcp's latest libopenblas.dll is causing this problems. Please check it once. #1648

**Comment by tterava** [comment]
Yeah it was the new libopenblas.dll. Good catch! I keep introducing too many variables to my testing.

**Comment by sethtroisi** [comment]
closing >6month old issue.
