### ISSUE TITLE
Need testers on real fp16 cards

### ISSUE THREAD

**Issue by gcp** [leela-zero/leela-zero#1689]
I just merged autodetection + use of fp16 support:
https://github.com/gcp/leela-zero/pull/1672

On a card that has *real* fp16 support, this greatly increases performance. The question is about precision->strength at fixed playouts. I have cards with partial fp16 support, but no real ones, like P100/V100 or AMD Vega.

No-one responded in the original pull request, so I'll ask here again: if someone with such a card could verify the strength loss (if any!) at fixed visits or playouts, that would be useful for us.

**Comment by bood** [comment]
Does Titan V has real fp16 support too? if yes, I can try this on a friend's machine.

**Comment by SebastienFaurite** [comment]
It seems that it does support fp16 and the performance should double. 
https://devtalk.nvidia.com/default/topic/1027346/titan-v-fp16-performance/

**Comment by fishcu** [comment]
Does the Titan XP have real fp16 support? if yes, I can try this. Would need some instructions on what to test exactly (scripts to run, etc.)

**Comment by akdtg** [comment]
The performance of my Intel HD Graphics 620 increases from 33 n/s to 42 n/s.
But how to verify the strength loss?

**Comment by gcp** [comment]
>The performance of my Intel HD Graphics 620 increases from 33 n/s to 42 n/s.

@Ttl tested this and it was fine, but I am not sure if Intel HD does the compute in 16-bit or if it is just freeing up registers or something.

**Comment by Ttl** [comment]
I'm not 100% sure either what the Intel GPUs do, but unlike AMD GPU it is faster with fp16 compute than with fp16 storage and some sources list that half precision should have twice as high GFLOPs (https://www.techpowerup.com/gpudb/2911/hd-graphics-620-mobile). CLBlast SGEMM tuner was also about 50% faster with half precision.

I can run some fp16 vs fp32 games on my laptop this weekend but it would be still good to also have tests with high-end GPUs.

**Comment by akdtg** [comment]
Well, this fp16 build works very unstable on my PC.
Before this merge to "next" branch, the typical rate of the self-play game was about 35 seconds per move.

With f1p16 build, the 1st game was played with 52971 ms/move, the 2nd one was aborted due to 'Error in OpenCL calculation: Update your GPU drivers or reduce the amount of games played simultaneously.' error, and the 3rd game was played with 28448 ms/move.

**Comment by roy7** [comment]
Half precision compute support: NO

For some reason I thought my 1080Ti would benefit from this. Is fp16 support only in the higher cards like a Titan?

**Comment by Ttl** [comment]
@roy7 1080 Ti doesn't support half precision compute. Half option chosen is half precision storage with computation done in single precision (Same as the old `USE_HALF` option). On cards with half precision compute support half precision should be almost twice as fast as single precision.

1080 Ti does support int8 inference that should be about 4 times faster than the single precision, but cudnn is needed to use it and it can't be used with LZ at the moment.

**Comment by gcp** [comment]
>Well, this fp16 build works very unstable on my PC.

What configuration is this? OS, drivers, card...?

**Comment by akdtg** [comment]
> What configuration is this? OS, drivers, card...?

Using 2 thread(s).
RNG seed: 8163530978958224083
Detecting residual layers...v1...256 channels...20 blocks.
Initializing OpenCL (autodetect precision).
Detected 2 OpenCL platforms.
Platform version: OpenCL 1.2 beignet 1.3
Platform profile: FULL_PROFILE
Platform name:    Intel Gen OCL Driver
Platform vendor:  Intel
Device ID:     0
Device name:   Intel(R) HD Graphics Kabylake ULT GT2
Device type:   GPU
Device vendor: Intel
Device driver: 1.3
Device speed:  1000 MHz
Device cores:  24 CU
Device score:  612
Platform version: OpenCL 1.1 Mesa 18.1.2
Platform profile: FULL_PROFILE
Platform name:    Clover
Platform vendor:  Mesa
Error getting device(s): clGetDeviceIDs: -1
Selected platform: Intel Gen OCL Driver
Selected device: Intel(R) HD Graphics Kabylake ULT GT2
with OpenCL 1.2 capability.
Half precision compute support: YES
Loaded existing SGEMM tuning.
Found Leela Version : 0.15
Tuning process finished

**Comment by Mardak** [comment]
Not real fp16, but not sure if this is interesting to track. Here's the numbers for a two GPUs and various network sizes with the best number for both single and half across a few runs.

```
Device name:   Intel(R) HD Graphics 530
Device type:   GPU
Device vendor: Intel Inc.
Device driver: 1.2(May  8 2018 15:59:46)
Device speed:  1050 MHz
Device cores:  24 CU
Device score:  612
Half precision compute support: NO

256x20 Measuring performance -   9.26 n/s single vs.  15.32 n/s half - Using OpenCL half precision (at least 5% faster than single)
192x15 Measuring performance -   1.08 n/s single vs.   0.38 n/s half - Using OpenCL single precision (less than 5% slower than half)
128x10 Measuring performance -  90.10 n/s single vs.  99.01 n/s half - Using OpenCL half precision (at least 5% faster than single)
 64x 5 Measuring performance - 374.00 n/s single vs. 417.00 n/s half - Using OpenCL half precision (at least 5% faster than single)

Device name:   AMD Radeon Pro 460 Compute Engine
Device type:   GPU
Device vendor: AMD
Device driver: 1.2 (Jun 29 2018 18:33:51)
Device speed:  907 MHz
Device cores:  16 CU
Device score:  1112
Half precision compute support: NO

256x20 Measuring performance -  52.94 n/s single vs.  69.31 n/s half - Using OpenCL half precision (at least 5% faster than single)
192x15 Measuring performance -  99.01 n/s single vs. 112.87 n/s half - Using OpenCL half precision (at least 5% faster than single)
128x10 Measuring performance - 220.00 n/s single vs. 260.00 n/s half - Using OpenCL half precision (at least 5% faster than single)
 64x 5 Measuring performance - 513.00 n/s single vs. 628.00 n/s half - Using OpenCL half precision (at least 5% faster than single)
```

Interestingly, I updated os version / drivers and now run into #1677 when using the integrated Intel device…

**Comment by l1t1** [comment]
why 256x20 has more n/s than 192x15 of intel gpu

**Comment by bood** [comment]
Test result on Titan V (3 threads with single card, 20x256 network):

Command used:

```
for  i in {1..3}; do
./lznext -w networks/b0841a68b4beae9314e47757b44dbe16c5d421dfadcba9ddfe25373e8c27b262 --benchmark --precision single -t 3;
done
```


precision|result1|result2|result3
--|-|-|-
fp16 (half) | 817 | 793 | 807
fp32 (single) | 707 | 715 | 713

Auto mode prefers fp16 too:

`Measuring performance - 663.00 n/s single vs. 742.00 n/s half - Using OpenCL half precision (at least 5% faster than single)`

**Comment by Ttl** [comment]
Does the log have YES or NO on line with`Half precision compute support: `? I think it should be faster if it was really using half precision compute.

**Comment by godmoves** [comment]
I get a `No` on V100, seems the code does not support it? @Ttl 🤔

**Comment by Ttl** [comment]
If it says no then the driver reports that half precision is not supported. Possibly nVidia doesn't support half precision in OpenCL but only in CUDA?

**Comment by AncalagonX** [comment]
A user with an AMD laptop GPU (*not* cpu/onboard GPU) could not run the /next/ build compiled immediately after PR #1672 "Half precision compute support".

When this user forced `--precision single`, the same leelaz.exe ran properly as expected.

The cause is presumably a failure in the full/half precision auto-detect routine. It may be related to issue #1690.

Here are his abbreviated logs:

```./leelaz.exe -w network
Using 2 thread(s).
RNG seed: 7924010773806070189
Leela Zero 0.15  Copyright (C) 2017-2018  Gian-Carlo Pascutto and contributors
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; see the COPYING file for details.
 
Detecting residual layers...v1...192 channels...15 blocks.
Initializing OpenCL (autodetect precision).
Detected 2 OpenCL platforms.
Platform version: OpenCL 1.2
Platform profile: FULL_PROFILE
Platform name:    Intel(R) OpenCL
Platform vendor:  Intel(R) Corporation
Device ID:     0
Device name:   Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz
Device type:   CPU
Device vendor: Intel(R) Corporation
Device driver: 3.0.1.10891
Device speed:  2600 MHz
Device cores:  4 CU
Device score:  512
Device ID:     1
Device name:   Intel(R) HD Graphics 4000
Device type:   GPU
Device vendor: Intel(R) Corporation
Device driver: 10.18.10.4358
Device speed:  1100 MHz
Device cores:  16 CU
Device score:  612
Platform version: OpenCL 2.0 AMD-APP (1800.11)
Platform profile: FULL_PROFILE
Platform name:    AMD Accelerated Parallel Processing
Platform vendor:  Advanced Micro Devices, Inc.
Device ID:     2
Device name:   Turks
Device type:   GPU
Device vendor: Advanced Micro Devices, Inc.
Device driver: 1800.11 (VM)
Device speed:  500 MHz
Device cores:  6 CU
Device score:  1120
Device ID:     3
Device name:   Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz
Device type:   CPU
Device vendor: GenuineIntel
Device driver: 1800.11 (sse2,avx)
Device speed:  2594 MHz
Device cores:  4 CU
Device score:  520
Selected platform: AMD Accelerated Parallel Processing
Selected device: Turks
with OpenCL 2.0 capability.
Half precision compute support: NO
 
Started OpenCL SGEMM tuner.
Will try 290 valid configurations.
Failed to find a working configuration.
Check your OpenCL drivers.
```

**Comment by zhanzhenzhen** [comment]
Just tested on a V100 on EC2 (using Ubuntu deep learning image). It says NO support for half precision. The benchmark for half and single are nearly the same.

But I have a question: Why the current benchmark on V100 so high, 931 n/s?

Here's the benchmark (256x20):

```
./leelaz -w leelaz-model-best.gz -t 3 --benchmark

13.1 average depth, 27 max depth
2443 non leaf nodes, 1.31 average children
3204 visits, 1111430 nodes, 3203 playouts, 931 n/s
```

The benchmark of an 192x15 network on V100 some months ago is just about 1500 n/s.

Here's the GPU info today:

```
Detecting residual layers...v1...256 channels...20 blocks.
Initializing OpenCL (half precision).
Detected 1 OpenCL platforms.
Platform version: OpenCL 1.2 CUDA 9.2.147
Platform profile: FULL_PROFILE
Platform name:    NVIDIA CUDA
Platform vendor:  NVIDIA Corporation
Device ID:     0
Device name:   Tesla V100-SXM2-16GB
Device type:   GPU
Device vendor: NVIDIA Corporation
Device driver: 396.37
Device speed:  1530 MHz
Device cores:  80 CU
Device score:  1112
Selected platform: NVIDIA CUDA
Selected device: Tesla V100-SXM2-16GB
with OpenCL 1.2 capability.
Half precision compute support: NO
Loaded existing SGEMM tuning.
Wavefront/Warp size: 32
Max workgroup size: 1024
Max workgroup dimensions: 1024 1024 64 
BLAS Core: HASWELL
```

**Comment by y-ich** [comment]
Hi.
You can verify half float on [GPU EATER](https://www.gpueater.com/). They provide RX Vega 56 and RX Vega FE.

    src/leelaz -g --weights 62b5417b64c46976795d10a6741801f15f857e5029681a42d02c9852097df4b9.gz

    Using 2 thread(s).
    RNG seed: 2583744436918106026
    Detecting residual layers...v2...224 channels...20 blocks.
    Initializing OpenCL (autodetect precision).
    Detected 1 OpenCL platforms.
    Platform version: OpenCL 2.1 AMD-APP.internal (2574.0)
    Platform profile: FULL_PROFILE
    Platform name:    AMD Accelerated Parallel Processing
    Platform vendor:  Advanced Micro Devices, Inc.
    Device ID:     0
    Device name:   gfx900
    Device type:   GPU
    Device vendor: Advanced Micro Devices, Inc.
    Device driver: 2574.0 (HSA1.1,LC)
    Device speed:  1590 MHz
    Device cores:  56 CU
    Device score:  1121
    Selected platform: AMD Accelerated Parallel Processing
    Selected device: gfx900
    with OpenCL 2.1 capability.
    Half precision compute support: YES
    
    Started OpenCL SGEMM tuner.
    Will try 290 valid configurations.
    (1/290) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=16 NDIMB=8 NDIMC=8 NWG=16 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 0.0820 ms (1101.4 GFLOPS)
    (2/290) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=32 NDIMB=8 NDIMC=8 NWG=16 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 0.0782 ms (1155.7 GFLOPS)
    (19/290) KWG=16 KWI=2 MDIMA=16 MDIMC=16 MWG=32 NDIMB=8 NDIMC=8 NWG=16 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 0.0555 ms (1627.8 GFLOPS)
    (25/290) KWG=32 KWI=2 MDIMA=16 MDIMC=16 MWG=32 NDIMB=8 NDIMC=8 NWG=16 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 0.0525 ms (1720.9 GFLOPS)
    (34/290) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=16 NDIMB=16 NDIMC=16 NWG=32 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 0.0512 ms (1763.1 GFLOPS)
    (40/290) KWG=32 KWI=2 MDIMA=8 MDIMC=8 MWG=16 NDIMB=16 NDIMC=16 NWG=32 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 0.0507 ms (1781.2 GFLOPS)
    (46/290) KWG=16 KWI=2 MDIMA=16 MDIMC=16 MWG=32 NDIMB=16 NDIMC=16 NWG=32 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 0.0481 ms (1877.2 GFLOPS)
    (50/290) KWG=32 KWI=2 MDIMA=16 MDIMC=16 MWG=32 NDIMB=16 NDIMC=16 NWG=32 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 0.0405 ms (2228.9 GFLOPS)
    (111/290) KWG=32 KWI=8 MDIMA=16 MDIMC=16 MWG=32 NDIMB=16 NDIMC=16 NWG=32 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 0.0403 ms (2239.2 GFLOPS)
    (145/290) KWG=32 KWI=2 MDIMA=8 MDIMC=8 MWG=32 NDIMB=16 NDIMC=16 NWG=32 SA=1 SB=1 STRM=0 STRN=0 VWM=4 VWN=2 0.0351 ms (2574.9 GFLOPS)
    (259/290) KWG=32 KWI=2 MDIMA=8 MDIMC=8 MWG=32 NDIMB=8 NDIMC=8 NWG=32 SA=1 SB=1 STRM=0 STRN=0 VWM=4 VWN=4 0.0335 ms (2694.4 GFLOPS)
    Wavefront/Warp size: 64
    Max workgroup size: 256
    Max workgroup dimensions: 1024 1024 1024 
    Detected 1 OpenCL platforms.
    Platform version: OpenCL 2.1 AMD-APP.internal (2574.0)
    Platform profile: FULL_PROFILE
    Platform name:    AMD Accelerated Parallel Processing
    Platform vendor:  Advanced Micro Devices, Inc.
    Device ID:     0
    Device name:   gfx900
    Device type:   GPU
    Device vendor: Advanced Micro Devices, Inc.
    Device driver: 2574.0 (HSA1.1,LC)
    Device speed:  1590 MHz
    Device cores:  56 CU
    Device score:  1121
    Selected platform: AMD Accelerated Parallel Processing
    Selected device: gfx900
    with OpenCL 2.1 capability.
    Half precision compute support: YES
    
    Started OpenCL SGEMM tuner.
    Will try 290 valid configurations.
    (1/290) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=16 NDIMB=8 NDIMC=8 NWG=16 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 0.0557 ms (1622.4 GFLOPS)
    (2/290) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=32 NDIMB=8 NDIMC=8 NWG=16 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 0.0522 ms (1729.4 GFLOPS)
    (25/290) KWG=32 KWI=2 MDIMA=16 MDIMC=16 MWG=32 NDIMB=8 NDIMC=8 NWG=16 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 0.0461 ms (1958.6 GFLOPS)
    (86/290) KWG=32 KWI=8 MDIMA=16 MDIMC=16 MWG=32 NDIMB=8 NDIMC=8 NWG=16 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 0.0460 ms (1961.7 GFLOPS)
    (178/290) KWG=32 KWI=8 MDIMA=8 MDIMC=8 MWG=32 NDIMB=16 NDIMC=16 NWG=32 SA=1 SB=1 STRM=0 STRN=0 VWM=4 VWN=2 0.0432 ms (2089.5 GFLOPS)
    (238/290) KWG=32 KWI=8 MDIMA=16 MDIMC=16 MWG=32 NDIMB=8 NDIMC=8 NWG=32 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=4 0.0423 ms (2133.4 GFLOPS)
    Wavefront/Warp size: 64
    Max workgroup size: 256
    Max workgroup dimensions: 1024 1024 1024 
    BLAS Core: Prescott
    Measuring performance - 387.00 n/s single vs. 503.00 n/s half - Using OpenCL half precision (at least 5% faster than single)

Results of netbench with 62b are,
     1600 evaluations in  3.10 seconds -> 516 n/s # ROCm driver with half float support

     1600 evaluations in  4.59 seconds -> 348 n/s # amdpro driver that does not support half float

Cheers.

**Comment by zhanzhenzhen** [comment]
@y-ich Oh, gpueater looks very attractive! But why its alexa ranking is just 3,500,272?

**Comment by zhanzhenzhen** [comment]
@y-ich I tried a vega56 instance on GPU Eater. But I ran into this error:

```
Started OpenCL SGEMM tuner.
Will try 290 valid configurations.
Failed to find a working configuration.
Check your OpenCL drivers.
terminate called after throwing an instance of 'std::runtime_error'
  what():  Tuner failed to find working configuration.
Aborted (core dumped)
```

**Comment by y-ich** [comment]
@zhanzhenzhen san,

I am sorry that I omitted ” inconvenient" detail.

Two weeks ago I had tried to run Leela Zero branch "next" on GPU EATER and failed. The output of NN was kind of nosense.
Then I had tried "Ubuntu 16.04 x64" image rather than "AMD-ROCm 1.8 192+TensorFlow1.8 Ubuntu 16.04 x64" and succeeded on amdgpu-pro driver.
So I concluded that ROCm driver may have a bug or at least has different behavior from amdgpu-pro driver.

Today I tried again since I knew this issue, and it seemed to succeed. (Sorry, I did not confirm well.)
I thought that change of leela-zero code may avoid the previous error.

My conditions today are,
1. leela-zero verion: next branch commit 488de437e9c669da9870aefa39749322661bb8bf
2. weight: 62b5417b64c46976795d10a6741801f15f857e5029681a42d02c9852097df4b9

Any differences may cause an error.

If you want to confirm whether the cause is the driver or not, you can try on "Ubuntu 16.04 x64" image as I did.
But amdgpu-pro driver does not support half float unfortunately.

Investigating the bug and issuing onto ROCm repository are best but it is hard for me.

If you tell me your conditions, I will try the same conditions.

Thanks.

**Comment by zhanzhenzhen** [comment]
@y-ich I'm also on commit 488de43. When I ran `sudo apt-get update` it gives an error. But I ignored it. Is it the problem?

```
# apt-get update
Hit:1 http://repo.radeon.com/rocm/apt/debian xenial InRelease         
Err:1 http://repo.radeon.com/rocm/apt/debian xenial InRelease                        
  The following signatures were invalid: KEYEXPIRED 1533155360  KEYEXPIRED 1533155360  KEYEXPIRED 1533155360
Get:2 http://security.ubuntu.com/ubuntu xenial-security InRelease [107 kB]           
Get:3 http://security.ubuntu.com/ubuntu xenial-security/main amd64 Packages [533 kB]
Get:4 http://security.ubuntu.com/ubuntu xenial-security/main Translation-en [228 kB]
Get:5 http://security.ubuntu.com/ubuntu xenial-security/universe amd64 Packages [365 kB]
Get:6 http://security.ubuntu.com/ubuntu xenial-security/universe Translation-en [137 kB]
Hit:7 http://archive.ubuntu.com/ubuntu xenial InRelease                                                      
Get:8 http://archive.ubuntu.com/ubuntu xenial-updates InRelease [109 kB]                                     
Get:9 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages [824 kB]                           
Get:10 http://archive.ubuntu.com/ubuntu xenial-updates/main Translation-en [339 kB]                          
Get:11 http://archive.ubuntu.com/ubuntu xenial-updates/restricted amd64 Packages [7,556 B]                   
Get:12 http://archive.ubuntu.com/ubuntu xenial-updates/universe amd64 Packages [679 kB]                      
Get:13 http://archive.ubuntu.com/ubuntu xenial-updates/universe Translation-en [273 kB]                      
Get:14 http://archive.ubuntu.com/ubuntu xenial-updates/multiverse amd64 Packages [16.4 kB]                   
Fetched 3,618 kB in 10s (337 kB/s)                                                                           
Reading package lists... Done
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://repo.radeon.com/rocm/apt/debian xenial InRelease: The following signatures were invalid: KEYEXPIRED 1533155360  KEYEXPIRED 1533155360  KEYEXPIRED 1533155360
W: Failed to fetch http://repo.radeon.com/rocm/apt/debian/dists/xenial/InRelease  The following signatures were invalid: KEYEXPIRED 1533155360  KEYEXPIRED 1533155360  KEYEXPIRED 1533155360
W: Some index files failed to download. They have been ignored, or old ones used instead.
```

My conditions are not anything different. I just followed the steps in the README of this repo before building:

```
apt install libboost-dev libboost-program-options-dev libopenblas-dev opencl-headers ocl-icd-libopencl1 ocl-icd-opencl-dev zlib1g-dev
```

**Comment by y-ich** [comment]
@zhanzhenzhen san,

The error of apt update is no problems.

Here is what I did.

    git clone -b next http://github.com/gcp/leela-zero.git
    cd leela-zero/src
    apt install -y libboost-dev libboost-program-options-dev libopenblas-dev opencl-headers ocl-icd-libopencl1 ocl-icd-opencl-dev zlib1g-dev
    make
    cd ..
    wget http://zero.sjeng.org/networks/62b5417b64c46976795d10a6741801f15f857e5029681a42d02c9852097df4b9.gz
    src/leelaz -g --weights 62b5417b64c46976795d10a6741801f15f857e5029681a42d02c9852097df4b9.gz

And I reproduced your error by using best-network instead of 62b5417b64c46976795d10a6741801f15f857e5029681a42d02c9852097df4b9.

ROCm driver may have a bug. 

If you use 62b5417b64c46976795d10a6741801f15f857e5029681a42d02c9852097df4b9, it seems to work well except for policy network of the first move. I confirmed Lizzie.

The image of GPU EATER is new but not latest. You can try to install the lastet ROCm to use best-network though I have no idea if the bug was fixed or not.

Cheers.

**Comment by zhanzhenzhen** [comment]
@y-ich Oh, sorry didn't notice the weight is different. I'll try it. Thanks!

**Comment by Ttl** [comment]
It looks like the tuner issue with 20x256 networks is a bug in the LZ. The error bound is still too strict even though I already relaxed it to what I thought was a safe value. I'll try to make a better fix for that than just relaxing it more.

**Comment by Ttl** [comment]
I can't really see any reason other than driver bug why single precision wouldn't work when half precision does. Single precision worked using the same GPU in https://github.com/gcp/leela-zero/issues/1689#issuecomment-410946046.

**Comment by estonte** [comment]
On my Windows 7 running vega 56, half precision doesn't work. Single precision works fine.

leelaz.exe -w lz157.gz --benchmark --precision half

Thinking at most 2678400.0 seconds. . .
NN eval=-nan(ind)

**Comment by estonte** [comment]
From OpenGPU's website on [First steps when implementing FP16] (https://gpuopen.com/first-steps-implementing-fp16/):
>First of all, you need Windows 8 or later. Older versions of Windows will simply fail to create shaders if you use min16float . Whilst there is a Platform Update available for Windows 7 which enables FP16 shaders to compile, it simply compiles the code as FP32.

I guess need to try to instal ubuntu with rocm to test fp16 on vega 56.
