### ISSUE TITLE
How strong is LeelaZero now?

### ISSUE THREAD

**Issue by kris-computer-go** [leela-zero/leela-zero#170]
We can see on zero.sjeng.org that after 265.000 games LZ is above 1200 ELO. It means about 8kyu (european). But if you look at any of the last games they clearly don't look like that strength. Can anyone explain this, please.

**Comment by gcp** [comment]
Look at the scale. 0 Elo is random play.

I don't know what the European scale is calibrated to, but it's likely something different.

**Comment by roy7** [comment]
It's a relative ELO to itself starting at 0. You can't compare it in any way to human ELO ratings, sorry. It's only useful to track LZ's own increasing strength.

**Comment by Sikun** [comment]
Leela just beat Idiot-Bot on KGS with 15 Points, so about 29k

**Comment by sbbdms** [comment]
The account "IdiotBot" on KGS might have similar level as current LZ.
I wonder when LZ can reach similar level as WeakBot50k :P

**Comment by jgkwok** [comment]
If you use the Elo anchored to Deepmind's paper, early networks were about -3500. 

So if you assume Deepmind's early networks are similar to LZ's early networks, it is somewhere around -2,300 Elo.

Someone has been updating the spreadsheet below with this kind of information.

https://docs.google.com/spreadsheets/d/1QhYWYQvXBhI5eHJm45fvf97CaV2rRmgrATwVgBFGKoU/edit?usp=sharing

**Comment by kris-computer-go** [comment]
So we probably will see real 1200 ELO in about 2 weeks, right?

**Comment by jgkwok** [comment]
Only if progress keeps up at this pace. 

Some things that might affect it 

- Increasing the size (blocks, filters, other technical stuff) of the network will slow the game playing.

- Increasing strength of LZ could mean shorter games, speeding testing up.

- Getting more publicity as it gets stronger could get more people to volunteer GPU time.

**Comment by olbrichj** [comment]
We've seen her beating Idiotbot. Maybe it would be nice to see these reference points in the strength graph, whenever she beats someone.

**Comment by marcocalignano** [comment]
on OGS 1200 ELO is 19Kyu

**Comment by MartinDevelopment** [comment]
LeelaZero has been able to beat Idiotbot, but also lose to it. So, I guess it is around 30-32k

**Comment by godmoves** [comment]
Leela Zero 256k beat a human(?) beginner on OGS just now, you can search the account leelaz to review that game.

**Comment by Matuiss2** [comment]
The human player trolled hard tho, so this dont mean much,  this leela is 1 - 1 against idiotbot, which much weaker than a human beginner still.

**Comment by roy7** [comment]
@godmoves The game is at https://online-go.com/game/10719773. I'm not sure that really counts as winning though. Human player making nearly random moves and resigned early.

**Comment by godmoves** [comment]
@roy7 It seems that this is his first 19*19 go game

**Comment by saweiss** [comment]
Has anyone else noticed that the latest iteration of the network plays extremely short games consistently? Is something wrong, or is to be expected?

**Comment by jkiliani** [comment]
It does in self-pity, but not in testing mode. I guess it finally knows how to count and now came up with the strategy "pass early as white while ahead and hope Black does too".

This will likely sort itself out quickly once enough training games exist on 265k network.

**Comment by Matuiss2** [comment]
Yeah, this will probably the next step for leela (do not pass early) since a lot of the games are ending like this in the actual network,

**Comment by olbrichj** [comment]
I had different versions of the client running. Windows 0.6 didn't pass early, while self compiled mac version did (master branch). Maybe there are differences. I'm also not sure if I was on the most current master, or if it was an older version.
My Windows 0.6 Version had around 300 to 400 games

**Comment by saweiss** [comment]
@jkiliani What do you mean by testing mode?

@Matuiss2 @olbrichj After using the newest network, the games are longer. I tried pulling the latest changes, but I didn't see anything added that made a difference.

**Comment by jkiliani** [comment]
@saweiss By testing mode I mean the competition mode of autogtp currently only present in the /next branch.

**Comment by Marcin1960** [comment]
25 kyu on KGS?

**Comment by pcengine** [comment]
@Marcin1960 No, It's still in the negative ELO zone for now. That means LeelaZ is still much weaker than a human beginner.

**Comment by gcp** [comment]
Recent fixes likely mean that the level will be a lot higher now, also for the supervised network in the README.

**Comment by Vandertic** [comment]
Our lady started playing in a reasonable 25k level in my opinion now. :-D
Misses some important ataris and doesn't understand life very well, but it has often a grasp of connection and territory. Quite amusing to watch :-)

**Comment by OmnipotentEntity** [comment]
I'm currently running a "full-strength" Leela Zero bot on KGS under the name OmniBot, if you want to try it out.  It lives in the Computer Go room and offers 10:00 w/3x0:30 free games.

**Comment by gcp** [comment]
```
1 void games; see log file.
leelaz-154e v gnugo-l1 (24/1000 games)
board size: 19   komi: 7.5
              wins              black         white       avg cpu
leelaz-154e      6 25.00%       3  25.00%     3  25.00%    541.55
gnugo-l1        18 75.00%       9  75.00%     9  75.00%     28.92
                                12 50.00%     12 50.00%
```

GNU Go 3.8 level 1
Leela Zero 0.9 154e -p 1600

GNU Go is starting to be within reach. Assuredly if I would uncap the playouts it could be defeated.

**Comment by fishcu** [comment]
Would it make sense to play many games against gnugo once the network with 1600 playouts reaches about 50% winrate against it, so to have a very stable anchor that all other intermediate networks relate to?

**Comment by OmnipotentEntity** [comment]
Just an update to my previous post.  I'm still running the bot, except it's now known as LeelaZSlow, and I also have LeelaZFast running as well.  Still updating to the latest network.  I'm told it's SDK range currently.
