### ISSUE TITLE
16-bit floating point implementation?

### ISSUE THREAD

**Issue by ihavnoid** [leela-zero/leela-zero#172]
Anybody interested in a 16bit floating point implementation?

A lot of times GPU performance is memory bandwidth bound, so I gave it a try and put some hacky modifications to convert all NN parameters and input/output data to half float types.  Search performance (using my GTX1080) did improve about 15% using the supervise-learned network (the one described on README) but I am not sure how strong/weak it is compared to the original version.

Aside of all this, I wonder if there are many people who are interested in a fp16 implementation.  Not sure if a fp16 implementation on a CPU makes sense, and there probably will be other headache that I am not aware of.

Opinions?

**Comment by fishcu** [comment]
I would welcome any kind of CPU implementation, see also #70. However, I'm not sure if mixing different precision floats could affect overall training negatively. Do you mean for separate training?

**Comment by ihavnoid** [comment]
Probably re-training for fp16 would be optimal, but it may not be practical due to the sheer compute that may be required.  Currently what I am trying is simply reuse the current weights and lose some precision and see how good it still is.  I am having fp32 vs fp16 runs on my PC.

**Comment by Ttl** [comment]
Google's TPUs seem to actually quantize weights to 8-bit ints [0], so I'm pretty sure that 16-bit floats would work fine. However I think that the half-precision floats are only faster on very new cards and old cards don't get any performance benefit from it.

[0] https://cloud.google.com/blog/big-data/2017/05/an-in-depth-look-at-googles-first-tensor-processing-unit-tpu

**Comment by ihavnoid** [comment]
The reason that half-precision floats are useful in older GPUs might be simply because the NN is more likely to be bandwidth-constrained (reading and re-reading the parameters and tensors) but not by allowing more floating point operations to be done.  I think many of the older GPUs have instructions that does fp16 to fp32 conversion and vice versa, since fp16/fp32 conversion existed since CUDA toolkit 2.3 (June 2009, see https://developer.nvidia.com/cuda-toolkit-23-downloads)

However, I am not sure whether it is true, nor I do know how to profile these under opencl (I just started reading code to learn opencl).

BTW, if anybody is willing to look at my quick hack, I can fork and push it somewhere.  Actually my code does fp32 computation internally...

**Comment by zhu-jz** [comment]
> Anybody interested in a 16bit floating point implementation?

A lot of times GPU performance is memory bandwidth bound, so I gave it a try and put some hacky modifications to convert all NN parameters and input/output data to half float types. Search performance (using my GTX1080) did improve about 15% using the supervise-learned network (the one described on README) but I am not sure how strong/weak it is compared to the original version.

Aside of all this, I wonder if there are many people who are interested in a fp16 implementation. Not sure if a fp16 implementation on a CPU makes sense, and there probably will be other headache that I am not aware of.

Opinions?

but the fp16 performance of GTX 1080 is too slow, that is about 1/64 of its fp32 performance, how did you manage to get 15% improvement over fp32?

**Comment by isty2e** [comment]
If my understanding is correct, he saved the time consumption for RAM-VRAM transfer by using fp16, and then the numbers are converted to fp32 format in VRAM for further calculations.

**Comment by ihavnoid** [comment]
@isty2e - Yes, it is fp32 once it enters the GPU core, and all arithmetic is done in fp32.  It is only stored in memory as fp16.

I put a PR so that other people who are interested can have a look:
https://github.com/gcp/leela-zero/pull/182

**Comment by sethtroisi** [comment]
This is supported now.
