### ISSUE TITLE
fails to run 256 x 20 weights

### ISSUE THREAD

**Issue by wang1834** [leela-zero/leela-zero#1739]
Whenever I use 256 x 20 weights, Sabaki terminated each time showing this error code:

terminate called after throwing an instance of 'cl::error'
  what():    clEnqueueWriteBuffer

**Comment by Ttl** [comment]
What's your GPU? Operating system? What version of LZ?

Please post the full logs of what LZ prints at the start.

**Comment by wang1834** [comment]
Using 4 thread(s).
RNG seed: 17584672677522725341
Detecting residual layers...v1...256 channels...20 blocks.
Initializing OpenCL.
Detected 1 OpenCL platforms.
Platform version: OpenCL 1.2 CUDA 9.1.84
Platform profile: FULL_PROFILE
Platform name:    NVIDIA CUDA
Platform vendor:  NVIDIA Corporation
Device ID:     0
Device name:   GeForce 610M
Device type:   GPU
Device vendor: NVIDIA Corporation
Device driver: 390.48
Device speed:  1175 MHz
Device cores:  1 CU
Device score:  1112
Selected platform: NVIDIA CUDA
Selected device: GeForce 610M
with OpenCL 1.2 capability.
Loaded existing SGEMM tuning.
Wavefront/Warp size: 32
Max workgroup size: 1024
Max workgroup dimensions: 1024 1024 64 
BLAS Core: Sandybridge
>>name
= Leela Zero

>>version
= 0.15

>>protocol_version
= 2

>>list_commands
= protocol_version
name
version
quit
known_command
list_commands
boardsize
clear_board
komi
play
genmove
showboard
undo
final_score
final_status_list
time_settings
time_left
fixed_handicap
place_free_handicap
set_free_handicap
loadsgf
printsgf
kgs-genmove_cleanup
kgs-time_settings
kgs-game_over
heatmap

>>komi 6.5
= 

>>boardsize 19
= 

>>clear_board
= 

Using 4 thread(s).
RNG seed: 6409513012478245447
Detecting residual layers...v1...256 channels...20 blocks.
Initializing OpenCL.
Detected 1 OpenCL platforms.
Platform version: OpenCL 1.2 CUDA 9.1.84
Platform profile: FULL_PROFILE
Platform name:    NVIDIA CUDA
Platform vendor:  NVIDIA Corporation
Device ID:     0
Device name:   GeForce 610M
Device type:   GPU
Device vendor: NVIDIA Corporation
Device driver: 390.48
Device speed:  1175 MHz
Device cores:  1 CU
Device score:  1112
Selected platform: NVIDIA CUDA
Selected device: GeForce 610M
with OpenCL 1.2 capability.
Loaded existing SGEMM tuning.
Wavefront/Warp size: 32
Max workgroup size: 1024
Max workgroup dimensions: 1024 1024 64 
BLAS Core: Sandybridge
>>name
= Leela Zero

>>version
= 0.15

>>protocol_version
= 2

>>list_commands
= protocol_version
name
version
quit
known_command
list_commands
boardsize
clear_board
komi
play
genmove
showboard
undo
final_score
final_status_list
time_settings
time_left
fixed_handicap
place_free_handicap
set_free_handicap
loadsgf
printsgf
kgs-genmove_cleanup
kgs-time_settings
kgs-game_over
heatmap

>>komi 6.5
= 

>>boardsize 19
= 

>>clear_board
= 

>>genmove B
Thinking at most 27.3 seconds...
NN eval=0.460999
Playouts: 4, Win: 18.42%, PV: Q16 D4
Playouts: 13, Win: 27.96%, PV: Q16 D4 D16
Playouts: 25, Win: 34.13%, PV: D16 D4 Q16 Q4
Playouts: 37, Win: 37.19%, PV: D16 D4 Q16 Q4 R6
Playouts: 48, Win: 38.89%, PV: D16 D4 Q16 Q4 R6
Playouts: 60, Win: 40.11%, PV: D16 Q4 D4 Q17 R15
Playouts: 75, Win: 41.17%, PV: D16 Q4 Q16 D4 R6
Playouts: 99, Win: 42.27%, PV: Q16 D4 Q4 D16 F17

 Q16 ->      28 (V: 46.08%) (N: 20.80%) PV: Q16 D4 D16 Q4 R6 R14
 D16 ->      28 (V: 46.05%) (N: 20.61%) PV: D16 Q4 Q16 D4 R6 R14
  Q4 ->      26 (V: 46.09%) (N: 20.24%) PV: Q4 D16 Q16 D3 C5 C4
  D4 ->      26 (V: 46.05%) (N: 20.54%) PV: D4 Q16 Q4 C16 E17 D17
5.0 average depth, 8 max depth
78 non leaf nodes, 1.38 average children
109 visits, 39026 nodes, 108 playouts, 4 n/s

= D16

>>play B D16
= 
![screenshot from 2018-08-17 19-47-11](https://user-images.githubusercontent.com/42450055/44264820-9970e500-a256-11e8-86bf-85a8c17cf59f.png)

**Comment by wang1834** [comment]
OMG, that means I need to add ram...

**Comment by MartinDevelopment** [comment]
Since it says you are getting 4n/s, I recommend you try the CPU-only mode. It seems your GPU is old and might actually be slower to run LZ with than your CPU.

**Comment by sethtroisi** [comment]
closing old techsupport issue
