### ISSUE TITLE
leelazero failed to run with RK3288 OpenCL

### ISSUE THREAD

**Issue by genleung** [leela-zero/leela-zero#1759]
I successfully built leelazero next branch on a Linux(Linaro) @ RK3288 SoC which has OpenCL1.1 support, but failed to run it. Here are the results:

> linaro@tkb:~/software/lz$ ./leelaz -w 5b_3rdparty.txt -g --noponder -p1
> Using 2 thread(s).
> RNG seed: 18061742662717508185
> BLAS Core: ARMV6
> Detecting residual layers...v1...64 channels...5 blocks.
> Initializing OpenCL (autodetect precision).
> Detected 1 OpenCL platforms.
> Platform version: OpenCL 1.2 v1.r9p0-05rel0-git(f980191).e4ba9e4c6ff8005348d0332aae160089
> Platform profile: FULL_PROFILE
> Platform name:    ARM Platform
> Platform vendor:  ARM
> Device ID:     0
> Device name:   Mali-T760
> Device type:   GPU
> Device vendor: ARM
> Device driver: 1.2
> Device speed:  99 MHz
> Device cores:  4 CU
> Device score:  112
> Selected platform: ARM Platform
> Selected device: Mali-T760
> with OpenCL 1.2 capability.
> Half precision compute support: YES
> 
> Started OpenCL SGEMM tuner.
> Will try 290 valid configurations.
> (1/290) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=16 NDIMB=8 NDIMC=8 NWG=16 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 0.0000 ms (inf GFLOPS)
> (2/290) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=32 NDIMB=8 NDIMC=8 NWG=16 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 0.0000 ms (inf GFLOPS)
> (3/290) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=64 NDIMB=8 NDIMC=8 NWG=16 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 0.0000 ms (inf GFLOPS)
> (4/290) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=16 NDIMB=8 NDIMC=8 NWG=32 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 0.0000 ms (inf GFLOPS)
> (5/290) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=32 NDIMB=8 NDIMC=8 NWG=32 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 0.0000 ms (inf GFLOPS)
> .... ( the similar outputs are omitted here) ...
> SB=1 STRM=0 STRN=0 VWM=4 VWN=4 0.0000 ms (inf GFLOPS)
> (288/290) KWG=32 KWI=8 MDIMA=8 MDIMC=8 MWG=64 NDIMB=16 NDIMC=16 NWG=64 SA=1 SB=1 STRM=0 STRN=0 VWM=4 VWN=4 0.0000 ms (inf GFLOPS)
> (289/290) KWG=16 KWI=8 MDIMA=16 MDIMC=16 MWG=64 NDIMB=16 NDIMC=16 NWG=64 SA=1 SB=1 STRM=0 STRN=0 VWM=4 VWN=4 0.0000 ms (inf GFLOPS)
> (290/290) KWG=32 KWI=8 MDIMA=16 MDIMC=16 MWG=64 NDIMB=16 NDIMC=16 NWG=64 SA=1 SB=1 STRM=0 STRN=0 VWM=4 VWN=4 0.0000 ms (inf GFLOPS)
> Failed to enqueue: 14 kernels
> Failed to find a working configuration.
> Check your OpenCL drivers.
> Minimum error: 0.000000. Error bound: 0.000100
> Detected 1 OpenCL platforms.
> Platform version: OpenCL 1.2 v1.r9p0-05rel0-git(f980191).e4ba9e4c6ff8005348d0332aae160089
> Platform profile: FULL_PROFILE
> Platform name:    ARM Platform
> Platform vendor:  ARM
> Device ID:     0
> Device name:   Mali-T760
> Device type:   GPU
> Device vendor: ARM
> Device driver: 1.2
> Device speed:  99 MHz
> Device cores:  4 CU
> Device score:  112
> Selected platform: ARM Platform
> Selected device: Mali-T760
> with OpenCL 1.2 capability.
> Half precision compute support: YES
> 
> Started OpenCL SGEMM tuner.
> Will try 290 valid configurations.
> (1/290) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=16 NDIMB=8 NDIMC=8 NWG=16 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 0.0000 ms (inf GFLOPS)
> (2/290) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=32 NDIMB=8 NDIMC=8 NWG=16 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 0.0000 ms (inf GFLOPS)
> (3/290) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=64 NDIMB=8 NDIMC=8 NWG=16 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 0.0000 ms (inf GFLOPS)
> (4/290) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=16 NDIMB=8 NDIMC=8 NWG=32 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 0.0000 ms (inf GFLOPS)
> (5/290) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=32 NDIMB=8 NDIMC=8 NWG=32 SA=1 SB=1 
> .... ( the similar outputs are omitted here) ...
> (286/290) KWG=16 KWI=8 MDIMA=8 MDIMC=8 MWG=64 NDIMB=16 NDIMC=16 NWG=64 SA=1 SB=1 STRM=0 STRN=0 VWM=4 VWN=4 0.0000 ms (inf GFLOPS)
> (287/290) KWG=32 KWI=8 MDIMA=8 MDIMC=8 MWG=32 NDIMB=16 NDIMC=16 NWG=64 SA=1 SB=1 STRM=0 STRN=0 VWM=4 VWN=4 0.0000 ms (inf GFLOPS)
> (288/290) KWG=32 KWI=8 MDIMA=8 MDIMC=8 MWG=64 NDIMB=16 NDIMC=16 NWG=64 SA=1 SB=1 STRM=0 STRN=0 VWM=4 VWN=4 0.0000 ms (inf GFLOPS)
> (289/290) KWG=16 KWI=8 MDIMA=16 MDIMC=16 MWG=64 NDIMB=16 NDIMC=16 NWG=64 SA=1 SB=1 STRM=0 STRN=0 VWM=4 VWN=4 0.0000 ms (inf GFLOPS)
> (290/290) KWG=32 KWI=8 MDIMA=16 MDIMC=16 MWG=64 NDIMB=16 NDIMC=16 NWG=64 SA=1 SB=1 STRM=0 STRN=0 VWM=4 VWN=4 0.0000 ms (inf GFLOPS)
> Failed to enqueue: 14 kernels
> Failed to find a working configuration.
> Check your OpenCL drivers.
> Minimum error: 0.000079. Error bound: 0.100000
> Both single precision and half precision failed to run
> terminate called after throwing an instance of 'std::runtime_error'
>   what():  Failed to initialize net
> Given up
>

**Comment by gcp** [comment]
>Failed to find a working configuration.
Check your OpenCL drivers.

This device has broken drivers, nothing we can do.

**Comment by gcp** [comment]
You can try to force --full-tuner to see if there's any kernel that works but from the above it's not looking good.

**Comment by genleung** [comment]
The device seems OK running other programs like chromium-browser with OpenCL enabled. And here are more details about OpenCL implementations on RK3288 SoC :
> 
> Number of platforms: 	1
> 	CL_PLATFORM_PROFILE:	FULL_PROFILE
> 	CL_PLATFORM_VERSION:	OpenCL 1.2 v1.r14p0-01rel0-git(966ed26).eedaf0c5244add8e249cecdd3c721329
> 	CL_PLATFORM_VENDOR:	ARM
> 	CL_PLATFORM_EXTENSIONS:	cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_byte_addressable_store cl_khr_3d_image_writes cl_khr_fp64 cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_fp16 cl_khr_gl_sharing cl_khr_icd cl_khr_egl_event cl_khr_egl_image cl_khr_image2d_from_buffer cl_arm_core_id cl_arm_printf cl_arm_thread_limit_hint cl_arm_non_uniform_work_group_size cl_arm_import_memory
> 	Number of devices: 	1
> 		CL_DEVICE_TYPE:	CL_DEVICE_TYPE_GPU
> 		CL_DEVICE_VENDOR_ID:	122683393
> 		CL_DEVICE_MAX_COMPUTE_UNITS:	4
> 		CL_DEVICE_MAX_WORK_ITEM_DIMENSIONS:	3
> 	CL_DEVICE_MAX_WORK_ITEM_SIZES:	256 256 256 
> 		CL_DEVICE_MAX_WORK_GROUP_SIZE:	256
> 		CL_DEVICE_PREFERRED_VECTOR_WIDTH_CHAR:	16
> 		CL_DEVICE_PREFERRED_VECTOR_WIDTH_SHORT:	8
> 		CL_DEVICE_PREFERRED_VECTOR_WIDTH_INT:	4
> 		CL_DEVICE_PREFERRED_VECTOR_WIDTH_LONG:	2
> 		CL_DEVICE_PREFERRED_VECTOR_WIDTH_FLOAT:	4
> 		CL_DEVICE_PREFERRED_VECTOR_WIDTH_DOUBLE:	2
> 		CL_DEVICE_PREFERRED_VECTOR_WIDTH_HALF:	8
> 		CL_DEVICE_NATIVE_VECTOR_WIDTH_CHAR:	16
> 		CL_DEVICE_NATIVE_VECTOR_WIDTH_SHORT:	8
> 		CL_DEVICE_NATIVE_VECTOR_WIDTH_INT:	4
> 		CL_DEVICE_NATIVE_VECTOR_WIDTH_LONG:	2
> 		CL_DEVICE_NATIVE_VECTOR_WIDTH_FLOAT:	4
> 		CL_DEVICE_NATIVE_VECTOR_WIDTH_DOUBLE:	2
> 		CL_DEVICE_NATIVE_VECTOR_WIDTH_HALF:	8
> 		CL_DEVICE_MAX_CLOCK_FREQUENCY:	100
> 		CL_DEVICE_ADDRESS_BITS:	64
> 		CL_DEVICE_MAX_MEM_ALLOC_SIZE:	527194112
> 		CL_DEVICE_IMAGE_SUPPORT:	1
> 		CL_DEVICE_MAX_READ_IMAGE_ARGS:	128
> 		CL_DEVICE_MAX_WRITE_IMAGE_ARGS:	8
> 		CL_DEVICE_IMAGE2D_MAX_WIDTH:	65536
> 		CL_DEVICE_IMAGE2D_MAX_WIDTH:	65536
> 		CL_DEVICE_IMAGE2D_MAX_HEIGHT:	65536
> 		CL_DEVICE_IMAGE3D_MAX_WIDTH:	65536
> 		CL_DEVICE_IMAGE3D_MAX_HEIGHT:	65536
> 		CL_DEVICE_IMAGE3D_MAX_DEPTH:	65536
> 		CL_DEVICE_MAX_SAMPLERS:	16
> 		CL_DEVICE_MAX_PARAMETER_SIZE:	1024
> 		CL_DEVICE_MEM_BASE_ADDR_ALIGN:	1024
> 		CL_DEVICE_MIN_DATA_TYPE_ALIGN_SIZE:	128
> 		CL_DEVICE_SINGLE_FP_CONFIG:	CL_FP_DENORM | CL_FP_INF_NAN | CL_FP_ROUND_TO_NEAREST | CL_FP_ROUND_TO_ZERO | CL_FP_ROUND_TO_INF | CL_FP_FMA
> 		CL_DEVICE_SINGLE_FP_CONFIG:	CL_READ_ONLY_CACHE | CL_READ_WRITE_CACHE
> 		CL_DEVICE_GLOBAL_MEM_CACHE_TYPE:	CL_READ_WRITE_CACHE
> 		CL_DEVICE_GLOBAL_MEM_CACHELINE_SIZE:	64
> 		CL_DEVICE_GLOBAL_MEM_CACHE_SIZE:	262144
> 		CL_DEVICE_GLOBAL_MEM_SIZE:	2108776448
> 		CL_DEVICE_MAX_CONSTANT_BUFFER_SIZE:	65536
> 		CL_DEVICE_MAX_CONSTANT_ARGS:	8
> 		CL_DEVICE_LOCAL_MEM_TYPE:	CL_LOCAL | CL_GLOBAL
> 		CL_DEVICE_LOCAL_MEM_SIZE:	32768
> 		CL_DEVICE_ERROR_CORRECTION_SUPPORT:	0
> 		CL_DEVICE_HOST_UNIFIED_MEMORY:	1
> 		CL_DEVICE_PROFILING_TIMER_RESOLUTION:	1000
> 		CL_DEVICE_ENDIAN_LITTLE:	1
> 		CL_DEVICE_AVAILABLE:	1
> 		CL_DEVICE_COMPILER_AVAILABLE:	1
> 		CL_DEVICE_EXECUTION_CAPABILITIES:	CL_EXEC_KERNEL
> 		CL_DEVICE_QUEUE_PROPERTIES:	CL_QUEUE_OUT_OF_ORDER_EXEC_MODE_ENABLE | CL_QUEUE_PROFILING_ENABLE
> 		CL_DEVICE_PLATFORM:	0xb6ece370
> 	CL_DEVICE_NAME:	Mali-T760
> 	CL_DEVICE_VENDOR:	ARM
> 	CL_DRIVER_VERSION:	1.2
> 	CL_DEVICE_PROFILE:	FULL_PROFILE
> 	CL_DEVICE_VERSION:	OpenCL 1.2 v1.r14p0-01rel0-git(966ed26).eedaf0c5244add8e249cecdd3c721329
> 	CL_DEVICE_OPENCL_C_VERSION:	OpenCL C 1.2 v1.r14p0-01rel0-git(966ed26).eedaf0c5244add8e249cecdd3c721329
> 	CL_DEVICE_EXTENSIONS:	cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_byte_addressable_store cl_khr_3d_image_writes cl_khr_fp64 cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_fp16 cl_khr_gl_sharing cl_khr_icd cl_khr_egl_event cl_khr_egl_image cl_khr_image2d_from_buffer cl_arm_core_id cl_arm_printf cl_arm_thread_limit_hint cl_arm_non_uniform_work_group_size cl_arm_import_memory
>

**Comment by gcp** [comment]
>The device seems OK running other programs like chromium-browser with OpenCL enabled

Chromium doesn't use OpenCL, it uses **OpenGL**, a graphics API whose drivers are much better tested.

I repeat: the drivers are broken, nothing we can do.

**Comment by Ttl** [comment]
```
Failed to enqueue: 14 kernels
Failed to find a working configuration.
Check your OpenCL drivers.
Minimum error: 0.000000. Error bound: 0.000100
```

It looks like only 14 kernels fail to run and the rest are working fine. The broken part is OpenCL kernel profiling that is used to time the kernel execution. It seems that this driver always returns zero seconds for the runtime. 0 is used as uninitialized value and it fails since tuner checks if runtime is 0 after the tuning for a sign of no working kernels.

You can fix this by adding an alternative method of timing to the tuner. It should only be used if the driver profiling timer returns zero since driver profiling is much more accurate with working drivers.

**Comment by genleung** [comment]
@Ttl Thanks for the hints. I will give it a try.

**Comment by gcp** [comment]
The problem with reliably profiling may also be the underlying cause of issue 1753.

**Comment by sethtroisi** [comment]
closing old techsupport issue
