### ISSUE TITLE
256x40 net is eating up memory

### ISSUE THREAD

**Issue by ihavnoid** [leela-zero/leela-zero#1805]
One side effect of the huge net is that the weights itself is quite big... A leelaz instance is consuming roughly 2.5GB right after launching (with zero tree evaluations and zero NNCache entries).  I am having a hard time saturating my GPUs (2xGTX1080) under autogtp due to lack of memory.  I did push some optimizations but I think... we need more.  Maybe we have to really store the CPUPipe thingy in half precision?

Any good ideas?

**Comment by ihavnoid** [comment]
To give you a perspective, 4 parallel games is going to need 8 processes if I am unlucky and get 4 match games at once.  8 process x 2.5GB/process = 20GB.

**Comment by ihavnoid** [comment]
> Storing the CPU side in half probably incurs a hefty performance hit on some systems? I know F16C instructions got introduced at some point but AFAIK CPU's aren't really fast at handling "half".

Yeah it probably won't work for CPU-only implementations.  My hope is that it will help reducing the footprint of the CPU based self-check reference.  Anyway, we have to do something...

**Comment by ihavnoid** [comment]
I did figure out one more thing - I was mistakenly using the batched implementation hence was over-creating nets.  I see that it's more like 1.7GB footprint before any evaluation, which goes down to 1.3GB footprint with #1795

**Comment by joseph-ireland** [comment]
One idea would be to store the weights vectors in shared memory using boost interprocess. Would be a big win for this specific case.

**Comment by ihavnoid** [comment]
> Yeah it probably won't work for CPU-only implementations. My hope is that it will help reducing the footprint of the CPU based self-check reference. Anyway, we have to do something...

I implemented the world worst half-precision CPU implementation just for the weights (immediately cast half precision weights from memory to single precision right before using them) and lo and behold, it is roughly 40% of native single precision.  Maybe it's good enough for self-check since it is only going to happen pretty rarely...or not?

(One additional strategy is to run self-check for the first 1000 evals and then abandon it later, but that isn't going to help if some opencl implementation is broken only on the late game when there are a lot of stones... but maybe it's unlikely it's okay initially but broken later on...?)

**Comment by Ttl** [comment]
Storing the filters untransformed and transforming them just before they are needed would use one quarter of the memory, but has at least 20% performance hit. That should be acceptable for self-check.

**Comment by Ttl** [comment]
I tried storing the weights untransformed in CPUPipe. It saves memory, but it looks like it's too slow. CPU performance goes from 1.7 n/s to 0.26 n/s. Swapping some loops in transformation doubles it to 0.56 n/s, but it still looks like the performance hit is too large.

**Comment by ihavnoid** [comment]
How about returning to the non winograd transform implementation for self check?  Will that be an acceptable compromise?

**Comment by Ttl** [comment]
With #1826 merged I now get 1.0 n/s with runtime filter transformation. Extrapolating from results in #523 direct convolution would get 1.2 n/s on 40 block network. Maybe that's not worth the trouble?

**Comment by sethtroisi** [comment]
closing old issue with no proposed action items
