### ISSUE TITLE
Match-playing fails

### ISSUE THREAD

**Issue by ashinpan** [leela-zero/leela-zero#1815]
autogtp (next) on my machine (Linux Mint 19) can produce self-play games but fails to play matches, even though both networks required for the match are ready in the network folder. 

Sample terminal output:

----------------------
4 game(s) (4 self played and 0 matches) played in 61 minutes = 915 seconds/game, 8418 ms/move, last game took 1013 seconds.
{
    "black_hash": "c9d70c413e589d338743bfa83783e23f378dc0b9aa98940a2fbd1d852dab8781",
    "black_hash_gzip_hash": "6a4335770fba9ebc01a8aa3b3bd06b6c356d2be81c049db998b20dc60bc6db42",
    "cmd": "match",
    "minimum_autogtp_version": "16",
    "minimum_leelaz_version": "0.15",
    "options": {
        "noise": "false",
        "playouts": "0",
        "randomcnt": "0",
        "resignation_percent": "5",
        "visits": "1600"
    },
    "options_hash": "0ef1f92e1ad538c7025e05a09af7cb5e4b63231b53b4760dbe7f2dd21911bdaafc0590",
    "random_seed": "3633130553962762436",
    "required_client_version": "16",
    "white_hash": "d3b966d16b98c91215b424bf5a63dadfc82462865c60d14bd00b92463539dbf7",
    "white_hash_gzip_hash": "41ad61bcb5d813d282753fbc157b7dddf59146297d525b5cebbca5f2fcaaef42"
}

Got new job: match
first network: c9d70c413e589d338743bfa83783e23f378dc0b9aa98940a2fbd1d852dab8781.
second network d3b966d16b98c91215b424bf5a63dadfc82462865c60d14bd00b92463539dbf7.
Engine has started.
time_settings 0 1 0
Thinking time set.
*ERROR*: Could not talk to engine after launching

**Comment by Ttl** [comment]
What's your GPU? 40b requires lot of GPU memory. You might run out with two networks.

Try launching two leelaz instances with 40b networks and see if that works. If it doesn't post the error here.

**Comment by ashinpan** [comment]
@Ttl  I have just launched two autogtp self-playing instances, and the machine becomes very slow but still working.

**Comment by ashinpan** [comment]
@Ttl  I also tried to launch two leelaz tune-only instances with two different 40b networks. It still works.

**Comment by Ttl** [comment]
LZ requires 800 MB of GPU memory with single precision and half of that with half precision. With 2 GB of GPU memory you are very close to running out of memory if there is some other program also using GPU.

Also make sure that autogtp uses the latest next with commit ebfe51a1f6f34edcd6d11e9ef51de97f9bb1edf1, otherwise you need 1.2 GB of memory during initialization which is not enough when initializing two leelaz instances at the same time.

**Comment by ashinpan** [comment]
I think it may be an autogtp bug.

**Comment by ashinpan** [comment]
@Ttl I have been using the latest leelaz (next) version for a long time.

**Comment by alreadydone** [comment]
As a last resort: https://github.com/alreadydone/lz/blob/4b1a87f7aee81d113f3901db26f3b6d5edcb77e2/autogtp/Management.cpp#L312

**Comment by ihavnoid** [comment]
I have seen that the memory consumption is hitting the max for many people (#1805) and even my machine with 16GB of RAM is hitting that message occasionally.  Same pattern.  Eating up a lot of RAM, swapping, and then crashing.

I am trying to work on some solutions to reduce memory footprint (e.g., #1795) and there will be more patches coming, but fundamentally I think we need some more user-friendly way to say that 'we ran out of memory'.

**Comment by ihavnoid** [comment]
Especially match games are problematic because we have to load two weights.  2 threads x 2 nets = 4 600MB nets = out of GPU memory.

**Comment by l1t1** [comment]
may be the client should use fp16

**Comment by ihavnoid** [comment]
It's not that simple.  Autotraining itself needs a peak memory consumption equal to single precision anyway.  Hence I think we should need autogtp to detect what the right precision should be, and then only use that.

**Comment by sethtroisi** [comment]
closing old issue with no clear action items or owner
