### ISSUE TITLE
Why is the final 'dual head' implemented in CPU?

### ISSUE THREAD

**Issue by ihavnoid** [leela-zero/leela-zero#185]
My understanding is that currently the bulk of the work is done using OpenCL, but the final convolve/batchnorm/innerproduct is done from the CPU.  Is there any reason that it is implemented this way, e.g., is it based on experiment results, or is it that we did not have time to investigate what to do here?

**Comment by gcp** [comment]
The heads are a relatively tiny portion of work compared to the residual stack, they are more irregular and especially the fully connected/innerproduct layers are more memory bound than compute bound. So it's not clear there is (much if any) benefit to having them on the GPU, and it is more annoying to implement.
You can try to make a GPU implementation and see if it provides any speedup.

**Comment by ihavnoid** [comment]
Understood.  GPU has a lot of raw memory bandwidth so maybe there is value, but agree it's a tiny portion of the whole network.  Will think and analyze a bit more.

**Comment by gcp** [comment]
The problem of innerproduct is that the compute density is very low (1 operation per weight, huge difference from a convolution). GPUs have incredibly tiny memory bandwidth compared to their compute throughput, that's why they have GDDR5X, HBM2 etc.

**Comment by ihavnoid** [comment]
Hmm some anecdotal evidence that the final 'dual head' might not be so insignificant...

One thing I figured out that the OpenBLAS that I am using is not detecting the processor properly, probably due to being a very recent Coffee Lake core.  What I ended up was that the default detection was being Prescott.

After manually forcing Haswell (export OPENBLAS_CORETYPE=Haswell) there was a nontrivial amount of performance uplift (760n/s -> 850n/s).  If the final two heads were so insignificant there should have been only a very small difference depending on the BLAS type that was being used.

FYI I am using a GTX1080 non-TI, and this test was done by generating the first move using https://sjeng.org/zero/best_v1.txt.zip

**Comment by gcp** [comment]
"Only" 11% speedup from running code that is 4 time faster (AVX2 FMA vs SSE2) sounds about right :-)

In any case, more arguing is pointless here. Would need to write the code and check if this is faster on GPU or CPU to be sure. I assessed that it wouldn't help much.

But this does mean I need to potentially update the OpenBLAS that is bundled, as it's almost a year old and may suffer from the same bug.

**Comment by ihavnoid** [comment]
Agree that we shouldn't argue at more - it's either implement and try it, or else.  Will have a look when I have time, but probably will take a while.

**Comment by ihavnoid** [comment]
Just to leave my observations here... as an exercise to learn OpenCL, I implemented the dual head's convolution part in OpenCL, and there was almost no difference in terms of performance.  I wonder if there is anybody interested in my implementation, though.

FYI, I am using a i7-8700 and GTX 1080.

**Comment by sethtroisi** [comment]
Haha, I also implemented the convolution in OpenCL! And also so no improvement with GTX 1080. I continued by testing on my 970 where I saw a performance decrease of ~10%.

I'm interested in seeing your implementation. (mine is [here](https://github.com/sethtroisi/leela-zero/tree/gpu_convolve)).

**Comment by ihavnoid** [comment]
See here : https://github.com/ihavnoid/leela-zero/tree/dualhead_conv

I created the convolution code from scratch specifically for the final heads.
