### ISSUE TITLE
Accelerate rather than resign self-play games?

### ISSUE THREAD

**Issue by TFiFiE** [leela-zero/leela-zero#1868]
If new output heads like score or territory estimation are added, then these could only be trained on games played to completion, which would mean disregarding the vast majority of self-play games for that purpose. As that seems very wasteful, whenever games become too lopsided for one side or the other, instead of resigning them, they could be (quickly) played out for both sides with just (a single pass through) the network. Obviously, the policy head would not be trained on this phase.

**Comment by Vandertic** [comment]
@TFiFiE actually you can train the score estimation without completing the games. In SAI we did so by using win/lose as target and training with variable komi with resignation allowed. In this way the net learns that from position x the agent will probably win if komi is (say) >=10 and probably lose if komi is (say) <=5.
When the two numbers are close to each other, it means that the game is more or less decided, and the score difference is the same number.
In [SAI](https://github.com/gcp/leela-zero/issues/1835) this is done by training two parameters, but in principle one could also train only one to achieve what you suggest.

**Comment by TFiFiE** [comment]
I wonder whether accelerating would result in the wrong winner less often than resigning; if it does, it might be worth doing regardless.

**Comment by sethtroisi** [comment]
closing old issue with no clear action items or owner

**Comment by TFiFiE** [comment]
I guess it would be possible to train territory output on resigned games _as is_ by making the final (aggregated) predicted intersection winrates the target instead of any final scored board. Unlike the overall winrate, however, these values should not first be "snapped" to an absolute result (with .5 signifying a neutral point in seki), because fractional values can sometimes actually express the game-theoretic truth in unfinished games. For example, in a game in which the only meaningful plays left are three _dame_, the predicted winrate for each of them should be two thirds for the player to move.
