### ISSUE TITLE
Feature suggestion: flexible structure of the network heads

### ISSUE THREAD

**Issue by Vandertic** [leela-zero/leela-zero#1870]
Different people are now training LZ candidate networks with some success. 
At the moment one can play with the number of layers and filters, but the structure of the value and policy heads is fixed. In particular the 1x1 convolutions have 1 and 2 filters respectively and the fully connected layer of the value head has 256 filters.
I propose to implement more flexibility by making these numbers parameters that can be changed.
The function loading the weights file in SAI does [this](https://github.com/gcp/leela-zero/issues/1835) at the cost of a slight slower loading time.
If this could be implemented in LZ, then networks with different head structure could be tested in official matches.

**Comment by sethtroisi** [comment]
closing issue with no clear owner
