### ISSUE TITLE
Is it possible to specify the training mode from gpu to cpu?

### ISSUE THREAD

**Issue by chucklu** [leela-zero/leela-zero#1893]
Hi,
   I am using leela-zero-0.15-cpuonly-win64.
   But when I start the training, it seems the program is running with gpu.
```powershell
E:\Go\leela-zero-0.15-cpuonly-win64>.\autogtp.exe -k kifu
AutoGTP v16
Using 1 thread(s) for GPU(s).
Starting tuning process, please wait...
Net filename: networks/25c2313d8c11b9320de4795cf593f237f32e8a61c4524a6305ff30073b760132
net: 25c2313d8c11b9320de4795cf593f237f32e8a61c4524a6305ff30073b760132.
./leelaz --tune-only -w networks/25c2313d8c11b9320de4795cf593f237f32e8a61c4524a6305ff30073b760132
Tuning process finished
Starting thread 1 on GPU 0
{
    "cmd": "selfplay",
    "hash": "25c2313d8c11b9320de4795cf593f237f32e8a61c4524a6305ff30073b760132",
    "hash_gzip_hash": "2cd08933244a2de5674dd1dcd9a1065606705bee0dfc9c0edde300a6eea8c1b9",
    "minimum_autogtp_version": "16",
    "minimum_leelaz_version": "0.15",
    "options": {
        "noise": "true",
        "playouts": "0",
        "randomcnt": "999",
        "resignation_percent": "5",
        "visits": "1601"
    },
    "options_hash": "b37dca",
    "random_seed": "56409509298368009",
    "required_client_version": "16"
}

Got new job: selfplay
net: 25c2313d8c11b9320de4795cf593f237f32e8a61c4524a6305ff30073b760132.
Engine has started.
Infinite thinking time set.
```

I  only  have a intel gpu  `Intel(R) HD Graphics 530`, it's too slow.
Is it possible that I can pass a parameter to autogtp.exe to specify the training mode?
My operation system is Microsoft Windows 10.0.16299

**Comment by chucklu** [comment]
When I try to find the following info on readme

> You need a PC with a GPU, i.e. a discrete graphics card made by NVIDIA or AMD, preferably not too old, and with the most recent drivers installed.

I find the tutorial about using google colab to do the training
https://github.com/gcp/leela-zero/blob/master/COLAB.md
Tried it successfully!
![image](https://user-images.githubusercontent.com/3004057/46240578-499c4680-c3dc-11e8-9a54-177c96445614.png)

**Comment by wonderingabout** [comment]
successfully yes, but after a few hours the colab will get disconnected with this message : "no GPU backend available", then you'll have to wait for some time (maybe even a few days) before being able to use it again... for a few hours until it disconnects again, see : 
https://research.google.com/colaboratory/faq.html#gpu-availability

"why are GPU unavailable"

**Comment by chucklu** [comment]
Hi @wonderingabout ,
   I hope I can run with cpu mode on my laptop.
   I will run with gpu mode on Google colab

**Comment by dvdkhlng** [comment]
@chuklu, I think that when autogtp prints

    Starting thread 1 on GPU 0

It doesn't really know whether leela zero has GPU support.  If your leela zero binary was compiled for cpu-only operation, then it can't use the GPU whatever autogtp tells it to do.

If you want to play it really save, then rename your leelaz binary and replace it with a batch file or other kind of wrapper that adds argument "--cpu-only" when leelaz is invoked via autogtp.

Currently autogtp enforces single-threaded leelaz for training (don't ask me why), which means you would have abysmal performance on a CPU.  However, that can be mitigated partially by running "autogtp -g4" (or higher depending on your hardware thread count and available RAM) to make autogtp run multiple instances of leelaz in parallel.

**Comment by gcp** [comment]
>Currently autogtp enforces single-threaded leelaz for training (don't ask me why)

Because it's much more efficient to run several games in parallel, rather than use several threads for a single game.

**Comment by gcp** [comment]
>I am using leela-zero-0.15-cpuonly-win64.
>But when I start the training, it seems the program is running with gpu.

@dvdkhlng is correct in that this is just a display issue. AutoGTP doesn't have any autodetection code so it just assumes Leela will be using the GPU and uses that in its messages. If you don't have one and are using the cpuonly binary, it will use the CPU.

**Comment by chucklu** [comment]
@wonderingabout  yes, I encounter the same problem about unavailable gpu.
@gcp  It seems google colab do not want user to run something like leela zero.

https://research.google.com/colaboratory/faq.html#gpu-availability

> How may I use GPUs and why are they sometimes unavailable?
> Colaboratory is intended for interactive use. Long-running background computations, particularly on GPUs, may be stopped. Please do not use Colaboratory for cryptocurrency mining. Doing so is unsupported and may result in service unavailability. We encourage users who wish to run continuous or long-running computations through Colaboratory’s UI to use a local runtime.
