### ISSUE TITLE
why the time cost of a self-play game is not a Linear function of moves?

### ISSUE THREAD

**Issue by l1t1** [leela-zero/leela-zero#1895]
[slow.txt](https://github.com/gcp/leela-zero/files/2431110/slow.txt)

moves |sec.
-|-
202 |5461
113 |5161
247 |8238
107 |4220
169 |6412
723 |60739

**Comment by l1t1** [comment]
[find_last.txt](https://github.com/gcp/leela-zero/files/2431111/find_last.txt)

**Comment by Ishinoshita** [comment]
I did some statistics on LZ177 training data (train_dec5b9d8, network promoted on 15-Sep-2018).
I took an arbitrary slice of ~3200 games (training data chunks 1000 to 1099,  ~610k positions).

* Here is the average normalized cost for genrerating a game (1 cost unit corresponds to  1600 visits, thus cost scales to time):
![image](https://user-images.githubusercontent.com/37498331/46257629-4036db00-c4bd-11e8-9b7e-07df5a365b5b.png)

* For reference, the average game length:
![image](https://user-images.githubusercontent.com/37498331/46256644-b895a000-c4ad-11e8-8a01-8b74cbc12ce3.png)
One can observe two main distributions, the resign games (average @165move count), and and secondary distribution of no resign games spanning up to 722 moves.

* To illustrate @alreadydone's answer, here is the probability (%visits) p_picked (orange/red curves) of the move that has been actually picked by T=1 in a given position, in a no resign game. The graph also displays (blue curves), for each move count, p_best10, the cumulative probability of the 10 best moves. In this game, it drops ~45% after ~180 moves when value collapse below 5% (from the POV of the loser side). Thus there is on average 65% probability of picking a move with a rank higher than 10  and a very low probability in the search.
![image](https://user-images.githubusercontent.com/37498331/46257499-0c5ab600-c4bb-11e8-9b9b-c2dde19558e8.png)
![image](https://user-images.githubusercontent.com/37498331/46257528-8d19b200-c4bb-11e8-9983-7681672387cc.png)
 * p_picked also corresponding to the tree reuse ratio in the next position, this translates into a normalized cost for generating a move, norm_cost(current position) = 1 - p_picked(previous position).
![image](https://user-images.githubusercontent.com/37498331/46256763-5342ae80-c4af-11e8-8d38-5a9f25e34891.png)
After the resign threshold is hit, one can see that picked move probability falls below 5%, meaning that 95% of the tree is thrown away and move generation cost of 95% of the 1600 visits budget.

* Overall (on average over the 3200 games) the cost per move doubles between 180 and 360 moves count as the distribution switch to 100% of no-resign game:
![image](https://user-images.githubusercontent.com/37498331/46257619-17aee100-c4bd-11e8-80b3-61f7ae0440ef.png)

**Comment by Ishinoshita** [comment]
Here is the sgf of the 720 moves game chosen here above, with embeded statistics derived from the training data (best viewed with Sabaki) : [chunk_1098_game_23.zip](https://github.com/gcp/leela-zero/files/2431568/chunk_1098_game_23.zip)

![image](https://user-images.githubusercontent.com/37498331/46257726-b7b93a00-c4be-11e8-9a2f-978c3c632e3c.png)

**Comment by nmcle** [comment]
That seems quit convincing analysis, I hope something can be done

**Comment by Ishinoshita** [comment]
My point was just to answer @l1t1 question "why the time cost of a self-play game is not a linear function of moves?". The reasons behind the data I show here are already well known and have been much debated. BTW, 'something' has already been done lately on the server side: the reduction of the theoritical proportion of self-play games sent to client from 20% to 10%. Practically, used to be more in the range of 15%-18%. Now seems to me a bit less than 10% (gonna check).

**Comment by jokkebk** [comment]
We’d probably have about 13 million training games already if some of the ideas to speed up long games (e.g. half of the visits) had been implemented...

@Ishinoshita amazing analysis, could you multiply time spent histogram with number of games histogram and do a cumulative plot so we’d see what portion of contributed time is used to generate different lengths of games?

**Comment by Ishinoshita** [comment]
@jokkebk I'm working on a more comprehensive post, which touches other aspects of the training data (found weird games / training values for example; still digging into them). I will cover games cost and include the graph you mention.

**Comment by sethtroisi** [comment]
closing issue with answer to original question
