### ISSUE TITLE
autogtp quits with an error after a few games have been played

### ISSUE THREAD

**Issue by grolich** [leela-zero/leela-zero#191]
After a number of games have been played, I get an error message of the form:

"Game data 26c60c065b8f2d13f462aeec19c4375250d026ce21ff9bf04fc56492cc8cac7f stored in database
8 game(s) played in 44 minutes = 337 seconds/game, last game took 299 seconds.
Unexpected output from server:

"

The number of games before the error differs between runs, and seems that it can be anything (even 1), but it's never high.

Makes it impossible to leave it alone when I stop using the computer.

**Comment by ThePokerDude** [comment]
Is it possible you have short internet disconnects?
If a game is finished autogtp tries to upload the game.
If it fails because you're offline autogtp stops working.

I thinh this issue occured some times before and will be fixed soon - see #130 in "pull requests"

**Comment by grolich** [comment]
hmm I don't know, might be a good idea (in general) to add a couple of timed reconnection attempts. It will also enable testing this, but it also seems to be a smart idea in general to prevent large game-dataset losses by continuing to run over small network problems overnight on people's computers.

thinking of ways to test it here as well(I can't really rebuild it here, I'm running on windows and still didn't have the time to set up the build for leela-zero here.

However, it seems unlikely that there will be short disconnects every hour or so (sometimes every couple of minutes) with other things running smoothly.

Definitely possible though. I'll try to look into it

**Comment by ThePokerDude** [comment]
Hi,

not sure what @gcp plans are on when to release version 0.7. 
Maybe you should wait for it and check if the error still occurs after the update before investing too much time into the error search.

**Comment by grolich** [comment]
Looking at the code, the error message doesn't happen if upload fails at all, but in the fetch_best_network_hash function, which downloads the best hash. 

The fact that according to its output it failed to receive any string at all (or perhaps just a newline, which would be a huge difference for pinpointing the problem, but I'll try to test that) shows a problem is occurring when curl attempting to get the best hash, which is either no connection is established, or problems with data fetching.
Probably lack of error checking (if at all possible) after the curl call doesn't make it easier to answer.

I think it never observed a problem with the game upload here yet. Strange behavior if that was repeated short connectivity errors, to never happened on the upload but a second later in the curl download attempt.

Thanks.

until i can find the time to create a normal build here, or @gcp or someone else will have a better answer, I probably have to wait on it anyway.

**Comment by Ttl** [comment]
One reason that you haven't observer errors might be because the success of the upload is not checked. If the uploading fails the game is lost forever and no error is generated to the user. Failed upload looks identical to successful one.

**Comment by Phelanpt** [comment]
See issue #59 , especially [this message](https://github.com/gcp/leela-zero/issues/59#issuecomment-344855051). When there's some network errors/problems, curl times out, and you don't see the error message in autogtp. I had similar problems with this, posted in issue #148, which seemed to be due to some network issues with hibernating my laptop. I didn't figure it out fully.

If you see it happen, try running the curl request for best network hash as per message above, and see if you're getting a timeout.

**Comment by Ttl** [comment]
Curl writes error message to stderr if it fails. However autogtp only reads stdout and stderr is ignored. That's why if curl gives error nothing is printed to console when running autogtp. You can only see the error message if you run curl from the command line yourself.

**Comment by grolich** [comment]
I'll look into it.
Curl seems to have a pretty detailed list of error values. It would be nice to add extensive error checking to Leela zero (not only for curl return values), as it would really speed up error solving and let people know if they are facing the same issue/s or not.

In the meantime I'll try to get the build working from source on my windows system if I can find the time in the next couple of days.

Thanks
