### ISSUE TITLE
Linux and Mac binaries

### ISSUE THREAD

**Issue by hadim** [leela-zero/leela-zero#1911]
That would be nice to have compiled packages for Linux and Mac so we don't have to compile leela-zero.

Ideally, those could be generated by a CI service (Travis is nice for Linux but for Windows, you might want to use Appveyor instead).

In the meantime, I can provide binaries for Linux.

**Comment by vascopimenta** [comment]
I'm having trouble compiling the latest source in Mac. I get a number of errors in Network.cpp, the first being "Network.cpp:377:9: error: use of undeclared identifier 'cfg_precision'". Both with make and cmake. Have updated all submodules, updated cmake through homebrew, etc.

Any help would be appreciated.

**Comment by alreadydone** [comment]
The same error appears in https://github.com/gcp/leela-zero/issues/1921 but you are not compiling for CPUs ...

**Comment by gcp** [comment]
>for Windows, you might want to use Appveyor instead

We are already using that, but I don't know how to get build artifacts off of it, and we have some problems that the regular Windows build has an outdated OpenBLAS.

**Comment by hadim** [comment]
@gcp conda-forge has a recent version of OpenBLAS: https://anaconda.org/conda-forge/openblas. It can be worth installing Anaconda on Appveyor.

What about Travis? It supports both Linux and Mac. I see you are already using it for CI. Would you be ok to add some code that update the binaries to GH release when a tag is detected?

**Comment by hadim** [comment]
For Linux binaries, it's easy to setup:

```
deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "FILE TO UPLOAD"
  skip_cleanup: true
  on:
    tags: true
```

You would also have to use `docker cp` to retrieve binaries from the docker containers.

For Mac, you would need to write a new build script specific to Mac.

- https://docs.travis-ci.com/user/reference/osx/
- https://docs.travis-ci.com/user/deployment/releases/

I can help if needed.

**Comment by hadim** [comment]
On Appveyor it's also possible to upload files to GH release: https://www.appveyor.com/docs/deployment/github/

**Comment by gcp** [comment]
>I can help if needed.

Yes please, I'm not very familiar with either Travis or Appveyor. Using anconda to get updated OpenBLAS sounds fine.

**Comment by sethtroisi** [comment]
closing old issue with no clear owner or comment for >4 months
