### ISSUE TITLE
nvidia 384 can not be installed on colab today

### ISSUE THREAD

**Issue by simonnier** [leela-zero/leela-zero#1923]
Dear developers,

I use colab to run autogtp according to https://github.com/gcp/leela-zero/blob/master/COLAB.md . It is fine. But today I got some problem when installing nvidia, in the output of ipython, I found 

> The following packages have unmet dependencies:
>  nvidia-384 : Depends: libgl1 but it is not going to be installed
>               Depends: xorg-video-abi-11 but it is not installable or
>                        xorg-video-abi-12 but it is not installable or
>                        xorg-video-abi-13 but it is not installable or
>                        xorg-video-abi-14 but it is not installable or
>                        xorg-video-abi-15 but it is not installable or
>                        xorg-video-abi-18 but it is not installable or
>                        xorg-video-abi-19 but it is not installable or
>                        xorg-video-abi-20 but it is not installable or
>                        xorg-video-abi-23
>               Depends: xserver-xorg-core but it is not going to be installed
> E: Unable to correct problems, you have held broken packages.

and when compiling leelaz, I got error

> make[1]: Entering directory '/content/leela-zero/src'
> g++ -I/usr/include/openblas -I. -Wall -Wextra -pipe -O3 -g -ffast-math -flto -march=native -std=c++14 -DNDEBUG -MD -MP -c -o Network.o Network.cpp
> In file included from OpenCL.h:27:0,
>                  from OpenCLScheduler.h:26,
>                  from Network.cpp:46:
> ./CL/cl2.hpp:506:10: fatal error: CL/opencl.h: No such file or directory
>  #include <CL/opencl.h>
>           ^~~~~~~~~~~~~
> compilation terminated.
> Makefile:61: recipe for target 'Network.o' failed
> make[1]: *** [Network.o] Error 1
> make[1]: Leaving directory '/content/leela-zero/src'
> Makefile:4: recipe for target 'default' failed
> make: *** [default] Error 2

What is wrong? Is there something changed today? How to solve this?

best regards

**Comment by wonderingabout** [comment]
@balabi0github 
i dont know about this specific issue, but google colab uses a tesla K80 and shuts down after a few hours due to google non interactive use policy
if you want to contribute to leela zero for free, i strongly suggest you look at google cloud free trial, that gives access to a tesla V100 totally free just like colab: #1905

**Comment by balabi0github** [comment]
@wonderingabout Thank you for reply. I found colab upgrade to Ubuntu 18.04. Maybe this is the problem.

I found following code works: 
```

!apt install linux-headers-generic nvidia-390 libnvidia-compute-390  nvidia-opencl-dev  opencl-headers
!apt install -y --fix-missing --no-install-recommends clinfo cmake git libboost-all-dev libopenblas-dev zlib1g-dev
!apt install build-essential qtbase5-dev qttools5-dev qttools5-dev-tools
!clinfo

!rm -rf leela-zero
!git clone https://github.com/gcp/leela-zero
!cd leela-zero/src && make

!cd leela-zero/autogtp && qmake -qt5
!cd leela-zero/autogtp && make
!cp leela-zero/src/leelaz leela-zero/autogtp/

leela-zero/autogtp && ./autogtp -k sgf
```

**Comment by gcp** [comment]
if someone wants to make a pull for an updated COLAB README...

**Comment by wonderingabout** [comment]
@wonderingabout 
indeed, the old script was made for ubuntu 17.04

**Comment by balabi0github** [comment]
@gcp I simplified the code. Now it is

!apt install nvidia-opencl-dev
!apt install libboost-all-dev libopenblas-dev zlib1g-dev
!apt install qt5-default qt5-qmake

!rm -rf leela-zero
!git clone https://github.com/gcp/leela-zero
!cd leela-zero/src && make

!cd leela-zero/autogtp && qmake -qt5
!cd leela-zero/autogtp && make
!cp leela-zero/src/leelaz leela-zero/autogtp/

!cd leela-zero/autogtp && ./autogtp -k sgf

**Comment by kwccoin** [comment]
> @gcp I simplified the code. Now it is
> 
> ```
> !apt install nvidia-opencl-dev
> !apt install libboost-all-dev libopenblas-dev zlib1g-dev
> !apt install qt5-default qt5-qmake
> 
> !rm -rf leela-zero
> !git clone https://github.com/gcp/leela-zero
> !cd leela-zero/src && make
> 
> !cd leela-zero/autogtp && qmake -qt5
> !cd leela-zero/autogtp && make
> !cp leela-zero/src/leelaz leela-zero/autogtp/
> 
> !cd leela-zero/autogtp && ./autogtp -k sgf
> ```

Seems work for me now ... 

`Cloning into 'leela-zero'...
remote: Enumerating objects: 21, done.
remote: Counting objects: 100% (21/21), done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 4341 (delta 7), reused 7 (delta 3), pack-reused 4320
Receiving objects: 100% (4341/4341), 3.22 MiB | 8.24 MiB/s, done.
Resolving deltas: 100% (3111/3111), done.
Detected OS: Linux
make CC=gcc CXX=g++ \
	CXXFLAGS='-I/usr/include/openblas -I. -Wall -Wextra -pipe -O3 -g -ffast-math -flto -march=native -std=c++14 -DNDEBUG'  \
	LDFLAGS=' -flto -g' \
	leelaz
make[1]: Entering directory '/content/leela-zero/src'
g++ -I/usr/include/openblas -I. -Wall -Wextra -pipe -O3 -g -ffast-math -flto -march=native -std=c++14 -DNDEBUG -MD -MP -c -o Network.o Network.cpp
In file included from OpenCL.h:27:0,
                 from OpenCLScheduler.h:26,
                 from Network.cpp:46:
./CL/cl2.hpp:5855:63: warning: ignoring attributes on template argument ‘cl_int {aka int}’ [-Wignored-attributes]
     typename std::enable_if<!std::is_pointer<T>::value, cl_int>::type
                                                               ^
./CL/cl2.hpp:6155:22: warning: ignoring attributes on template argument ‘cl_int {aka int}’ [-Wignored-attributes]
         vector<cl_int>* binaryStatus = NULL,
                      ^
g++ -I/usr/include/openblas -I. -Wall -Wextra -pipe -O3 -g -ffast-math -flto -march=native -std=c++14 -DNDEBUG -MD -MP -c -o FullBoard.o FullBoard.cpp
g++ -I/usr/include/openblas -I. -Wall -Wextra -pipe -O3 -g -ffast-math -flto -march=native -std=c++14 -DNDEBUG -MD -MP -c -o KoState.o KoState.cpp
g++ -I/usr/include/openblas -I. -Wall -Wextra -pipe -O3 -g -ffast-math -flto -march=native -std=c++14 -DNDEBUG -MD -MP -c -o Training.o Training.cpp
g++ -I/usr/include/openblas -I. -Wall -Wextra -pipe -O3 -g -ffast-math -flto -march=native -std=c++14 -DNDEBUG -MD -MP -c -o TimeControl.o TimeControl.cpp
g++ -I/usr/include/openblas -I. -Wall -Wextra -pipe -O3 -g -ffast-math -flto -march=native -std=c++14 -DNDEBUG -MD -MP -c -o UCTSearch.o UCTSearch.cpp
g++ -I/usr/include/openblas -I. -Wall -Wextra -pipe -O3 -g -ffast-math -flto -march=native -std=c++14 -DNDEBUG -MD -MP -c -o GameState.o GameState.cpp
g++ -I/usr/include/openblas -I. -Wall -Wextra -pipe -O3 -g -ffast-math -flto -march=native -std=c++14 -DNDEBUG -MD -MP -c -o Leela.o Leela.cpp
g++ -I/usr/include/openblas -I. -Wall -Wextra -pipe -O3 -g -ffast-math -flto -march=native -std=c++14 -DNDEBUG -MD -MP -c -o SGFParser.o SGFParser.cpp
g++ -I/usr/include/openblas -I. -Wall -Wextra -pipe -O3 -g -ffast-math -flto -march=native -std=c++14 -DNDEBUG -MD -MP -c -o Timing.o Timing.cpp
g++ -I/usr/include/openblas -I. -Wall -Wextra -pipe -O3 -g -ffast-math -flto -march=native -std=c++14 -DNDEBUG -MD -MP -c -o Utils.o Utils.cpp
g++ -I/usr/include/openblas -I. -Wall -Wextra -pipe -O3 -g -ffast-math -flto -march=native -std=c++14 -DNDEBUG -MD -MP -c -o FastBoard.o FastBoard.cpp
g++ -I/usr/include/openblas -I. -Wall -Wextra -pipe -O3 -g -ffast-math -flto -march=native -std=c++14 -DNDEBUG -MD -MP -c -o SGFTree.o SGFTree.cpp
g++ -I/usr/include/openblas -I. -Wall -Wextra -pipe -O3 -g -ffast-math -flto -march=native -std=c++14 -DNDEBUG -MD -MP -c -o Zobrist.o Zobrist.cpp
g++ -I/usr/include/openblas -I. -Wall -Wextra -pipe -O3 -g -ffast-math -flto -march=native -std=c++14 -DNDEBUG -MD -MP -c -o FastState.o FastState.cpp
g++ -I/usr/include/openblas -I. -Wall -Wextra -pipe -O3 -g -ffast-math -flto -march=native -std=c++14 -DNDEBUG -MD -MP -c -o GTP.o GTP.cpp
g++ -I/usr/include/openblas -I. -Wall -Wextra -pipe -O3 -g -ffast-math -flto -march=native -std=c++14 -DNDEBUG -MD -MP -c -o Random.o Random.cpp
g++ -I/usr/include/openblas -I. -Wall -Wextra -pipe -O3 -g -ffast-math -flto -march=native -std=c++14 -DNDEBUG -MD -MP -c -o SMP.o SMP.cpp
g++ -I/usr/include/openblas -I. -Wall -Wextra -pipe -O3 -g -ffast-math -flto -march=native -std=c++14 -DNDEBUG -MD -MP -c -o UCTNode.o UCTNode.cpp
g++ -I/usr/include/openblas -I. -Wall -Wextra -pipe -O3 -g -ffast-math -flto -march=native -std=c++14 -DNDEBUG -MD -MP -c -o UCTNodePointer.o UCTNodePointer.cpp
g++ -I/usr/include/openblas -I. -Wall -Wextra -pipe -O3 -g -ffast-math -flto -march=native -std=c++14 -DNDEBUG -MD -MP -c -o UCTNodeRoot.o UCTNodeRoot.cpp
g++ -I/usr/include/openblas -I. -Wall -Wextra -pipe -O3 -g -ffast-math -flto -march=native -std=c++14 -DNDEBUG -MD -MP -c -o OpenCL.o OpenCL.cpp
In file included from OpenCL.h:27:0,
                 from OpenCL.cpp:22:
./CL/cl2.hpp:5855:63: warning: ignoring attributes on template argument ‘cl_int {aka int}’ [-Wignored-attributes]
     typename std::enable_if<!std::is_pointer<T>::value, cl_int>::type
                                                               ^
./CL/cl2.hpp:6155:22: warning: ignoring attributes on template argument ‘cl_int {aka int}’ [-Wignored-attributes]
         vector<cl_int>* binaryStatus = NULL,
                      ^
g++ -I/usr/include/openblas -I. -Wall -Wextra -pipe -O3 -g -ffast-math -flto -march=native -std=c++14 -DNDEBUG -MD -MP -c -o OpenCLScheduler.o OpenCLScheduler.cpp
In file included from OpenCL.h:27:0,
                 from OpenCLScheduler.h:26,
                 from OpenCLScheduler.cpp:23:
./CL/cl2.hpp:5855:63: warning: ignoring attributes on template argument ‘cl_int {aka int}’ [-Wignored-attributes]
     typename std::enable_if<!std::is_pointer<T>::value, cl_int>::type
                                                               ^
./CL/cl2.hpp:6155:22: warning: ignoring attributes on template argument ‘cl_int {aka int}’ [-Wignored-attributes]
         vector<cl_int>* binaryStatus = NULL,
                      ^
g++ -I/usr/include/openblas -I. -Wall -Wextra -pipe -O3 -g -ffast-math -flto -march=native -std=c++14 -DNDEBUG -MD -MP -c -o NNCache.o NNCache.cpp
g++ -I/usr/include/openblas -I. -Wall -Wextra -pipe -O3 -g -ffast-math -flto -march=native -std=c++14 -DNDEBUG -MD -MP -c -o Tuner.o Tuner.cpp
In file included from OpenCL.h:27:0,
                 from Tuner.cpp:33:
./CL/cl2.hpp:5855:63: warning: ignoring attributes on template argument ‘cl_int {aka int}’ [-Wignored-attributes]
     typename std::enable_if<!std::is_pointer<T>::value, cl_int>::type
                                                               ^
./CL/cl2.hpp:6155:22: warning: ignoring attributes on template argument ‘cl_int {aka int}’ [-Wignored-attributes]
         vector<cl_int>* binaryStatus = NULL,
                      ^
g++ -flto -g -o leelaz Network.o FullBoard.o KoState.o Training.o TimeControl.o UCTSearch.o GameState.o Leela.o SGFParser.o Timing.o Utils.o FastBoard.o SGFTree.o Zobrist.o FastState.o GTP.o Random.o SMP.o UCTNode.o UCTNodePointer.o UCTNodeRoot.o OpenCL.o OpenCLScheduler.o NNCache.o Tuner.o  -lboost_program_options -lpthread -lz -lopenblas -lOpenCL
make[1]: Leaving directory '/content/leela-zero/src'
Info: creating stash file /content/leela-zero/autogtp/.qmake.stash
g++ -c -pipe -O2 -std=gnu++1y -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o main.o main.cpp
g++ -c -pipe -O2 -std=gnu++1y -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o Game.o Game.cpp
g++ -c -pipe -O2 -std=gnu++1y -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o Worker.o Worker.cpp
g++ -c -pipe -O2 -std=gnu++1y -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o Order.o Order.cpp
g++ -c -pipe -O2 -std=gnu++1y -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o Job.o Job.cpp
g++ -c -pipe -O2 -std=gnu++1y -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o Management.o Management.cpp
g++ -pipe -O2 -std=gnu++1y -Wall -W -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
/usr/lib/qt5/bin/moc -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/content/leela-zero/autogtp -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Worker.h -o moc_Worker.cpp
g++ -c -pipe -O2 -std=gnu++1y -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o moc_Worker.o moc_Worker.cpp
/usr/lib/qt5/bin/moc -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/content/leela-zero/autogtp -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Job.h -o moc_Job.cpp
g++ -c -pipe -O2 -std=gnu++1y -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o moc_Job.o moc_Job.cpp
/usr/lib/qt5/bin/moc -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/content/leela-zero/autogtp -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Management.h -o moc_Management.cpp
g++ -c -pipe -O2 -std=gnu++1y -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o moc_Management.o moc_Management.cpp
/usr/lib/qt5/bin/moc -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/content/leela-zero/autogtp -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Console.h -o moc_Console.cpp
g++ -c -pipe -O2 -std=gnu++1y -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o moc_Console.o moc_Console.cpp
g++ -Wl,-O1 -o autogtp main.o Game.o Worker.o Order.o Job.o Management.o moc_Worker.o moc_Job.o moc_Management.o moc_Console.o   -lQt5Gui -lQt5Core -lGL -lpthread 
AutoGTP v16
Using 1 thread(s) for GPU(s).
Starting tuning process, please wait...
Net filename: networks/68d7c8fcabe792dfe2b8e8360629d08171ec8e02530b14f0451e59fa181733ce
net: 68d7c8fcabe792dfe2b8e8360629d08171ec8e02530b14f0451e59fa181733ce.
./leelaz --tune-only -w networks/68d7c8fcabe792dfe2b8e8360629d08171ec8e02530b14f0451e59fa181733ce
Using 2 thread(s).
RNG seed: 9989479592129604176
Detecting residual layers...v1...256 channels...40 blocks.
Initializing OpenCL.
Detected 1 OpenCL platforms.
Platform version: OpenCL 1.2 CUDA 9.2.176
Platform profile: FULL_PROFILE
Platform name:    NVIDIA CUDA
Platform vendor:  NVIDIA Corporation
Device ID:     0
Device name:   Tesla K80
Device type:   GPU
Device vendor: NVIDIA Corporation
Device driver: 396.44
Device speed:  823 MHz
Device cores:  13 CU
Device score:  1112
Selected platform: NVIDIA CUDA
Selected device: Tesla K80
with OpenCL 1.2 capability.

Started OpenCL SGEMM tuner.
Will try 290 valid configurations.
(1/290) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=16 NDIMB=8 NDIMC=8 NWG=16 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 0.4603 ms (455.6 GFLOPS)
(2/290) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=32 NDIMB=8 NDIMC=8 NWG=16 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 0.4028 ms (520.6 GFLOPS)
(5/290) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=32 NDIMB=8 NDIMC=8 NWG=32 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 0.3753 ms (558.9 GFLOPS)
(8/290) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=32 NDIMB=8 NDIMC=8 NWG=64 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 0.3372 ms (622.0 GFLOPS)
(9/290) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=64 NDIMB=8 NDIMC=8 NWG=64 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 0.2955 ms (709.6 GFLOPS)
(127/290) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=32 NDIMB=8 NDIMC=8 NWG=64 SA=1 SB=1 STRM=0 STRN=0 VWM=4 VWN=2 0.2846 ms (737.0 GFLOPS)
(128/290) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=64 NDIMB=8 NDIMC=8 NWG=64 SA=1 SB=1 STRM=0 STRN=0 VWM=4 VWN=2 0.2729 ms (768.5 GFLOPS)
(161/290) KWG=16 KWI=8 MDIMA=8 MDIMC=8 MWG=64 NDIMB=8 NDIMC=8 NWG=64 SA=1 SB=1 STRM=0 STRN=0 VWM=4 VWN=2 0.2721 ms (770.7 GFLOPS)
(276/290) KWG=16 KWI=8 MDIMA=8 MDIMC=8 MWG=64 NDIMB=8 NDIMC=8 NWG=64 SA=1 SB=1 STRM=0 STRN=0 VWM=4 VWN=4 0.2718 ms (771.5 GFLOPS)
Tuning process finished
Starting thread 1 on GPU 0
{
    "cmd": "selfplay",
    "hash": "68d7c8fcabe792dfe2b8e8360629d08171ec8e02530b14f0451e59fa181733ce",
    "hash_gzip_hash": "b5168159a3d65571e4f9bf2cedacc7cdf44d418ca13a20a7964ddbf1bff8c12e",
    "minimum_autogtp_version": "16",
    "minimum_leelaz_version": "0.15",
    "options": {
        "noise": "true",
        "playouts": "0",
        "randomcnt": "999",
        "resignation_percent": "0",
        "visits": "1601"
    },
    "options_hash": "007e49",
    "random_seed": "4302544105181036778",
    "required_client_version": "16"
}

Got new job: selfplay
net: 68d7c8fcabe792dfe2b8e8360629d08171ec8e02530b14f0451e59fa181733ce.
Engine has started.
Infinite thinking time set.
1 (B D16) 2 (W Q4) 3 (B D4) 4 (W R16) 5 (B P17) 6 (W Q14) 7 (B R3) 8 (W Q3) 9 (B R4) 10 (W R6) 11 (B R5) 12 (W Q5) 13 (B S6) 14 (W R2) `

**Comment by balabi0github** [comment]
@kwccoin Yeah, I know. I am just worried if those warnings matters

**Comment by chucklu** [comment]
@balabi0github 

> 
> !apt install nvidia-opencl-dev
> !apt install libboost-all-dev libopenblas-dev zlib1g-dev
> !apt install qt5-default qt5-qmake
> 
> !rm -rf leela-zero
> !git clone https://github.com/gcp/leela-zero
> !cd leela-zero/src && make
> 
> !cd leela-zero/autogtp && qmake -qt5
> !cd leela-zero/autogtp && make
> !cp leela-zero/src/leelaz leela-zero/autogtp/

!cd leela-zero/autogtp && ./autogtp -k sgf

Tried with your script, still  have some problems.
terminate called after throwing an instance of 'cl::Error'
*ERROR*: Could not talk to engine after launching.
```
AutoGTP v16
Using 1 thread(s) for GPU(s).
Starting tuning process, please wait...
Net filename: networks/2da87ea8da0f54e87b70159e6bb82811b61d1c31091b6e019fbe62aeaa803b9c
net: 2da87ea8da0f54e87b70159e6bb82811b61d1c31091b6e019fbe62aeaa803b9c.
./leelaz --tune-only -w networks/2da87ea8da0f54e87b70159e6bb82811b61d1c31091b6e019fbe62aeaa803b9c
Using 2 thread(s).
RNG seed: 3792090713662793847
Detecting residual layers...v1...256 channels...40 blocks.
Initializing OpenCL.
OpenCL: clGetPlatformIDs
terminate called after throwing an instance of 'cl::Error'
  what():  clGetPlatformIDs
Tuning process finished
Starting thread 1 on GPU 0
{
    "cmd": "selfplay",
    "hash": "2da87ea8da0f54e87b70159e6bb82811b61d1c31091b6e019fbe62aeaa803b9c",
    "hash_gzip_hash": "11f2fdf61a20b3b52e7b4052e2819f2757fc514f45e9ab0f3e43bb69856b65e0",
    "minimum_autogtp_version": "16",
    "minimum_leelaz_version": "0.15",
    "options": {
        "noise": "true",
        "playouts": "0",
        "randomcnt": "999",
        "resignation_percent": "5",
        "visits": "1601"
    },
    "options_hash": "b37dca",
    "random_seed": "7770404724080032133",
    "required_client_version": "16"
}

Got new job: selfplay
net: 2da87ea8da0f54e87b70159e6bb82811b61d1c31091b6e019fbe62aeaa803b9c.
*ERROR*: Could not talk to engine after launching.
```

**Comment by balabi0github** [comment]
@chucklu Are you sure you have correctly set Runtime as GPU? This type of error usually because it can not find GPU device, maybe google  doesn't  give you one at the moment

**Comment by chucklu** [comment]
@balabi0github  
Tried this command `!clinfo`, and I got this

> Number of platforms                               0

Maybe I need wait two or three days to start the training according this https://github.com/gcp/leela-zero/issues/1905
