### ISSUE TITLE
A 'freestyle' tournament is taking place in Germany

### ISSUE THREAD

**Issue by nerai** [leela-zero/leela-zero#1926]
This is just for your information and enjoyment.

Prof. Ingo Althöfer initiated an online team tournament in Germany which has virtually no restrictions on any kind of supplementary aids (hiring pro players, joseki books, ...), in particular computer usage is encouraged. You can review the rules and progress at https://www.althofer.de/codecentric-freistil.html

The official language is German. Team size is 2, matches are played roughly once a month from October until April 2019. There are 7 teams registered. KGS is used, room Deutsche Ecke. Time limit 60m + 15 stones in 5m. *Japanese rules and 7.0 komi* (sic).

Our team is called Oktgopus, KGS accounts Oktgopus1 and 2. So far, a few days ago we won the first match 2:0. I cannot comment on my team's setup, but it is generally expected that most teams are very strong. All our changes/improvements will be made available to the source project(s) after April.

**Comment by l1t1** [comment]
can leelaz play  7.0 komi well?

**Comment by nerai** [comment]
@wonderingabout Yeah, basically.

@l1t1 The Japanese rules and 7.0 komi must be considered by the human operator. We did not expect any bot to be able to do this itself.

**Comment by nerai** [comment]
@betterworld I agree that it is an important factor. As a counter point, the Japanese rules and Canadian byoyomi require some human skill still. Also, I was looking for a way to get good results with less expenses, and I believe I have found a few good angles of attack (that I would love to talk about but cannot). So just throwing money at the problem may not be enough to win.

Interestingly, one team decided to mirror both boards, such that their opponent is playing against himself. I am not sure what exactly happened, but in the end it was a tie (1:1). So there's that :)
