### ISSUE TITLE
Minor issue - not easy to id your own submitted games 

### ISSUE THREAD

**Issue by kwccoin** [leela-zero/leela-zero#1943]
Find no easy way to save the sgf file under linux but thanks for wonderingabout  there is a way out.  

Still it is hard to match the game sgf with the game published.

(a) can we have the file name same as the match data (to ease to find it on the site) or the site list can show the uploaded match sgf file name (as well  as the Match data hash if needed)

(b) and even better Is there any way to add a "token" to the main command so that somehow we can easy identify the game we submit to the  https://zero.sjeng.org/self-plays.   

===== Details for why I raise the issue ============

First thanks for great posting by wonderingabout i.e. https://github.com/gcp/leela-zero/issues/1905 (some minor issue related to nvidia-410 but resolve easily by combing the two related steps into one i.e. treat the stable 410 as using the latest).

I feel great to use the option of V100 instead of K80.  It is so fast compared with my windows 10 1080ti one (~3 min 1 game vs >30 min per game; my last result is 

28 game(s) (28 self played and 0 matches) played in 217 minutes = 466 seconds/game, 2739 ms/move, last game took 543 seconds.  

(Side track: did wonder why there is no matches and it seems my last one have some matches).  

However, if one look into the output 

`Score: B+Resign 
Winner: black
Uploading match: 09ce2bf322024e45bdfd3de0975ca48b.sgf for networks aba192255eeecdd25b8f5c5b10c031221c6b2c35021fa83e90e436396a05cd71 and 68d7c8fcabe792dfe2b8e8360629d08171ec8e02530b14f0451e59fa181733ce
Match data e85d2fdf385fdb7a0670575c55ef56c7acab4b4263666dd76cd4f12312e8af9c stored in database
3 game(s) (0 self played and 3 matches) played in 17 minutes = 352 seconds/game, 1770 ms/move, last game took 313 seconds.`

You cannot easy associate the game sgf with the match data output.  It is hard to find your games and their environment for which they are produced.  Some tuning would be lost.  

I finally decided to use 'nohup ./autogtp -k sgf &' 
and then use 'tail -n 100 nohup.out to monitor it' . Still it is hard

As I submit both 1080Ti, Vega56 and now V100, I really want to know how they compared.  But no way I can find it out.  

There are time record in the web site just none can be easily ID is from me or id which platform it was being generated.  It would be much helpful if I can access my games such as I can add a token say 1080Ti-W10-Mbp2017-8t ...

**Comment by Ishinoshita** [comment]
Also: I don't know how the process of posting the last 400 self-play games on https://zero.sjeng.org/self-play and the process of making the training file chunks are sequenced in time, but would be great, if feasible, to have at least the chunk number (if not also the game number whithin the chunk) in the self-play game label, either concatenated to the hash or in separate column. Would simplify sanity check, when needed.

**Comment by wonderingabout** [comment]
@kwccoin 

i hope you will find these steps helpful : 

![autogtp help k save sgf v2](https://user-images.githubusercontent.com/38690718/47152170-40681080-d2dc-11e8-9eeb-bfb680bad9c6.PNG)


download link for my example

(replace v1.zip) by whatever name you want, always a different one for each archive you make

**Comment by kwccoin** [comment]
@wonderingabout one good comment leading to V100,  then another good to help me to get my sgf files!!!! Heaven sent like!!!

Back to my trivial minor issue - I think we all want to help but on the path want to see something of our minor contribution.   Still as now I found -k work, I change the title and amend the comment.  

Still really want to associate the sgf and the published files.  In fact, I cannot match the sgf file name even with the directory storing the sgf files.

**Comment by wonderingabout** [comment]
@kwccoin 
by "associate the sgf", do you mean you want to identify which sgf is uploaded at which moment ?

if yes, you can go in allsgf folder, and use ls -t, it will sort them by date (most recent one on top) : 

![all sgf v3](https://user-images.githubusercontent.com/38690718/47164591-9e0a5600-d2f8-11e8-9f27-d71fa85152e7.PNG)

note that the sgf are also sorted by time in the zip archive : 

![all sgf sorted by date](https://user-images.githubusercontent.com/38690718/47164629-afebf900-d2f8-11e8-8be0-c0f710dad696.PNG)

glad to see i helped :)

**Comment by kwccoin** [comment]
My main suggestion is to have a way for the program to let us store a token for future reference.

***
Back to the name matching issue: 

What I suggest  if the token part is not easy to do, a way to associate with the 'Uploading match: 09ce2bf322024e45bdfd3de0975ca48b.sgf ...' to  the file in the  'Match data e85d2fdf385fdb7a0670575c55ef56c7acab4b4263666dd76cd4f12312e8af9c stored in database'  For example use the name of the sgf as part of the match data hash ...

**Comment by wonderingabout** [comment]
@kwccoin 

oh i understand what you mean
i dont think you can change sgf gamedata name so easily, but: 

i think an easier way to do what you know is to create a log text file in autogtp folder, by adding this autogtp option : 

 (-l : --logtextfile <directory>)

this would be a gedit text and would contain for every sgf uploaded, a format like this

> autogtp started 18/10/2018 :
> abc.sgf
> gamedata : abcdefghijzzzzzzz
> network : 68d7
> result : w+r
> moves : 158
> time : 10 minutes
> 
> efg.sgf
> gamedata : efghijzzzzzzzzzzzz
> network : 68d7
> result : b+r
> time : 10 minutes
> moves : 210
> 
> hij.sgf
> result : w+r
> network b : 68d7
> network w : 007k
> time : 5 minutes
> moves : 93
> 
> matchdata : hijklhmzzzzzzzzzz
> time : 3.7 minutes
> 
>

**Comment by kwccoin** [comment]
> @kwccoin
> 
> oh i understand what you mean
> i dont think you can change sgf gamedata name so easily, but:
> 
> i think an easier way to do what you want is to create a log text file in autogtp folder, by adding this autogtp option :
> 
> `(-l : --logtextfile <directory> )`
> `# saves a log text file of autogtp session in <directory> selected`
> 
> in your example, it would be :
> 
> `cd leela-zero/autogtp`
> `./autogtp -k allsgf -l logs`
> 
> this would be a gedit text and would contain, for every sgf uploaded, a format like this
> 
> > autogtp started 18/10/2018 :
> > type : selfplay
> > abc.sgf
> > gamedata : abcdefghijzzzzzzz
> > network b : 68d7
> > network w : 68d7
> > result : w+r
> > moves : 158
> > time : 7 minutes
> > type : selfplay
> > efg.sgf
> > gamedata : efghijzzzzzzzzzzzz
> > network b : 68d7
> > network w : 68d7
> > result : b+r
> > time : 10 minutes
> > moves : 210
> > type : match
> > hij.sgf
> > matchdata : hijklhmzzzzzzzzzz
> > network b : 68d7
> > network w : 007k
> > result : w+r
> > time : 3.7 minutes
> > moves : 93
> 
> > autogtp ends
> > total games produced : 3 games (2 selfplay games and 1 match games) in 20.7 minutes

That is good but seems do not have such option in my ubuntu gcp autogtp ver 16:

./autogtp -h
Usage: ./autogtp [options]

Options:
  -h, --help                            Displays this help.
  -v, --version                         Displays version information.
  -g, --gamesNum <num>                  Play 'gamesNum' games on one GPU at the
                                        same time.
  -u, --gpus <num>                      Index of the GPU to use for multiple
                                        GPUs support.
  -k, --keepSgf <output directory>      Save SGF files after each self-play
                                        game.
  -d, --debug <output directory>        Save training and extra debug files
                                        after each self-play game.
  -t, --timeout <time in minutes>       Save running games after the timeout
                                        (in minutes) is passed and then exit.
  -s, --single                          Exit after the first game is completed.
  -m, --maxgames <max number of games>  Exit after the given number of games is
                                        completed.
  -e, --erase                           Erase old networks when new ones are
                                        available.

**Comment by wonderingabout** [comment]
@kwccoin 
yes i know this option doesnt exist

i suggested someone adds a commit for it

**Comment by wonderingabout** [comment]
@kwccoin 

thankfully, i found a solution for your issue, and your solution was mine

add a startup script in your instance as described here : 
https://github.com/gcp/leela-zero/issues/1905#issuecomment-431791568

the script contains these commands (i added the -k allsgf modification for you) : 
(replace mygooglename by your gmail account name, or the custom name you chose if you did like me)

```
#!/bin/bash
sudo apt-get update && sudo apt-get -y upgrade && sudo apt-get -y dist-upgrade
cd /home/mygooglename/leela-zero/autogtp/ && ./autogtp -k allsgf
```

then everytime you start your instance (green circle),
now it will automatically start playing games even if you dont click SSH button, even if your computer is powered off !
so you dont have to do cd leela-zero/autogtp && ./autogtp anymore !

the log file that you wanted to have is also thankfully my solution too,
click on SSH button, and run this command (you can remove -b if you want to access older records, see the journal --help for more details) :

`sudo journalctl -u google-startup-scripts.service -b -e -f `

you will get something like this : 
https://github.com/gcp/leela-zero/issues/1905#issuecomment-431761756


i of course plan to add this to the main tutorial,
note also that the steps to create a new instance are much easier now

**Comment by sethtroisi** [comment]
closing old issue with proposed solution
