### ISSUE TITLE
--full-tuner can do 3 tunings instead of 1 or 2

### ISSUE THREAD

**Issue by liujn2018** [leela-zero/leela-zero#1973]
I have downloaded the latest source and compiled on google colab.
However, when I did the full tuner, the tuner process ran again and again.

My command is:
`!cd run_lz_in_gg && ./leelaz -w networks/2da87ea8da0f54e87b70159e6bb82811b61d1c31091b6e019fbe62aeaa803b9c.gz --full-tuner
`

The output is:
`Using 2 thread(s).
RNG seed: 11407022574244404640
Leela Zero 0.16  Copyright (C) 2017-2018  Gian-Carlo Pascutto and contributors
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; see the COPYING file for details.

BLAS Core: built-in Eigen 3.3.5 library.
Detecting residual layers...v1...256 channels...40 blocks.
Initializing OpenCL (autodetecting precision).
Detected 1 OpenCL platforms.
Platform version: OpenCL 1.2 CUDA 9.2.176
Platform profile: FULL_PROFILE
Platform name:    NVIDIA CUDA
Platform vendor:  NVIDIA Corporation
Device ID:     0
Device name:   Tesla K80
Device type:   GPU
Device vendor: NVIDIA Corporation
Device driver: 396.44
Device speed:  823 MHz
Device cores:  13 CU
Device score:  1112
Selected platform: NVIDIA CUDA
Selected device: Tesla K80
with OpenCL 1.2 capability.
Half precision compute support: No.
Detected 1 OpenCL platforms.
Platform version: OpenCL 1.2 CUDA 9.2.176
Platform profile: FULL_PROFILE
Platform name:    NVIDIA CUDA
Platform vendor:  NVIDIA Corporation
Device ID:     0
Device name:   Tesla K80
Device type:   GPU
Device vendor: NVIDIA Corporation
Device driver: 396.44
Device speed:  823 MHz
Device cores:  13 CU
Device score:  1112
Selected platform: NVIDIA CUDA
Selected device: Tesla K80
with OpenCL 1.2 capability.
Half precision compute support: No.

Started OpenCL SGEMM tuner.
Will try 5355 valid configurations.
(1/5355) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=16 NDIMB=8 NDIMC=8 NWG=16 SA=0 SB=0 STRM=0 STRN=0 VWM=1 VWN=1 0.7798 ms (151.3 GFLOPS)
(2/5355) KWG=16 KWI=2 MDIMA=8 MDIMC=16 MWG=64 NDIMB=8 NDIMC=8 NWG=32 SA=0 SB=0 STRM=0 STRN=0 VWM=1 VWN=1 0.4100 ms (287.7 GFLOPS)
(3/5355) KWG=32 KWI=2 MDIMA=8 MDIMC=16 MWG=64 NDIMB=8 NDIMC=8 NWG=32 SA=0 SB=0 STRM=0 STRN=0 VWM=1 VWN=1 0.4083 ms (288.9 GFLOPS)
(87/5355) KWG=16 KWI=2 MDIMA=8 MDIMC=16 MWG=64 NDIMB=8 NDIMC=8 NWG=32 SA=0 SB=0 STRM=0 STRN=0 VWM=2 VWN=1 0.3289 ms (358.7 GFLOPS)
(130/5355) KWG=32 KWI=8 MDIMA=32 MDIMC=16 MWG=64 NDIMB=16 NDIMC=8 NWG=32 SA=0 SB=0 STRM=0 STRN=0 VWM=2 VWN=1 0.3166 ms (372.6 GFLOPS)
(134/5355) KWG=32 KWI=8 MDIMA=8 MDIMC=8 MWG=64 NDIMB=32 NDIMC=8 NWG=32 SA=0 SB=0 STRM=0 STRN=0 VWM=2 VWN=1 0.2621 ms (450.1 GFLOPS)
(139/5355) KWG=16 KWI=8 MDIMA=32 MDIMC=8 MWG=64 NDIMB=32 NDIMC=8 NWG=32 SA=0 SB=0 STRM=0 STRN=0 VWM=2 VWN=1 0.2610 ms (452.0 GFLOPS)
(159/5355) KWG=32 KWI=8 MDIMA=16 MDIMC=8 MWG=64 NDIMB=32 NDIMC=8 NWG=32 SA=0 SB=0 STRM=0 STRN=0 VWM=4 VWN=1 0.2163 ms (545.3 GFLOPS)
(296/5355) KWG=16 KWI=8 MDIMA=16 MDIMC=8 MWG=64 NDIMB=16 NDIMC=8 NWG=32 SA=0 SB=0 STRM=0 STRN=0 VWM=4 VWN=2 0.1923 ms (613.5 GFLOPS)
(2361/5355) KWG=32 KWI=8 MDIMA=16 MDIMC=8 MWG=32 NDIMB=8 NDIMC=8 NWG=32 SA=1 SB=0 STRM=0 STRN=1 VWM=2 VWN=4 0.1903 ms (619.9 GFLOPS)
(2370/5355) KWG=32 KWI=8 MDIMA=8 MDIMC=8 MWG=32 NDIMB=8 NDIMC=8 NWG=32 SA=1 SB=0 STRM=0 STRN=1 VWM=4 VWN=4 0.1852 ms (637.1 GFLOPS)
(2711/5355) KWG=16 KWI=8 MDIMA=32 MDIMC=8 MWG=64 NDIMB=8 NDIMC=8 NWG=32 SA=1 SB=0 STRM=1 STRN=1 VWM=2 VWN=4 0.1818 ms (648.8 GFLOPS)
(3652/5355) KWG=16 KWI=8 MDIMA=8 MDIMC=8 MWG=64 NDIMB=16 NDIMC=8 NWG=32 SA=0 SB=1 STRM=0 STRN=1 VWM=8 VWN=2 0.1817 ms (649.2 GFLOPS)
(4602/5355) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=64 NDIMB=8 NDIMC=8 NWG=32 SA=1 SB=1 STRM=1 STRN=0 VWM=4 VWN=2 0.1814 ms (650.1 GFLOPS)
Wavefront/Warp size: 32
Max workgroup size: 1024
Max workgroup dimensions: 1024 1024 64 

Started OpenCL SGEMM tuner.
Will try 5355 valid configurations.
(1/5355) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=16 NDIMB=8 NDIMC=8 NWG=16 SA=0 SB=0 STRM=0 STRN=0 VWM=1 VWN=1 0.7486 ms (157.6 GFLOPS)
(2/5355) KWG=16 KWI=2 MDIMA=8 MDIMC=16 MWG=64 NDIMB=8 NDIMC=8 NWG=32 SA=0 SB=0 STRM=0 STRN=0 VWM=1 VWN=1 0.4401 ms (268.1 GFLOPS)
(17/5355) KWG=32 KWI=2 MDIMA=8 MDIMC=16 MWG=64 NDIMB=16 NDIMC=8 NWG=32 SA=0 SB=0 STRM=0 STRN=0 VWM=1 VWN=1 0.4366 ms (270.2 GFLOPS)
(87/5355) KWG=16 KWI=2 MDIMA=8 MDIMC=16 MWG=64 NDIMB=8 NDIMC=8 NWG=32 SA=0 SB=0 STRM=0 STRN=0 VWM=2 VWN=1 0.4358 ms (270.7 GFLOPS)
(130/5355) KWG=32 KWI=8 MDIMA=32 MDIMC=16 MWG=64 NDIMB=16 NDIMC=8 NWG=32 SA=0 SB=0 STRM=0 STRN=0 VWM=2 VWN=1 0.4190 ms (281.6 GFLOPS)
(134/5355) KWG=32 KWI=8 MDIMA=8 MDIMC=8 MWG=64 NDIMB=32 NDIMC=8 NWG=32 SA=0 SB=0 STRM=0 STRN=0 VWM=2 VWN=1 0.3727 ms (316.5 GFLOPS)
(139/5355) KWG=16 KWI=8 MDIMA=32 MDIMC=8 MWG=64 NDIMB=32 NDIMC=8 NWG=32 SA=0 SB=0 STRM=0 STRN=0 VWM=2 VWN=1 0.3722 ms (317.0 GFLOPS)
(204/5355) KWG=16 KWI=8 MDIMA=16 MDIMC=8 MWG=64 NDIMB=8 NDIMC=8 NWG=32 SA=0 SB=0 STRM=0 STRN=0 VWM=1 VWN=2 0.3668 ms (321.6 GFLOPS)
(281/5355) KWG=32 KWI=2 MDIMA=8 MDIMC=8 MWG=64 NDIMB=8 NDIMC=8 NWG=32 SA=0 SB=0 STRM=0 STRN=0 VWM=4 VWN=2 0.3532 ms (334.0 GFLOPS)
(302/5355) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=64 NDIMB=16 NDIMC=8 NWG=32 SA=0 SB=0 STRM=0 STRN=0 VWM=8 VWN=2 0.3529 ms (334.3 GFLOPS)
(1371/5355) KWG=32 KWI=2 MDIMA=32 MDIMC=8 MWG=64 NDIMB=16 NDIMC=8 NWG=32 SA=1 SB=0 STRM=0 STRN=0 VWM=1 VWN=1 0.3374 ms (349.6 GFLOPS)
(1443/5355) KWG=32 KWI=2 MDIMA=8 MDIMC=8 MWG=64 NDIMB=16 NDIMC=8 NWG=32 SA=1 SB=0 STRM=0 STRN=0 VWM=2 VWN=1 0.3170 ms (372.1 GFLOPS)
(1457/5355) KWG=16 KWI=2 MDIMA=32 MDIMC=8 MWG=64 NDIMB=32 NDIMC=8 NWG=32 SA=1 SB=0 STRM=0 STRN=0 VWM=2 VWN=1 0.3055 ms (386.2 GFLOPS)
(1475/5355) KWG=16 KWI=8 MDIMA=16 MDIMC=8 MWG=64 NDIMB=16 NDIMC=8 NWG=32 SA=1 SB=0 STRM=0 STRN=0 VWM=2 VWN=1 0.3049 ms (386.9 GFLOPS)
(1501/5355) KWG=32 KWI=8 MDIMA=16 MDIMC=8 MWG=64 NDIMB=16 NDIMC=8 NWG=32 SA=1 SB=0 STRM=0 STRN=0 VWM=4 VWN=1 0.2848 ms (414.1 GFLOPS)
(1608/5355) KWG=32 KWI=8 MDIMA=16 MDIMC=8 MWG=64 NDIMB=8 NDIMC=8 NWG=32 SA=1 SB=0 STRM=0 STRN=0 VWM=4 VWN=2 0.2805 ms (420.6 GFLOPS)
(4123/5355) KWG=16 KWI=2 MDIMA=16 MDIMC=8 MWG=64 NDIMB=16 NDIMC=8 NWG=32 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=1 0.2776 ms (424.9 GFLOPS)
(4260/5355) KWG=32 KWI=2 MDIMA=8 MDIMC=8 MWG=64 NDIMB=16 NDIMC=8 NWG=32 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 0.2696 ms (437.6 GFLOPS)
(4276/5355) KWG=16 KWI=8 MDIMA=8 MDIMC=8 MWG=64 NDIMB=8 NDIMC=8 NWG=32 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 0.2618 ms (450.6 GFLOPS)
(4284/5355) KWG=16 KWI=8 MDIMA=16 MDIMC=8 MWG=64 NDIMB=16 NDIMC=8 NWG=32 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 0.2534 ms (465.5 GFLOPS)
(4302/5355) KWG=16 KWI=8 MDIMA=8 MDIMC=8 MWG=64 NDIMB=16 NDIMC=8 NWG=32 SA=1 SB=1 STRM=0 STRN=0 VWM=8 VWN=2 0.2423 ms (486.8 GFLOPS)
Wavefront/Warp size: 32
Max workgroup size: 1024
Max workgroup dimensions: 1024 1024 64 
Using OpenCL single precision (less than 5% slower than half).
Detected 1 OpenCL platforms.
Platform version: OpenCL 1.2 CUDA 9.2.176
Platform profile: FULL_PROFILE
Platform name:    NVIDIA CUDA
Platform vendor:  NVIDIA Corporation
Device ID:     0
Device name:   Tesla K80
Device type:   GPU
Device vendor: NVIDIA Corporation
Device driver: 396.44
Device speed:  823 MHz
Device cores:  13 CU
Device score:  1112
Selected platform: NVIDIA CUDA
Selected device: Tesla K80
with OpenCL 1.2 capability.
Half precision compute support: No.

Started OpenCL SGEMM tuner.
Will try 5355 valid configurations.
(1/5355) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=16 NDIMB=8 NDIMC=8 NWG=16 SA=0 SB=0 STRM=0 STRN=0 VWM=1 VWN=1 0.5249 ms (224.8 GFLOPS)
(2/5355) KWG=16 KWI=2 MDIMA=8 MDIMC=16 MWG=64 NDIMB=8 NDIMC=8 NWG=32 SA=0 SB=0 STRM=0 STRN=0 VWM=1 VWN=1 0.4124 ms (286.0 GFLOPS)
(3/5355) KWG=32 KWI=2 MDIMA=8 MDIMC=16 MWG=64 NDIMB=8 NDIMC=8 NWG=32 SA=0 SB=0 STRM=0 STRN=0 VWM=1 VWN=1 0.4124 ms (286.1 GFLOPS)
(87/5355) KWG=16 KWI=2 MDIMA=8 MDIMC=16 MWG=64 NDIMB=8 NDIMC=8 NWG=32 SA=0 SB=0 STRM=0 STRN=0 VWM=2 VWN=1 0.3330 ms (354.3 GFLOPS)
(130/5355) KWG=32 KWI=8 MDIMA=32 MDIMC=16 MWG=64 NDIMB=16 NDIMC=8 NWG=32 SA=0 SB=0 STRM=0 STRN=0 VWM=2 VWN=1 0.3140 ms (375.7 GFLOPS)
(134/5355) KWG=32 KWI=8 MDIMA=8 MDIMC=8 MWG=64 NDIMB=32 NDIMC=8 NWG=32 SA=0 SB=0 STRM=0 STRN=0 VWM=2 VWN=1 0.2630 ms (448.5 GFLOPS)
(159/5355) KWG=32 KWI=8 MDIMA=16 MDIMC=8 MWG=64 NDIMB=32 NDIMC=8 NWG=32 SA=0 SB=0 STRM=0 STRN=0 VWM=4 VWN=1 0.2172 ms (543.0 GFLOPS)
(296/5355) KWG=16 KWI=8 MDIMA=16 MDIMC=8 MWG=64 NDIMB=16 NDIMC=8 NWG=32 SA=0 SB=0 STRM=0 STRN=0 VWM=4 VWN=2 0.1960 ms (602.0 GFLOPS)
^C`

**Comment by ihavnoid** [comment]
Looking at the code, it seems that the full tuner will run three times; once for single precision, another time for half precision, and then if single precision is selected, once more for single precision.  This is because invoking full tuner will not reuse prior tuned results.

I think the easy way is to explicitly disable the tunet on the third run although it feels a bit hacky...

**Comment by liujn2018** [comment]
@ihavnoid Thank you.

**Comment by Ttl** [comment]
Specifying `--precision` manually should run it only once for the specified precision. See the startup logs during precision autodetection to find out which precision is faster.

**Comment by gcp** [comment]
>I think the easy way is to explicitly disable the tunet on the third run although it feels a bit hacky...

What about only allowing full-tuner with an explicitly specified precision?

**Comment by pondturtle** [comment]
I specifically tried to do full tuning with explicitely specified single precision. It  generates tuning file (with suspiciously low performance number) which upon running LZ through GTP is ignored and instead LZ runs fast tuning automatically.

**Comment by ihavnoid** [comment]
@pondturtle  Seems a bit odd.  Can you put the actual command line that you used when you ran through GTP?

**Comment by ihavnoid** [comment]
@gcp my concern is that doing so is not a backwards-compatible behavior.  Anybody who was using 0.15 with the exact same command line will start seeing failures on the new behavior because they never assumed auto precision detection.  Explicitly running two batches of tuning might be the better, more sensible behavior - even if it takes double the runtime it at least doesn't break.

**Comment by pondturtle** [comment]
@ihavnoid 

`%~dp0\leelaz.exe --precision single --tune-only --threads 4 --gpu 0 --gpu 1 --full-tuner -w leelaz-modelbest`

**Comment by ihavnoid** [comment]
@pondturtle - it seems that you have two GPUs - possibly different ones.  Can you dump the full stdout so that we can understand what GPUs are used when...?

**Comment by gcp** [comment]
>@gcp my concern is that doing so is not a backwards-compatible behavior.

True, but I have no particular qualms about breaking --full-tuner. The need for it is something I want to get away from, i.e. only to be run very exceptionally.

Is the concern that a lot of people are using some sort of cloud scripts that would need an update?

**Comment by ihavnoid** [comment]
@gcp well I agree that this should be somewhat rare, but the concern is simply that we just don't know.

If we were to introduce non backward compatible behavior I would take the more extreme behavior that the full tuner implies tune only.  I dunno why anybody would want to wait for the full tuner to run while he/she wants to play a game right now...?

**Comment by ihavnoid** [comment]
I think I understand what's going on.  --tune-only terminates right after the first tuner completed, which is the single precision.  The second run that you saw from sabaki is the half precision run.

Looks like we can't just terminate leelaz right after the tuning is done - or the easier way is to explicitly request precision when somebody wants --tune-only and/or --full-tuner.

**Comment by pondturtle** [comment]
But it specifically says 

> Half precision compute support: No.

In light of that it makes no sense to me why LZ would run half precision tuning at all. Still  I reran full tuning with these parameters to check your assumption.

`%~dp0\leelaz.exe --tune-only --threads 4 --gpu 0 --gpu 1 --full-tuner -w leelaz-modelbest --precision half`

Doesn't seem to make any difference. Did I go wrong somewhere?

[GTP log from sabaki - half precision.txt](https://github.com/gcp/leela-zero/files/2544259/GTP.log.from.sabaki.-.half.precision.txt)
[log of full tuning - half precision.txt](https://github.com/gcp/leela-zero/files/2544260/log.of.full.tuning.-.half.precision.txt)

**Comment by Hersmunch** [comment]
What command line do you use in sabaki? Does it also include the same --precision argument as used for the full tuning? It looks like it is left on auto and therefore doing the tuning for the other precision that isn’t in the full tuning run.
Even without half precision compute support it is still possible to use half precision storage.

**Comment by ihavnoid** [comment]
Half precision 'compute' is different - the normal 'half precision' is that it computes in single precision but does the memory storage in half precision - that is, half precision 'memory storage' support (this is supported on most GPUs with a reasonable device driver since early 2010s).  This is the mode that you are using on sabaki.

This time, this seems to be what happened:
1) Full tuner on half precision
2) Run was on auto detection - since there is no single precision tune result it runs the single precision tuning routines, while reusing the half precision tuning results from the full tuner.

My experience is that the number of flops for the matrix multiplication is similar for both single and half precision, while half precision is significantly faster because all the other routines are much faster.

**Comment by ihavnoid** [comment]
@gcp for the fix, here is my suggestion:
- --full-tuner implies --tune-only
- --full-tuner requires explicit precision

What do you think?

**Comment by pondturtle** [comment]
So if I gather this correctly then something like 
```

%~dp0\leelaz.exe --tune-only --threads 4 --gpu 0 --gpu 1 --full-tuner -w leelaz-modelbest --precision half 

%~dp0\leelaz.exe --tune-only --threads 4 --gpu 0 --gpu 1 --full-tuner -w leelaz-modelbest --precision single
```

should give me best results?

**Comment by ihavnoid** [comment]
@pondturtle yes, for now.

**Comment by ihavnoid** [comment]
Hmm let's see if #1986 looks okay.

**Comment by gcp** [comment]
I had to back out the fix for this:

```
AutoGTP v17
Starting tuning process, please wait...
./leelaz --tune-only -w networks/6c7c1c83d15c53089b13f1a361853c5107f16fb163856ca3b2995d2a030ed04f.gz
Automatic precision not supported when tuning only
Please add '--precision single' or '--precision half'
```

AutoGTP wants to do a tuning run before starting, so it can inform that users what's going on. But it has no idea about what precision it should use, so it relies on autodetection.

**Comment by gcp** [comment]
>@gcp for the fix, here is my suggestion:  --full-tuner implies --tune-only --full-tuner requires explicit precision  What do you think?

This is fine, but somewhere along the way --tune-only also broke to only support explicit precision.

**Comment by alreadydone** [comment]
Would we store the detected precision (and maybe whether full tuner has been run) in leelaz_opencl_tuning as another attribute or in a separate file? That can be used to solve this and https://github.com/gcp/leela-zero/issues/1987 I assume.

**Comment by sethtroisi** [comment]
closing techsupport issue with PR and answer
