### ISSUE TITLE
Limiting GPU usage?

### ISSUE THREAD

**Issue by farmersrice** [leela-zero/leela-zero#1985]
When I run leela zero on linux (with lizzie) it uses 100% of the gpu, and as a result my screen basically becomes frozen and unusable. Is there some way to cap the usage?

**Comment by gcp** [comment]
No. I don't know of any good way to do this either.

**Comment by alreadydone** [comment]
@farmersrice Have you tried using one thread only (`-t 1`)?

@gcp Maybe the idea is naive, but what about sleeping for a few microseconds [before forwarding jobs to GPU](https://github.com/gcp/leela-zero/blob/6d1649774ac8a2524185d02b9c5aca2d4f3c30e1/src/OpenCLScheduler.cpp#L256) (with some probability, or once per one hundred times), or maybe somewhere in the middle of [convolutions](https://github.com/gcp/leela-zero/blob/6d1649774ac8a2524185d02b9c5aca2d4f3c30e1/src/OpenCL.cpp#L199) ...

**Comment by fishcu** [comment]
I have the same problem, but running with a single thread helps! It's not a great solution, but the engine is by far strong enough for my purposes already!

**Comment by sethtroisi** [comment]
closing old techsupport issue with no follow up.
