### ISSUE TITLE
a weight of strong 10b

### ISSUE THREAD

**Issue by l1t1** [leela-zero/leela-zero#1991]
[ZQ-i8.gz](https://github.com/gcp/leela-zero/files/2545532/ZQ-i8.gz)
from qq group

**Comment by barrtgt** [comment]
Ran a quick test at 10 playouts vs. the last official 10 block 39d.
```
39d      v ZQ-i8    ( 425 games)
              wins        black       white
39d       209 49.18%   98 49.25%  111 49.12%
ZQ-i8     216 50.82%  101 50.75%  115 50.88%
                      199 46.82%  226 53.18%
```
Currently running a test at 100 playouts. Will edit with results later.

**Comment by l1t1** [comment]
it is said zq i8 run at 100 po is strong

**Comment by bash99** [comment]
So good than 39d at 100po?

**Comment by l1t1** [comment]
@barrtgt can you test a match  zq i8 vs lz117 at 100 po?

**Comment by barrtgt** [comment]
Running tests on other nets at the moment. Will update with results soon.

**Comment by l1t1** [comment]
@barrtgt can you post the command line of validation of two weights each use same time per move

**Comment by l1t1** [comment]
i saw this from lifein19x19
Vargo wrote:

If you run a match at TIME PARITY, I bet you'll see a big difference !
```
"True" time parity test - v16 vs v15 (3s per move, 2x1080ti, #184):

Code:

gogui-twogtp -black "C:\APPS\l0gpu16\leelaz.exe --gtp --weights=C:\APPS\net\2da87ea8.gz -t 12 --gpu 0 --gpu 1 --noponder --precision half" -white "C:\APPS\l0gpu\leelaz.exe --gtp --weights=C:\APPS\net\2da87ea8.gz -t 12 --gpu 0 --gpu 1 --noponder" -games 50 -sgffile v16-v15 -auto -time 1s+4s/1 -komi 7.5 -verbose
gogui-twogtp -white "C:\APPS\l0gpu16\leelaz.exe --gtp --weights=C:\APPS\net\2da87ea8.gz -t 12 --gpu 0 --gpu 1 --noponder --precision half" -black "C:\APPS\l0gpu\leelaz.exe --gtp --weights=C:\APPS\net\2da87ea8.gz -t 12 --gpu 0 --gpu 1 --noponder" -games 50 -sgffile v15-v16 -auto -time 1s+4s/1 -komi 7.5 -verbose
```

**Comment by l1t1** [comment]
when I run leelaz -h , I didnot see -auto -time options

**Comment by barrtgt** [comment]
Yes 0.16 is definitely faster for the larger networks. The smaller networks, 10 blocks and under, have taken a hit in terms of speed going from 0.15 to 0.16 for me. But the larger networks are much better on my desktop anyways. Maybe someone could use knowledge distillation with the elf networks into 10 block for use with phones.

**Comment by y-ich** [comment]
@l1t1 san,
How can I contact the author of ZQ-i8.gz?
I want to ask permission to use the weight for my app.

Thanks.

**Comment by l1t1** [comment]
a 144x12b weight, which win lz157
Detecting residual layers...v1...144 channels...12 blocks.
https://userscloud.com/duy8n6dwmec4

**Comment by l1t1** [comment]
quantized https://userscloud.com/pipkpy6ukq0a
