### ISSUE TITLE
Version 0.16 (Win7, 64bit) crashes Intel HD Graphics 4000 driver

### ISSUE THREAD

**Issue by WeirdConstructor** [leela-zero/leela-zero#1997]
Since Version 0.16 I get GPU driver crashes at startup of leelaz.exe: A popup by Windows appears, saying (roughly translated from German): 'The Displaydriver 'Intel HD Graphics Drivers for Windows 8(R)" does not respond anymore'. The same thing worked fine with Version 0.15.

The GPU is really not fast and does not bring that much of improvement compared to CPU-only.
But I thought I would report this anyways, just in case there is some other underlying issue. On my other desktop computer with a GTX 1060 LeelaZero 0.16 runs fine.

My system is a regular Dell Optiplex 7010 office/development workhorse with a slow GPU:

- OS: Windows 7 64-bit
- CPU: Intel Core I7-3770 CPU
- GPU: Intel HD Graphics 4000
- Drivers were updated to most recent version that is provided by Dell (as the Intel driver refuses to install on this Dell OEM PC), but did not change the error.

The OpenCL tuning string:
`0;XgemmBatched;256;25;256;36; -DKWG=16 -DKWI=2 -DMDIMA=16 -DMDIMC=16 -DMWG=64 -DNDIMB=8 -DNDIMC=8 -DNWG=32 -DSA=1 -DSB=1 -DSTRM=0 -DSTRN=0 -DVWM=2 -DVWN=4;OpenCL: Intel(R) Corporation Intel(R) HD Graphics 4000 @ 1150MHz`

This is the output from leelaz.exe, the displays go black once "Max workgroup dimensions: 512 512 512" is printed and the above stated message appears from Windows.

```
> .\leelaz.exe -w ..\weights\6c7c1c83d15c53089b13f1a361853c5107f16fb163856ca3b2995d2a030ed04f.gz
Using 2 thread(s).
RNG seed: 7298082166808283844
Leela Zero 0.16  Copyright (C) 2017-2018  Gian-Carlo Pascutto and contributors
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; see the COPYING file for details.

BLAS Core: Sandybridge
Detecting residual layers...v1...256 channels...40 blocks.
Initializing OpenCL (autodetecting precision).
Detected 1 OpenCL platforms.
Platform version: OpenCL 1.2
Platform profile: FULL_PROFILE
Platform name:    Intel(R) OpenCL
Platform vendor:  Intel(R) Corporation
Device ID:     0
Device name:   Intel(R) HD Graphics 4000
Device type:   GPU
Device vendor: Intel(R) Corporation
Device driver: 10.18.10.4425
Device speed:  1150 MHz
Device cores:  16 CU
Device score:  612
Device ID:     1
Device name:   Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
Device type:   CPU
Device vendor: Intel(R) Corporation
Device driver: 3.0.1.10891
Device speed:  3400 MHz
Device cores:  8 CU
Device score:  512
Selected platform: Intel(R) OpenCL
Selected device: Intel(R) HD Graphics 4000
with OpenCL 1.2 capability.
Half precision compute support: No.
Detected 1 OpenCL platforms.
Platform version: OpenCL 1.2
Platform profile: FULL_PROFILE
Platform name:    Intel(R) OpenCL
Platform vendor:  Intel(R) Corporation
Device ID:     0
Device name:   Intel(R) HD Graphics 4000
Device type:   GPU
Device vendor: Intel(R) Corporation
Device driver: 10.18.10.4425
Device speed:  1150 MHz
Device cores:  16 CU
Device score:  612
Device ID:     1
Device name:   Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
Device type:   CPU
Device vendor: Intel(R) Corporation
Device driver: 3.0.1.10891
Device speed:  3400 MHz
Device cores:  8 CU
Device score:  512
Selected platform: Intel(R) OpenCL
Selected device: Intel(R) HD Graphics 4000
with OpenCL 1.2 capability.
Half precision compute support: No.
Loaded existing SGEMM tuning.
Wavefront/Warp size: 16
Max workgroup size: 512
Max workgroup dimensions: 512 512 512
```

As comparison here is the output of leela 0.15 on that system, which does not crash:

(Here is the OpenCL tuning string for 0.15 that works:
`0;XgemmBatched;256;100;256;16; -DKWG=16 -DKWI=2 -DMDIMA=8 -DMDIMC=8 -DMWG=64 -DNDIMB=16 -DNDIMC=8 -DNWG=64 -DSA=1 -DSB=1 -DSTRM=1 -DSTRN=0 -DVWM=4 -DVWN=2;OpenCL: Intel(R) Corporation Intel(R) HD Graphics 4000 @ 1150MHz` )

```
> .\leelaz.exe -w ..\weights\6c7c1c83d15c53089b13f1a361853c5107f16fb163856ca3b2995d2a030ed04f.gz
Using 2 thread(s).
RNG seed: 7869060061316344418
Leela Zero 0.15  Copyright (C) 2017-2018  Gian-Carlo Pascutto and contributors
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; see the COPYING file for details.

Detecting residual layers...v1...256 channels...40 blocks.
Initializing OpenCL.
Detected 1 OpenCL platforms.
Platform version: OpenCL 1.2
Platform profile: FULL_PROFILE
Platform name:    Intel(R) OpenCL
Platform vendor:  Intel(R) Corporation
Device ID:     0
Device name:   Intel(R) HD Graphics 4000
Device type:   GPU
Device vendor: Intel(R) Corporation
Device driver: 10.18.10.4425
Device speed:  1150 MHz
Device cores:  16 CU
Device score:  612
Device ID:     1
Device name:   Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
Device type:   CPU
Device vendor: Intel(R) Corporation
Device driver: 3.0.1.10891
Device speed:  3400 MHz
Device cores:  8 CU
Device score:  512
Selected platform: Intel(R) OpenCL
Selected device: Intel(R) HD Graphics 4000
with OpenCL 1.2 capability.
Loaded existing SGEMM tuning.
Wavefront/Warp size: 8
Max workgroup size: 512
Max workgroup dimensions: 512 512 512
BLAS Core: Sandybridge

Passes: 0            Black (X) Prisoners: 0
Black (X) to move    White (O) Prisoners: 0

   a b c d e f g h j k l m n o p q r s t
19 . . . . . . . . . . . . . . . . . . . 19
18 . . . . . . . . . . . . . . . . . . . 18
17 . . . . . . . . . . . . . . . . . . . 17
...
```

**Comment by l1t1** [comment]
blas version different?

**Comment by l1t1** [comment]
https://github.com/xianyi/OpenBLAS/blob/develop/README.md

**Comment by WeirdConstructor** [comment]
The libopenblas.dll that came with 0.15 is 29.12 MB big (mtime = 2018-01-08 13:34:36).
The libopenblas.dll that came with 0.16 is 19.52 MB big (mtime = 2018-11-05 11:54:51).

Replacing the libopenblas.dll in the 0.16 distribution with the one that came with 0.15 brings no change.

**Comment by Ttl** [comment]
Your drivers are broken. Nothing we can fix but it might be possible to circumvent it somehow.

Does adding `--precision single` argument on command line help?

**Comment by WeirdConstructor** [comment]
> Your drivers are broken. Nothing we can fix but it might be possible to circumvent it somehow.

Yes, I guessed it might be a driver issue, as that GPU was/is not intended for any serious GPU work in the first place. I don't mind.

> Does adding `--precision single` argument on command line help?

In fact, that changes the error a bit. If I give --precision single at cmd line, it starts up until I see the board position. But once I give the genmove command, the same error appears (blank screen & driver crash notification).

Thanks for the feedback. I will use a proper GPU or CPU only on that machine then.

**Comment by wonsiks** [comment]
Mine has same problem.
So I'm using version 0.15 for Lizzie now.

**Comment by Jaafarw** [comment]
Same problem here with the intel HD 4000, it stops working without crashing after 
`Max workgroup dimensions: 512 512 512`

Adding --precision single shows the board but crashes the PC

**Comment by WeirdConstructor** [comment]
I guess this is no longer relevant 2+ years later.
