### ISSUE TITLE
About continuation of interrupted autogtp training

### ISSUE THREAD

**Issue by simonnier** [leela-zero/leela-zero#1999]
Dear developers,

Currently, we have a large group of people training leelaz on google colab. Since colab limit GPU time for 1 hour, a typical running of leelaz on colab will finish 2 to 3 games using latest 0.16 version. However, when colab suddenly stops, the last game is wasted. It is especially a pity when the last game is long and almost finished.

As an example, this is the third game running on a colab accout, and it stopped at 150, what a pity
![image](https://user-images.githubusercontent.com/11294083/48122622-f6f35b80-e2b2-11e8-8169-592f257cc9fd.png)

But I just noticed that autogtp has -t option to limit running time. For example -t10 will limit autogtp run 10 minutes , and when 10 minutes is up, the unfinished games will store as three files: a sgf file, a train file, a bin file. If we start autogtp locally, it will continue previous training by loading these 3 files. So I am wondering why not make this continuation scheme a distributed scheme? We can simply make autogtp upload unfinished temporary files when it is using -t option, and on the server side, it could dispatch unfinished games to other clients if it finds some. This should not be so hard to implement in my naive thought. And if this is realized, training on colab will have no wasted games (we can run ./autogtp -t58, to limit it within 1 hour before it is interrupted), that will be quite good.

best regards

**Comment by alreadydone** [comment]
We could ask SAI people for help since they already implemented this ...

**Comment by balabi0github** [comment]
@alreadydone Is SAI open source? I can not find a github of SAI

**Comment by l1t1** [comment]
sai https://github.com/gcp/leela-zero/issues/1835

**Comment by balabi0github** [comment]
> sai #1835

Thank you so much

**Comment by Vandertic** [comment]
Hi, we have public github for [sai](https://github.com/sai-dev/sai) and for sai-[server](https://github.com/sai-dev/sai-server). Sadly, they are forks of fairly old master branches of LZ and server. This is in particular true for the server, but maybe you  can manage.

**Comment by sethtroisi** [comment]
closing old suggestion thread
