### ISSUE TITLE
Minigo converter script does not work well with the most recent minigo weights

### ISSUE THREAD

**Issue by wpstmxhs** [leela-zero/leela-zero#2020]
Tensorflow fails to load the minigo weight to convert.

See below for the most recent minigo network weights:
https://github.com/tensorflow/minigo/issues/568

Is there anyone to help?

**Comment by alreadydone** [comment]
The script is from https://github.com/gcp/leela-zero/pull/1538 so @Ttl

**Comment by sethtroisi** [comment]
@wpstmxhs, Sorry I missed your message in 568.
Out of curiosity what model are you trying to convert?  and what run is it from v10? v12? v13?

I broke the script in https://github.com/tensorflow/minigo/pull/292 when I removed bias on conv2d layers.
I was working on fixing the converter script in this branch but other stuff got in the way of finishing that.
https://github.com/gcp/leela-zero/compare/master...sethtroisi:mcts?expand=1#diff-b9843922aa6e2ef4e2063c05f087381b

**Comment by wpstmxhs** [comment]
@sethtroisi Yes, I noticed that conv layer's bias was removed when I was working with the most recent networks.
But I had no idea how to make it work right, so I wrote an issue to get help.
I just wanted to test the most recent minigo weights on Lizzie with convenience.
Korean go enthusiasts are waiting for it. Thank you for your work.

**Comment by amj** [comment]
@wpstmxhs have you tried our front-end, 'minigui' ?

**Comment by wpstmxhs** [comment]
@amj I've never tried it but i know its existence. I'll take a look into it.
Thank you for nice project, @amj !

**Comment by wpstmxhs** [comment]
@sethtroisi Oh, Does minigo's value head output differ from Leela Zero's one?
Then Leela Zero should be modified to fit into minigo weights.
Thank you for your hard work and nice tips!

**Comment by sethtroisi** [comment]
I made good progress on this. 

https://github.com/gcp/leela-zero/compare/next...sethtroisi:converter?expand=1

I'll queue up some games between LZ and MG with the "same" model and verify 50% winrate then I'll try to clean this up to a patch.

**Comment by sethtroisi** [comment]
I fixed this for models up to and including v16
v17 uses squeeze-and-excitation which isn't supported in LZ currently.
