### ISSUE TITLE
a go gui can use multi engines

### ISSUE THREAD

**Issue by l1t1** [leela-zero/leela-zero#2048]
looks fine
https://github.com/popojan/goban
now support gnugo and pachi, can someone port it to use leelaz?

**Comment by WeirdConstructor** [comment]
goban can actually use any GTP engine as far as I understand. you just need to configure it. if you wonder how, you should open up an issue on their github project about missing documentation.

**Comment by l1t1** [comment]
solved. thanks
https://github.com/popojan/goban/issues/3#issuecomment-442265140

**Comment by denniscxc** [comment]
can you give an example of two GPU? thanks

**Comment by popojan** [comment]
> can you give an example of two GPU? thanks

it works, as long as the processes can share the graphics card
you can even switch engines/players in the middle of the game

missing docs is a good point

![image](https://user-images.githubusercontent.com/8307969/49391867-1f913880-f72d-11e8-8d56-6955dc280907.png)

**Comment by sethtroisi** [comment]
closing old announcement issue with no action items
