### ISSUE TITLE
"Couldn't set default memory limits" and benchmark bugs

### ISSUE THREAD

**Issue by Marcin1960** [leela-zero/leela-zero#2094]
I tried 32bit,GPU LZ v16 and got this error. I made a temporary fix (next below) and it works.

(Mentioned on https://github.com/gcp/leela-zero/issues/2091)

I tried to run 99297f (new strong 192x15) and got following errors:

Loaded existing SGEMM tuning.
Wavefront/Warp size: 64
Max workgroup size: 256
Max workgroup dimensions: 256 256 256
LOW MEMORY SETTINGS! Couldn't set default memory limits.
The network you are using might be too big
for the default settings on your system.
gru 22, 2018 12:53:16 PM com.gokgs.client.gtp.GtpClient d
FINE: EOF from engine, closing down.

===
Fix/hack:

 I commented out throwing exception in void GTP::initialize (GTP.cpp, 102):
// throw std::runtime_error("Error setting memory requirements.");

And it works!!! Running as LeelaZeroT on KGS

**Comment by evdwerf** [comment]
I saw something similar when cross-compiling 0.16 for Android; a simple work around was to change some values for DEFAULT_MAX_MEMORY in UCTSearch.h, but then later I got the weird situation that it could load some big networks but failed on a small network, so I suspect there is a more subtle bug hiding somewhere related to the word size, sign bit or some kind of cast error. 

BTW I think it's a bit silly to specify memory defaults at byte level precision; just go for megabytes and there's no more hassle with the type range.

**Comment by l1t1** [comment]
when deal with small weights, give DEFAULT_MAX_MEMORY a defaut value big enough, eg, 256MB

**Comment by Marcin1960** [comment]
@l1t1: "when deal with small weights, give DEFAULT_MAX_MEMORY a defaut value big enough, eg, 256MB"

You mean to make a separate branch for  small weights? I think this is a bug.

**Comment by Marcin1960** [comment]
Another bug. For Win 32 benchmark output does not show.

**Comment by sethtroisi** [comment]
closing techsupport issue with proposed solution
