### ISSUE TITLE
`printsgf' and 'loadsgf' have incomplete time property support

### ISSUE THREAD

**Issue by Hersmunch** [leela-zero/leela-zero#2097]
Noticed whilst testing #2096.
leelaz doesn't parse sgf time properties for a `loadsgf` GTP command. `printsgf` also doesn't write time or stones remaining for either side. See e.g. https://www.red-bean.com/sgf/properties.html#BL

I realise that [the GTP spec](http://www.lysator.liu.se/~gunnar/gtp/gtp2-spec-draft2/gtp2-spec.html) only mentions `loadsgf` and the effect given is met:
> Board size and komi are set to the values given in the sgf file. Board configuration, number of captured stones, and move history are found by replaying the game record up to the position before move_number or until the end if omitted.

However, I think that adding support for saving and parsing the other time properties would be desirable for both users playing against leelaz and for pausing and resuming any games with time controls set up as per #2096.

**Comment by gcp** [comment]
The complication is probably that the way to notate the time isn't standardized. Would still be nice if it was at least lossless in Leela itself, though.
