### ISSUE TITLE
Upcoming metabot OGS AI tournament - OGS 2019x19

### ISSUE THREAD

**Issue by wonderingabout** [leela-zero/leela-zero#2109]
hi, 

i will be helding an AI tournament on OGS, are you in ? 

![phoenixgo-text-winrate](https://user-images.githubusercontent.com/38690718/50558337-96e6c780-0ced-11e9-849a-5334809f3096.png)

- AI group link : 
https://online-go.com/group/3211

tournament 1st edition link : 
- **The 1st edition of the OGS AI tournament will be Saturday 12 January 2019, starting at 09:00 AM GMT Time**
https://online-go.com/tournament/44207

Please read rules, everyone is welcome

@roy7 @alreadydone @AncalagonX @l1t1 @Friday9i @bjiyxo @yenw @baduk1 @bubblesld @Marcin1960 @Mardak @Ishinoshita @godmoves @MartinDevelopment @petgo3 @Hersmunch @marcocalignano @TFiFiE @Ttl @tterava @pangafu @lemonsqueeze

i mentionned the most likely and frequent names i saw, but again everyone is welcome,

read carefully rules though please, especially regarding AI diversity condition

Max number is 10 participants 

Participants so far (will be updated)

1. me, with PhoenixGo 20b native provided by Tencent github : https://online-go.com/user/view/592558//meta-金毛测试-20b
2. Saphira AI, an AI trained on human games, stronger than leela zero : https://online-go.com/user/view/598330/Saphira-test
3. roy7 RoyalZero : https://online-go.com/player/484523/RoyalZero
4. Stefe has confirmed to enter with NightlyLeela (most likely elf v1) : https://online-go.com/player/530672/NightlyLeela
5. Dorus has confirmed to run the new lz 15b #2091 released by @bjiyxo recently : https://online-go.com/user/view/195118/Dorus using the 15bTurboLeela bot account https://online-go.com/player/602660/15bTurboLeela
6. mafutrct https://online-go.com/user/view/30107/mafutrct is interested to take one seat too with a customized LZ : lz 40b weights with a significantly modified search algorithmm, which is nerai13 AI : https://online-go.com/player/602718/nerai13
7. FREE SEAT
8. FREE SEAT
9. FREE SEAT
10. FREE SEAT

**UPDATE : if there are many bots, i am willing to open a B block with 10 new seats !!** 
update 2 : due to new things to manage (nothing dire), Aquabot informed me he will not be able use his AI at the same time, but will be looking forward to it : https://online-go.com/player/495496/AquaBotTest

4 seats remain now

community discussion here : 

- leela zero github : https://github.com/gcp/leela-zero/issues/2109
- leela zero discord : https://discord.gg/5vacH5F
- lifein19x19 forum : https://www.lifein19x19.com/viewtopic.php?f=18&t=16340
- reddit r/cbaduk : https://www.reddit.com/r/cbaduk/comments/ab9utu/upcoming_ogs_ai_tournament_2019x19/
- ogs forum : https://forums.online-go.com/t/ai-tournament-metabot-2019x19/19727
- go players discord : https://discord.gg/Tbdp2z3

**Comment by wonderingabout** [comment]
tournament just created now : 

https://online-go.com/tournament/44193

looking forward to it

**Comment by wonderingabout** [comment]
@Ishinoshita thanks :)

i also am looking forward to it, i hope we'll see many new AI

as for time limit, remember that it is a time limit : i do not plan this tournament to last one year, the time limit is here to end the game fast if the bot admin is away (after 24 hours the bot will lose by timeout)

also, i set the following playouts limit so that : 

- this tournament can be played with simple hardware
- this tournament will NOT be a horse race of who has the most powerful hardware
- at the opposite, this tournament is aimed to be fair and played in a friendly and non competitive environment

- for 40b : 10 000 playouts max
- for 20b : 18 000 playouts max
- for 15b : 20 000 playouts max

**Comment by wonderingabout** [comment]
opened a reddit page here : https://www.reddit.com/r/cbaduk/comments/ab9utu/upcoming_ogs_ai_tournament_2019x19/

**Comment by barrtgt** [comment]
I would like to hear more about Saphira. I'm glad to see more strong supervised ai.

**Comment by wonderingabout** [comment]
list of possible AI here (non exhaustive) : 
https://www.reddit.com/r/cbaduk/comments/7e05b8/go_software/

first that come to my mind 

ray
AQ
lz 15b new
leela master
crazystone
deep zen

**Comment by wonderingabout** [comment]
@barrtgt

Saphira is a japanese AI trained from 20k pro human games
it is a 15b network yet much stronger than the current lz with just 5000 playouts

**Comment by barrtgt** [comment]
@wonderingabout thanks

**Comment by wonderingabout** [comment]
welcome @barrtgt 

update : Mistunari has confirmed to be willing to participate, he will be using one seat of this tournament

update 2 : Stefe has confirmed to be entering too with NightlyLeela (most likely elf v1)

**Comment by l1t1** [comment]
https://online-go.com/game/15938164 hakudragon won

**Comment by wonderingabout** [comment]
only 2 free seats are left now

**Comment by wonderingabout** [comment]
this is an example of how the canadian clock will work for this tournament https://beta.online-go.com/game/4122

**Comment by wonderingabout** [comment]
**UPDATE : 

if there are many bots, i am willing to open a B block with 10 new seats !!**

**Comment by wonderingabout** [comment]
update 3 : due to new things to manage, Aquabot informed me he will not be able use his AI at the same time, but will be looking forward to it : https://online-go.com/player/495496/AquaBotTest

Mitsunari is also unsure to participate (need to set up the cloud, not decided yet)

**Comment by dbosst** [comment]
start date 15th or 12th of January?
Saturday is the 12th.... You have 15th several other places.... all mixed up

**Comment by wonderingabout** [comment]
second saturday of january, which can only be 12th my bad, will be fixed soon :)

**Comment by wonderingabout** [comment]
update : pondering is now DISABLED for this tournament, bot admins are forbidden to use --persist for the tournament

**Comment by wonderingabout** [comment]
so to sum up, 3 free seats remain out of 10

**Comment by wonderingabout** [comment]
update : Tokumoto has decided to withdraw his bot Bifron from the tournament

**Comment by wonderingabout** [comment]
update 2 : 

nerai13 AI is entering the competition (seat number 6) : https://online-go.com/player/602718/nerai13

without news from mitsunari, i have to withdraw him from the competition until i get any news

**Comment by wonderingabout** [comment]
the AI tournament has started !!!

https://online-go.com/tournament/44207

**Comment by wonderingabout** [comment]
end of tournament !!

phoenixgo got a bronze medal !!

![trophy](https://user-images.githubusercontent.com/38690718/51085588-fd330780-173b-11e9-906e-c9fd2b0e1f31.png)


we have many new ideas of what to improve and try for 2nd edition, which will be 

**sunday 10 february 2019**

the last game of phoenixgo vs 15b turbo leela had an amazing comeback by phoenixgo

**Comment by wonderingabout** [comment]
closed as it was stale
