### ISSUE TITLE
Any plan for cuda branch?

### ISSUE THREAD

**Issue by fell111** [leela-zero/leela-zero#211]
As I know currently the computing was implemented on opencl. Is there any plan to build up cuda branch?
It'll will increase the training speed greatly on Nvida card.

**Comment by isty2e** [comment]
I'm not sure but I don't think there's a fundamental difference in performance between CUDA and OpenCL. Things are different if CuDNN comes in, but this cannot be redistributed and individual user should make a NVIDIA account and download it. So in that case more complexities enter to the development, I suppose, and I doubt if gcp himself will consider branching for CuDNN.

However, there's a PR you probably are interested in [here](https://github.com/gcp/leela-zero/pull/196). It seems incomplete at this moment (for example, it doesn't automatically download new weight parameters if it gets updated), but will be mature in upcoming days, hopefully.

**Comment by NTT123** [comment]
It is *ready* to **test** now, checkout this branch https://github.com/NTT123/leela-zero/tree/udpserver 

Feedbacks are very welcome :-)

**Comment by bood** [comment]
@NTT123 Have you measured how much performance it gains? If it looks promising I'll give it a shot.

**Comment by NTT123** [comment]
I see about 2X speed up with simple tests on my GPU. Another guy with CPU only see ~ 10X speed up.

**Comment by bood** [comment]
@NTT123 Actually it appears to be slower than before! How can I verify it's using CuDNN lib. Any thoughts?
My GPU is K80 and running only one instance.

**Comment by NTT123** [comment]
Hmm, did you turn on the `USE_SERVER_TEST` flag?  In that case, it should be slower because it is run both OpenCL and Cuda to compare the results. For real running, just disable the flag.

Moreover, for this branch, @gcp suggested me to run with only 1 thread (which should lead to stronger player). So, for speeding up, your batch size should >= 2.

Perhaps, with the K80, you should set batch size = `16` or `8` or say `50`.

**Comment by bood** [comment]
ok, let me try test first. will there be a comparing result when running in test mode?

But how could it be possible that K80 can run like 50 `autogtp` instance? With the original version, one instance already make K80 like 90+% usage.

BTW is it by nature that CuDDN is much faster than opencl on NVIDIA cards?

**Comment by NTT123** [comment]
Test mode basically compares the output of two neural networks, OpenCL network and Cuda network. I put it there for checking the correctness of my implementation.

In this branch, leela does almost nothing cpu intensive. All computation is computed by a single theano process. Of course, you may not get about 50x speed up. But with K80 big memory, it is still better with large batch-size.

CUDNN is an optimised neural network library provided by Nvidia for Nvida GPUs. It *should* run faster than other libs but I don't know how much.

**Comment by bood** [comment]
Looks like `gpupy` is not installed earlier. But really frustrating installing that...giving up
You should really put that in your install instruction too.

**Comment by NTT123** [comment]
@bood Could you show your output of the command:

    THEANO_FLAGS='device=cuda0,dnn.conv.algo_fwd=time_once,floatX=float32' python server.py 4

**Comment by bood** [comment]
I think my `gpupy` is not correctly installed, and I've no idea how to fix (I followed the official instruction)
```
bood@leela-zero:~/cuda/leela-zero$ THEANO_FLAGS='device=cuda0,dnn.conv.algo_fwd=time_once,floatX=float32' python server.py 4
Leela Zero TCP Neural Net Service

Loading latest network
Hash: 92c658d7325fe38f0c8adbbb1444ed17afd891b9f208003c272547a7bcb87909
Downloading weights
Done!
 64 channels and 5 blocks

Compling the latest neural network
ERROR (theano.gpuarray): Could not initialize pygpu, support disabled
Traceback (most recent call last):
  File "/home/bood/.local/lib/python2.7/site-packages/theano/gpuarray/__init__.py", line 164, in <module>
    use(config.device)
  File "/home/bood/.local/lib/python2.7/site-packages/theano/gpuarray/__init__.py", line 151, in use
    init_dev(device)
  File "/home/bood/.local/lib/python2.7/site-packages/theano/gpuarray/__init__.py", line 60, in init_dev
    sched=config.gpuarray.sched)
  File "pygpu/gpuarray.pyx", line 614, in pygpu.gpuarray.init
  File "pygpu/gpuarray.pyx", line 566, in pygpu.gpuarray.pygpu_init
  File "pygpu/gpuarray.pyx", line 1021, in pygpu.gpuarray.GpuContext.__cinit__
GpuArrayException: Could not load "libnvrtc.so": libnvrtc.so: cannot open shared object file: No such file or directory: 0
Done!

Batch size = 4

Serving on ('127.0.0.1', 9999)

Starting a thread for auto updating latest weights
Now, you should run 4 autogtp instances at different locations to start the playing process
```

**Comment by NTT123** [comment]
How about you run

    LD_LIBRARY_PATH=[PATH] THEANO_FLAGS='device=cuda0,dnn.conv.algo_fwd=time_once,floatX=float32' python server.py 4

where `[PATH]` is your cuda library directory. E.g.,  `LD_LIBRARY_PATH=/usr/local/cuda/lib64`

**Comment by bood** [comment]
I think my cuda kit is not installed correctly, let me try that first

**Comment by NTT123** [comment]
@bood CUDA kit installation basically unzip files to a directory and set the correct environment variables.

Visit http://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#environment-setup for detail helps

**Comment by bood** [comment]
@NTT123 Some progress made, but still got an error complaining about header files:
```
bood@leela-zero:~$ THEANO_FLAGS=device=cuda0 python gpu_tutorial1.py
Can not use cuDNN on context None: cannot compile with cuDNN. We got this error:
In file included from /tmp/try_flags_UTP9sy.c:4:0:
/usr/include/cudnn.h:63:26: fatal error: driver_types.h: No such file or directory
 #include "driver_types.h"
                          ^
compilation terminated.

Mapped name None to device cuda0: Tesla K80 (043C:00:00.0)
[GpuElemwise{exp,no_inplace}(<GpuArrayType<None>(float64, (False,))>), HostFromGpu(gpuarray)(GpuElemwise{exp,no_inplace}.0)]
Looping 1000 times took 0.422130 seconds
Result is [ 1.23178032  1.61879341  1.52278065 ...,  2.20771815  2.29967753
  1.62323285]
Used the gpu
```

**Comment by NTT123** [comment]
Seem to me l, cuda is working, even though no cudnn. Try this first to see any speed up. Good luck ;)

**Comment by NTT123** [comment]
@bood Perhaps, you should copy CuDNN files into the same location as Cuda toolkit. 

E.g. 

     cp -r /path/to/CuDNN/lib/*    /path/to/cuda/lib/
     cp -r /path/to/CuDNN/include/*  /path/to/cuda/include/

**Comment by bood** [comment]
@NTT123 I ended up updating gpupy to 0.7.5, theaon to 1.0.0 since I'm using CUDA 9.0

**Comment by NTT123** [comment]
@bood tbh, I don't think *versions* is your problem. Your problem is about setting `PATH` and `LD_LIBRARY_PATH` correctly.

**Comment by bood** [comment]
Anyway, it's solved now. I'm running a batch size of 4, but nvidia-smi shows the gpu usage is only 60%

**Comment by NTT123** [comment]
How about speed?

**Comment by bood** [comment]
For each instance, it's obvious slower than the original version, but since there are 4, I don't know yet.
I thought the speed is bounded by GPU bandwidth, but you're saying it's bounded to GPU memory? And why in this CUDA version, a single instance cannot use as much GPU as before? (60% vs 90%)

**Comment by bood** [comment]
There does look like an improvement @NTT123 
Original version was like 1sec/move, and with batch 4 I got 0.5sec/move, with batch 32 it seems to be like 0.4sec/mov now.

But the GPU memory usage is still far from full even with 32, do you know why?

```
bood@leela-zero:~/cuda/leela-zero$ nvidia-smi
Thu Nov 30 11:31:04 2017
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.90                 Driver Version: 384.90                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 0000043C:00:00.0 Off |                    0 |
| N/A   83C    P0   103W / 149W |   2979MiB / 11439MiB |     59%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0     28512      C   python                                      2968MiB |
+-----------------------------------------------------------------------------+
```

**Comment by NTT123** [comment]
@bood Current leela neural network is still a small model, so it will not use much of the memory.

As I can see from your output, only 60% of GPU is used. This explains why you got a small speed up. I'm working a better version which hopefully uses more GPU powers. Please come back in few days.

**Comment by NTT123** [comment]
@bood Would you mind run the latest commit which now uses shared memory instead of tcp, to see any improvement? Thanks.

**Comment by bood** [comment]
@NTT123 Met following error, I'm using python `2.7.13`
```
bood@leela-zero:~/cuda/leela-zero/ipc$ python server.py 8
Traceback (most recent call last):
  File "server.py", line 40, in <module>
    mv  = memoryview(mem)
TypeError: cannot make memory view because object does not have the buffer interface
bood@leela-zero:~/cuda/leela-zero/ipc$ python --version
Python 2.7.13
```

**Comment by bood** [comment]
BTW I'm not a fan of implement the CUDA support this way actually, it makes setup more complicated. I prefer some kind of inline support in `leelaz`, easy for distribution too, is it possible?

**Comment by NTT123** [comment]
Yes, I agree with you. At first, my goal is to have a quick hack to see any speedup using CuDNN, but it then causes a lot of problems to communicate between Py anc C++. Will look at using Cudnn directly instead of a third-part library(e.g. Theano). 

Btw, the last commit fixed the incompatibility with Py27.

**Comment by bood** [comment]
@NTT123 working now, but GPU usage not improved. also still around 0.5s/move.
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.90                 Driver Version: 384.90                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 0000751F:00:00.0 Off |                    0 |
| N/A   53C    P0   118W / 149W |   2979MiB / 11439MiB |     57%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      3559      C   python                                      2968MiB |
+-----------------------------------------------------------------------------+
```

I'm running on Microsoft Azure actually, they have a $200 free credit for new users (10 days running for a NC6 instance, which has a K80 card attached), I think you can try yourself too.

**Comment by NTT123** [comment]
@bood, OK,  can you try  with `batchsize = 8 / 16 / 64 / 128`?

**Comment by bood** [comment]
Actually I already tried batch size 16 as well and it was very similar to 32 batch size. You can try it on NC6 yourself too. I can try other variations when I have time tomorrow if you insist, just don't think they'll make any difference.

**Comment by NTT123** [comment]
@bood Thanks for your information. I'll try NC6.

**Comment by bood** [comment]
@NTT123 Any updates recently? One of my friend also tried and see a small improvement in sgf generation with 4 batch and 12 batch, just FYI (divided by batch sized already):

`4 batch: 0.76s/move`

`12 batch: 0.58s/move`

**Comment by NTT123** [comment]
@bood, my last commit allows to run multiple batches in parallel for better using GPU. For example, if 1 batch uses only about 60% GPU, you may better run two batches in parallel.

See readme for instructions at https://github.com/NTT123/leela-zero

**Comment by bood** [comment]
Cool, I'll give a try later.

Still expecting  a inline implementation though. Thought should be easier than this? Just replace the calculation part in `Network.cpp` with cuDNN? I'm not a expert cuDNN though... wish I can do it by my own.

**Comment by NTT123** [comment]
@bood, Yes, I'm also not familiar with cuDNN. I'll try it in my free time.

You can follow a tutorial on cuDNN at http://www.goldsborough.me/cuda/ml/cudnn/c++/2017/10/01/14-37-23-convolutions_with_cudnn/

This tutorial has detail instructions to implement a convolutional layer which is the main part of Leela Zero network.

**Comment by bood** [comment]
BTW have you tried the new version on NC6 already? how it performs?

**Comment by NTT123** [comment]
I tried a few times yesterday but the website hangs up at the second step when I'm creating "Ubuntu WM for data scientist."

**Comment by bood** [comment]
```
Traceback (most recent call last):
  File "server.py", line 80, in <module>
    t2 = time.perf_counter()
AttributeError: 'module' object has no attribute 'perf_counter'
```
Still got python 2 compatible issue...

**Comment by NTT123** [comment]
Oh, my bad, just remove that line.

**Comment by bood** [comment]
So I opened two server instance with `LEELAZ=inst1 python server.py 16 8` and `LEELAZ=inst2 python server.py 16 8`, and running 16 leelaz each (so 32 in total), GPU usage is still around 60

Why do you need to run multiple servers if you already have backup instances for a single server? I mean the `16/8` thing. Doesn't they both try to do the same thing i.e. keeping the GPU busy?

**Comment by NTT123** [comment]
Explain this is a bit tricky. 

On my tested GPU, a batch size of, say, 100 will not use all GPU cores. When I increase batch size to 300, now each GPU-computing step uses all GPU cores, however, too many leelaz instances at each step consume all CPUs. The time for preparing inputs for each batch is longer than the time of GPU computation itself.

In other words, at 100% GPU, if we use 1 batch, CPU for each instance will slow down which causes GPU has to wait for the input of the next batch.

This is probably the reason why the speedup and GPU usage are much different across GPUs and CPUs.

So, my solution is to run 3 batches of 100 in parallel so each it step GPU doesn't have to wait and also can better use of GPU. But wait, does it also have 300 instances running and use all CPUs? The thing is, now, all 300 instances doesn't need to be synchronized (so don't slow everything down), only each 100s of them need to.

**Comment by isty2e** [comment]
@NTT123 For me it sounds like batch preparation is performed only after processing the previous batch with GPU, in a synchronous way... Or is the batch prepared so slowly so that the time required exceeds the GPU processing time?

**Comment by NTT123** [comment]
The latter. Preparation for each instance is not slow but 300 of them on 8 cpu is slow.

**Comment by isty2e** [comment]
Oh, quite surprising for me...

**Comment by NTT123** [comment]
@isty2e  Did you try multiple batches in parallel, any speed up?

**Comment by isty2e** [comment]
@NTT123 My GPU is one from AMD so I didn't even grab any chance to test it, unfortunately.

**Comment by bood** [comment]
@NTT123 This is how I interpret your explains (correct me if I were wrong):
If too many `leelaz` instances run at the same time, they generate data at about the same time, so CPU cannot finish process next batch of data for GPU before GPU complete the first batch, which causes GPU waiting for CPU.

But I'm afraid you're making things over complicated here... My suggestion would be building a pipeline-alike architecture:

1. `CPU threads` (leelaz) runs as fast as it can to prepare datas and feeding to GPU threads
2. `GPU threads` (your server) just consumes datas as fast as it can using GPU
3. some buffer in-between in case of over feeding

I also tried `64 16` and when starting `autogtp` I pause 10 seconds between every 16 autogtp instances, hoping data prepearing can be evenly distributed instead of a burst. But still no luck increasing GPU usage. Maybe implementation limitations I don't know here?

Command I was using:

`for n in {1..4}; do for i in {1..16}; do echo $n $i; (./autogtp -k ../sgf &); done; sleep 10; done`

**Comment by NTT123** [comment]
@bood, I'm creating (finally) a NC6 VM, so will get back to you soon.

**Comment by NTT123** [comment]
@bood, I tried with num instances = 64, batch size = 32 and run two batches in parallel. I get about 77-85 % GPU. It take about 45-46s for each move (total instances 128), so ~ 0.36s per move.

**Comment by zhu-jz** [comment]
I'm afraid the multiple batches is not work.

`python server.py 32` was tested on a NC6 VM, I got about 0.35 sec per move after running about 22 hours continuously, exactly is 77668 seconds for 219110 moves generated.

**Comment by NTT123** [comment]
@zhu-jz, thanks. I guess the speedup depend on machines. As on my tested GPU P5000, I can some speed up (and GPU usage) from multiple mini-batches.

**Comment by NTT123** [comment]
Hi, I merged v0.7 commits to my branch. We now use 1600 playouts, so it is about 1.6 times slower than before.

**Comment by bood** [comment]
It's v0.8 now

**Comment by NTT123** [comment]
I merged v0.8 already. My little experiment shows a better use of GPU than v0.6.

**Comment by zhu-jz** [comment]
looks good on a NC6 vm, 394 ms/move

![image](https://user-images.githubusercontent.com/5400130/33760680-72f4ea60-dc41-11e7-9f19-b06f6ebf503a.png)

**Comment by NTT123** [comment]
Great! What is your % GPU usage from `nvidia-smi`?

**Comment by zhu-jz** [comment]
`Fri Dec  8 11:34:29 2017
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.90                 Driver Version: 384.90                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00003A04:00:00.0 Off |                  Off |
| N/A   82C    P0   144W / 149W |   3175MiB / 12205MiB |     69%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0     17951      C   python                                      3164MiB |
+-----------------------------------------------------------------------------+
`

**Comment by bood** [comment]
@NTT123 Possible to merge next branch now?

**Comment by NTT123** [comment]
@bood, at first, I thought it will be easy, then, I realised the next branch uses multiple networks for testing at the same time. And It's a problem when using mini-batch, ...

**Comment by NTT123** [comment]
@bood, you may want to checkout my *premature* `next` branch which now runs cuda/cudnn directly from leelaz c++. No mini-batch supported. I only tested it on my macOS with Cuda SDK 9 + CuDNN7, perhaps, you need to modify the include/lib paths to make it works.

https://github.com/NTT123/leela-zero/tree/next

**Comment by bood** [comment]
When compiling darknet:

```
ptxas
/tmp/tmpxft_00007ccb_00000000-12_convolutional_kernels.compute_30.ptx, line
113; error   : Call has wrong number of parameters
ptxas
/tmp/tmpxft_00007ccb_00000000-12_convolutional_kernels.compute_30.ptx, line
142; error   : Call has wrong number of parameters
ptxas
/tmp/tmpxft_00007ccb_00000000-12_convolutional_kernels.compute_30.ptx, line
224; error   : Call has wrong number of parameters
ptxas
/tmp/tmpxft_00007ccb_00000000-12_convolutional_kernels.compute_30.ptx, line
254; error   : Call has wrong number of parameters
ptxas
/tmp/tmpxft_00007ccb_00000000-12_convolutional_kernels.compute_30.ptx, line
337; error   : Call has wrong number of parameters
ptxas
/tmp/tmpxft_00007ccb_00000000-12_convolutional_kernels.compute_30.ptx, line
357; error   : Call has wrong number of parameters
ptxas
/tmp/tmpxft_00007ccb_00000000-12_convolutional_kernels.compute_30.ptx, line
375; error   : Call has wrong number of parameters
ptxas
/tmp/tmpxft_00007ccb_00000000-12_convolutional_kernels.compute_30.ptx, line
395; error   : Call has wrong number of parameters
ptxas fatal   : Ptx assembly aborted due to errors
```

Any idea? @NTT123

**Comment by NTT123** [comment]
@bood, can you change this line [here](https://github.com/NTT123/leela-zero/blob/next/src/darknet/Makefile#L51)

to `LDFLAGS+= -L/usr/local/cuda/lib64 -lcuda -lcudart -lcublas -lcurand`

and run it again?

**Comment by bood** [comment]
Same error.

It was complaining `nvcc` not found, so I installed `apt install
nvidia-cuda-toolkit`, but it's a 8.0 version and my cuda is 9.0, will it be
the problem?
How can I install a 9.0 version if so.

**Comment by NTT123** [comment]
@bood, take a look at this link https://devtalk.nvidia.com/default/topic/1024915/install-cuda-9-on-ubuntu-16-04-with-the-runfile-and-pre-installed-drivers/

**Comment by bood** [comment]
OK, my fault, forgot to set the PATH...

It's working now!
Have you tried on NC6 to see it's performance? How is it with cuda compared
to cudnn?

**Comment by bood** [comment]
My test shows either cuda/cudnn is not super fast.
And CPU load is high, e.g. with -g 4, each process is using 100% of one vCPU

**Comment by NTT123** [comment]
I didn't test on NC6. It should be slower than theano/python version for two reasons: (1) batch-size=1 and (2) cuda kernels possibly does not be as optimized as theano.

**Comment by NTT123** [comment]
Hmm, slower than OpenCL on NC6. Something's wrong here.
