### ISSUE TITLE
Testing next AutoGTP

### ISSUE THREAD

**Issue by Hersmunch** [leela-zero/leela-zero#2156]
Before the next release I think it would be a good idea to test some of the changes to AutoGTP. I've still got one more PR to make for adding full options and starting GTP commands to the sgf files produced but it is probably time to start a conversation on what to do and how to do it. Especially as server side changes are also needed.
I propose that the next branch is temporarily changed to request tasks from a test URL that will provide tasks such as games for:
1. a time limited match
   - I think reproducing a 20 block vs 40 block match for which there is data already available thanks to offline comparisons would be a good idea
2. self-play or a match with handicap
   - perhaps also giving the two sides different visit limits and/or komi (if self-play and excluded from training :)
3. a match using a set of given opening sgfs
   - could either use random existing sgfs with various numbers of moves played or perhaps from "a standard set"

Any thoughts?

**Comment by Friday9i** [comment]
A larger exploration of first moves?
Using a set of openings is a nice option, I vote for it. However, these openings have to be chosen before, which is a bit painful and would need to be automated too.
An alternative would be to change the exploration of LZ in the first few moves, if/when an option is activated in gtp (eg "--exploration").
When "exploration" is activated, for the first 5 moves (or a random number between 2 and 10?), LZ would:
- dedicate 1 playout for each possible moves, to get their winrates
- dedicate 10 playouts to all moves with a winrate within 5% of the winrate of the best move
- dedicate 100 playouts to all moves with a winrate within 3% of the winrate of the best move
- select randomly one move among all the moves with a winrate within 2% of the best move after 100 playouts
- after this exploration for 5 moves, play normaly (ie -v 1600 -m 30).

That would ensure a wide exploration of the first moves, with many 5-4, 5-3 and 3-3 corner moves (almost never played in selfplay currently), while excluding "stupid moves" (such as 1st line moves: their winrates are very low, so by construction they are excluded from the exploration process).
Note: Deepmind developped this kind of approach for AlphaChess, and they used it in the match against Stockfish (chosing moves within 1% winrate from the best move IIRC). Not clear if they also used that for selfplay (I guess they did, but who knows?). 

What do you think of that approach?

**Comment by Hersmunch** [comment]
Just so it is clear, what do you think the data gathered from such a match could be used for? I think it's good to consider various options so we can make best use of the data produced by the tests. However, that is a side-benefit to the main goal of testing AutoGTP. Ideally the test conditions should be kept fairly simple to give us an obvious result. If the functionality you describe is added to next in good time for this testing to occur, then I don't see why it can't be used, with a specific aim in mind. 
Do you know if anyone has reproduced the Deepmind approach in code?

**Comment by alreadydone** [comment]
In self-play they actually initialize value to 'loss', making moves with low policy more unlikely to be played. Dedicating 1 playout for each possible move could be achieved by initializing to 'win', so the exact opposite. However during self-play the policy has Dirichlet noise applied, so whatever move that gets lucky (gets a high policy) will get more visits in AZ than in LZ. AZ is focusing on one move at a time instead of spreading out the search (especially in self-play situation where the visits are limited and precious). It's most economic to devote most of playouts to the move you actually play (or are very likely to play), which also affects the value.

BTW Minigo has adopted init-to-loss and their latest model seems already on par with LZ#201 on time parity. (so these are 20b nets that are likely better than ELF IIUC)
@amj (bearcat on Discord):
> after 50 games each pairing, all of v15 990, 939, and 815 are within the margin of error for 50-50 vs LZ201
LZ 201 vs MG 990, 939, 815, at 2s/move settings

**Comment by alreadydone** [comment]
@Hersmunch  Per discussions following https://github.com/gcp/leela-zero/issues/2143#issuecomment-453237525, what do you think of allowing autogtp to accept more options from the server and pass them to leelaz? Maybe all command line options allowed by leelaz, including those ones enabled by USE_TUNER?

**Comment by Friday9i** [comment]
It's not really an 'initialize to win', it's a way to generate more exploration of interesting  moves (ie more diversity) in the beginning of the game, for a few moves. Basically, it is a kind of increased noise for a few moves.
Hence, this additional noise for a few moves is not really an initialize to loss.
In terms of learning, it would help to learn deeply many interesting openings, not explored today
