### ISSUE TITLE
build encounter cpp syntax error on ubuntu

### ISSUE THREAD

**Issue by nobsessive** [leela-zero/leela-zero#2185]
I have run clone and apt-install commands indicated in "Example of Compiling and Running - Ubuntu & similar" successfully. However when I changed into build directory and entered build directory to run cmake --build . I got following error:

/home/amaa/Documents/leela/leela-zero-master/src/GTP.cpp:442:17: error: ‘cout’ was not declared in this scope
                 cout<<"move "<<move<<endl;
                 ^
/home/amaa/Documents/leela/leela-zero-master/src/GTP.cpp:442:38: error: ‘endl’ was not declared in this scope
                 cout<<"move "<<move<<endl;

Then got Makefile error for all targets.

I don't feel the source code cloned with git have any problem, but I don't know where I got wrong. 
Following are outputs of executing cmake .. : 

-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonInterp: /home/amaa/anaconda3/bin/python (found version "3.7.1") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   program_options
--   filesystem
--   system
-- Found ZLIB: /home/amaa/anaconda3/lib/libz.so (found version "1.2.11") 
-- Looking for CL_VERSION_2_2
-- Looking for CL_VERSION_2_2 - not found
-- Looking for CL_VERSION_2_1
-- Looking for CL_VERSION_2_1 - not found
-- Looking for CL_VERSION_2_0
-- Looking for CL_VERSION_2_0 - found
-- Found OpenCL: /usr/lib/x86_64-linux-gnu/libOpenCL.so (found version "2.0") 
-- Using built-in matrix library.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/amaa/Documents/leela/leela-zero-master/build

**Comment by gcp** [comment]
I can't find those lines in our source code?

**Comment by kennyfs** [comment]
> I messed it up, solved. Thanks for help.  

Can you explain how you solved it?
