### ISSUE TITLE
is it possible that lz weights run faster than converted minigo weight

### ISSUE THREAD

**Issue by l1t1** [leela-zero/leela-zero#2194]
someone said  Using leela engine to run leela weights, the amount of calculation is obviously faster than running minigo. For example, 40B Leela runs 100po per second, 40B minigo may only run 60po.

**Comment by WhiteHalmos** [comment]
Not according to my visit tests: https://github.com/leela-zero/leela-zero/issues/2190

See avg cpu column, they're approximately the same.

**Comment by gcp** [comment]
The "avg cpu" column only tracks CPU usage, not real time, which is an issue if you're running off of the GPU.

**Comment by teraStars** [comment]
Yes, lz weights run faster than converted minigo weight,.
