### ISSUE TITLE
ImportError: cannot import name 'bigtable'

### ISSUE THREAD

**Issue by chunmwan** [leela-zero/leela-zero#2195]
after I git clone mining ,and tried to run self play.py on local tensor flow env of my Mac, 
i got below error:

(tensorflow) bash-3.2$ python3 selfplay.py --verbose=2 --num_readouts=400 --load_file=./models/000798-golden-lion
Traceback (most recent call last):
  File "selfplay.py", line 29, in <module>
    import preprocessing
  File "/Users/chunmwan/Downloads/minigo/preprocessing.py", line 19, in <module>
    import bigtable_input
  File "/Users/chunmwan/Downloads/minigo/bigtable_input.py", line 29, in <module>
    from google.cloud import bigtable
ImportError: cannot import name 'bigtable'
(tensorflow) bash-3.2$ python 
Python 3.6.4 | packaged by conda-forge | (default, Dec 23 2017, 16:54:01) 
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from google.cloud import bigtable
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'bigtable'
>>> 

who knows how to resolve this issue ?

Thanks

**Comment by sethtroisi** [comment]
Can you re-ask on the [minigo](https://github.com/tensorflow/minigo/issues) github. 

It's easy for use to find issues (and less noise for LZ)

I think the issues is not having installed all of the libraries in requirements.txt specifically `google.cloud.bigtable`. More generally, want are you try to do?
