### ISSUE TITLE
Can someone make binary packages for common Linux distros?

### ISSUE THREAD

**Issue by l1t1** [leela-zero/leela-zero#220]
also including dependencies

**Comment by syys96** [comment]
I believe it's not too complicated to compile the project on linux. Indeed with just several commands as gcp writes in the readme:

# Test for OpenCL support & compatibility
sudo apt install clinfo && clinfo
# Clone github repo
git clone https://github.com/gcp/leela-zero
cd leela-zero/src
sudo apt install libboost-all-dev libopenblas-dev opencl-headers ocl-icd-libopencl1 ocl-icd-opencl-dev zlib1g-dev
make
cd ..
wget https://sjeng.org/zero/best_v1.txt.zip
unzip best_v1.txt.zip
src/leelaz --weights weights.txt

Besides, it's not easy to supply all the dependent packages and tools in one project. Why not just type "sudo apt-get ..."?

**Comment by gcp** [comment]
Distributing binaries on Linux is very difficult because every distribution has their own versions of everything. It's much better to let someone make packages for the specific distro, built from the source.
