### ISSUE TITLE
it seems new weights is puased

### ISSUE THREAD

**Issue by l1t1** [leela-zero/leela-zero#2204]
more than 16 hours

**Comment by l1t1** [comment]
288 in past 24 hours, 1 in past hour
View most recent match win by best network fe695742 vs 4f2b779b: [EidoGo / WGo]

**Comment by l1t1** [comment]
it skiped 256k, resumed at 32k now

**Comment by l1t1** [comment]
it paused again

**Comment by l1t1** [comment]
it skiped 192k 256k, resumed at 32k now

**Comment by l1t1** [comment]
why does this happen

**Comment by roy7** [comment]
Generally it is if gcp's internet connection goes down when it is trying to upload a network.

@gcp I don't suppose catching that error for automatic retry later would be doable? (Does curl, if you are using that, have an auto retry option?)

**Comment by gcp** [comment]
If I let curl auto-retry then continuing the training also stops. No good solution that doesn't make the whole training running script quite a bit more complicated.

**Comment by roy7** [comment]
Can the script that calls curl just append a & to launch curl in the background and forget about it? ;)

**Comment by l1t1** [comment]
it paused again
12 hours since last 96k step weight

**Comment by gcp** [comment]
The training server was working correctly, but the webserver was down and refused the uploads.

**Comment by l1t1** [comment]
13.2 housrs passed since last weight
