### ISSUE TITLE
leelaz stops with gpu on linux

### ISSUE THREAD

**Issue by TamasSzerb** [leela-zero/leela-zero#2207]
Hello,

do you have any idea why 

commit d8ea34d06048e4d4e5da33b2d571ba75e0e65cd3 (HEAD -> next, origin/next)

version of leelaz stops with:

./leelaz --gtp --gpu 1 -l ez

(see the attachment for log)?

while 

./leelaz --gtp --cpu        
Using 4 thread(s).
RNG seed: 10756213592634142764
BLAS Core: built-in Eigen 3.3.7 library.
Detecting residual layers...v1...256 channels...40 blocks.
Initializing CPU-only evaluation.
Setting max tree size to 3736 MiB and cache size to 415 MiB.
version
= 0.16

works well.

Thanks!

**Comment by marcocalignano** [comment]
I do not see any attachment. 
How many GPU have you got? `--gpu 1` means the second GPU. 
If you have only one GPU just leave that option out it will automatically take the first GPU available.

**Comment by TamasSzerb** [comment]
I know.

clinfo -l                                                                                                                                          ✔  1735  07:30:15
Platform #0: Intel(R) OpenCL
 `-- Device #0: Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz
Platform #1: NVIDIA CUDA
 `-- Device #0: GeForce GTX 1060 6GB

leelaz --gtp --gpu 0

rror in OpenCL calculation: Update your GPU drivers or reduce the amount of games played simultaneously.
Loaded existing SGEMM tuning.
Wavefront/Warp size: 128
Max workgroup size: 8192
Max workgroup dimensions: 8192 8192 8192 
Error in OpenCL calculation: Update your GPU drivers or reduce the amount of games played simultaneously.
Both single precision and half precision failed to run.
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to initialize net.
zsh: abort      leelaz --gtp --gpu 0

leelaz --gtp --gpu 1

Max workgroup size: 1024
Max workgroup dimensions: 1024 1024 64 
Using OpenCL half precision (at least 5% faster than single).
Setting max tree size to 3736 MiB and cache size to 415 MiB.
$

only. any idea?

**Comment by gcp** [comment]
Note the error:

>Error in OpenCL calculation: Update your GPU drivers or reduce the amount of games played simultaneously.

What drivers are you using?

**Comment by TamasSzerb** [comment]
removed intel driver for opencl, upgraded nvidia kernel driver, and now w/o --gpu it works perfectly. thanks!

**Comment by sethtroisi** [comment]
closing resolved issue
