### ISSUE TITLE
What is hardware configuration currently used by leela for training and evaluation?

### ISSUE THREAD

**Issue by lcwd2** [leela-zero/leela-zero#2209]
According to the statistics, it takes around 37 minutes for 1 game. A round of evaluation has 400 games which will take about 10 machine days. I wonder what kind of hardware is currently used by Leela for training and evaluation.

**Comment by alreadydone** [comment]
A large portion of self-play games is generated by K20/K20X on a supercomputer which is rather slow. Match/evaluation games are only distributed to fast clients, which probably means 1080Ti/2080Ti (might be some V100 as well).

**Comment by lcwd2** [comment]
how about the hardware for the network training portion?

**Comment by alreadydone** [comment]
@gcp uses a 2080 now. @bjiyxo and @bubblesld use several 1080Ti I think.
All of them have produced official networks (listed under Best Network Hash in zero.sjeng.org).

**Comment by gcp** [comment]
I still use the GTX 1080 Ti, the machine has been untouched for a long time.

I'm using the RTX for experiments.

**Comment by bjiyxo** [comment]
I use 4*1080Ti.

**Comment by lcwd2** [comment]
Hi bjiyxo, you have a version of the network training program that can run on multiple GPU on the same machine?

**Comment by alreadydone** [comment]
multi-gpu training support was added to the official training script(s) in this commit: https://github.com/leela-zero/leela-zero/commit/648b230494c72a6ab39f85c9ddb73a703b184f43

**Comment by lcwd2** [comment]
Hi Bjiyxo,

 

Which motherboard do you use for the 4 GPU?

 

Regards,

Lcwd

**Comment by bjiyxo** [comment]
@lcwd2 
We use ESC8000 G3
https://www.asus.com/tw/Commercial-Servers-Workstations/ESC8000_G3/specifications/
I'm not sure which motherboard they used.
