### ISSUE TITLE
Don't manage to compile autogtp on Linux

### ISSUE THREAD

**Issue by kennychenfs** [leela-zero/leela-zero#2219]
I compile autogtp, it says<br> `/usr/bin/ld: cannot find -lGL
collect2: error: ld returned 1 exit status
Makefile:165: recipe for target 'autogtp' failed
make: *** [autogtp] Error 1`

**Comment by genleung** [comment]
It's not a CRASH, but a compiling error. You need  a OpenGL library which provides by your graphics card driver.

**Comment by kennychenfs** [comment]
http://www.codebind.com/linux-tutorials/install-opengl-ubuntu-linux/
this?
I tried it, but it still can't compile.

Genleung <notifications@github.com> 於 2019年2月15日 週五 上午11:17寫道：

**Comment by kennychenfs** [comment]
I found the problem, I installed the nvidia driver incorrectly before.
So, I remove the link and relink the correct /usr/lib/x86_64-linux-gnu/libGL.so to /usr/lib/x86_64-linux-gnu/libGL.so.1.7.0.
