### ISSUE TITLE
all.sgf is broken

### ISSUE THREAD

**Issue by sethtroisi** [leela-zero/leela-zero#2234]
I tried to run sgfsplit on all.sgf (2019-Jan-28 14:06 from https://leela.online-go.com/zero/)

```
Splitting "/media/big-ssd/rsync/all.sgf" (22G)
sgfsplit: trailing junk discarded
Splitting took 476.89 seconds
Found 6753278 files
```

Looking at offset ~13G one of the games doesn't have a closing `)`
```
(;GM[1]FF[4]RU[Chinese]DT[2018-04-14]SZ[19]KM[7.5]PB[Leela Zero 0.13 c0cb605b]PW[Leela Zero 0.13 c0cb605b]RE[W+2.5]
C[Leela Zero options: -p 0 -v 3201 -r 0 -m 30 -t 1 -d -n --noponder -s 8344334272416944285 -g -q
-w networks/c0cb605b3dfb366eeec805841495379efc7d206bcd04e95ef4566614100074c5]
...
;B[os];W[sr];B[ss];W[hf];B[ph];W[hl];B[re];W(;GM[1]FF[4]
```

I find this helpful to inspect
```
tail -c +13655868K ../../rsync/all.sgf | head -n 200 | grep '391374742733758337\|$'
```

**Comment by l1t1** [comment]
suggest to publish the sgf by peroids, such as 2018-12 and 2019-1 to avoid repeatly download same older content.

**Comment by sethtroisi** [comment]
I split the file with

```
split --verbose -l 1000000 -u -d -a3 all.sgf all_split
```

The search for broken file and fix it manually :/
Now it's broken after
```
Found 6813209 files
```

**Comment by gcp** [comment]
I'll see if I can split it per network.

**Comment by gcp** [comment]
I split all.sgf into files with 1M games each. The error will still be there, as it's in the database.

**Comment by l1t1** [comment]
i see, but huge xz file is hard to use and download, may also hard to make and upload, i wonder the benifit of does so
