### ISSUE TITLE
appvoyer link points at gcp/leela-zero and is out of date

### ISSUE THREAD

**Issue by sethtroisi** [leela-zero/leela-zero#2247]
https://ci.appveyor.com/project/gcp/leela-zero/branch/next

Last update is from 21 days ago

@gcp I tried changing gcp to leela-zero but get "project not found", I think this is because there's some config on the appveyor side we (READ: you) might need to update

**Comment by sethtroisi** [comment]
The travis link is also out-of-date but was easy to fix (https://github.com/leela-zero/leela-zero/pull/2246)

**Comment by roy7** [comment]
Correct new one is https://ci.appveyor.com/project/gcp/leela-zero-8arv1 I believe.

I'd put in some changes for these but maybe did it wrong, so gcp force pushed some changes, but I guess it's still not in there properly?

**Comment by sethtroisi** [comment]
This is fixed in https://github.com/leela-zero/leela-zero/pull/2229
