### ISSUE TITLE
leela zero crashes at Initializing OpenCL

### ISSUE THREAD

**Issue by huanyge** [leela-zero/leela-zero#2252]
OS:win10   cpu:intel g4560    gpu:gtx 1050
leela zero 0.16
run  >leelaz -w ..\weight\15B-192F
      ... 
      ...
      BLAS Core: atom  <---- error
      Detecting residual layers... ...
      Initializing OpenCL (autodetecting precision).
     >     <--- crashes to the prompt
reinstall vc++2015 and update 1050 driver，The problem remains.

**Comment by l1t1** [comment]
replace 15B-192F with an offical weight, such as lz 157 http://zero.sjeng.org/networks/d351f06e446ba10697bfd2977b4be52c3de148032865eaaf9efc9796aea95a0c.gz

**Comment by Wizr** [comment]
@huanyge after trying various methods, reinstall/reset Windows 10 fixed the issue.
