### ISSUE TITLE
prior in lz-analyze

### ISSUE THREAD

**Issue by bvandenbon** [leela-zero/leela-zero#2262]
What is the "prior" value in the `lz-analyze` output ?
_(And in what unit-of-measure / scale is it measured ?)_

Thank you in advance,
Bram Vdb.

**Comment by alreadydone** [comment]
It's the output of the policy head, a probability for each move. The unit is 10^-4. https://github.com/leela-zero/leela-zero/commit/c64dd2ad415659e38c01cace3a52ee40fed14832#diff-70aab7683fe64f9428b8bc47d1d183c0R56

**Comment by bvandenbon** [comment]
Thank you for clarifying.
