### ISSUE TITLE
an idea of speed up play

### ISSUE THREAD

**Issue by l1t1** [leela-zero/leela-zero#2263]
after one player thought many paths and chose a move from the best path,
- if the opponent 's move is match one path, it dierct chose the next move from the existing best path  without thinking again.
- if not the case, then it think again.

**Comment by WhiteHalmos** [comment]
I believe this is what pondering and tree reuse already does, just in a more general way that respects playouts/visits counts.

**Comment by l1t1** [comment]
thanks
