### ISSUE TITLE
what is the meaning of XXM in filenames of new format allsgf.xz

### ISSUE THREAD

**Issue by l1t1** [leela-zero/leela-zero#2265]
https://leela.online-go.com/zero/
all_12M.sgf.xz	245278296	2019-Feb-25 15:05
all_13M.sgf.xz	161252704	2019-Feb-25 15:20

**Comment by l1t1** [comment]
https://github.com/leela-zero/leela-zero/issues/2234#issuecomment-467466019
1M= 1 month or 1 million games

**Comment by gcp** [comment]
Million games.

I split up the file to make it easier to upload/download/process.

**Comment by l1t1** [comment]
i thought i contributed 3 things to the project.
1. advice to use 7zips gz format
2. advice to split allselfgames xz 
3. made a pr and be accepted, though it be rollback due to larger error that reduced the weight strength

**Comment by l1t1** [comment]
could you upload the full 13M sgf at https://leela.online-go.com/zero/all_13M.sgf.xz
