### ISSUE TITLE
https://zero.sjeng.org/ server down?

### ISSUE THREAD

**Issue by l1t1** [leela-zero/leela-zero#2266]
Error 502 Ray ID: 4b28cbbeffd22276 • 2019-03-05 02:52:48 UTC
Bad gateway

**Comment by roy7** [comment]
Yes, server ran out of space. Mongod and whatever else needs restarted by @gcp when he's available. autogtp should collect games in the mean time to upload them all once the server is back.

**Comment by l1t1** [comment]
3 game(s) (3 self played and 0 matches) played in 206 minutes = 4138 seconds/game, 24681 ms/move, last game took 6425 seconds.
Network connection to server failed.
NetworkException: JSON parse error: illegal value
Retrying in 30 s.
Network connection to server failed.
NetworkException: JSON parse error: illegal value
Retrying in 45 s.
Network connection to server failed.
NetworkException: JSON parse error: illegal value
Retrying in 67 s.
Maximum number of retries exceeded. Falling back to previous network.
Engine has started.
time_settings 0 1 0
Thinking time set.
1 (B D3) 2 (W Q4) 3 (B D17)

**Comment by roy7** [comment]
Yes the server is offline.

**Comment by gcp** [comment]
Server is back up. I will have to move the old networks off of it, it's starting to show it wasn't originally set up to handle 256x40 etc.
