### ISSUE TITLE
Visualization of search progress

### ISSUE THREAD

**Issue by kaorahi** [leela-zero/leela-zero#2268]
I wrote a [tool](https://github.com/kaorahi/lizgoban) that can visualize the progress of the search process.

![screen](https://user-images.githubusercontent.com/38910552/53954769-7df9f880-411a-11e9-9553-4d9472f592eb.gif)

(winrate bar below the main board) x-axis = winrate, y-axis = visits, size = prior

The options "Winrate trail" and "Expand winrate bar" are selected in "View" menu for the above screenshot.

**Comment by PublicStarMoon** [comment]
Awesome ! 

I was looking forward to this kind of tool for a very long time.

**Comment by ThorAvaTahr** [comment]
cool!
