### ISSUE TITLE
The best Windows GUI for Leela?

### ISSUE THREAD

**Issue by Marcin1960** [leela-zero/leela-zero#2269]
I have problems with Sabaki, what else would you recommend?

**Comment by criptopark** [comment]
There are still gogui, lizzie, drago, smartgo. what problems? maybe they can be solved ...

**Comment by Marcin1960** [comment]
drago inserts "--gtp-mode" argument, gogui sends "name" command etc Perhaps I will try lizzie?

**Comment by Marcin1960** [comment]
criptopark: "what [sabaki] problems? maybe they can be solved"

I tried everything. Their some bug with newer version of Sabaki on 32 bit Windows. They are not interested in fixing it. I try Drago,  Leelaz chokes on "--gtp-mode" option forced by Drago. Maybe I can hack the binary?

**Comment by Marcin1960** [comment]
The newest version of Sabaki works. :)

**Comment by criptopark** [comment]
I connected leelaz to drago, if it's still interesting, I can write how.

**Comment by l1t1** [comment]
it is a pity that gcp wouldnt continue to dev the leela gui

**Comment by TFiFiE** [comment]
From https://github.com/leela-zero/leela-zero/issues/2157#issuecomment-456516287:
> [...]I'm for example more concerned about the UI and GTP protocol situation. There's a fairly constant stream of people asking whether the "old" Leela will ever get updates[...]
