### ISSUE TITLE
the relation of visits and winrate

### ISSUE THREAD

**Issue by l1t1** [leela-zero/leela-zero#2271]
3200 vs 1600 2;1
1600 vs 800 3;1
800 vs 400 4;1
https://lifein19x19.com/viewtopic.php?p=242184#p242184

**Comment by petgo3** [comment]
Nice to know, but can't it be also the -m influence?

**Comment by featurecat** [comment]
They used -m 40 but this probably affects the results a little too much. I think in general you want the lowest -m value possible for your sample size. For example I think -m 20 would also be more than enough.

But the data makes sense :) I'd love to also know how this pattern continues at high visit counts eg 100,000 vs 50,000, or if it stacks on itself eg 6400 vs 1600.

**Comment by nerai** [comment]
I just tested -m20, 800v400 = 84:16 (84%) compared to their 16:4 (80%).

**Comment by gcp** [comment]
I did a larger test a while back (somewhere in an issue here) and the relation was much more linear with increasing visits. The test done there is not very reliable due to the incredibly tiny amount of games used.
