### ISSUE TITLE
winrate of lz against elfv2 cut down

### ISSUE THREAD

**Issue by l1t1** [leela-zero/leela-zero#2274]
http://www.yss-aya.com/cgos/19x19/cross/LZ_208_d016_p400.html
http://www.yss-aya.com/cgos/19x19/cross/LZ_209_0da8_p400.html

**Comment by l1t1** [comment]
```
    elfv2  elfv1
205 28.26  46.43
206 40.00  55.88
207 36.00  48.72
208 52.94  40.00
209 12.50 100.00
```

**Comment by l1t1** [comment]
from view of elf
http://www.yss-aya.com/cgos/19x19/cross/LZ_05db_ELFv2_p800.html
http://www.yss-aya.com/cgos/19x19/cross/LZ_d13c_ELFv1_p800.html

**Comment by l1t1** [comment]
LZ_05db_ELFv2_p800	3256	1 / 10	10.00

**Comment by l1t1** [comment]
LZ_05db_ELFv2_p800	3256	1 / 12	8.33
and lz209 will soon be replaced by lz210

**Comment by gjm11** [comment]
These results seem to be based on something on the order of 10 games. Practically anything can happen in 10 games, and often it does. There's a reason why LZ's test matches use hundreds of games.

**Comment by l1t1** [comment]
LZ_05db_ELFv2_p800	3260	1 / 16	6.25
can someone investgate the games

**Comment by l1t1** [comment]
my test
``` D:\tool\go_gui\gogui-twogtp -white "D:\leela-zero-0.16-win64\leelaz.exe --gtp -w d:\209.gz --noponder -v 801" -black "D:\leela-zero-0.16-win64\leelaz.exe --gtp -w D:\elfv2.gz --noponder -v 1601"  -games 10 -sgffile lz209_lzelfv2 -auto -komi 7.5```
result elfv2 v1601 vs 209 v801 10:0
```
# Black: Leela Zero
# BlackCommand: D:\leela-zero-0.16-win64\leelaz.exe --gtp -w D:\elfv2.gz --noponder -v 1601
# BlackLabel: Leela Zero:0.16
# BlackVersion: 0.16
# Date: March 12, 2019 4:42:08 PM CST
# Host: PC
# Komi: 7.5
# Referee: -
# Size: 19
# White: Leela Zero
# WhiteCommand: D:\leela-zero-0.16-win64\leelaz.exe --gtp -w d:\209.gz --noponder -v 801
# WhiteLabel: Leela Zero:0.16
# WhiteVersion: 0.16
# Xml: 0
#
#GAME	RES_B	RES_W	RES_R	ALT	DUP	LEN	TIME_B	TIME_W	CPU_B	CPU_W	ERR	ERR_MSG
0	B+R	B+R	B+R	0	-	217	1818	2121.8	0	0	0	
1	B+R	B+R	B+R	0	0	217	20.9	33.9	0	0	0	
2	B+R	B+R	B+R	0	-	155	1323.6	1512.2	0	0	0	
3	B+R	B+R	B+R	0	-	251	989.4	1069.5	0	0	0	
4	B+R	B+R	B+R	0	-	167	1689.1	1669.2	0	0	0	
5	B+R	B+R	B+R	0	4	167	16.4	16.1	0	0	0	
6	B+R	B+R	B+R	0	1?	223	157.7	235.5	0	0	0	
7	B+R	B+R	B+R	0	5?	167	12.1	15	0	0	0	
8	B+R	B+R	B+R	0	-	249	473.3	600.2	0	0	0	
9	B+R	B+R	B+R	0	-	171	1188.7	1357.8	0	0	0
```

**Comment by l1t1** [comment]
https://www.lifein19x19.com/viewtopic.php?p=242225#p242225
shows 208 is also weak at sometime
