### ISSUE TITLE
gomill-explain_last_move misreports visits

### ISSUE THREAD

**Issue by roy7** [leela-zero/leela-zero#2280]
> >>genmove w
> Thinking at most 36.5 seconds...
> NN eval=0.550535
> 
>   S6 ->    1190 (V: 56.47%) (N: 13.26%) (LCB-Bi: 51.96%) (UCB-Bi: 60.91%) PV: S6 S8 Q8 S9 Q9 R10 Q10 S11 Q11 Q12 O9 P13 N7 O6 N6 O5 R3 M4 L6 K3
>   Q8 ->    1780 (V: 54.94%) (N: 72.65%) (LCB-Bi: 51.26%) (UCB-Bi: 58.59%) PV: Q8 P8 S8 Q5 P9 P13 P4 R4 R3 O5 S4 R5 P5 P6 O4 N4 Q3 N6 N9 S5 N3 M4
>   S8 ->     253 (V: 54.78%) (N:  8.75%) (LCB-Bi: 44.88%) (UCB-Bi: 64.41%) PV: S8 Q5 R4 P4 S6 P13 C14 D14 D13 E14 C15 C16 J17 D11 E13 E17 F16 D15 F13
> 14.2 average depth, 29 max depth
> 2617 non leaf nodes, 1.23 average children
> 3224 visits, 1013181 nodes, 11 playouts, 220 n/s
> 
> = S6
> 
> >>gomill-explain_last_move
> = move 35, W => S6
> Playouts: 11, Win: 55.49%, PV: S6 S8 Q8 S9 Q9 R10 Q10 S11 Q11 Q12 O9 P13 N7 O6 N6 O5 R3 M4 L6 K3

So the output is telling us how many new playouts went to this move before we moved. I wonder if that's intended. Would it be better to report the # of visits for this move (1190) instead of new playouts? Or add a bit more info to this, maybe like a "Visits: 1190" in addition to the above?

I wonder if this output was set up way back before tree re-use and visit support were even added. :)

**Comment by sethtroisi** [comment]
this was just an oversight. I added the code recently in https://github.com/leela-zero/leela-zero/pull/2174

See https://github.com/leela-zero/leela-zero/pull/2174/files#diff-70aab7683fe64f9428b8bc47d1d183c0R588

**Comment by roy7** [comment]
We could use `m_root->get_visits()` instead, but that'd be total visits for the whole tree not just the visits under the move chosen. (Maybe size of whole tree is worth reporting, I don't know.)

When we print normal dump_stats we use get_visits() of the specific child node in question.

Perhaps walk the `for (const auto& node : parent.get_children()) {` loop dump_stats does to find the child we're going to report and pull get_visits() from it?

**Comment by gcp** [comment]
I think it's OK to report the root visits, we report the entire PV so it makes sense that the stated playout count refers to the complete search.

**Comment by Dorus** [comment]
If we want to use this for PV, it would make most sense to report both root visits and root playouts, currently most bots i've seen reporting pv, report either both of those or just visits. Only bots that do not support visits report playouts, and half the time those do not support tree reuse, so playouts and visits are equal anyway.
