### ISSUE TITLE
suggest add elfv2 weight to selfplay

### ISSUE THREAD

**Issue by l1t1** [leela-zero/leela-zero#2288]
lz 213 is trained by using part of those games

**Comment by l1t1** [comment]
suggest to use v 3200 parameter

**Comment by l1t1** [comment]
https://www.lifein19x19.com/viewtopic.php?p=242318#p242318

http://www.yss-aya.com/cgos/19x19/cross/LZ_213_e5dd_p400.html

**Comment by l1t1** [comment]
no 40b weight can win elfv2 when visits is half of elf

**Comment by gcp** [comment]
https://github.com/leela-zero/leela-zero/issues/2157#issuecomment-456516287
