### ISSUE TITLE
too many duplicate in first 40-50 moves in self play?

### ISSUE THREAD

**Issue by hskim70** [leela-zero/leela-zero#2292]
I have watched recent self play sgf files
and found too many same moves at the first 40-50 moves.
for example, check https://zero.sjeng.org/match-games/5c9135e96789b028e03277ef
https://zero.sjeng.org/viewmatch/21325a39c95eb4e8652d9227608f3b5ffa6ef7c549cd37f396e892a89f5eac62?viewer=wgo
https://zero.sjeng.org/viewmatch/db067a76887d3ce5f5eb45b7b63e47d2c5b994e9fc431804352e02c3de93bc16?viewer=wgo
https://zero.sjeng.org/viewmatch/e4ec02a37df70fccec073d70408fbef6d996d2044db5ff8d100f38d912d67881?viewer=wgo
https://zero.sjeng.org/viewmatch/65e1d17597b573ae74559c777765c833c542058e85badae5f8537ee2c5482b22?viewer=wgo

Can anyone check other sgf files?
and is it good for training?

**Comment by alreadydone** [comment]
URL says these are match games between two networks (to test strength), not self-play games. They're not used for training. Self-play games have randomized selection for the first 30 moves, as well as Dirichlet noise. Some people do worry about lack of diversity in match games.
