### ISSUE TITLE
Deepmind's new PUCT for wider search as visits rise

### ISSUE THREAD

**Issue by roy7** [leela-zero/leela-zero#2298]
They added a new scaling term in the final paper I believe, to expand search out more as the visits rise. Should we adopt something similar?

Here's a great example how LZ doesn't go wide enough. 1.2M in top move, no other move with over 200 visits. Check # 16 on https://explorebaduk.com/2019/03/20/2690/.

**Comment by Hersmunch** [comment]
Are you referring to what #2072 addresses?

**Comment by roy7** [comment]
Ah ha! I thought someone had made the change but I looked and couldn't find it. The author of the article must have been using master instead of next, which makes sense as I think next is only used by fans that hang out here. :)
