### ISSUE TITLE
Compiling 0.17 on Ubuntu on Google Cloud

### ISSUE THREAD

**Issue by MarcelGruenauer** [leela-zero/leela-zero#2303]
I'm not able to compile 0.17 with Ubuntu on Google Cloud (P100).

"cmake .." says, among other things:

-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0

Then "cmake --build ." fails at the "Linking CXX executable tests" step with:

Scanning dependencies of target tests
[ 58%] Building CXX object CMakeFiles/tests.dir/src/tests/gtests.cpp.o
[ 60%] Building CXX object CMakeFiles/tests.dir/src/tests/utils_unittest.cpp.o
[ 62%] Linking CXX executable tests
gtest/googlemock/gtest/libgtest.a(gtest-all.cc.o): In function testing::TestCase::TestCase(char const*, char const*, void (*)(), void (*)())': gtest-all.cc:(.text+0x8d7d): undefined reference to std::vector<int, std::allocator >::~vector()'
gtest/googlemock/gtest/libgtest.a(gtest-all.cc.o): In function testing::TestCase::~TestCase()': gtest-all.cc:(.text+0x8e30): undefined reference to std::vector<int, std::allocator >::~vector()'
gtest-all.cc:(.text+0x8ea3): undefined reference to std::vector<int, std::allocator<int> >::~vector()' gtest/googlemock/gtest/libgtest.a(gtest-all.cc.o): In function testing::internal::UnitTestImpl::UnitTestImpl(testing::UnitTest*)':
gtest-all.cc:(.text+0x12827): undefined reference to std::vector<int, std::allocator<int> >::~vector()' gtest/googlemock/gtest/libgtest.a(gtest-all.cc.o): In function testing::internal::UnitTestImpl::~UnitTestImpl()':
gtest-all.cc:(.text+0x129d6): undefined reference to std::vector<int, std::allocator<int> >::~vector()' gtest/googlemock/gtest/libgtest.a(gtest-all.cc.o):gtest-all.cc:(.text+0x12b09): more undefined references to std::vector<int, std::allocator >::~vector()' follow
collect2: error: ld returned 1 exit status
CMakeFiles/tests.dir/build.make:177: recipe for target 'tests' failed
make[2]: *** [tests] Error 1
CMakeFiles/Makefile2:69: recipe for target 'CMakeFiles/tests.dir/all' failed
make[1]: *** [CMakeFiles/tests.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

0.16 compiled fine a few months ago. Any ideas?

**Comment by l1t1** [comment]
maybe 0.17 use some new feature of new compiler, try upgrade to gcc 8

**Comment by MarcelGruenauer** [comment]
That was it; thank you! I have Ubuntu 16.04 - newer versions don't work with the CUDA version I have; but I don't know too much about that.

So these steps worked:

sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt-get update
sudo apt-get install gcc-8 g++-8

mkdir build && cd build
cmake -DCMAKE_C_COMPILER=/usr/bin/gcc-8 -DCMAKE_CXX_COMPILER=/usr/bin/g++-8 ..
cmake --build .

A benchmark with the latest 15 block network that was trained on 40 block games shows that v0.16 gets 598 n/s, while v0.17 gets 1938 n/s; very impressive!
