### ISSUE TITLE
Got "null white_hash_gzip_hash" when getting match task

### ISSUE THREAD

**Issue by ciberponk** [leela-zero/leela-zero#2304]
getWorkInternal(): curl -s -J https://zero.sjeng.org/get-task/17
curl.exitCode(): 0
{
    "black_hash": "edb61bc2c2beec680ffe004aa330d878d5cc7813f4dba1aff9377ec7a49eb1c1",
    "black_hash_gzip_hash": "93a5281becf90932e40929ba169b04971dd3c7576f7fb68ee9bd012c154d8619",
    "cmd": "match",
    "minimum_autogtp_version": "16",
    "minimum_leelaz_version": "0.15",
    "options": {
        "noise": "false",
        "playouts": "0",
        "randomcnt": "0",
        "resignation_percent": "5",
        "visits": "1600"
    },
    "options_hash": "0ef1f9ef8208ca0b973e20e52fad9acc80d0c504dd9428a94cd8b38b6f4e86f3b23a32",
    "random_seed": "3848215601266554944",
    "required_client_version": "16",
    "white_hash": "f438268ef88e083aaf7a08fba885552818abc08cd0aefce9671954a8df3cf707",
    **"white_hash_gzip_hash": null**
}

**Comment by roy7** [comment]
I'm guessing because that net is so old it isn't on server any more, it's on the archival system instead. I guess it isn't stopping things from working though since we have results flowing in on those two text matches?

**Comment by ciberponk** [comment]
the net file exists, and can be downloaded from server
https://zero.sjeng.org/networks/f438268ef88e083aaf7a08fba885552818abc08cd0aefce9671954a8df3cf707.gz
but got {"white_hash_gzip_hash": null} in response from https://zero.sjeng.org/get-task/17

**Comment by l1t1** [comment]
f438 is a 40b trained 15b weight, not an offical

**Comment by roy7** [comment]
This one was never promoted. :) it's part of the series of 15b nets people have worked on over time. I can copy it back to server next time we do tests but I was worried that might break the archive system if it moves over a file that is already there.

**Comment by Friday9i** [comment]
I also had a problem, but a different one it seems: 
My autogtp crashed repeatedly too when the 15b were tested yesterday evening (european time): I was running next at that time, and I went back to test the official v16 as I thought it could be the problem: it didn't work either ; -(. I had a message about a difference of hash, around "the server says the hash should be 'xyz' and when I compute it, it is 'abc', so it doesn't match" and then, autogtp was crashing very fast (probably less than 1 second after). I haven't had time to make a screen copy of the exact error message.
So after several tries, I gave up and launch a test of LCB-Normal vs Next at 5000 visits (and first early results seem to confirm LCB works well too at 5k visits ; -)

**Comment by roy7** [comment]
Since it seems this is causing some people problems, but not all, I'll go ahead and copy the network back to server then delete it when enough matches are done.

Maybe we need client to cleanly fall back to old gunzip/hash compare if the gzip hash is null? (ie: old network no longer on server so server doesn't know the gzip hash.)

**Comment by roy7** [comment]
Even with the gzip hash correct and not null people are reporting autogtp crashing sometimes. I have no idea why.

**Comment by bjiyxo** [comment]
1. Download the 15b f438... on the website(http://zero.sjeng.org/networks/f438268ef88e083aaf7a08fba885552818abc08cd0aefce9671954a8df3cf707.gz) in your network folder.
2. Make f438 as read-only.
3. Open your autogtp, and it should work.
