### ISSUE TITLE
a 60b weight is testing at cgos

### ISSUE THREAD

**Issue by l1t1** [leela-zero/leela-zero#2309]
http://www.yss-aya.com/cgos/19x19/cross/lz_60b_test.html

**Comment by Splee99** [comment]
It has ladder problem, still.

**Comment by l1t1** [comment]
yes, the two lost games, both
http://www.yss-aya.com/cgos/19x19/SGF/2019/03/30/540243.sgf
and
http://www.yss-aya.com/cgos/19x19/SGF/2019/03/30/540261.sgf

**Comment by l1t1** [comment]
again ladder
http://www.yss-aya.com/cgos/19x19/SGF/2019/03/31/540362.sgf

**Comment by l1t1** [comment]
http://www.yss-aya.com/cgos/19x19/cross/binary_star.html

**Comment by l1t1** [comment]
a 80b is testing
http://www.yss-aya.com/cgos/19x19/cross/lz_80b_p400.html
is a bit stronger than lz 222
http://www.yss-aya.com/cgos/19x19/cross/LZ_222_0407_p400.html
