### ISSUE TITLE
Should old clients be allowed to contribute?

### ISSUE THREAD

**Issue by pliuphys** [leela-zero/leela-zero#2318]
I see we are still getting games from 0.16. If lcb chooses best move differently, is results from old clients inferior?

**Comment by Ttl** [comment]
Shouldn't be a problem. LCB only affects the played move but the policy training data is still visit distribution and the policy training data should be of the same quality. Played moves might be little weaker affecting the value training data, but I don't think it's very significant. Training worked fine with proportional move selection after all and it has much weaker value data.

**Comment by pliuphys** [comment]
@Ttl Now I realize there's a more basic question I don't understand. When training the network, for policy do we use MCTS search fractions? Even for moves with zero temperature?

**Comment by Ishinoshita** [comment]
@pliuphys Policy training targets have always been normalized visits distributions. I don't see why there should be a change here (I believe we just switched back to -m30 as used before May 2018). Even with  - m30, there still some form of exploration in the policy training, thanks to dirichlet noise (-m30 stop randomness in move picking, but does not remove dirichlet noise in self-play games, IIRC).

**Comment by pliuphys** [comment]
@Ishinoshita Thanks for the clarification.
