### ISSUE TITLE
Default cfg_puct in LZ 0.17

### ISSUE THREAD

**Issue by Splee99** [leela-zero/leela-zero#2320]
I don't know why it's changed to 0.5. In LZ 0.16 it is 0.8. I believe 0.8 is much better at least in handicap games, which means that LZ often takes more daring missions as compared to the current version which is often over conservative.

**Comment by Hersmunch** [comment]
See #2072

**Comment by Splee99** [comment]
I see much work has been done to validate the change, but was based on the old network. I think now it is a good time to do a match with an anchor point, such as elfv2 running on 0.16.

**Comment by iopq** [comment]
I think with max lcb all of these parameters might be out of date

**Comment by Splee99** [comment]
With the current LCB setup, change cfg_puct to 0.8 seems to make LZ stronger.

**Comment by Splee99** [comment]
The new weight (#220) adjusted to this new puct setting very well. Case closed.
