### ISSUE TITLE
Leela 0.16&17 AMD Radeon VII - *ERROR* could not talk to engine

### ISSUE THREAD

**Issue by bearyangry** [leela-zero/leela-zero#2321]
Hi,

After swapping to new AMD Radeon VII GPU, I cannot launch Leela. It worked perfectly on my previous AMD RX580 card. I wiped and did a clean install of Win10 system and drivers. I receive a *ERROR" could not talk to engine after launching.

Leelaz.exe returns a "OpenCL: clGetPlatformIDs" as last output.

Attached output
[leela_error.txt](https://github.com/leela-zero/leela-zero/files/3050932/leela_error.txt)

Any ideas on how to test further or what might be the issue?

**Comment by iopq** [comment]
Does OpenCL work in other applications with the card?

**Comment by l1t1** [comment]
try use gpu-z to detect

**Comment by bearyangry** [comment]
I used GPU Caps Viewer and was able to run OpenCL demos with no issues. I've attached screenshots of the GPU info:

![GPU_Info](https://user-images.githubusercontent.com/49130388/55677240-3db4a400-5899-11e9-9b44-8551864802bf.JPG)
![GPU_OpenCL_Info](https://user-images.githubusercontent.com/49130388/55677241-3ee5d100-5899-11e9-85d0-fc065f9805b2.JPG)

**Comment by bearyangry** [comment]
Here is the GPU-Z info:

![GPUz](https://user-images.githubusercontent.com/49130388/55677644-5ffdf000-58a0-11e9-9f88-7e5f9be03724.JPG)
![GPUz_OpenCL_1](https://user-images.githubusercontent.com/49130388/55677645-61c7b380-58a0-11e9-97e9-ec9302286c1d.JPG)
![GPUz_OpenCL_2](https://user-images.githubusercontent.com/49130388/55677646-64c2a400-58a0-11e9-9bbf-246ece9c1444.JPG)

**Comment by l1t1** [comment]
maybe the opengl.dll version is too old to recognize your card
could you compile it from source code? or use linux platform

**Comment by wonderingabout** [comment]
this is usually an error i got with opencl not installed on linux
or sometimes when playing too much games in parallel as compared to number of cpu cores/ram

i suggest you try on ubuntu to see if same issue happens (ofc installing opencl)

**Comment by gcp** [comment]
>maybe the opengl.dll version is too old

The one bundled with 0.17 is the very latest one, and in any case even old versions should perfectly work if the video drivers aren't broken, it does not need to know or care about new cards at all as the loader just forwards to the actual OpenCL driver of the card. But that's a big if - at least NVIDIA has broken them in this way in the past.

The error you are getting does mean there is a problem with the OpenCL drivers. Leela queries which OpenCL devices are on the system and this immediately crashes.

Are you using the 64 bit version? I noticed that nowadays the driver packages don't bundle 32 bit support any more.

**Comment by gcp** [comment]
Oh, I checked the output and you are using 0.16. Please update, there's a new version of Leela Zero out.

**Comment by bearyangry** [comment]
I am using the 64-bit version. 

I tried both 0.16 and 0.17, I didn't post the output of .17 as it was the same. Here is the output for reference.

[leela0.17_error.txt](https://github.com/leela-zero/leela-zero/files/3051801/leela0.17_error.txt)

**Comment by l1t1** [comment]
can the cpu version/cpu only option  work?

**Comment by gcp** [comment]
>I didn't post the output of .17 as it was the same.

Thanks. Interesting. It surprises me that other tools work and can query the OpenCL devices. Leela can't even get a list of devices.

You can try deleting the OpenCL.dll that is bundled with Leela. This has been known to fix some broken NVIDIA drivers, maybe AMD made a similar goof.

**Comment by l1t1** [comment]
android driver has similar question
https://github.com/gcp/leela-zero/issues/1679

**Comment by bearyangry** [comment]
Deleting the OpenCL.dll file resolved the issue. Thanks for the input everyone!
