### ISSUE TITLE
Is there a command to do a memory clean without exiting the program?

### ISSUE THREAD

**Issue by zhanzhenzhen** [leela-zero/leela-zero#2323]
We'd like to use Leela command to do some automatic test matches. Originally, I used the GTP commands to clean the board and then generate moves to play a new game after the old game ended. But this makes it "remember" some positions in the old game, therefore makes the new game unfair. So now I exit and restart Leela for every game. This makes the network loading time a huge problem (our test is just 1 visit per move, so the playing lasts less than 5 seconds but the loading time is 10 seconds). So I have a question: Is there a command to do a memory clean so that we can have a pristine state as if it's just restarted?

**Comment by l1t1** [comment]
you can use a bat file instead of one command

**Comment by wpstmxhs** [comment]
I suggest to make a GTP command that clears search tree and NNCache.
`clear_board` command resets search tree but it does not reset NNCache.
For some purposes(e.g. testing strength), this may lead a biased search.

**Comment by zhanzhenzhen** [comment]
@wpstmxhs Thanks! So I also hope to add a GTP command to clear the NNCache!

**Comment by alreadydone** [comment]
See https://github.com/gcp/leela-zero/pull/2046 for what you need to do.

**Comment by zhanzhenzhen** [comment]
Thanks! That looks pretty good!
