### ISSUE TITLE
Tests fail after compiling 0.17

### ISSUE THREAD

**Issue by mr2cef** [leela-zero/leela-zero#2328]
I can compile LZ 0.17, but then gtests show the following:

Running main() from gtest_main.cc
[==========] Running 13 tests from 2 test cases.
[----------] Global test environment set-up.
BLAS Core: built-in Eigen 3.3.7 library.
Detecting residual layers...v1...8 channels...1 blocks.
Initializing OpenCL (autodetecting precision).
Detected 1 OpenCL platforms.
Platform version: OpenCL 1.2 CUDA 10.1.133
Platform profile: FULL_PROFILE
Platform name:    NVIDIA CUDA
Platform vendor:  NVIDIA Corporation
Device ID:     0
Device name:   GeForce RTX 2070
Device type:   GPU
Device vendor: NVIDIA Corporation
Device driver: 418.56
Device speed:  1620 MHz
Device cores:  36 CU
Device score:  1112
Selected platform: NVIDIA CUDA
Selected device: GeForce RTX 2070
with OpenCL 1.2 capability.
Half precision compute support: No.
Tensor Core support: Yes.
OpenCL: using fp16/half or tensor core compute support.

Started OpenCL SGEMM tuner.
Will try 380 valid configurations.
(2/380) KWG=32 KWI=2 MDIMA=16 MDIMC=16 MWG=32 NDIMB=16 NDIMC=16 NWG=16 SA=0 SB=0 STRM=0 STRN=0 TCE=1 VWM=2 VWN=2 0.0065 ms (17.8 GFLOPS)
(11/380) KWG=32 KWI=2 MDIMA=8 MDIMC=32 MWG=32 NDIMB=32 NDIMC=32 NWG=32 SA=0 SB=0 STRM=0 STRN=0 TCE=1 VWM=2 VWN=2 0.0063 ms (18.4 GFLOPS)
(12/380) KWG=32 KWI=2 MDIMA=32 MDIMC=32 MWG=32 NDIMB=8 NDIMC=8 NWG=32 SA=0 SB=0 STRM=0 STRN=0 TCE=1 VWM=2 VWN=2 0.0037 ms (31.0 GFLOPS)
double free or corruption (out)

is this a driver problem? 0.16 seems to work fine...

**Comment by egri-nagy** [comment]
I have the same card (GeForce RTX 2070) and exactly the same problem. LZ itself seems to work ok.
Nvidia driver: 418.56

**Comment by gcp** [comment]
Duplicate of #2347 I think.
