### ISSUE TITLE
reattatch children for faster evaluation

### ISSUE THREAD

**Issue by faheuer** [leela-zero/leela-zero#2340]
I don't write much C++ code so I'm not sure if this is already implemented in Leela or not, but I couldn't find this in any of the AG papers so maybe it is worth mentioning here:

When observing a node in the tree, does Leela check if this node exists in a different subtree already and cross-attaches it to the other tree? If not, I believe this could improve evaluation time a lot since for example two branches containing a 2ply move that just play the same moves in different orders need to be evaluated both independently while in this manner they need to be evaluated only once ("tewari"). Just a thought.

**Comment by roy7** [comment]
For the first 30 or so moves of the game, every rotation/symmetry of a board will be checked against the NNCache to see if it might already be in there. Past that point, it stops doing so, but from what you are asking if an identical node comes up it'll be in the NNCache. So it'll be in the tree separate times but only one GPU eval is done. Expanding any nodes under this one, if those are also NNCache hits, will be super fast.

**Comment by faheuer** [comment]
Okay, cool :)
