### ISSUE TITLE
aq become aqz

### ISSUE THREAD

**Issue by l1t1** [leela-zero/leela-zero#2346]
https://sports.sina.cn/others/qipai/2019-04-18/detail-ihvhiqax3677636.d.html?from=wap

**Comment by MartinVingerhoets** [comment]
You should try joining the LZ discord server instead of posting links in separate issues all the time. Here's the invite link: https://discord.gg/Ue8aGdr

**Comment by l1t1** [comment]
sorry, but discord is blocked in my area

**Comment by alreadydone** [comment]
Takeaway: aiming to win CITIC tournament this August and then open source.
https://github.com/zakki/Ray/issues/171#issuecomment-455089658
https://www.3-ize.jp/information/?p=590 vowing for championship
https://www.excite.co.jp/news/article/Dreamnews_0000193179/
https://twitter.com/ymg_aq/status/1118768007973498882
