### ISSUE TITLE
the validation tool in  leela-zero-0.17-cpuonly-win32.zip needs more dll files

### ISSUE THREAD

**Issue by l1t1** [leela-zero/leela-zero#2349]
suggest add a note of needs copy them from leela-zero-0.17-win32.zip

**Comment by gcp** [comment]
I'll re-upload the release package to fix this.

**Comment by gcp** [comment]
Reuploaded, should be fixed now.

**Comment by l1t1** [comment]
new zip file still missing libwinpthread-1.dll
