### ISSUE TITLE
Save value for each position in training data

### ISSUE THREAD

**Issue by windo** [leela-zero/leela-zero#235]
It looks like just move probabilities are stored in training data ATM. Though (presumably) not called for by the AGZ paper, I'd like to see the score/winrate/value of the board position stored as well as probabilities for moves.

If it is appended to the data for future games then it should not mess up the training pipeline too much? Would a patch to add it have a chance of being merged?

**Comment by Vandertic** [comment]
I think for the training the idea is to use the final result of the game, not the expected winrate in any position. The winrate for any position can be evaluated using the same net as the one that generated the game.

**Comment by windo** [comment]
It can be evaluated by the neural network by redoing the 1K deep search with MCTS which is expensive.

Currently (and based on AGZ) yes, the current position winrate does not end up being used for training. But as contributors also run side experiments it would be cool to have this available and it would be super cheap to collect and save.

For example, I wanted to use evaluations from the latest network to compare them to the previous network with tree search (the training data) and can only really do this for policy network but not for value network, because the valuation is not saved. Someone else may have other ideas in the future as well what to do with all the data we are generating so it would be great if this piece was present.

**Comment by killerducky** [comment]
See my pull request: https://github.com/gcp/leela-zero/pull/231 If you run autogtp -k savedir -d savedir it will save an extra debug file with the value and some other outputs.

**Comment by gcp** [comment]
I agree it would be a good idea to store the MCTS output in the training data, but not for this run (don't really want to deal with 2 different training data formats). It's a fairly easy patch to add.

**Comment by sethtroisi** [comment]
This is supported now.
