### ISSUE TITLE
 questions about validation tool

### ISSUE THREAD

**Issue by l1t1** [leela-zero/leela-zero#2350]
1. how to set the total game amouts in one task
2. how to pause the valid process, like press q in autogtp
3. when i set -g 6 and -t 1, the machine hang, how to avoid
4. how to save the tweo players info such as engine and parameters in the sgf, like gogui twogtp did
5. how to speed the init process between games

**Comment by l1t1** [comment]
6. how to avoid following error
```
302 (W L15) 303 (B M12) 304 (W resign) Game has ended.
Score: B+Resign
Winner: black
Stopping engine.
82 wins, 86 losses
168 games played.
Status: 0 LLR -0.0122857 Lower Bound -2.94444 Upper Bound 2.94444
Engine has started.
time_settings 0 1 0
Starting GTP commands sent.
*ERROR*: Could not talk to engine after launching.
```

**Comment by gcp** [comment]
One of the engines crashed for whatever reason.

**Comment by l1t1** [comment]
it played 488 games for lz 223 with visits 1, and score 231:257, when will it stop?

**Comment by l1t1** [comment]
question 2, press q will stop validate an print result
