### ISSUE TITLE
I tested the strength of LZ_223

### ISSUE THREAD

**Issue by Weberkx3** [leela-zero/leela-zero#2357]
I tested the strength of LZ_223, each group has a different weight and playout against 100 games, a total of 2800 games.

LZ_223 is close to LZ_220, but significantly stronger than LZ_200
Did not find the problem of rock-paper-scissors

Strength continues to grow as training progresses

![image](https://user-images.githubusercontent.com/25165640/56856353-8d175d00-698b-11e9-9412-6e7f80d15fb3.png)

![image](https://user-images.githubusercontent.com/25165640/56856431-b5538b80-698c-11e9-90ab-1ba49da63718.png)

[!PKResult.txt](https://github.com/leela-zero/leela-zero/files/3124467/PKResult.txt)

**Comment by l1t1** [comment]
good. could you attach the files?

**Comment by Weberkx3** [comment]
[LZ_223_FullTest.zip](https://github.com/leela-zero/leela-zero/files/3124515/LZ_223_FullTest.zip)
This is all 2,800 games

**Comment by l1t1** [comment]
i saw the sgf has many detail info about thinking
```
C[  Q4 ->       2 (V: 56.41%) (LCB:  0.00%) (N: 86.13%) PV: Q4 Q16
3 visits, 1077 nodes, 2 playouts.]
```
pls also supply the command line of pk. thanks,

**Comment by Weberkx3** [comment]
[AutoPK_V2.zip](https://github.com/leela-zero/leela-zero/files/3125268/AutoPK_V2.zip)

This is an automatic PK python program
Modify the AutoPK project to create my own version
https://github.com/guitanj/AutoPK/

Now my version supports multiple weights
Still in continuous improvement

![image](https://user-images.githubusercontent.com/25165640/56858811-1c843680-69b3-11e9-99ff-953f56b8bc06.png)

![image](https://user-images.githubusercontent.com/25165640/56867980-f300f480-6a1e-11e9-8a2e-b20fde5db341.png)

**Comment by l1t1** [comment]
very nice work

**Comment by Glrr** [comment]
LZ223 behaves well against elf on cgos : 
http://www.yss-aya.com/cgos/19x19/cross/LZ_223_c9fb_p400.html

**Comment by iopq** [comment]
This isn't time parity, right? Because Elf gets almost twice the playouts in the same time.

**Comment by Weberkx3** [comment]
This is the same Playout test
Next time, I also want to do the same time test.

**Comment by wonderingabout** [comment]
@Weberkx3 

same playout test is the most objective, big thanks for gathering this data even though playout is small

you may want to add lz minigo v15 as well and/or native phoenixgo :+1:

**Comment by Weberkx3** [comment]
May not join lz minigo and phoenixgo, other tests indicate that they are very close to ELFv2

But I want to add more new 15b weight tests, some 15b weights are very powerful

**Comment by wonderingabout** [comment]
@Weberkx3 

ok, makes sense indeed :+1:

**Comment by ozymandias8** [comment]
How do thread and batch size choices affect engine performance? I note that the study uses batch size of 1, whereas on my system, validation.exe chooses 10 threads and batch size 5 by default.

**Comment by Weberkx3** [comment]
Batch size cannot be greater than thread.
Thread greater than 1 will make the playout slightly exceed the set number

Test in small playout, I will use,
-t1 --batchsize 1

Maybe the test above 1600playout, I will use,
-t6 --batchsize 5

The more threads, the more speed

**Comment by iopq** [comment]
On life in 19x19 they mentioned more threads decreases the strength of LZ vs. Elf

Not sure if LZ gets weaker, or if Elf gets stronger

**Comment by ozymandias8** [comment]
I just looked, that seems like a strange result though since he or she is using LZ engine for both, right? I wonder what the batch size was set to for each of those.

**Comment by Friday9i** [comment]
Nice work!
@herazul and me ran ~12K games, all at 400 visits, in a "tournament" between LZ220, LZ215, LZ210, ..., LZ180 and LZ174. It gives us a clear and consistant view of the strength improvement of LZ 40b nets over time (ie number of additional ELO per new promoted net)!
We are currently running some additional matches at 1600 visits.
We'll post the details and results on github soon, probably in about one week ; -)
