### ISSUE TITLE
Finally got 0.17 work on Android fully

### ISSUE THREAD

**Issue by Grant-Tao** [leela-zero/leela-zero#2366]
after half a month's try, 0.17 works on my Honor V10 (CPU: kirin 970, GPU Mali G72, Android 9.0).

Good News:
          1.  no source modification
          2.  can work at both --cpu-only mode and OpenCL single precision mode
          3. for a 15X192 network, performance is around 20 nodes per seconds at cpu only mode
Bad news:
          1.  can not work at OpenCL half precision mode
          2.  for a 15X192 network, at OpenCL single precision mode, performance is around 10 nodes per second

it seems that mobile phone's GPU were not an attractive computing unit, except some one can work out the half precision mode. 

May 5 adding:
Got a fully workable version for Qualcomm Snapdragon 660 (a Redmi Note 7 phone), it can work at all modes (cpu, opencl single or hlaf), but the performace is disappointing:
       for a 15X192 network, 
            cpu-only:  20- 35 nodes per second
            opencl single:  6-7 nodes per second
            opencl half:     2-3 nodes per second

20-35 nodes per second is a quite impressive result, as a desktop cpu (for example, intel i5 7500) can only achieve about 35 nodes per second

@l1t1, try leelaz_660 for your 820

**Comment by Grant-Tao** [comment]
Done list:

Download following things:
       libOpenCL.so from mobile phone's /system/vendor/lib64
       OpenCL_headers from Github
       ndk r19c
       platform tools
       boost 1.69.0 (the compiled version for ndk 19c)
       OpenBLAS 0.35 (compiled for target armv8, see openblas' wiki)
 
then use ndk-build with following android.mk and appplication.mk

android.mk
----
LOCAL_PATH := $(call my-dir)

# ------------------------------------------------------------------------------
# arm64 OpenCL lib copy
# ------------------------------------------------------------------------------
include $(CLEAR_VARS)
ifeq ($(TARGET_ARCH_ABI),arm64-v8a)
LOCAL_MODULE    := arm64-OpenCL-Library
LOCAL_SRC_FILES := vendor/lib64/libOpenCL.so   
include $(PREBUILT_SHARED_LIBRARY)
endif

include $(CLEAR_VARS)
LOCAL_MODULE := openblas
LOCAL_SRC_FILES =/path to OpenBLAS_0_35/lib/libopenblas.a 
include $(PREBUILT_STATIC_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE := boost_program_options
LOCAL_SRC_FILES =/path to Boost_1_69_0/libs/llvm/arm64-v8a/libboost_program_options.a 
include $(PREBUILT_STATIC_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE := boost_filesystem
LOCAL_SRC_FILES =/path to Boost_1_69_0/libs/llvm/arm64-v8a/libboost_filesystem.a
include $(PREBUILT_STATIC_LIBRARY)

# ------------------------------------------------------------------------------
# Build execute binary
# ------------------------------------------------------------------------------
include $(CLEAR_VARS)
LOCAL_MODULE := leelaz
SRC_DIR      := src
CPP_FILES    := $(wildcard $(LOCAL_PATH)/$(SRC_DIR)/*.cpp)
SRC_FILES    :=
SRC_FILES    += $(subst $(LOCAL_PATH)/,, $(CPP_FILES))
$(info LOCAL_PATH:$(LOCAL_PATH))
$(info SRC_FILES:$(SRC_FILES))
C_INCLUEDS   := src/
CL_INCLUEDS  := $(LOCAL_PATH)/OpenCL-Headers 

LOCAL_STATIC_LIBRARIES := openblas boost_program_options boost_filesystem
LOCAL_SHARED_LIBRARIES := arm64-OpenCL-Library
LD_OPTION              := -lz -fuse-ld=gold

LOCAL_SRC_FILES  := $(SRC_FILES)
LOCAL_LDLIBS     := $(LD_OPTION)
LOCAL_CPPFLAGS   := 
LOCAL_C_INCLUDES := $(C_INCLUEDS) $(CL_INCLUEDS)
#LOCAL_ALLOW_UNDEFINED_SYMBOLS := true

$(info DST:$(NDK_APP_DST_DIR))
$(info PLATFORM : $(TARGET_PLATFORM))
$(info ARCH/ABI : $(TARGET_ARCH)/$(TARGET_ARCH_ABI))
include $(BUILD_EXECUTABLE)
---
 
application.mk
---
APP_PLATFORM := android-28
APP_ABI := arm64-v8a 
APP_STL := c++_static 
APP_CPPFLAGS += -std=c++14 
APP_CPPFLAGS += -I/path to Boost_1_69_0/include
APP_CPPFLAGS += -I/path to OpenBLAS_0_35/include
APP_CPPFLAGS += -fexceptions
APP_CPPFLAGS += -frtti

**Comment by l1t1** [comment]
nice job, will you try this on qualcomm platform?

**Comment by l1t1** [comment]
how did you run it?
i run it at a terminal of pydroid 3 using follwing command 
/storage/emulated/0/Download $ ./lz -w a.gz -g

**Comment by l1t1** [comment]
https://github.com/leela-zero/leela-zero/issues/2358
is a benchmark of 820, using 
https://github.com/uestccokey/AhQResource/issues/4

**Comment by Grant-Tao** [comment]
@l1t1  
1. I do not have a qualcomm cpu phone, if you can provide the libOpenCL.so file a mobile phone with qualcomm cpu and android 9.0, i may make one for you.

2. you can run 
          a, in an adb shell in command line mode: leelaz -w a.gz --cpu-only or leelaz -w a.gz --precision single, or
          b. embedded in Go GridMaster from Erik van der Werf @evdwerf. For opencl work mode, you must also copy the tuning file to the working directory. 

3. Kirin 970 is better than 835 but a little weaker than 845, 20 nodes per second performnace sounds normal

**Comment by l1t1** [comment]
thanks, i by chance have a Honor V10 too, could you attach the binary?
could you please build one  for qualcomm android 6 or 7 ?

**Comment by Grant-Tao** [comment]
@l1t1 
Here you are https://github.com/Grant-Tao/compiled-leelaz-0.17-for-android-phones
leelaz_855 for Mi9
leelaz_970 for V10

I stole the libOpenCL.so files from Mi 9's MIUI Rom, and compiled leelaz_855, try on your 820, may work or not, i can not guarantee.

**Comment by l1t1** [comment]
855 version doesnt work
···
/storage/emulated/0 $ cd Do*
/storage/emulated/0/Download $ lz8 -h                      
 sh: lz8: not found                                          /storage/emulated/0/Download $ ./lz8 -w lz0.gz              Using OpenCL batch size of 5                                Using 10 thread(s).                                         RNG seed: 13652567126494671430                              Leela Zero 0.17  Copyright (C) 2017-2019  Gian-Carlo Pascutto and contributors                                          This program comes with ABSOLUTELY NO WARRANTY.             This is free software, and you are welcome to redistribute it                                                           under certain conditions; see the COPYING file for details. BLAS Core: ARMV8                                            Detecting residual layers...v1...8 channels...1 blocks.     Initializing OpenCL (autodetecting precision).              Detected 1 OpenCL platforms.                                Platform version: OpenCL 2.0 QUALCOMM build: commit #be6f1c5 changeid #Ie5a8c7e47f Date: 05/29/16 Sun Local Branch:  Remote Branch:
Platform profile: FULL_PROFILE
Platform name:    QUALCOMM Snapdragon(TM)
Platform vendor:  QUALCOMM
Device ID:     0
Device name:   QUALCOMM Adreno(TM)
Device type:   GPU
Device vendor: QUALCOMM
Device driver: OpenCL 2.0 QUALCOMM build: commit #be6f1c5 changeid #Ie5a8c7e47f Date: 05/29/16 Sun Local Branch:  Remote Branch:  Compiler E031.29.02.00
Device speed:  1 MHz
Device cores:  4 CU
Device score:  120
Selected platform: QUALCOMM Snapdragon(TM)
Selected device: QUALCOMM Adreno(TM)
with OpenCL 2.0 capability.
Error creating OpenCL context: clCreateContext: -6terminating with uncaught exception of type std::runtime_error: Error creating OpenCL context.
Aborted
/storage/emulated/0/Download $
···

**Comment by l1t1** [comment]
btw --cpu-only works fine, genmove successfully

**Comment by l1t1** [comment]
/storage/emulated/0/Download $ ./lz8 -w ../aq/leela/elf1.gz --cpu-only -g                                               Using 4 thread(s).                                          RNG seed: 18086540850272635331                              BLAS Core: ARMV8                                            Detecting residual layers...v2...224 channels...20 blocks.  Initializing CPU-only evaluation.                           Setting max tree size to 4136 MiB and cache size to 459 MiB.netbench 100                                                  100 evaluations in 14.21 seconds -> 7 n/s                 =

**Comment by Grant-Tao** [comment]
Some one who has Mi 9 can try. 
OpenCL can only work at single precision, you shall type: ./lz8 -w lz0.gz --precision single.
But the error message said OpenCL context creating error, means the ICDs of 820 and 855 are not compatible, it's normal that leelaz_855 can not work with snapdragon 820.

**Comment by l1t1** [comment]
thanks, unfortunetly , gpu version error 

```
/storage/emulated/0 $ cd Dow*
/storage/emulated/0/Download $ ./lz6 -w lz57.gz -g          Using OpenCL batch size of 5                                Using 10 thread(s).                                         RNG seed: 13526026132112178864                              BLAS Core: ARMV8                                            Detecting residual layers...v1...64 channels...5 blocks.    Initializing OpenCL (autodetecting precision).              Detected 1 OpenCL platforms.                                Platform version: OpenCL 2.0 QUALCOMM build: commit #be6f1c5 changeid #Ie5a8c7e47f Date: 05/29/16 Sun Local Branch:  Remote Branch:                                                 Platform profile: FULL_PROFILE                              Platform name:    QUALCOMM Snapdragon(TM)                   Platform vendor:  QUALCOMM                                  Device ID:     0                                            Device name:   QUALCOMM Adreno(TM)                          Device type:   GPU                                          Device vendor: QUALCOMM                                     Device driver: OpenCL 2.0 QUALCOMM build: commit #be6f1c5 changeid #Ie5a8c7e47f Date: 05/29/16 Sun Local Branch:  Remote Branch:  Compiler E031.29.02.00
Device speed:  1 MHz
Device cores:  4 CU
Device score:  120
Selected platform: QUALCOMM Snapdragon(TM)
Selected device: QUALCOMM Adreno(TM)
with OpenCL 2.0 capability.
Error creating OpenCL context: clCreateContext: -6terminating with uncaught exception of type std::runtime_error: Error creating OpenCL context.
Aborted
/storage/emulated/0/Download $
```

**Comment by Grant-Tao** [comment]
@l1t1  try leelaz_820 please。

**Comment by l1t1** [comment]
820vetsion has same problem, should i copy some so file into the directory of leelaz placed?

**Comment by l1t1** [comment]
i use opencl-z tool to get info, it ouput the info same as leelaz, and lib is located at/system/vendor/lib/libOpenCL.so, my android version 6.01. btw, all your files run ok on my 820phone with --cpu-only, including the 970version

**Comment by l1t1** [comment]
i searched papers on internet, all of them said gpu are faster than cpu, such as
Accelerating CNN’s forward process on mobile GPU using OpenCL
10.1117/12.2244914

**Comment by l1t1** [comment]
good news, your 660 verion run on 625 pad success.
android version 7.1.1

**Comment by l1t1** [comment]
10x128 weight
gpu
Leela: netbench 100
  100 evaluations in 18.82 seconds -> 5 n/s


/storage/emulated/0/Download $ ./lz6 --cpu-only -w 8.gz -g
Using 8 thread(s).
RNG seed: 14900980956833851108
BLAS Core: ARMV8
Detecting residual layers...v1...128 channels...10 blocks.
Initializing CPU-only evaluation.
Setting max tree size to 4344 MiB and cache size to 482 MiB.
netbench 100
  100 evaluations in  3.76 seconds -> 26 n/s
=

**Comment by l1t1** [comment]
/storage/emulated/0/Download $ ./lz6 -w 8.gz -g --precision half
Using OpenCL batch size of 5
Using 10 thread(s).
RNG seed: 4846216754758579702
BLAS Core: ARMV8
Detecting residual layers...v1...128 channels...10 blocks.
Initializing OpenCL (half precision).
Detected 1 OpenCL platforms.
Platform version: OpenCL 2.0 QUALCOMM build: commit #dfab96b changeid #I762e720a6a Date: 01/31/17 Tue Local Branch:  Remote Branch:
Platform profile: FULL_PROFILE
Platform name:    QUALCOMM Snapdragon(TM)
Platform vendor:  QUALCOMM
Device ID:     0
Device name:   QUALCOMM Adreno(TM)
Device type:   GPU
Device vendor: QUALCOMM
Device driver: OpenCL 2.0 QUALCOMM build: commit #dfab96b changeid #I762e720a6a Date: 01/31/17 Tue Local Branch:  Remote Branch:  Compiler E031.31.00.03
Device speed:  1 MHz
Device cores:  1 CU
Device score:  120
Selected platform: QUALCOMM Snapdragon(TM)
Selected device: QUALCOMM Adreno(TM)
with OpenCL 2.0 capability.
Half precision compute support: Yes.
Tensor Core support: No.
Loaded existing SGEMM tuning.
Wavefront/Warp size: 8
Max workgroup size: 1024
Max workgroup dimensions: 1024 1024 1024
Setting max tree size to 4344 MiB and cache size to 482 MiB.
netbench 100
  100 evaluations in 48.97 seconds -> 2 n/s
=

**Comment by l1t1** [comment]
when i run lz820 on another 820 phone with android 7.0, it raise ""unable to stat file for the executable""..., same error shown on huawei btv pad with 950, how to solve it?

**Comment by l1t1** [comment]
you are right, my pc cpu i5 6600 and gpu gt 730
```
D:\tool\leela15>leelaz -w \157_quantized.txt -g --cpu-only
Using 4 thread(s).
RNG seed: 3525604882087202436
BLAS Core: Haswell
Detecting residual layers...v1...192 channels...15 blocks.
Initializing CPU-only evaluation.
Setting max tree size to 4248 MiB and cache size to 472 MiB.
netbench 100
  100 evaluations in  2.74 seconds -> 36 n/s
=

quit
=


D:\tool\leela15>leelaz -w \157_quantized.txt -g
Using OpenCL batch size of 5
Using 10 thread(s).
RNG seed: 13874705113649048023
BLAS Core: Haswell
Detecting residual layers...v1...192 channels...15 blocks.
Initializing OpenCL (autodetecting precision).
Detected 1 OpenCL platforms.
Platform version: OpenCL 1.2 CUDA 9.1.84
Platform profile: FULL_PROFILE
Platform name:    NVIDIA CUDA
Platform vendor:  NVIDIA Corporation
Device ID:     0
Device name:   GeForce GT 730
Device type:   GPU
Device vendor: NVIDIA Corporation
Device driver: 391.35
Device speed:  901 MHz
Device cores:  2 CU
Device score:  1112
Selected platform: NVIDIA CUDA
Selected device: GeForce GT 730
with OpenCL 1.2 capability.
Half precision compute support: No.
Tensor Core support: No.
Detected 1 OpenCL platforms.
Platform version: OpenCL 1.2 CUDA 9.1.84
Platform profile: FULL_PROFILE
Platform name:    NVIDIA CUDA
Platform vendor:  NVIDIA Corporation
Device ID:     0
Device name:   GeForce GT 730
Device type:   GPU
Device vendor: NVIDIA Corporation
Device driver: 391.35
Device speed:  901 MHz
Device cores:  2 CU
Device score:  1112
Selected platform: NVIDIA CUDA
Selected device: GeForce GT 730
with OpenCL 1.2 capability.
Half precision compute support: No.
Tensor Core support: No.
Loaded existing SGEMM tuning.
Wavefront/Warp size: 32
Max workgroup size: 1024
Max workgroup dimensions: 1024 1024 64
Loaded existing SGEMM tuning.
Wavefront/Warp size: 32
Max workgroup size: 1024
Max workgroup dimensions: 1024 1024 64
Using OpenCL single precision (less than 5% slower than half).
Detected 1 OpenCL platforms.
Platform version: OpenCL 1.2 CUDA 9.1.84
Platform profile: FULL_PROFILE
Platform name:    NVIDIA CUDA
Platform vendor:  NVIDIA Corporation
Device ID:     0
Device name:   GeForce GT 730
Device type:   GPU
Device vendor: NVIDIA Corporation
Device driver: 391.35
Device speed:  901 MHz
Device cores:  2 CU
Device score:  1112
Selected platform: NVIDIA CUDA
Selected device: GeForce GT 730
with OpenCL 1.2 capability.
Half precision compute support: No.
Tensor Core support: No.
Loaded existing SGEMM tuning.
Wavefront/Warp size: 32
Max workgroup size: 1024
Max workgroup dimensions: 1024 1024 64
Setting max tree size to 4248 MiB and cache size to 472 MiB.
netbench 100
  100 evaluations in  1.29 seconds -> 77 n/s
=
```

**Comment by l1t1** [comment]
maybe the memory of mobile gpu is too small to computer the big network. so it use system memory and reduce the perforance.
https://www.csdn.net/article/a/2018-11-05/15964582

**Comment by l1t1** [comment]
http://tieba.baidu.com/p/6067881954
says
660 的 GPU很弱，GPU GFLOPS 的烤鸡分数稳定为75，上限83。顶多……嗯…中端水平
820 的 GPU 烤鸡分数为 270 左右。
845 的 GPU 分数为 687
The 660's GPU is very weak, and the GPU GFLOPS's roast chicken score is stable at 75 and the upper limit is 83. At most... um... mid-level
The 820 GPU roast chicken score is around 270.
The 845 has a GPU score of 687.

**Comment by Grant-Tao** [comment]
I am not an expert in opencl, i do not know the reason. i googled, there are many complains about slow opencl computing on android platform.  I guess there are several reasons for slower speed of GPU (compared with CPU) in leela zero:
1. Neon & VFP instructions: OpenBlas and Boost are optimized with  Arm64 v8a neon and vfp instructions, , 8 core Arm 2G CPU is much more powerful

2.  Mobile GPU has very small local memory, usually less than 4M, "if you query the GPU local memory size of Kirin 970, the return is 0, i do not know why".

3.  narrow memory bandwidth between system memory and GPU local memory  (Mali G72 , less than 15G/s,  while gtx1070 256G/s.

**Comment by l1t1** [comment]
would this project helpful?
https://zhuanlan.zhihu.com/p/64818411

https://github.com/alibaba/MNN

**Comment by l1t1** [comment]
820 CPU only 11n/s for 15x192 net
/Download $ ./lz820 -w lz22415b.gz --cpu-only -g
Using 4 thread(s).
RNG seed: 9161151356363036656
BLAS Core: ARMV8
Detecting residual layers...v1...192 channels...15 blocks.
Initializing CPU-only evaluation.
Setting max tree size to 4248 MiB and cache size to 472 MiB.netbench 100
  100 evaluations in  8.41 seconds -> 11 n/s

**Comment by l1t1** [comment]
I only got 9 n/s in 970 v10 using a 15b weight. why?
http://www.flygo.net/bbs/forum.php?mod=redirect&goto=findpost&ptid=109850&pid=1150895&fromuid=777946

**Comment by l1t1** [comment]
https://www.anandtech.com/show/14384/arm-announces-cortexa77-cpu-ip
https://www.anandtech.com/show/14385/arm-announces-malig77-gpu
