### ISSUE TITLE
RTX 2060 Boost Clock Behavior

### ISSUE THREAD

**Issue by ozymandias8** [leela-zero/leela-zero#2368]
I have a strange issue that is proving difficult to debug. I just upgraded to a RTX 2060 and have been doing some tests.

While using autogtp, GPUZ reports high TDP (~90%), and I'm running at maximum boost clocks and high load.

![image](https://user-images.githubusercontent.com/49527008/57052264-460fbd00-6c54-11e9-9788-c41ab0a4d671.png)

Now, when I try to analyze one of my games, or play a bot match in Sabaki or Lizzie, all of the sudden boost mode refuses to kick in. GPUZ states the PerfCap Reason as "Idle".

![image](https://user-images.githubusercontent.com/49527008/57052296-6e97b700-6c54-11e9-8c9f-defe5868b7c6.png)

Some more investigation shows that both autogtp and Sabaki are using the P2 state while running Leela, but boost mode only kicks in with autogtp. That does not really make any sense to me. Does anyone know the issue here and how I might work around it?

![image](https://user-images.githubusercontent.com/49527008/57052256-3f814580-6c54-11e9-9a43-649119b4bed1.png)

**Comment by Splee99** [comment]
You may check the number of threads used in autogtp and compare it with Sabaki. The batch size also varies with the number of threads setting.

**Comment by ozymandias8** [comment]
I thought to check that as well, it doesn't seem to matter. Both autogtp and validation always use the higher clocks, regardless of thread and batch count, whereas the GPU stays in idle mode if Leela is run through third party software. I am baffled.

Edit: @Splee99 played with it some more this morning, I seem to have fixed the issue by changing the power setting from "Optimal" to "Adaptive". Still doesn't make any sense, but at least it is working now...

**Comment by lonemonkeywithwhiteshell** [comment]
Thank you for the information,but I had already done it.
