### ISSUE TITLE
How to access earlier leela zero network weights and other public domain data

### ISSUE THREAD

**Issue by nanzi** [leela-zero/leela-zero#2369]
Since @gcp mentioned in [issue 1220](https://github.com/leela-zero/leela-zero/issues/1220), the networks and training data are public domain. I create a self-play game dataset [repo](https://github.com/nanzi/leelazero_go_selfplay_game_datasets/), each game split in single sgf file and classified by network hash. Although uploading data still in progress, would you please to add this repo to readme last section: Related links?

And when I tried to download some old networks from ogs, I found some issue today(20190502).
Why don't create an repo to hold these files? Since v130 network was compared to katago's 15b weight, I think somebody may need those old guys.

**Comment by l1t1** [comment]
nice job.

**Comment by nanzi** [comment]
Job's done. I have uploaded all network pieces from all_1M.sgf.xz to all_13M.sgf.xz.

Spliting is not that easy. I will open another repo to release corner pattern reviews 

on those self-play games from each network. I am one of go amateurs who want to see joseki

evolution in recent networks.

all_14M.sgf.xz contains LZ215 only, so it and its successors would not appear for now.

Minigo's network analysis on its web inspired me. Mining these datasets could give us many conclusions on many aspects.

**Comment by gcp** [comment]
>And when I tried to download some old networks from ogs, I found some issue today(20190502).

We are trying to restore the data: https://github.com/leela-zero/leela-zero/issues/167

If you want to mirror and organize it, go ahead.
