### ISSUE TITLE
Overwriting weight files of a running instance.

### ISSUE THREAD

**Issue by bvandenbon** [leela-zero/leela-zero#2371]
What I would like to do:

1. Start leela zero with a network file.
2. While leela zero is running, overwrite the network file.
3. LeeLa zero should continue to run with the old weights, until it is restarted.

Is it correct to state that LeeLa Zero loads the full weight file in memory at startup, 
and does not access the disk/file anymore once it is running ?

Thanks.

**Comment by wpstmxhs** [comment]
Sure. Leela Zero does not keep the weight file open.
At the program initialization phase, Leela Zero opens the specified file and reads weights from file and constructs neural network upon memory.
And after it finishes, it closes the file.
It will never open that file again until it is restarted.

**Comment by bvandenbon** [comment]
Thanks ! :) super
