### ISSUE TITLE
May I ask an easy way to close LCB move choose?

### ISSUE THREAD

**Issue by zliu1022** [leela-zero/leela-zero#2372]
Wish to compare to the oldest algorithm, I wish to close LCB temporary.
So if I set ```cfg_lcb_min_visit_ratio = 0.0f```, is it the easiest way to close LCB?
Please give me some suggestion.
Thanks for help

**Comment by roy7** [comment]
I think if you make it 1.0f it'll turn off. Going from memory but I think ratio is what % the lcb has to be of best move visits to prevent being pruned.

Ok actually this won't turn it off, but it means time management can prune the move.

**Comment by roy7** [comment]
The true way to turn it off is in https://github.com/leela-zero/leela-zero/blob/3f297889563bcbec671982c655996ccff63fa253/src/UCTNode.cpp#L369 just set that from 2 to a super high number you'll never hit, like 20000000.

**Comment by zliu1022** [comment]
Thank you very much！
That's really helpful! @roy7
