### ISSUE TITLE
Training machine went down

### ISSUE THREAD

**Issue by l1t1** [leela-zero/leela-zero#2373]
more than 13 hours passed since last match began

**Comment by l1t1** [comment]
resumed

**Comment by l1t1** [comment]
7 hours passed since last match began

**Comment by l1t1** [comment]
does the training server encounter problems?

**Comment by gcp** [comment]
Training machine went offline, I'll investigate.

**Comment by gcp** [comment]
One of the switches in my office got wedged, which I power cycled.

The dmesg of the training machine was full of errors from the network driver, and one of the other machines on the same network was completely unreachable even after resetting the switch. So it seems broken switches can kill Linux network drivers pretty well.

Everything is back up now.

**Comment by l1t1** [comment]
more than 7 hours passed since last match began,  it should be 6.5 hours

**Comment by l1t1** [comment]
more than 13 hours passed since last match began

**Comment by l1t1** [comment]
the web site is not avariable

Error 502 Ray ID: 4ed30b738b696d3a • 2019-06-26 23:43:40 UTC
Bad gateway
