### ISSUE TITLE
It is suggested that PK 400 or more can pass. And change 55% pass to 54.5%.

### ISSUE THREAD

**Issue by a270709570** [leela-zero/leela-zero#2374]
This can avoid the unreasonable phenomenon that 54.09% can pass and 54.63% can only fail.

**Comment by ayssia** [comment]
No.
You'll want to change 54.5% to 54% later to avoid the unreasonable phenomenon that 53.59% can pass and 54.13% can only fail.

**Comment by a270709570** [comment]
Cancel early pass。Must be over 400 games。

**Comment by a270709570** [comment]
> No.
> You'll want to change 54.5% to 54% later to avoid the unreasonable phenomenon that 53.59% can pass and 54.13% can only fail.



> No.
> You'll want to change 54.5% to 54% later to avoid the unreasonable phenomenon that 53.59% can pass and 54.13% can only fail.

Cancel early pass。Must be over 400 games。

**Comment by l1t1** [comment]
promotion is very much by chance, lz224 is very strong, even the winrate is less than .55
