### ISSUE TITLE
Why is the new model passed below 55 percent win rate?

### ISSUE THREAD

**Issue by kekmodel** [leela-zero/leela-zero#2382]
2019-04-29 21:42
f3 vs c9 
54.09%

**Comment by l1t1** [comment]
it passed by a bigger winrate at some games less than 400, then lost many games after that

**Comment by kekmodel** [comment]
In the paper, it is based on 400 games. Is not rollback necessary?

**Comment by ozymandias8** [comment]
There are other similar promotions in the past I've noticed. The lower bound of the 95% confidence interval in this case is 49.23% (54.09% sample proportion with sample size of 403). I assume at the time of promotion it met the 95% criterion, but there were outstanding games still being played.
