### ISSUE TITLE
Sgf files' name rule

### ISSUE THREAD

**Issue by KhiemDuyNguyen** [leela-zero/leela-zero#2386]
![Screenshot from 2019-05-14 14-37-08](https://user-images.githubusercontent.com/37052526/57726903-c91e1380-7655-11e9-86d9-991d4d19f8fe.png)
Are there any differences between sgf files that start with "black" and ones that start with "white"? 
They are not winner related since I check a couple of black and white sgf, black always win.

Sorry if this issue is duplicated.

**Comment by l1t1** [comment]
validation switch colors of two weight/ engine  in every pairs of games, they use different prefix

**Comment by KhiemDuyNguyen** [comment]
Thank you so much!
