### ISSUE TITLE
cannot visit the sever site

### ISSUE THREAD

**Issue by l1t1** [leela-zero/leela-zero#2397]
Error 502 Ray ID: 4db1f1110a2b7a80 • 2019-05-22 21:39:15 UTC
Bad gateway
You
Browser Working
Los Angeles
Cloudflare Working
zero.sjeng.org
Host
Error
What happened?
The web server reported a bad gateway error.
What can I do?
Please try again in a few minutes.
Cloudflare Ray ID: 4db1f1110a2b7a80
Your IP: 106.38.x.x

**Comment by roy7** [comment]
Server ran out of space, pending gcp to save the day.

**Comment by l1t1** [comment]
gcp need redirect the email of root to get warn

**Comment by l1t1** [comment]
the server is running, but no new weight run in match after 14 hours (2019-05-26 15:43	994790aa)
