### ISSUE TITLE
Handicap testing based on dual-weights, use weak weight’s 1 playout to predict weak player’s behavior

### ISSUE THREAD

**Issue by zliu1022** [leela-zero/leela-zero#2404]
Now leelazero is so strong so many times go fans would like to use leelazero weights to play handicap game, it’s more interesting for me to know is it possible for leelazero to win a handicap game more than 4 stones. 

In this issue, the handicap games specially means  4 stones handicap games. I suppose it’s difficult to use the existing way to play handicap game with very strong player, for example, the zenith7 analyze mode, or professional player.  Even the normal guess is maybe it’s impossible for AI to win a 4 stones handicap game with a high rank player. It's really mysterious and interesting. No one knows now.

Maybe it’s only 1% chance for AI to win a 4 stones game even with very high playouts when fighting with very strong player. So I change the thinking method and change the question to “**if AI win a 4 stone game, what would the game looks like?**”.

Based on this question, and with ttl’s [aux code,](https://github.com/Ttl/leela-zero/tree/aux_net) I make my own [dual weights code](https://github.com/zliu1022/leela-zero/tree/dual-se), I call this aux mode as handicap(HP) mode. During white player’s MCTS thinking, it will pick black’s move from black weight and during uct_select_child, it will lock the policy and ignore the black’s winrate. But every node ’s winrate will ONLY use white’s winrate to update. So I don't need to play many many games, only let MCTS to find the handicap game's answer, but the opponent is only 1 playout of some weights.

So when I put 4 stones on board and open the white’s analyze mode, just need to wait MCTS to find the 4 handicap game's win answer automatically.

I use OZ14 as white player, and use 157, 223, GX5B, OZ14 as black player.
Maybe you're interesting to fight with this dual-net engine by yourself ;)
The following table show how many playouts the white player find the answer:
![image](https://user-images.githubusercontent.com/3665494/58406079-6d16ae80-809b-11e9-91f3-0b7cc341b33e.png)

My command line looks like:
```cat gtp_h4_k0 | ./leelaz-dual-se -g -w ./OZ14.gz --timemanage off --noponder --auxmode HP --aux ./157.gz -p1200000 -t1```

The gtp_h4_k0 is a file which contain:
```
komi 0
time_settings 0 1 0
play B Q16
play B D4
play B Q4
play B D16

go
```

I use one command option to control several aux weight mode:
- HP: handicap mode which is explained as before
- BW: which is ttl's original aux network working mode, black's policy and winrate use one weight, white use another
- PR: use one network's policy and use another network's winrate
- AVG: use average of two network 's policy or winrate, it can be used in different komi weight, one weight is trained for 6.5 komi, one is trained for 7.5 komi, use average mode can play komi 7 games very well
- BTW, I merge the latest senet code as ttl's PR(#2370)

**Comment by l1t1** [comment]
whai is the diff between komi 7.5-n and "komi 7.5 and handicap n" for player has handicap
