### ISSUE TITLE
best move: LCB vs Prior vs winrate

### ISSUE THREAD

**Issue by bvandenbon** [leela-zero/leela-zero#2408]
Right now ZBaduk orders the moves of LeeLa Zero **by number of visits.**
That is because I am/was under the assumption that LeeLa Zero always plays the moves with most visits.

However, am I correct that I should prefer the move with **highest LCB** instead ?
Or **perhaps the prior.**

![afbeelding](https://user-images.githubusercontent.com/20482760/58559224-e68cd900-8222-11e9-93bd-fa76d1bdb082.png)

**Comment by roy7** [comment]
LZ these days orders by LCB instead and will select the move with highest LCB instead of highest # of visits. There shouldn't be a different in move choice frequently, but it is something to check out when using other interfaces. :)

**Comment by bvandenbon** [comment]
@roy7 
Thanks Roy. Exactly the confirmation I was hoping for.
