### ISSUE TITLE
Then, the program is over. 

### ISSUE THREAD

**Issue by i-LOVE-cplusplus** [leela-zero/leela-zero#2413]
[ leelaz.exe -> start ]

name
Using 3 thread(s).
RNG seed: 11249354418957709256
BLAS Core: Barcelona
Detecting residual layers...v1...256 channels...40 blocks.
Initializing CPU-only evaluation.
Setting max tree size to 3813 MiB and cache size to 423 MiB.
= Leela Zero

protocol_version
= 2

version
= 0.17

list_commands
= protocol_version
name
version
quit
known_command
list_commands
boardsize
clear_board
komi
play
genmove
showboard
undo
final_score
final_status_list
time_settings
time_left
fixed_handicap
last_move
move_history
place_free_handicap
set_free_handicap
loadsgf
printsgf
kgs-genmove_cleanup
kgs-time_settings
kgs-game_over
heatmap
lz-analyze
lz-genmove_analyze
lz-memory_report
lz-setoption
gomill-explain_last_move

boardsize 19

clear_board

komi 6.5

genmove w
Thinking at most 9.0 seconds...
NN eval=0.594747
Playouts: 6, Win: 59.87%, PV: R17 R16
Playouts: 15, Win: 59.82%, PV: R17 R16 Q17 P16 O18

 C17 ->       8 (V: 60.24%) (LCB: 56.55%) (N: 52.32%) PV: C17 C16 D17 F17 E17 E16 F18 R6
 R17 ->       7 (V: 59.16%) (LCB: 54.81%) (N: 20.45%) PV: R17 R16 Q17 P16 O18 R6 O3
 C14 ->       8 (V: 59.42%) (LCB: 54.40%) (N:  5.83%) PV: C14 R6 F17 F16 G16 F15 D17
4.9 average depth, 9 max depth
20 non leaf nodes, 1.15 average children
24 visits, 8449 nodes, 23 playouts, 2 n/s

= C17

NN eval=0.388375
Nothing at other end - exiting

[ leelaz.exe -> over ]

What's the problem?

**Comment by Splee99** [comment]
If you are using Sabaki, some of its releases have issues.

**Comment by i-LOVE-cplusplus** [comment]
I use GoGui-1.4.9
and when I use cmd to start leelaz.exe ,
the problem is stil unresolved .

Maybe I should use LeelaZero 0.16 .

**Comment by i-LOVE-cplusplus** [comment]
Thanks.

I kept trying. I finally found the way to solve the problem.

I add ed
        " --noponder -p 1600 -v 3200"  to
        " leelaz.exe -w weight.gz --gtp".

**Comment by roy7** [comment]
I'm guessing GoGUI doesn't like pondering since it doesn't know what to do with the extra input coming from the engine?
