### ISSUE TITLE
Wrong winner because territory not closed

### ISSUE THREAD

**Issue by EnixCaryos** [leela-zero/leela-zero#2420]
A strange result in the game http://zero.sjeng.org/view/94616357725929936729942bf4e56969fe297cac2fca6a3e24f60b0af59a53db?viewer=wgo#player={"goto":{"m":264}} for which I would say that black won by a few points.
In fact at the end the center territory is still not bordered, and in that case counting the score might have encoutered some difficulties and over estimated white points.

**Comment by Hersmunch** [comment]
See #2410 and more discussion in #2421.
