### ISSUE TITLE
Changing the weights

### ISSUE THREAD

**Issue by ThomasDeb** [leela-zero/leela-zero#2430]
I've been a little out of touch, but in the new version of LZ, contrary to before, the weights seem to be provided by default. I assume the default is the current best network, however is there a way to use other weights ? I didn't find an answer in the documentation or the code.

**Comment by Friday9i** [comment]
You'll find the nets there: http://zero.sjeng.org/
Current best is LZ229 ("Best network hash", number 229): f935bd85

**Comment by ThomasDeb** [comment]
Thanks for your answer, yes I know how to find other weights, I just don't know how to compile LZ with a given weights file.

**Comment by l1t1** [comment]
you wrote a script as following, then run it
./ leelaz -w yourweight.gz
