### ISSUE TITLE
leela GTP communication issue

### ISSUE THREAD

**Issue by n0tperfect** [leela-zero/leela-zero#2464]
Hello!
I'm trying to develop a little application using leela zero and I've run into a block.

What I do (in Java) is start leela, create a thread for reading and parsing leela output and then start to send commands. First to set up the game and then "play" commands followed by "lz-analyze" in order to get analysis from leela for further processing in my application.

This works fine, leela receives and answers commands and sends analysis data. However for every game I try to analyze after just a few opening moves leela stops answering commands and doesn't react anymore. Sometimes after 3 moves, sometimes after 4 or 5. Process is still running, no exceptions or errors thrown but nothing happens anymore.

I don't know how to debug this, if it's not a leela problem then it may be a buffering issue. I just wanted to ask if anyone can think of what could make leela stop answering commands like this or any other help really ;)

Anyway thx for the great work!

**Comment by rooklift** [comment]
I've experienced this sort of thing when attaching a stderr reader but failing to consume it, so the stderr pipe gets full.

**Comment by n0tperfect** [comment]
Sir (or Madam :)), please let me tell you that you are amazing and have made my day! Thx a lot!!!
