### ISSUE TITLE
why this test match has so many games

### ISSUE THREAD

**Issue by l1t1** [leela-zero/leela-zero#2469]
2019-08-06 16:14	
88765231  VS  a4f5d99a
498 : 425 (53.95%)	923 / 400

**Comment by roy7** [comment]
It got queued a second time by accident which broke the server into running it non-stop.

**Comment by l1t1** [comment]
http://zero.sjeng.org/match-games/5d49994890f7b57f6673eb31 and @And pointed out the net 88765231 should passed at game 708 or earlier(403), why it failed finally? https://lifein19x19.com/viewtopic.php?f=18&t=15718&sid=ccc560572e5d8e1fd0e0f64890618339&start=400
