### ISSUE TITLE
Suggesting to use net #227 as reference

### ISSUE THREAD

**Issue by Splee99** [leela-zero/leela-zero#2472]
The net #227 showed strong performance in CGOS. It's OK to me that later networks become weaker during evolution. However, I think it's better to run test matches against this reference so that we can keep track of the strength evolution.

**Comment by jillybob** [comment]
Your statements is incorrect. See : https://cloudygo.com/leela-zero-eval/eval-graphs

**Comment by Splee99** [comment]
@jillybob Please explain the result from CGOS games where #227 runs with p400. Somehow that bot vanished. It used to be stronger than 228 and 229. I'm not claiming anything. I just suggest to use a fixed reference.

**Comment by sbbdms** [comment]
Even in CGOS, Net 227 is not the strongest with 400 playouts.
http://yss-aya.com/cgos/19x19/bayes.html

LZ_232_06e0_p400 | 3708
LZ_235_a4f5_p400 | 3701
LZ_227_4872_p400 | 3689
LZ_230_a954_p400 | 3681
LZ_231_f178_p400 | 3679
LZ_234_ac9b_p400 | 3679

How did you get your conclusion?

**Comment by Splee99** [comment]
OK. Maybe I'm not so clear of my original intention of this issue. For the network 235 there was a test match against network 225. I guess that was to show how strong 235 is against the old network. I would expect that there will be similar match for the latest network. Network 227 is just a suggestion. 228 and 229 is certainly not good because they are weak both in CGOS and in Minigo test matches. We could choose other network, presumably there will be indeed such test match. It is clear to me that the network 236 is weaker than several old networks, as shown in CGOS. Do we want to run a test match? Again I don't have any conclusion as which old network is "the strongest".

**Comment by l1t1** [comment]
lz236p400 is weaker than lzelfv2p800

204	LZ_236_1d93_p400	3653

**Comment by Splee99** [comment]
I agree that the minigo test matches provide an accurate image of network strength, but I'm not sure if they will continue to run the test after lz233. The test match like 235 vs 225 is also helpful for curious people like me.
