### ISSUE TITLE
Format of Leela zero Gamestate

### ISSUE THREAD

**Issue by xz-keg** [leela-zero/leela-zero#2479]
Hi, I try to load the leela zero weight  to my pytorch model.

I read the original code carefully and succeed in loading all model parameters. I got the same output of policy and winning rate when black is about to play.

However, when white is about to play, my model begins to output ridiculous results. 

I'd like to ask about the format of game state of leela zero, thanks. 

Currently I'm using 

Channel 0~15 represents the current board state, t-1 board state ...  t-7 board state. 

Channel 16 is set to 0 when white is about to play, and 1 when black is about to play.

Channel 17 is set to 0 when black is about to play, and 1 when white is about to play.

That works well when black is about to play, but produces very bad results when white is about to play. So there must be some misunderstandings.

Thanks very much for correcting my  misunderstanding.

**Comment by lzytek** [comment]
Channel 0~7 are current side's game states. Do you by any chance fix them to black's game states?

**Comment by xz-keg** [comment]
> Channel 0~7 are current side's game states. Do you by any chance fix them to black's game states?

Thanks very much. That is exactly the reason.
