### ISSUE TITLE
Half precision by default?

### ISSUE THREAD

**Issue by lzytek** [leela-zero/leela-zero#2480]
I got a 2080 ti to play with. Ran leelaz -w weightfile --benchmark and got a little over 1000 n/s.
If I added --precision single, it will drop to around 600 n/s.
It looks leelaz is using half precision by default but in gtp logs, half precision compute is n/a.
Any idea?

**Comment by roy7** [comment]
Nvidia doesn't support half precision compute in OpenCL. That's what the message is reporting. :)

**Comment by roy7** [comment]
> --precision half

 still normally makes things faster though because half precision storage does work via OpenCL.

**Comment by lzytek** [comment]
Thank you very much roy7. That makes sense.
