### ISSUE TITLE
Tensor core speedup

### ISSUE THREAD

**Issue by ihavnoid** [leela-zero/leela-zero#2489]
Folks,

I put a patch (#2485) on the pull requests.  I am getting roughly 1150 evals/second on my RTX2080 super which is roughly 20% faster than the current next branch.

However, I would like to understand how it behaves on other Turing GPUs - especially the lower-end ones (e.g., RTX2060 Super) since they have a similar amount of memory bandwidth compared to RTX2080 et al while having less compute resource.  I suspect we are short of bandwidth rather than compute, but without the data I am not sure.

Thus, can anybody try:
 - pickup branch #2485 
 - Run the full tuner
 - Report the final tuned results along with which GPU you have?

**Comment by luckyangman** [comment]
Good work！
Improvement is very effective, simple test 2060s increased by 34%

**Comment by luckyangman** [comment]
Some test data

~$ ./leelaz-tensorcore_opt -g --gpu 3 -wbest-network
Using OpenCL batch size of 5
Using 10 thread(s).
RNG seed: 9043873809850978168
BLAS Core: built-in Eigen 3.3.7 library.
Detecting residual layers...v1...256 channels...40 blocks.
Initializing OpenCL (autodetecting precision).
Detected 1 OpenCL platforms.
Platform version: OpenCL 1.2 CUDA 10.1.120
Platform profile: FULL_PROFILE
Platform name:    NVIDIA CUDA
Platform vendor:  NVIDIA Corporation
Device ID:     0
Device name:   GeForce RTX 2060 SUPER
Device type:   GPU
Device vendor: NVIDIA Corporation
Device driver: 430.40
Device speed:  1815 MHz
Device cores:  34 CU
Device score:  1112
Device ID:     1
Device name:   GeForce RTX 2060 SUPER
Device type:   GPU
Device vendor: NVIDIA Corporation
Device driver: 430.40
Device speed:  1815 MHz
Device cores:  34 CU
Device score:  1112
Device ID:     2
Device name:   GeForce RTX 2060 SUPER
Device type:   GPU
Device vendor: NVIDIA Corporation
Device driver: 430.40
Device speed:  1815 MHz
Device cores:  34 CU
Device score:  1112
Device ID:     3
Device name:   GeForce RTX 2060 SUPER
Device type:   GPU
Device vendor: NVIDIA Corporation
Device driver: 430.40
Device speed:  1815 MHz
Device cores:  34 CU
Device score:  1112
Selected platform: NVIDIA CUDA
Selected device: GeForce RTX 2060 SUPER
with OpenCL 1.2 capability.
Half precision compute support: No.
Tensor Core support: Yes.
OpenCL: using fp16/half or tensor core compute support.
Loaded existing SGEMM tuning.
Wavefront/Warp size: 32
Max workgroup size: 1024
Max workgroup dimensions: 1024 1024 64 
Setting max tree size to 3736 MiB and cache size to 415 MiB.


netbench 6400
 6400 evaluations in  7.41 seconds -> 863 n/s

Old version 680


~$ ./leelaz-tensorcore_opt -g -wbest-network
Using OpenCL batch size of 5
Using 10 thread(s).
RNG seed: 8631404195329049747
BLAS Core: built-in Eigen 3.3.7 library.
Detecting residual layers...v1...256 channels...40 blocks.
Initializing OpenCL (autodetecting precision).
Detected 1 OpenCL platforms.
Platform version: OpenCL 1.2 CUDA 10.1.120
Platform profile: FULL_PROFILE
Platform name:    NVIDIA CUDA
Platform vendor:  NVIDIA Corporation
Device ID:     0
Device name:   Tesla V100-SXM2-16GB
Device type:   GPU
Device vendor: NVIDIA Corporation
Device driver: 430.40
Device speed:  1530 MHz
Device cores:  80 CU
Device score:  1112
Selected platform: NVIDIA CUDA
Selected device: Tesla V100-SXM2-16GB
with OpenCL 1.2 capability.
Half precision compute support: No.
Tensor Core support: Yes.
OpenCL: using fp16/half or tensor core compute support.

Started OpenCL SGEMM tuner.
Will try 560 valid configurations.
(1/560) KWG=128 KWI=2 MDIMA=16 MDIMC=16 MWG=128 NDIMB=16 NDIMC=16 NWG=128 SA=0 SB=0 STRM=0 STRN=0 TCE=1 VWM=2 VWN=2 0.8873 ms (664.7 GFLOPS)
(2/560) KWG=16 KWI=8 MDIMA=8 MDIMC=8 MWG=16 NDIMB=8 NDIMC=8 NWG=32 SA=1 SB=1 STRM=0 STRN=0 TCE=0 VWM=2 VWN=2 0.1085 ms (5434.0 GFLOPS)
(3/560) KWG=64 KWI=2 MDIMA=8 MDIMC=16 MWG=64 NDIMB=32 NDIMC=32 NWG=128 SA=0 SB=0 STRM=0 STRN=0 TCE=1 VWM=2 VWN=2 0.0404 ms (14582.3 GFLOPS)
(5/560) KWG=128 KWI=2 MDIMA=16 MDIMC=32 MWG=128 NDIMB=16 NDIMC=32 NWG=64 SA=0 SB=0 STRM=0 STRN=0 TCE=1 VWM=2 VWN=2 0.0374 ms (15780.8 GFLOPS)
(36/560) KWG=32 KWI=2 MDIMA=32 MDIMC=32 MWG=128 NDIMB=8 NDIMC=16 NWG=64 SA=0 SB=0 STRM=0 STRN=0 TCE=1 VWM=2 VWN=2 0.0346 ms (17066.7 GFLOPS)
(160/560) KWG=32 KWI=2 MDIMA=16 MDIMC=32 MWG=128 NDIMB=16 NDIMC=32 NWG=128 SA=0 SB=0 STRM=0 STRN=0 TCE=1 VWM=2 VWN=2 0.0333 ms (17723.1 GFLOPS)
Wavefront/Warp size: 32
Max workgroup size: 1024
Max workgroup dimensions: 1024 1024 64 
Setting max tree size to 3736 MiB and cache size to 415 MiB.
netbench 20000
20000 evaluations in 12.86 seconds -> 1555 n/s

~$ ./leelaz-tensorcore_opt -g -wbest-network --batchsize 10
Using OpenCL batch size of 10
Using 20 thread(s).
RNG seed: 12950391931602201003
BLAS Core: built-in Eigen 3.3.7 library.
Detecting residual layers...v1...256 channels...40 blocks.
Initializing OpenCL (autodetecting precision).
Detected 1 OpenCL platforms.
Platform version: OpenCL 1.2 CUDA 10.1.120
Platform profile: FULL_PROFILE
Platform name:    NVIDIA CUDA
Platform vendor:  NVIDIA Corporation
Device ID:     0
Device name:   Tesla V100-SXM2-16GB
Device type:   GPU
Device vendor: NVIDIA Corporation
Device driver: 430.40
Device speed:  1530 MHz
Device cores:  80 CU
Device score:  1112
Selected platform: NVIDIA CUDA
Selected device: Tesla V100-SXM2-16GB
with OpenCL 1.2 capability.
Half precision compute support: No.
Tensor Core support: Yes.
OpenCL: using fp16/half or tensor core compute support.

Started OpenCL SGEMM tuner.
Will try 560 valid configurations.
(1/560) KWG=32 KWI=2 MDIMA=16 MDIMC=16 MWG=32 NDIMB=8 NDIMC=8 NWG=64 SA=1 SB=1 STRM=0 STRN=0 TCE=0 VWM=2 VWN=2 0.1713 ms (6887.9 GFLOPS)
(2/560) KWG=32 KWI=2 MDIMA=32 MDIMC=32 MWG=64 NDIMB=8 NDIMC=8 NWG=32 SA=1 SB=1 STRM=0 STRN=0 TCE=0 VWM=2 VWN=4 0.1549 ms (7616.5 GFLOPS)
(3/560) KWG=128 KWI=2 MDIMA=16 MDIMC=16 MWG=64 NDIMB=16 NDIMC=16 NWG=32 SA=0 SB=0 STRM=0 STRN=0 TCE=1 VWM=2 VWN=2 0.0543 ms (21735.8 GFLOPS)
(45/560) KWG=64 KWI=2 MDIMA=32 MDIMC=32 MWG=128 NDIMB=8 NDIMC=8 NWG=32 SA=0 SB=0 STRM=0 STRN=0 TCE=1 VWM=2 VWN=2 0.0489 ms (24125.7 GFLOPS)
(90/560) KWG=32 KWI=2 MDIMA=32 MDIMC=32 MWG=128 NDIMB=8 NDIMC=16 NWG=128 SA=0 SB=0 STRM=0 STRN=0 TCE=1 VWM=2 VWN=2 0.0466 ms (25318.7 GFLOPS)
(121/560) KWG=32 KWI=2 MDIMA=32 MDIMC=32 MWG=128 NDIMB=8 NDIMC=32 NWG=128 SA=0 SB=0 STRM=0 STRN=0 TCE=1 VWM=2 VWN=2 0.0443 ms (26635.8 GFLOPS)
(372/560) KWG=32 KWI=2 MDIMA=16 MDIMC=32 MWG=128 NDIMB=16 NDIMC=32 NWG=128 SA=0 SB=0 STRM=0 STRN=0 TCE=1 VWM=2 VWN=2 0.0425 ms (27759.0 GFLOPS)
Wavefront/Warp size: 32
Max workgroup size: 1024
Max workgroup dimensions: 1024 1024 64 
Setting max tree size to 3736 MiB and cache size to 415 MiB.
netbench 20000 
20000 evaluations in 10.27 seconds -> 1947 n/s

~$ ./leelaz-tensorcore_opt -g -wbest-network --batchsize 16
Using OpenCL batch size of 16
Using 32 thread(s).
RNG seed: 9992918293254958299
BLAS Core: built-in Eigen 3.3.7 library.
Detecting residual layers...v1...256 channels...40 blocks.
Initializing OpenCL (autodetecting precision).
Detected 1 OpenCL platforms.
Platform version: OpenCL 1.2 CUDA 10.1.120
Platform profile: FULL_PROFILE
Platform name:    NVIDIA CUDA
Platform vendor:  NVIDIA Corporation
Device ID:     0
Device name:   Tesla V100-SXM2-16GB
Device type:   GPU
Device vendor: NVIDIA Corporation
Device driver: 430.40
Device speed:  1530 MHz
Device cores:  80 CU
Device score:  1112
Selected platform: NVIDIA CUDA
Selected device: Tesla V100-SXM2-16GB
with OpenCL 1.2 capability.
Half precision compute support: No.
Tensor Core support: Yes.
OpenCL: using fp16/half or tensor core compute support.

Started OpenCL SGEMM tuner.
Will try 560 valid configurations.
(1/560) KWG=16 KWI=2 MDIMA=16 MDIMC=16 MWG=64 NDIMB=8 NDIMC=8 NWG=32 SA=1 SB=1 STRM=0 STRN=0 TCE=0 VWM=4 VWN=2 0.2161 ms (8735.5 GFLOPS)
(2/560) KWG=64 KWI=2 MDIMA=8 MDIMC=16 MWG=32 NDIMB=32 NDIMC=32 NWG=32 SA=0 SB=0 STRM=0 STRN=0 TCE=1 VWM=2 VWN=2 0.1321 ms (14288.4 GFLOPS)
(8/560) KWG=128 KWI=2 MDIMA=16 MDIMC=32 MWG=64 NDIMB=16 NDIMC=16 NWG=32 SA=0 SB=0 STRM=0 STRN=0 TCE=1 VWM=2 VWN=2 0.1014 ms (18618.2 GFLOPS)
(14/560) KWG=128 KWI=2 MDIMA=16 MDIMC=32 MWG=128 NDIMB=16 NDIMC=16 NWG=64 SA=0 SB=0 STRM=0 STRN=0 TCE=1 VWM=2 VWN=2 0.0835 ms (22616.0 GFLOPS)
(63/560) KWG=32 KWI=2 MDIMA=16 MDIMC=32 MWG=128 NDIMB=16 NDIMC=16 NWG=128 SA=0 SB=0 STRM=0 STRN=0 TCE=1 VWM=2 VWN=2 0.0663 ms (28466.4 GFLOPS)
(133/560) KWG=32 KWI=2 MDIMA=32 MDIMC=32 MWG=128 NDIMB=8 NDIMC=8 NWG=32 SA=0 SB=0 STRM=0 STRN=0 TCE=1 VWM=2 VWN=2 0.0556 ms (33976.0 GFLOPS)
Wavefront/Warp size: 32
Max workgroup size: 1024
Max workgroup dimensions: 1024 1024 64 
Setting max tree size to 3736 MiB and cache size to 415 MiB.
netbench 20000
20000 evaluations in  9.01 seconds -> 2219 n/s
=

**Comment by ihavnoid** [comment]
Thanks for the test data!  This seems to suggest that RTX2060 Super is definitely cost-effective since it provides roughly 3/4 of an RTX2080 Super at a 40% lower price.  Maybe we can buy two RTX2060 supers instead of one RTX2080 Super.

For V100s it definitely seems we need larger batches to be effective.  Maybe we need to tweak the batch sizing algorithm?

**Comment by l1t1** [comment]
https://www.mydrivers.com/zhuanti/tianti/gpu/ Ladder chart

**Comment by wentaol** [comment]
GPU: RTX 2070
CPU: Ryzen 3700x
next: 626 nps
pr: 877 nps

EDIT: with netbench 20000 instead of 1600
next: 750
pr: 948

Nice speedup, great work!

<details><summary>Tuning and benchmark details</summary>
<p>

# next
```
./leelaz -w242.gz --full-tune --precision half
Using OpenCL batch size of 5
Using 10 thread(s).
RNG seed: 8645092481632750986
Leela Zero 0.17  Copyright (C) 2017-2019  Gian-Carlo Pascutto and contributors
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; see the COPYING file for details.

BLAS Core: built-in Eigen 3.3.7 library.
Detecting residual layers...v1...256 channels...40 blocks.
Initializing OpenCL (half precision).
Detected 1 OpenCL platforms.
Platform version: OpenCL 1.2 CUDA 10.1.120
Platform profile: FULL_PROFILE
Platform name:    NVIDIA CUDA
Platform vendor:  NVIDIA Corporation
Device ID:     0
Device name:   GeForce RTX 2070
Device type:   GPU
Device vendor: NVIDIA Corporation
Device driver: 430.50
Device speed:  1620 MHz
Device cores:  36 CU
Device score:  1112
Selected platform: NVIDIA CUDA
Selected device: GeForce RTX 2070
with OpenCL 1.2 capability.
Half precision compute support: No.
Tensor Core support: Yes.

Started OpenCL SGEMM tuner.
Will try 5745 valid configurations.
(1/5745) KWG=16 KWI=2 MDIMA=32 MDIMC=32 MWG=256 NDIMB=8 NDIMC=64 NWG=64 SA=0 SB=1 STRM=0 STRN=0 TCE=1 VWM=2 VWN=4 0.2833 ms (2082.1 GFLOPS)
(3/5745) KWG=32 KWI=2 MDIMA=8 MDIMC=16 MWG=64 NDIMB=8 NDIMC=8 NWG=16 SA=1 SB=1 STRM=1 STRN=0 TCE=0 VWM=2 VWN=2 0.2796 ms (2109.7 GFLOPS)
(7/5745) KWG=16 KWI=2 MDIMA=16 MDIMC=8 MWG=32 NDIMB=16 NDIMC=16 NWG=64 SA=0 SB=0 STRM=1 STRN=1 TCE=0 VWM=1 VWN=4 0.2685 ms (2196.8 GFLOPS)
(8/5745) KWG=32 KWI=2 MDIMA=16 MDIMC=32 MWG=64 NDIMB=16 NDIMC=32 NWG=32 SA=1 SB=1 STRM=0 STRN=0 TCE=1 VWM=8 VWN=4 0.2375 ms (2483.3 GFLOPS)
(11/5745) KWG=16 KWI=2 MDIMA=16 MDIMC=8 MWG=64 NDIMB=32 NDIMC=8 NWG=32 SA=0 SB=1 STRM=0 STRN=1 TCE=0 VWM=2 VWN=1 0.2265 ms (2603.8 GFLOPS)
(14/5745) KWG=16 KWI=2 MDIMA=16 MDIMC=32 MWG=64 NDIMB=16 NDIMC=8 NWG=64 SA=1 SB=1 STRM=1 STRN=0 TCE=0 VWM=2 VWN=2 0.1766 ms (3339.6 GFLOPS)
(17/5745) KWG=32 KWI=2 MDIMA=16 MDIMC=32 MWG=128 NDIMB=16 NDIMC=16 NWG=32 SA=0 SB=1 STRM=0 STRN=0 TCE=1 VWM=2 VWN=4 0.1343 ms (4393.0 GFLOPS)
(77/5745) KWG=16 KWI=8 MDIMA=8 MDIMC=16 MWG=64 NDIMB=32 NDIMC=8 NWG=64 SA=1 SB=1 STRM=1 STRN=0 TCE=0 VWM=4 VWN=2 0.1278 ms (4614.6 GFLOPS)
(154/5745) KWG=32 KWI=2 MDIMA=32 MDIMC=32 MWG=256 NDIMB=8 NDIMC=8 NWG=32 SA=0 SB=1 STRM=0 STRN=0 TCE=1 VWM=2 VWN=4 0.1251 ms (4713.2 GFLOPS)
(317/5745) KWG=16 KWI=8 MDIMA=16 MDIMC=16 MWG=64 NDIMB=8 NDIMC=8 NWG=64 SA=1 SB=1 STRM=1 STRN=1 TCE=0 VWM=4 VWN=8 0.1232 ms (4786.3 GFLOPS)
(811/5745) KWG=32 KWI=2 MDIMA=32 MDIMC=64 MWG=256 NDIMB=8 NDIMC=8 NWG=32 SA=0 SB=1 STRM=0 STRN=0 TCE=1 VWM=2 VWN=8 0.1227 ms (4807.5 GFLOPS)
(1018/5745) KWG=64 KWI=2 MDIMA=8 MDIMC=8 MWG=32 NDIMB=32 NDIMC=32 NWG=64 SA=0 SB=0 STRM=0 STRN=0 TCE=1 VWM=2 VWN=2 0.1187 ms (4970.9 GFLOPS)
(1619/5745) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=64 NDIMB=32 NDIMC=32 NWG=64 SA=0 SB=0 STRM=0 STRN=0 TCE=1 VWM=2 VWN=2 0.0980 ms (6021.1 GFLOPS)
(5265/5745) KWG=32 KWI=2 MDIMA=16 MDIMC=32 MWG=256 NDIMB=16 NDIMC=32 NWG=64 SA=0 SB=0 STRM=0 STRN=0 TCE=1 VWM=2 VWN=2 0.0966 ms (6107.9 GFLOPS)

./leelaz -g -w242.gz --precision half
Using OpenCL batch size of 5
Using 10 thread(s).
RNG seed: 17413446790566132489
BLAS Core: built-in Eigen 3.3.7 library.
Detecting residual layers...v1...256 channels...40 blocks.
Initializing OpenCL (half precision).
Detected 1 OpenCL platforms.
Platform version: OpenCL 1.2 CUDA 10.1.120
Platform profile: FULL_PROFILE
Platform name:    NVIDIA CUDA
Platform vendor:  NVIDIA Corporation
Device ID:     0
Device name:   GeForce RTX 2070
Device type:   GPU
Device vendor: NVIDIA Corporation
Device driver: 430.50
Device speed:  1620 MHz
Device cores:  36 CU
Device score:  1112
Selected platform: NVIDIA CUDA
Selected device: GeForce RTX 2070
with OpenCL 1.2 capability.
Half precision compute support: No.
Tensor Core support: Yes.
Loaded existing SGEMM tuning.
Wavefront/Warp size: 32
Max workgroup size: 1024
Max workgroup dimensions: 1024 1024 64 
Setting max tree size to 3736 MiB and cache size to 415 MiB.
netbench
 1600 evaluations in  2.55 seconds -> 626 n/s
```


# PR

```
 ./leelaz -w242.gz --full-tune --precision half
Using OpenCL batch size of 5
Using 10 thread(s).
RNG seed: 15476701200427605817
Leela Zero 0.17  Copyright (C) 2017-2019  Gian-Carlo Pascutto and contributors
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; see the COPYING file for details.

BLAS Core: built-in Eigen 3.3.7 library.
Detecting residual layers...v1...256 channels...40 blocks.
Initializing OpenCL (half precision).
Detected 1 OpenCL platforms.
Platform version: OpenCL 1.2 CUDA 10.1.120
Platform profile: FULL_PROFILE
Platform name:    NVIDIA CUDA
Platform vendor:  NVIDIA Corporation
Device ID:     0
Device name:   GeForce RTX 2070
Device type:   GPU
Device vendor: NVIDIA Corporation
Device driver: 430.50
Device speed:  1620 MHz
Device cores:  36 CU
Device score:  1112
Selected platform: NVIDIA CUDA
Selected device: GeForce RTX 2070
with OpenCL 1.2 capability.
Half precision compute support: No.
Tensor Core support: Yes.

Started OpenCL SGEMM tuner.
Will try 6526 valid configurations.
(1/6526) KWG=16 KWI=8 MDIMA=16 MDIMC=8 MWG=64 NDIMB=16 NDIMC=8 NWG=64 SA=1 SB=1 STRM=1 STRN=0 TCE=0 VWM=4 VWN=1 0.1617 ms (3646.7 GFLOPS)
(2/6526) KWG=128 KWI=2 MDIMA=8 MDIMC=32 MWG=128 NDIMB=32 NDIMC=64 NWG=64 SA=0 SB=0 STRM=0 STRN=0 TCE=1 VWM=2 VWN=2 0.1219 ms (4836.8 GFLOPS)
(89/6526) KWG=32 KWI=2 MDIMA=16 MDIMC=16 MWG=64 NDIMB=16 NDIMC=64 NWG=128 SA=0 SB=1 STRM=0 STRN=0 TCE=1 VWM=2 VWN=4 0.1095 ms (5385.1 GFLOPS)
(144/6526) KWG=32 KWI=2 MDIMA=16 MDIMC=32 MWG=256 NDIMB=16 NDIMC=16 NWG=64 SA=1 SB=0 STRM=0 STRN=0 TCE=1 VWM=8 VWN=2 0.0802 ms (7353.7 GFLOPS)
(371/6526) KWG=32 KWI=2 MDIMA=16 MDIMC=32 MWG=256 NDIMB=16 NDIMC=32 NWG=128 SA=0 SB=1 STRM=0 STRN=0 TCE=1 VWM=2 VWN=8 0.0699 ms (8440.5 GFLOPS)
(1289/6526) KWG=64 KWI=2 MDIMA=32 MDIMC=64 MWG=256 NDIMB=8 NDIMC=16 NWG=128 SA=0 SB=1 STRM=0 STRN=0 TCE=1 VWM=2 VWN=8 0.0675 ms (8739.7 GFLOPS)
(1353/6526) KWG=32 KWI=2 MDIMA=8 MDIMC=16 MWG=256 NDIMB=32 NDIMC=32 NWG=64 SA=0 SB=0 STRM=0 STRN=0 TCE=1 VWM=2 VWN=2 0.0640 ms (9220.6 GFLOPS)
(2614/6526) KWG=32 KWI=2 MDIMA=32 MDIMC=64 MWG=256 NDIMB=8 NDIMC=16 NWG=128 SA=0 SB=0 STRM=0 STRN=0 TCE=1 VWM=2 VWN=2 0.0592 ms (9960.6 GFLOPS)
(4404/6526) KWG=32 KWI=2 MDIMA=16 MDIMC=16 MWG=128 NDIMB=16 NDIMC=32 NWG=128 SA=0 SB=0 STRM=0 STRN=0 TCE=1 VWM=2 VWN=2 0.0588 ms (10033.8 GFLOPS)
(5535/6526) KWG=64 KWI=2 MDIMA=32 MDIMC=32 MWG=128 NDIMB=8 NDIMC=8 NWG=64 SA=0 SB=0 STRM=0 STRN=0 TCE=1 VWM=2 VWN=2 0.0587 ms (10048.8 GFLOPS)

./leelaz -g -w242.gz --precision half
Using OpenCL batch size of 5
Using 10 thread(s).
RNG seed: 14191827683092889313
BLAS Core: built-in Eigen 3.3.7 library.
Detecting residual layers...v1...256 channels...40 blocks.
Initializing OpenCL (half precision).
Detected 1 OpenCL platforms.
Platform version: OpenCL 1.2 CUDA 10.1.120
Platform profile: FULL_PROFILE
Platform name:    NVIDIA CUDA
Platform vendor:  NVIDIA Corporation
Device ID:     0
Device name:   GeForce RTX 2070
Device type:   GPU
Device vendor: NVIDIA Corporation
Device driver: 430.50
Device speed:  1620 MHz
Device cores:  36 CU
Device score:  1112
Selected platform: NVIDIA CUDA
Selected device: GeForce RTX 2070
with OpenCL 1.2 capability.
Half precision compute support: No.
Tensor Core support: Yes.
Loaded existing SGEMM tuning.
Wavefront/Warp size: 32
Max workgroup size: 1024
Max workgroup dimensions: 1024 1024 64 
Setting max tree size to 3736 MiB and cache size to 415 MiB.
netbench     
 1600 evaluations in  1.82 seconds -> 877 n/s
```
</p>
</details>

**Comment by ihavnoid** [comment]
Closed due to code merged into next branch
