### ISSUE TITLE
How is size upgrade being made?

### ISSUE THREAD

**Issue by jborbik** [leela-zero/leela-zero#2495]
This is not actually an issue, but I wanted to ask a question for clarification, I hope that's fine. 

I wanted to ask what is the method which you use to upgrade the network size for example from 10x128 to 15x192? How can you transfer the weights between models of different architecture and avoid huge degradation of ELO when switching to new network?

I was trying to get this information from AlphaZero paper, but it seems, that they are using constant network size of either 20 or 40 if I understand correctly.

Thank you for the clarification!

**Comment by l1t1** [comment]
https://arxiv.org/abs/1511.05641

**Comment by jborbik** [comment]
You are a hero, thank you!

So you (LeelaZero authors) came up with the idea to transfer the knowledge between different networks, in the original AlphaZero work the neural networks of size 20 and 40 were trained separately from scratch? Do you know something about it?

**Comment by zediir** [comment]
See https://github.com/leela-zero/leela-zero/issues/648

**Comment by jborbik** [comment]
Thanks a lot!
