### ISSUE TITLE
Can I Reduce startup time? 

### ISSUE THREAD

**Issue by xiaominghe2014** [leela-zero/leela-zero#2512]
Now it took twenty seconds，It takes too long

**Comment by xiaominghe2014** [comment]
the startup command is "leelaz  -g -t 1 -p 1 --noponder"

**Comment by l1t1** [comment]
use smaller net, such as lz 157

**Comment by xiaominghe2014** [comment]
> use smaller net, such as lz 157

Many thanks，It's very effective

**Comment by xpxpxpLilac** [comment]
Is it possible to have your contact, I'm a university student working on this and looking for someone to figure out what's happening in here. Thanks!
