### ISSUE TITLE
optimize training

### ISSUE THREAD

**Issue by xpxpxpLilac** [leela-zero/leela-zero#2513]
Hi there, I'm a software engineering student who is working on a thesis project to optimize alphago zero based on leela zero. I've learnt the principles of alphago zero but when came the code, I cannot tell where to start.  Our project is meant to simplify the gameboard to 9*9, so how to configure that? Furthermore, we want to upgrade Monte Carlo tree search to our optimized version, where can we find the corresponding code? If we only want to change MCTS, is there anywhere related we also have to reconfigure?

Thanks so much for any useful response!

**Comment by jillybob** [comment]
I'd recommend using KataGo rather than Leela Zero. You get much faster results

**Comment by xpxpxpLilac** [comment]
To get a quick preview, what is the biggest difference between this one and leela zero?

**Comment by xpxpxpLilac** [comment]
> I'd recommend using KataGo rather than Leela Zero. You get much faster results

To get a quick preview, what is the biggest difference between this one and leela zero?

**Comment by iopq** [comment]
> > I'd recommend using KataGo rather than Leela Zero. You get much faster results
> To get a quick preview, what is the biggest difference between this one and leela zero?

https://arxiv.org/abs/1902.10565
