### ISSUE TITLE
a bad self-play game was uploaded

### ISSUE THREAD

**Issue by l1t1** [leela-zero/leela-zero#2518]
only 30 moves

Self-Play Hash | Network | Winner | Move Count | Started | Duration | Download | Client | Version
-- | -- | -- | -- | -- | -- | -- | -- | --
b22e4bbd4d639cde1273c963d4ec4c67 | e76d365d | white | 30 | 24.4 minutes ago | 3.1 minutes | sgf | 42 | 18

http://zero.sjeng.org/view/b22e4bbd4d639cde1273c963d4ec4c67398a9d67bb81dcd42c009d87c7beacd0?viewer=wgo

http://zero.sjeng.org/view/b22e4bbd4d639cde1273c963d4ec4c67398a9d67bb81dcd42c009d87c7beacd0.sgf

**Comment by Ishinoshita** [comment]
@l1t1 That game does not seems to me as obviously fake. That may just be 'luck' that, with -m 30, picked twice in a row 'pass' move. I had observed that once in a while, in the past. Even found 20 moves game, with 'normal' training data attached.

**Comment by l1t1** [comment]
there is a minimal 92 moves limit

**Comment by Ishinoshita** [comment]
This limit applies to resign threshold only.
There is no mechanism to prevent randomness to pick two consecutive pass moves. Though pass move has very low policy in early phase of the game, it is non-zero and can be picked by uniform sampling.
