### ISSUE TITLE
Build in Raspberry Pi4,runnning test failed.

### ISSUE THREAD

**Issue by kppomzh** [leela-zero/leela-zero#2521]
Compile steps in accordance like Ubuntu steps.

Exception message is :
Running main() from gtest_main.cc
[==========] Running 13 tests from 2 test cases.
[----------] Global test environment set-up.
BLAS Core: built-in Eigen 3.3.7 library.
Detecting residual layers...v1...8 channels...1 blocks.
Initializing OpenCL (autodetecting precision).
OpenCL: clGetPlatformIDs
unknown file: Failure
C++ exception with description "clGetPlatformIDs" thrown in auxiliary test code (environments or event listeners).

**Comment by l1t1** [comment]
similar with error on android

**Comment by kppomzh** [comment]
> similar with error on android

I know how to start it on Raspberry.
