### ISSUE TITLE
Custom live Linux for pendrive?

### ISSUE THREAD

**Issue by Marcin1960** [leela-zero/leela-zero#255]
Could someone make a small bootable ISO image that could be burned into pendrive
with all set for the Leela Zero project. With persistent data, browser and appropriate tools?

Perhaps 100MB would be enough? That way anyone could download boot any computer
and run the project stuff?

**Comment by Marcin1960** [comment]
I could burn a few USB drives and distribute them to friends working in IT. They could boot some PCs overnight or weekends. Also I could post the image  on torrent sites.

One utility would be nice to display progress and stats during processing, and most important to update Leela Zero binaries, either on demand or automatically.

I guess ISO image could be less than 50MB, preferably loadable into RAM.

**Comment by ggPeti** [comment]
Good idea, I will be on this tonight.

**Comment by jpetrich** [comment]
I'd be interested in helping with this. What about using Docker Machine?
