### ISSUE TITLE
some changes need to be done

### ISSUE THREAD

**Issue by l1t1** [leela-zero/leela-zero#2559]
increae visits, increase size of weight, force promote etc

**Comment by l1t1** [comment]
@bubblesld could you do a test?

**Comment by bubblesld** [comment]
what to test?
1. I do not have resource to generate enough selfplay games with larger visits
2. I do not have a larger size of weight which is stronger.
3. force promote? I do not have this power.

**Comment by l1t1** [comment]
maybe you could set a server to receive selfplay games, just like sai.unich.it did

**Comment by bubblesld** [comment]
No, I won't. Too much for me.
