### ISSUE TITLE
Learning possible improvement

### ISSUE THREAD

**Issue by athaa** [leela-zero/leela-zero#2568]
Hello 

If I'm correct, the NN currently learn chess aiming for mate. Could we make a modification to make the NN aiming for winning engame TB position ? 
What I mean is to add to the NN chess rules, that a a winning engame TB position is a gain (like mate).

It will surely slow down the learning curve but we should reach a better level on the long term (and probably a less aggressive style of play).
Not sure it will follow the zero knowledge philosophy of leela-zero though.

Sorry if this has already been discuss.

**Comment by roy7** [comment]
HI there, this is actually the github for the Go AI not Chess. The Chess github is over at https://github.com/LeelaChessZero/lc0. 

I like this idea myself and suggested it on LC0 discord once upon a time, but the general response seemed to be that it'd violate 'zero' approach and that learning how to capture/win might help other aspects of play vs simply learning to get to a winning tablebase position.

Still you might add the issue for discussion over in their github though. :)

**Comment by athaa** [comment]
...
One more time, I confuse the two projects.
Thx for the rapid and informative reply.
