### ISSUE TITLE
Leela Zero, Sabaki and LizGoban on RaspberryPi 4 

### ISSUE THREAD

**Issue by Dorin1972** [leela-zero/leela-zero#2569]
I managed to install Leela Zero on RPi4 - 4Gb with Raspbian Buster, and it run pretty well.  With the following setting for leelaz: `--gtp -w 40b.gz --noponder -p 3200 -timemanage off` it took aprox 40 sec. for a move.
So:
1. Install NodeJS
`
curl -sL https://deb.nodesource.com/setup_13.x | sudo bash -
sudo apt install nodejs
`
2. Install LeelaZero
`
cd ~
sudo apt install clinfo && clinfo
git clone https://github.com/leela-zero/leela-zero
cd leela-zero
git submodule update --init --recursive
sudo apt install cmake g++ libboost-dev libboost-program-options-dev libboost-filesystem-dev opencl-headers ocl-icd-libopencl1 ocl-icd-opencl-dev zlib1g-dev
mkdir build && cd build
cmake -DUSE_CPU_ONLY=1 ..
cmake --build .
`
3. Install Sabaki
`
cd ~
git clone https://github.com/SabakiHQ/Sabaki
cd Sabaki
npm install
npm run build
npm start
`
4. Install LizGoban
`
cd ~
git clone https://github.com/kaorahi/lizgoban
cd lizgoban
npm install
npm start
`
5. Copy to lizgoban/external directory, leelaz executable and network.gz weights file...

I tried before as gui quarry and kigo but I had issues with them (exits unexpectedly)

**Comment by Terkwood** [comment]
Nicely done, and thanks for the write-up!
