### ISSUE TITLE
Both single precision and half precision failed to run.

### ISSUE THREAD

**Issue by bvandenbon** [leela-zero/leela-zero#2574]
ZBaduk installs and runs leela zero on several servers every day.
But about 2 hours ago, I detected the following problem:

    Detected 1 OpenCL platforms.
    Platform version: OpenCL 1.2 CUDA 10.1.120
    Platform profile: FULL_PROFILE
    Platform name:    NVIDIA CUDA
    Platform vendor:  NVIDIA Corporation
    Device ID:     0
    Device name:   GeForce GTX 1080 Ti
    Device type:   GPU
    Device vendor: NVIDIA Corporation
    Device driver: 430.64
    Device speed:  1582 MHz
    Device cores:  28 CU
    Device score:  1112
    Selected platform: NVIDIA CUDA
    Selected device: GeForce GTX 1080 Ti
    with OpenCL 1.2 capability.
    Half precision compute support: No.
    Tensor Core support: No.
    
    Started OpenCL SGEMM tuner.
    Will try 290 valid configurations.
    Failed to compile: 290 kernels.
    Failed to find a working configuration.
    Check your OpenCL drivers.
    Minimum error: 100.000000. Error bound: 0.000100
    
    Started OpenCL SGEMM tuner.
    Will try 290 valid configurations.
    Failed to compile: 290 kernels.
    Failed to find a working configuration.
    Check your OpenCL drivers.
    Minimum error: 100.000000. Error bound: 0.100000
    Both single precision and half precision failed to run.
    terminate called after throwing an instance of 'std::runtime_error'
      what():  Failed to initialize net.
    Aborted (core dumped)

I tried with the master branche of leela zero, and with some of the previous ones.
I also tried with different network files.
And I tried updating the opencl drivers, but it's already the latest.

If I run `clinfo` :

    Number of platforms                               1
      Platform Name                                   NVIDIA CUDA
      Platform Vendor                                 NVIDIA Corporation
      Platform Version                                OpenCL 1.2 CUDA 10.1.120
      Platform Profile                                FULL_PROFILE
      Platform Extensions                             cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_k$
      Platform Extensions function suffix             NV
    
      Platform Name                                   NVIDIA CUDA
    Number of devices                                 1
      Device Name                                     GeForce GTX 1080 Ti
      Device Vendor                                   NVIDIA Corporation
      Device Vendor ID                                0x10de
      Device Version                                  OpenCL 1.2 CUDA
      Driver Version                                  430.64
      Device OpenCL C Version                         OpenCL C 1.2
      Device Type                                     GPU
      Device Topology (NV)                            PCI-E, 02:00.0
      Device Profile                                  FULL_PROFILE
      Device Available                                Yes
      Compiler Available                              Yes
      Linker Available                                Yes
      Max compute units                               28
      Max clock frequency                             1582MHz
      Compute Capability (NV)                         6.1
      Device Partition                                (core)
        Max number of sub-devices                     1
        Supported partition types                     None
      Max work item dimensions                        3
      Max work item sizes                             1024x1024x64
      Max work group size                             1024
      Preferred work group size multiple              <getWGsizes:675: build program : error -11>
     Warp size (NV)                                  32
      Preferred / native vector sizes
        char                                                 1 / 1
        short                                                1 / 1
        int                                                  1 / 1
        long                                                 1 / 1
        half                                                 0 / 0        (n/a)
        float                                                1 / 1
        double                                               1 / 1        (cl_khr_fp64)
      Half-precision Floating-point support           (n/a)
      Single-precision Floating-point support         (core)
        Denormals                                     Yes
        Infinity and NANs                             Yes
        Round to nearest                              Yes
        Round to zero                                 Yes
        Round to infinity                             Yes
        IEEE754-2008 fused multiply-add               Yes
        Support is emulated in software               No
        Correctly-rounded divide and sqrt operations  Yes
      Double-precision Floating-point support         (cl_khr_fp64)
        Denormals                                     Yes
        Infinity and NANs                             Yes
        Round to nearest                              Yes
        Round to zero                                 Yes
        Round to infinity                             Yes
        IEEE754-2008 fused multiply-add               Yes
        Support is emulated in software               No
      Address bits                                    64, Little-Endian
      Global memory size                              11721506816 (10.92GiB)
      Error Correction support                        No
      Max memory allocation                           2930376704 (2.729GiB)
    Unified memory for Host and Device              No
      Integrated memory (NV)                          No
      Minimum alignment for any data type             128 bytes
      Alignment of base address                       4096 bits (512 bytes)
      Global Memory cache type                        Read/Write
      Global Memory cache size                        458752 (448KiB)
      Global Memory cache line size                   128 bytes
      Image support                                   Yes
        Max number of samplers per kernel             32
        Max size for 1D images from buffer            134217728 pixels
        Max 1D or 2D image array size                 2048 images
        Max 2D image size                             16384x32768 pixels
        Max 3D image size                             16384x16384x16384 pixels
        Max number of read image args                 256
        Max number of write image args                16
      Local memory type                               Local
      Local memory size                               49152 (48KiB)
      Registers per block (NV)                        65536
      Max number of constant args                     9
      Max constant buffer size                        65536 (64KiB)
      Max size of kernel argument                     4352 (4.25KiB)
      Queue properties
        Out-of-order execution                        Yes
        Profiling                                     Yes
      Prefer user sync for interop                    No
      Profiling timer resolution                      1000ns
      Execution capabilities
        Run OpenCL kernels                            Yes
        Run native kernels                            No
        Kernel execution timeout (NV)                 No
      Concurrent copy and kernel execution (NV)       Yes
        Number of async copy engines                  2
      printf() buffer size                            1048576 (1024KiB)
      Built-in kernels
      Device Extensions                               cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_k$
    
    NULL platform behavior
      clGetPlatformInfo(NULL, CL_PLATFORM_NAME, ...)  NVIDIA CUDA
      clGetDeviceIDs(NULL, CL_DEVICE_TYPE_ALL, ...)   Success [NV]
      clCreateContext(NULL, ...) [default]            Success [NV]
      clCreateContextFromType(NULL, CL_DEVICE_TYPE_DEFAULT)  No platform
      clCreateContextFromType(NULL, CL_DEVICE_TYPE_CPU)  No devices found in platform
      clCreateContextFromType(NULL, CL_DEVICE_TYPE_GPU)  No platform
      clCreateContextFromType(NULL, CL_DEVICE_TYPE_ACCELERATOR)  No devices found in platform
      clCreateContextFromType(NULL, CL_DEVICE_TYPE_CUSTOM)  Invalid device type for platform
      clCreateContextFromType(NULL, CL_DEVICE_TYPE_ALL)  No platform
    
    ICD loader properties
      ICD loader Name                                 OpenCL ICD Loader
      ICD loader Vendor                               OCL Icd free software
      ICD loader Version                              2.2.11
      ICD loader Profile                              OpenCL 2.1

The `NULL platform behavior` error does seem to indicate that there's something wrong with the opencl driver, right ?
Any ideas ?

(PS: I have been encountering this issue on multiple servers.)

**Comment by bvandenbon** [comment]
I guess it's more of a driver issue than anything else.

**Comment by bvandenbon** [comment]
I was having this issue more and more on multiple servers, and I started blacklisting some of the providers. But as the problem grew bigger something had to be done.

The server is installed from a docker image: `nvidia/opencl` , which is an Ubuntu 18.04.1 LTS

So, I started comparing clinfo output of different systems (good ones and bad ones).
And I noticed that actually the problem is this line:

     Preferred work group size multiple              <getWGsizes:675: build program : error -11>

Similar buglogs on the internet pointed towards a dependency issue with the glibc libraries, but I am not sure if this is relevant at all. Anyway, those people debugged it as follows: I ran the `export LD_DEBUG=libs` prior to running `clinfo`.
(Afterwards turn it off with `export LD_DEBUG=`)

Here are some of the errors that I spotted:

```
calling init: /usr/lib/x86_64-linux-gnu/libnvidia-opencl.so.1
      9198:
      9198:     /usr/lib/x86_64-linux-gnu/libnvidia-opencl.so.1: error: symbol lookup error: undefined symbol: clIcdGetPlatformIDsKH
R (fatal)
      9198:     clinfo: error: symbol lookup error: undefined symbol: pthread_setaffinity_np (fatal)
      9198:     clinfo: error: symbol lookup error: undefined symbol: pthread_getaffinity_np (fatal)
      9198:     find library=libcuda.so.1 [0]; searching
      9198:      search cache=/etc/ld.so.cache
      9198:       trying file=/usr/lib/x86_64-linux-gnu/libcuda.so.1
      ...
=== CL_PROGRAM_BUILD_LOG ===                                                                                                       
      9198:     clinfo: error: symbol lookup error: undefined symbol: clSetProgramSpecializationConstant (fatal)
```

So, I checked the existence of the `libnvidia-opencl.so.1` file, which seems in order:
There is a symbolic link to the correct lib, both in the folder.
```
root@C.460079:~$ ls -la /usr/lib/x86_64-linux-gnu/ | grep opencl
lrwxrwxrwx  1 root root       26 Jan 24 15:44 libnvidia-opencl.so.1 -> libnvidia-opencl.so.430.64
-rw-r--r--  1 root root 28744872 Oct 27 11:27 libnvidia-opencl.so.430.64
```

And that's where I am stuck.

However, as a solution, I forbid suppliers to offer me driver version 430.64 , which seems to be present at several systems with errors. (perhaps even all).

**Comment by roy7** [comment]
I tried searching the error messages, wasn't too useful but I did find on your " undefined symbol: clSetProgramSpecializationConstant" portion of the problems an answer at https://github.com/KhronosGroup/OpenCL-CTS/issues/165. This symbol is from OpenCL 2.2, it isn't present in 2.1 and I see from your clinfo above you have OpenCL 2.1.

So if nothing else, you should look for a newer OpenCL 2.2 package to update to and try again?

**Comment by roy7** [comment]
I notice my Manjaro (Arch) machine doesn't print anything about ICD in clinfo. Maybe we use different opencl libraries. Googling around for Ubuntu and OpenCL 2.2 I see someone suggest what should be installed is "sudo apt install ocl-icd-* opencl-headers" and I see from https://github.com/OCL-dev/ocl-icd that 2.2 support was added ~3 years ago.

On my personal machine for AI stuff under Manjaro, I have:

> [roy@ryzen-one ~]$ pacman -Q | grep opencl
> opencl-headers 2:2.2.20170516-2
> opencl-nvidia-430xx 430.64-1
> [roy@ryzen-one ~]$ pacman -Q | grep icd
> ocl-icd 2.2.12-3
> vulkan-icd-loader 1.1.127-1
> [roy@ryzen-one ~]$ pacman -Q | grep nvidia
> linux414-nvidia-430xx 430.64-2
> mhwd-nvidia-304xx 1:304.137-1
> mhwd-nvidia-340xx 340.107-1
> mhwd-nvidia-390xx 390.132-1
> mhwd-nvidia-418xx 418.113-1
> mhwd-nvidia-430xx 430.64-1
> mhwd-nvidia-435xx 435.21-1
> mhwd-nvidia-440xx 440.31-1
> nvidia-430xx-utils 430.64-1
> opencl-nvidia-430xx 430.64-1
> [roy@ryzen-one ~]$ pacman -Q | grep cuda
> cuda 10.1.243-2
