### ISSUE TITLE
Leela Zero has Retire

### ISSUE THREAD

**Issue by Google9876** [leela-zero/leela-zero#2578]
Leela Zero has Retire,
China Leela Zero is going to join Katago.
Leela Zero,Thank you .
gcp @gcp ,Thank you .
Leela Zero is algorithmically behind Katago.

**Comment by kennyfs** [comment]
Do you train a new network yourself, or do you have a training program like this(g170)?

**Comment by Google9876** [comment]
No, I plan to help katago to improve (not necessarily) I personally like to do ai test and ai match

**Comment by Google9876** [comment]
What is your g170?

**Comment by kennyfs** [comment]
katago official third run.

**Comment by Grant-Tao** [comment]
Is this an official announcement? @Google9876

**Comment by Google9876** [comment]
Yes @Grant-Tao

**Comment by Google9876** [comment]
It was officially told me @Grant-Tao

**Comment by ataoister** [comment]
@Google9876 It's none of your business.
LZ is still training.

**Comment by Google9876** [comment]
@ataoister    No, Leela Zero is retiring this year

**Comment by Google9876** [comment]
@ataoister  You do n’t want to comment

**Comment by Google9876** [comment]
@ataoister  Don't mess around

**Comment by zyrf-cl** [comment]
You don't have to say anything. LZ's going on

**Comment by kennyfs** [comment]
Yes, it seems that Chinese people is still producing many games during the daytime.
@Google9876 Can you explain what do you mean again?(We are not messing around, but you.)

**Comment by kennyfs** [comment]
And what is your official?

**Comment by Google9876** [comment]
China Leela Zero officials told me: This year will be retired. Weights may be trained up to 270-290 and will join Katago after retirement

**Comment by zyrf-cl** [comment]
No，LeelaZero never stop

**Comment by Fan-Mi** [comment]
@Google9876 China doesn't even have something named "China Leela Zero official". Which group exactly are you talking about?

**Comment by Google9876** [comment]
![IMG_20200229_073349](https://user-images.githubusercontent.com/60776843/75595347-ed54bf00-5ac6-11ea-9dc7-b2c03f359cc2.png)

Can speak to them in Chinese and English, they don't understand! They just look at it now. This is what Leela Zero told me. No one believes it. I have to use pictures!

**Comment by Google9876** [comment]
the second one
![IMG_20200229_074522](https://user-images.githubusercontent.com/60776843/75595547-d793c980-5ac7-11ea-86b5-8e45b2bc6a58.png)

**Comment by Google9876** [comment]
the second one
![IMG_20200229_074908](https://user-images.githubusercontent.com/60776843/75595600-04e07780-5ac8-11ea-9e47-e129b22a628b.png)

**Comment by Google9876** [comment]
If you still do n’t believe it, then I ca n’t help it. Later, when you see Leela Zero really retired (this year), you will be sad that day!

**Comment by zyrf-cl** [comment]
He can't represent the author, and we are not interested in katago。

**Comment by Grant-Tao** [comment]
Very interesting. A guy with no business in LZ declared the death of LZ, and the owner of the business has been quiet.

**Comment by Celasca** [comment]
I'm just among the community of LZ in China and I won't stop running LZ at least at present. And neither there is such a thing called "China Leela Zero", nor anyone can represent the whole community of LZ in China. Whether Katago is advanced or not has nothing to do with LZ running itself. The only one that can stop LZ running is gcp himself. So take a look at what you have said, "Leela Zero has Retire" sounds absurd.
It's even more absurd that you come here trying to spread fake news created by yourself after gcp decided not to stop running LZ which made many people felt relieved (at least I am).
If you don't understand anything please stop saying stupid things here and messing up around. LZ is none of your business.
And maybe someone can close this issue which is the most absurd one in LZ history.

**Comment by kennyfs** [comment]
As https://github.com/leela-zero/leela-zero/issues/2560 said, LZ will stop training when the games of the best net reaches 750k.  So maybe he and his friend is talking about that it may stop this year(only their prediction), but they added much unnecessary guess. And I also think "LZ has retired" is too much.  Maybe his English is not so good because he is a Chinese.  I think he mean "Will retire soon"

I'm just commenting in order to stop this absurd issue. I think we must have some misunderstandings between each other.

**Comment by Celasca** [comment]
As a Chinese myself, I can read what is in those pictures. The one who had conversation with him comes from one of QQ groups with most of contributors from China (I'm just in one of those groups). He said many of them knew that LZ was going to stop running (at that time) and some of them had lost interest and want to switch to Kata.

**Comment by Blossomstripe** [comment]
These are the translations of the two screenshots by @Google9876 (sorry for my English level)

Pic. 1:
> 1. When will LZ retire is not sure, but it'll hardly get the 300th weight. Probably training will stop before the 280th weight is generated. 
> 2. The main leader of this project gcp is a European, and he's more interested in chess. He used to think that it'll be great to run to 6b(?), but he fell into it deeply and that's how LZ was created. Now gcp doesn't care about Go AI and it's hard to contact with him.
> 3. KataGo doesn't have a CPU version, so you cannot load it. I recommend you to buy NVIDIA 20 series to get a better experience (not advertising!)
> 4. (Answering a personal question)
> 5. LZ has a poorer algorithm than KataGo, so it's unavoidable that it will be surpassed.

Pic. 2:

> Some of us are not interested in chess, so we may part accompany with the creator.

> I cannot judge when LZ will retire. Lots of people know that LZ will retire. Thousands of people in the char groups we created do.

> Planning to join KataGo.

@Google9876 I hope I have translated accurately. Still I'm curious that, what part does the "China official" play in Project LZ, and how can you get in touch with them?

**Comment by Google9876** [comment]
Let's just say that I was on a gaming platform expressing my regret at Leela zero's withdrawal, and he asked me to friend him, and that's what happened.

**Comment by Google9876** [comment]
(I'm speaking through a translator. The words may be inaccurate.)
