### ISSUE TITLE
suspectable problem with the 9×9 board

### ISSUE THREAD

**Issue by ghbin59** [leela-zero/leela-zero#2592]
It's on the 9×9 board that I use the analysis playing with Leela-zero.  But LZ told me the best solution is to put the chess outside the 9×9 board. I think it's obvious LZ has mistaken the 9×9 board with the 19×19 board. I am a beginner learning to play Go. I wish I can start from playing on the 9×9 board. I hope LZ can teach me on the 9×9 board.

**Comment by roy7** [comment]
Unless you've compiled a special copy of LZ and found a 9x9 network to use for it, normal LZ doesn't support 9x9. It does 19x19 only. If you like, you could try Katago, which can play any board size without special networks/etc required.

https://github.com/lightvector/KataGo/releases/tag/v1.3.5

**Comment by ghbin59** [comment]
Thanks for answering.
