### ISSUE TITLE
Leela stops with a bigger than the default network 

### ISSUE THREAD

**Issue by GosseRomkes** [leela-zero/leela-zero#2599]
On my Surface Book with NVIDIA Maxwell GPU Leela (25.1) runs fine in CUDA but only with the smaller enclosed and default network. Replacing this network for a bigger one the exe stops working. Does somebody recognize this and does someone has a clue to overcome this problem?

Gosse

**Comment by CGLemon** [comment]
I think that what you ask for is not Leela Zero. It is LeelaChessZero. Their Network format are different.
You can download Leela Zero weight files from here.
https://zero.sjeng.org/

LeelaChessZero is here.
https://lczero.org/play/networks/bestnets/

**Comment by GosseRomkes** [comment]
Thx. My concern is indeed on Lcz (chess). I cannot use the bigger networks with CUDA but only the smaller default network enclosed the version 25.1.

**Comment by GosseRomkes** [comment]
This place is not for Leela chess zero? Oke.

**Comment by roy7** [comment]
No sorry. Their github is https://github.com/LeelaChessZero/lc0.
