### ISSUE TITLE
Does Leela consider equivalent situations when training？

### ISSUE THREAD

**Issue by Eglusaxie** [leela-zero/leela-zero#2610]
When I use Leela + sabaki, I find that every time Leela is ready, the console will output a matrix of 19 * 19. I don't know AI or programs, but I know how to play go. Obviously, some points on the chessboard are completely equivalent. But when I looked at some equivalent points of the 19 * 19 matrix, I was surprised to find that the values at these points were not equal, such as (4,4) and (16,16); Then I tried several times to make sure that it was not due to some random factors.

So I want to know whether Leela has considered equivalent situations in training, and if not, whether it can improve training efficiency. After all, each situation has at most eight equivalent situations.
Besides, who doesn't like the perfect symmetry? Hahaha.
![图片](https://user-images.githubusercontent.com/44467205/88992004-c2d88d80-d314-11ea-8e2b-0960aa7555ac.png)

**Comment by OmnipotentEntity** [comment]
Leela Zero is based off of the Alpha Go and Alpha Zero papers.  Within one of these, I believe it's the original Alpha Go paper, there was a comment that attempting to regularize the networks by forcing it to be symmetrical actually resulted in a reduction of strength.

It stands to reason from a certain viewpoint.  If a policy or value is allowed to be dependent upon rotation, then the network can be more agile as (approximately 8x) fewer weights are affected by any particular position being learned.

As far as I'm aware, no independent confirmation of this has yet been tested.  Also, it is possible that the method Deepmind used to enforce this was somehow detrimental, but not the concept itself.  For instance, if they performed this regularization as just another entry in the loss function, they may have weighted it too highly.

**Comment by Eglusaxie** [comment]
Hahaha,actually I don't quite understand what you mean,my English is not good.(Thx the AI translation app).
And I don't know about the technical details and principles of AI too.
So I'm still a little confused,I noticed you said:
......regularize the networks by forcing it to be symmetrical......
......For instance, if they performed this regularization as just another entry in the loss function, they may have weighted it too highly.......
I guess,maybe we don’t need to make any special modifications to the networks.We can naturally get a symmetrical weights with a few tricks.For example,if Leela can training concurrently, it's just like seven more mirror threads in each training session.

**Comment by Eglusaxie** [comment]
@OmnipotentEntity

**Comment by OmnipotentEntity** [comment]
Yes, you could do that.  But that's 8x as expensive as training normally.

**Comment by Eglusaxie** [comment]
Ah~I see. Thank you very much for your patience. Haha, In fact, I am still a little reluctant. I thought maybe that part of the GPU cost could be saved.
I think, from the perspective of go fans, keeping weights symmetrical may be more important than training efficiency or weight strength.
But now we are satisfied enough. Thank you AI researchers and open source contributors.

**Comment by Eglusaxie** [comment]
> 
> 
> Yes, you could do that. But that's 8x as expensive as training normally.

Ah~I see. Thank you very much for your patience. Haha, In fact, I am still a little reluctant. I thought maybe part of the GPU cost could be saved.
I think, from the perspective of go fans, keeping weights symmetrical may be more important than training efficiency or weight strength.
But now we are satisfied enough. Thank you AI researchers and open source contributors.
