### ISSUE TITLE
"Human" player in the early self play games?

### ISSUE THREAD

**Issue by sciginto** [leela-zero/leela-zero#2615]
Hi!
I am new and looked at the early self-play games in the "Raw" sgf collection and found that in the first 1M and 2M games many games (in the beginning all) are played by a player named "Human" (usually as white).

Why is it?
Were not all games played by Leela Zero?

**Comment by roy7** [comment]
It was how autogtp worked back in the beginning, the opposing player in the sgf dumps was named 'Human'. :) No Human games were used for self-play.

https://github.com/leela-zero/leela-zero/pull/365

**Comment by sciginto** [comment]
Thank you very much.
