### ISSUE TITLE
LeelaZero's performance on the 2020 World AI Go championship tournament

### ISSUE THREAD

**Issue by Lefannew** [leela-zero/leela-zero#2619]
Dear GCP 
Hello sir,I have a question for you.
I know LeelaZero has participated the 2020 World Go AI championship tournament. And LeelaZero performed masterfully. Here is the link of the tournament information. https://gameofgo.app/general/world-go-artificial-intelligence-tournament-2020
Pre semi final result
https://gameofgo.app/general/world-go-ai-championship-2020-pre-finals-results
Game sgfs
https://gameofgo.app/general/world-go-artificial-intelligence-tournament-2020-sgfs

One thing surprised me was LeelaZero beat likes Golaxy and it lost all the games by time out,however,a lot of AI users ran LeelaZero,kataGo and Golaxy at home and realized LeelaZero was winning all these time out games. And users used LeelaZero 276 network to tried to found moves on the tournament.However LeelaZero 276 missed a lot of tournament games that LeelaZero performed.
Therefore,my question is, is there a new LeelaZero network exists that much superior to the normal LeelaZero network? Or it has a tons of hardware with a modified LeelaZero network? I am curious about it.Since LeelaZero's masterful performance indeed changed my mind on LeelaZero is weaker than kataGo.
Thank you so much to read my question.
Sincerely tiger 1856

**Comment by roy7** [comment]
To my knowledge none of the contributors to the github were involved with the operation of bots in that event. We don't know the specific hardware or network weights used, etc.

**Comment by hwj-111** [comment]
After watching all these AI tournaments of last couple of years,  I lost my interest on them totally as these tournaments had no regulations/rules on hardware/power consumption/AI-origin (that make such competitions meaningless completely).  Especially this year, so many "new" close-developed (who knows how they got developed) AI bots show up suddenly.   To me, they all look like Leela-zero or Katago shameless clones (if they cannot reveal their true development efforts at end)

**Comment by l1t1** [comment]
semi final matches began

**Comment by l1t1** [comment]
https://game.egcode.cn/#/game-simple/457198

**Comment by l1t1** [comment]
leelazero https://game.egcode.cn/#/match/15

**Comment by l1t1** [comment]
https://game.egcode.cn/#/game-simple/460653

**Comment by l1t1** [comment]
https://sports.sina.com.cn/go/2020-12-02/doc-iiznezxs4881685.shtml
>里拉零比赛结束后迅速公开了所用权重
where to download the weight of the tournament?

**Comment by HackYardo** [comment]
As far as I know, LZ used the weight of KG, which was published in the QQ group of LZ. And the weight's name is:
 
![NAME](https://user-images.githubusercontent.com/57677458/101550918-19548780-39eb-11eb-9aee-ec79a009e755.jpg)

In the event, many KG eliminated numerous strong enemies, leaving only Goaxy and MyrtleGo.
