### ISSUE TITLE
leela trademark

### ISSUE THREAD

**Issue by bvandenbon** [leela-zero/leela-zero#2623]
Somebody filed a trademark registration for the name "Leela". Apparently there is some company which is called "Leela AI Inc." which makes AI software for different applications.

It was registered just a couple of months ago, and the status is still "pending" at this stage.

I don't know what the implications are of this. Maybe it's nothing really.

**Comment by OmnipotentEntity** [comment]
Per https://trademarks.justia.com/889/44/leela-88944467.html

This trademark has been withdrawn (as of September 15), probably because they realized that this project exists.

**Comment by bvandenbon** [comment]
cool :-) thanks for feedback.
