### ISSUE TITLE
Network connection to server failed. NetworkException: JSON parse error: illegal value

### ISSUE THREAD

**Issue by pedante** [leela-zero/leela-zero#2635]
the other issues that are the same are closed and have two years old. 
https://zero.sjeng.org/home            doesn't work
http://zero.sjeng.org/                                   work

How can i make leela work again?

AutoGTP v18
Using 1 game thread(s) per device.
Starting tuning process, please wait...
Network connection to server failed.
NetworkException: JSON parse error: illegal value
Retrying in 30 s.

**Comment by pedante** [comment]
2021-02-15 Server shut down. The project has finished.

might it be that the reason?

:(

**Comment by roy7** [comment]
Yes, Leela Zero server is closed for good. Please consider contributing to SAI or Katago instead. :)
