### ISSUE TITLE
http://zero.sjeng.org/best-network down

### ISSUE THREAD

**Issue by leu14** [leela-zero/leela-zero#2636]
Yesterday I found out that the download (via curl) does no longer work.

It just returns:

<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.19.7</center>
</body>
</html>

**Comment by roy7** [comment]
@gcp I wonder if that url can be hard coded to the final network gz file?

**Comment by leu14** [comment]
@roy7 I do not understand your comment. Did the download page for the weights change, then? It's the one mentioned in the readme.md file.

**Comment by roy7** [comment]
The web page is a static site now since the server has been shut down. We should probably have that web address still work though. Just needs to always show the final best network.

**Comment by leu14** [comment]
Yes, that would be good. So that people can still use the bot if they come to find the page for the first time.

**Comment by gcp** [comment]
I noticed this too and fixed the web server config about a week ago.

**Comment by kotenok2000** [comment]
https://web.archive.org/web/20220122104111/https://zero.sjeng.org/networks/0e9ea880fd3c4444695e8ff4b8a36310d2c03f7c858cadd37af3b76df1d1d15f.gz
For a case when website dies.
