### ISSUE TITLE
NetworkException: JSON parse error

### ISSUE THREAD

**Issue by zh450** [leela-zero/leela-zero#2637]
I got the following after  running AutoGTP v18, is the server down or something?
AutoGTP v18
Using 1 game thread(s) per device.
Starting tuning process, please wait...
Network connection to server failed.
NetworkException: JSON parse error: illegal value
Retrying in 30 s.
Network connection to server failed.
NetworkException: JSON parse error: illegal value
Retrying in 45 s.
Network connection to server failed.
NetworkException: JSON parse error: illegal value
Retrying in 67 s.
Maximum number of retries exceeded. Falling back to previous network.

**Comment by roy7** [comment]
Yes the server is offline for good, the project has ended. :)

Please check out SAI (http://sai.unich.it/) or Katago (https://katagotraining.org/) if you'd like to contribute more to Go AI projects.

**Comment by zh450** [comment]
Thank you very much. Leela-zero is good. As I know there are many go
players (either ameture or professional) who use leea-zero for training and
learning.

Regards,

Jun
