### ISSUE TITLE
Difference between running multiple games and more instances?

### ISSUE THREAD

**Issue by barrtgt** [leela-zero/leela-zero#275]
Just coming from 0.6 master. Is there a difference?

**Comment by gcp** [comment]
Less console windows? :P Not really.

**Comment by BHydden** [comment]
What exactly do you mean by getting in each other's way? I used to run a few instances of autogtp and if I needed the computer I could just close and reopen as many as I needed at that time... This was pretty convenient, but is there something in particular about running multiple games from the one instance that makes the whole process better / smoother?

**Comment by gcp** [comment]
I think there's a (mostly theoretical!) possibility that they end up deleting each others files if one finishes a game just as the other is uploading (if they're running in the same directory).

**Comment by BHydden** [comment]
Wouldn't that only happen if they somehow had the exact same 32char random name assigned to multiple games simultaneously? Is that a legitimate risk?

**Comment by gcp** [comment]
At some point autogtp was searching for the stuff to upload by just doing a *.sgf etc.
