### ISSUE TITLE
Add a safe way to close multi game autogtp.

### ISSUE THREAD

**Issue by Dorus** [leela-zero/leela-zero#280]
Before i would close autogtp when it just started a new game, to prevent my spend computer resources to go to waste when i close it right before a long game ends.

Right now with multi game autogtp i will pretty much always have to close it with 1 game half way played.

A button to tell multi-game autogtp to switch to single game mode when the current game ends, or a button to just make it close when all ongoing games ended would be very useful.

**Comment by gcp** [comment]
This pretty much requires making a GUI for the entire thing.

Without the buttons, a sentinel file would work. (Check if abort.txt exists, and start stopping if it does).

**Comment by Armavica** [comment]
Or handling interrupts? First ^C = "don't start new games", second = "terminate now".

**Comment by isty2e** [comment]
Or possibly [this](https://github.com/gcp/leela-zero/issues/132) can be an alternative to this.

**Comment by Dorus** [comment]
You mean storing the state and continue later? That would be even better for shutting down for the night.

Wouldn't really work for updating the client, but client updates are so spare, that's not really something to worry about.

**Comment by marcocalignano** [comment]
On this matter I would like to know firs if it is worth to do a GUI interface for autogtp. In that case we can just add a button (or two) for this feature. Otherwise we have to catch keyboard press like ctrl-C, etc.
I guess to store the game we could save the SGF file and load it back the next time around.

**Comment by sethtroisi** [comment]
This is supported-ish
"While autogtp is running, typing q+Enter will save the processed data and exit. When autogtp runs next, autogtp will continue the game."
