### ISSUE TITLE
Output in ver 0.7 is unreadable

### ISSUE THREAD

**Issue by kris-computer-go** [leela-zero/leela-zero#281]
When AutoGTP play many games it displays move numbers of each game which are totaly messed, like:
F2) 340 (K19) 98 (L3) 23 (F17) 52 (P6) 190 (C3) 105 (R4) 71 (E4) 253 (B4) 341 (N19) 99 (L2) 24 (R15) 53 (R4) 191 (G8) 106 (S4) 72 (C3) 254 (R1) 342 (N16) 100 (H6) 25 (N6) 54 (P11) 192 (F5) 107 (Q4) 73 (E3) 343 (G4) 255 (A4) 101 (N3) 26 (L14) 55 (C4) 193 (G4) 74 (P15) 344 (T16) 108 (S6) 256 (P1) 102 (P11) 27 (N9) 56 (C5) 194 (F8) 75 (F5) 345 (T5) 109 (S3) 257 (O2) 103 (F5) 28 (A17) 57 (F4) 195 (F4) 346 (T1) 76 (K12) 110 (S5) 258 (A6) 104 (H16) 29 (B7) 58 (O6) 196 (H4) 347 (D2) 77 (R15) 111 (R3) 105 (G6) 259 (L19) 30 (F3) 59 (Q5) 197 (G8) 348 (N17) 78 (O18) 112 (P4) 106 (O15) 260 (M19) 31 (D5) 60 (S4) 349 (S13) 198 (E4) 79 (R16) 113 (P3) 107 (P15) 32 (F2) 261 (L18) 61 (L4) 199 (D3) 350 (J5) 80 (R17) 114 (H14) 108 (T6) 33 (G16) 262 (T3) 62 (F3) 351 (H6) 200 (F8) 81 (Q17) 115 (P6) 109 (O14)
I think this kind of output is at least confusing.

**Comment by qysnn** [comment]
There is also one problem about the output of final result and every move: they are mixed together. It is an old bug from previous versions.
> ...
> Score: B+Resign
> Winner: black
> Writing aecffd9163e34cb5886f666522a4aaa8.sgf
> Dumping aecffd9163e34cb5886f666522a4aaa8.txt
> 164 (C15) 4 game(s) played in 18 minutes = 277 seconds/game, 168 ms/move, last game took 1109 seconds.
> curl -F networkhash=2184b7500795533b97a40cc83bdfd51d1f18183c6e76d7cca3053237e0f18c7c -F clientversion=7 -F sgf=@aecffd9163e34cb5886f666522a4aaa8.sgf.gz -F trainingdata=@aecffd9163e34cb5886f666522a4aaa8.txt.0.gz http://zero.sjeng.org/submit
> 165 (P4) 164 (T11) 164 (S8) 166 (L10) 165 (Q13) Game data 1e5b26ef334fc46dee6e1b13e1722156febff087d94c1bcfb6ba19e125049a85 stored in database
> 165 (Q5) 166 (M8) 166 (M6) 165 (O16) 164 (P2) 164 (T8) Best network hash: 2184b7500795533b97a40cc83bdfd51d1f18183c6e76d7cca3053237e0f18c7c
> Required client version: 4 (OK)
> 166 (F18) 164 (L13) Already downloaded network.
> Stopping engine.
> 166 (J3) ./leelaz -r 1 --gpu=1  -g -t 1 -q -d -n -m 30 -w 2184b7500795533b97a40cc83bdfd51d1f18183c6e76d7cca3053237e0f18c7c -p 1600 --noponder
> 158 (T3) 165 (P12) 166 (M16) 166 (Q12) 166 (J14) 165 (H7) 165 (N10) Engine has started.
> Infinite thinking time set.
> 165 (P17) 12 (R14) 166 (K2) ...

**Comment by isty2e** [comment]
I can't think of any clear-cut solution for this if we are sticking with stdout... But at least logging games into different files might be helpful.

**Comment by roy7** [comment]
When you say "play many games" do you mean 'play many games at the same time"? ie: Could multiple game threads be running and the stdout all mixing together? Or does autogtp run each game in a different shell window? I've never tried it myself.

**Comment by qysnn** [comment]
@roy7 It seems all the instances will output to the same console.

**Comment by gcp** [comment]
The output is really more there to see that things are moving rather than reading the moves off of the screen, especially as you can now have to save the SGFs...

**Comment by earthengine** [comment]
I am thinking we should have an html frontend like a local Node.js to allow realtime monitoring. Maybe create another project.

**Comment by sethtroisi** [comment]
I've written a small script that attempts to parse overlapping game output from stdout into sgfs of the current, partial, games.

it doesn't work in all cases but once the games are at different moves it gives you partial SGF files, I'll upload it in the morning.

**Comment by earthengine** [comment]
You don't need this though. Just run `autogtp -k sgf` it will keep all sgf files in a subfolder under working folder.

**Comment by earthengine** [comment]
This feel like strange to me: when I started `autogtp` it starts two `leelaz` instances, and the output are interleaved. However, when I finished work and come back home, the output (game #54) is now fully synchronised as if there is only one `leelaz`. Windows Task manager clearly shows there are two instances though. How come this can happen?
