### ISSUE TITLE
please set curl with resume  from break point mode

### ISSUE THREAD

**Issue by l1t1** [leela-zero/leela-zero#284]
I tried the game and each time ,it download from begin of the network file.
<b>
D:\tool\leela8>autogtp -g sga
AutoGTP v7
Using 0 thread(s).
Best network hash: 2184b7500795533b97a40cc83bdfd51d1f18183c6e76d7cca3053237e0f18c7c
Required client version: 4 (OK)
curl.exe -s -O -J -w %{filename_effective} http://zero.sjeng.org/best-network
Network connection to server failed.
NetworkException: Curl returned non-zero exit code 56
Retrying in 30 s.
Best network hash: 2184b7500795533b97a40cc83bdfd51d1f18183c6e76d7cca3053237e0f18c7c
Required client version: 4 (OK)
curl.exe -s -O -J -w %{filename_effective} http://zero.sjeng.org/best-network
Network connection to server failed.
NetworkException: Curl returned non-zero exit code 18
Retrying in 45 s.
Best network hash: 2184b7500795533b97a40cc83bdfd51d1f18183c6e76d7cca3053237e0f18c7c
Required client version: 4 (OK)
curl.exe -s -O -J -w %{filename_effective} http://zero.sjeng.org/best-network
</b>

**Comment by l1t1** [comment]
and I had to download the file by using wget -c 
<b>
--2017-12-08 08:38:24--  (try: 3)  http://zero.sjeng.org/networks/2184b7500795533b97a40cc83bdfd51d1f18183c6e76d7cca30532
37e0f18c7c.gz

Proxy request sent, awaiting response... 206 Partial Content
Length: 2803429 (2.7M), 2524976 (2.4M) remaining [application/gzip]
Saving to: '2184b7500795533b97a40cc83bdfd51d1f18183c6e76d7cca3053237e0f18c7c.gz'

                      2184b75  23%[++++======>                                       ] 653.34K  2.63KB/s    eta 19m 9s
</b>

**Comment by roy7** [comment]
I believe this would just mean adding  "-C -" to curl when downloading. I have no idea if resume is possible given the way we serve files off the web site, but someone could test it. :)

**Comment by l1t1** [comment]
-C, --continue-at <offset> Resumed transfer offset
it seems hard to implement for offset value of each time depends on the file size partial downloaded

**Comment by roy7** [comment]
Using "-C -" will autocompute the offset.

**Comment by l1t1** [comment]
I tried but failed
<b>
D:\>tool\leelaz5\curl -C - -o test.gz http://zero.sjeng.org/networks/d645af975ed5b9d08530d092d484482d9aee014f9498c7afcde
8570743f85751.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 48 1341k   48  644k    0     0   1586      0  0:14:26  0:06:56  0:07:30     0
curl: (56) Recv failure: Connection was reset
</b>

**Comment by l1t1** [comment]
and run the command again, it works.
<pre>
D:\>tool\leelaz5\curl -C - -o test.gz http://zero.sjeng.org/networks/d645af975ed5b9d08530d092d484482d9aee014f9498c7afcde
8570743f85751.gz
** Resuming transfer from byte position 660125
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  696k  100  696k    0     0   7355      0  0:01:37  0:01:37 --:--:--  5399
</pre>

**Comment by gcp** [comment]
That setting used to be in there but IIRC it caused other problems.

**Comment by gcp** [comment]
I think the problem is that with -C it will refuse to do the initial download.

**Comment by bood** [comment]
@gcp Just a reminder, this issue is going to be worse after `distributed testing` version released, especially for those in China. I think most of people in China currently suffer from downloading the network file directly.

Is it possible to offer a mirror for China users? https://www.qiniu.com/ would be a good place to get started. I can help if you have registration problem.

However, it requires some client change too, e.g. retry the mirror url if original url does not work.

**Comment by roy7** [comment]
Perhaps autogtp should have an option for "selfplay only"and it won't do matches. That'd reduce the amount of network downloads.

**Comment by roy7** [comment]
Although a simple caching proxy located in China might solve it as well.

**Comment by roy7** [comment]
A variety of CDNs work out of China, and Amazon has an EC2 cloud there through a partner company. I imagine we'd want a zero cost solution though. OGS is providing cloud storage for various parts of this project. I wonder if one of the Chinese Go servers might do the same?

**Comment by bood** [comment]
I'm not aware of any but I can ask if you think it's a good idea.

Also, noticing we rarely have problems submitting results, probably the problem only exists for long time connection. So maybe just retry/resume would also be a good place to start too?

I tried `curl -C` and it seems to be working on my Mac, even the file does not exist (I suppose this is the initial download @gcp mentioned earlier).
