### ISSUE TITLE
fp16 training

### ISSUE THREAD

**Issue by ihavnoid** [leela-zero/leela-zero#330]
I am trying to test how good (or bad) it is if we move the training using fp16.  Quick testing using supervised learning seems to show that my GPU (GTX 1080 non-TI) is running out of memory when I tried to train using the full network (20 deep, 256 planes).  Moving to fp16 at least did seem to help by reducing the memory footprint of various data structures (still a smaller batch was needed), and even on the reduced network, the reduced bandwidth requirement seemed to help training performance.

(BTW, tensorflow seemed to keep the in-memory structure at fp16 but still do compute on fp32 - not sure how it was done on my GTX1080)

Questions:
- Is it expected that GPU memory capacity is going to be a bottleneck?  If so, any hint on where it would be good to start?
- Is there where I can download the raw training data rather than the sgf files?

**Comment by Ttl** [comment]
Raw training data can be found at #167.

**Comment by billyswong** [comment]
Most consumer graphic cards are very weak in fp16 compute, and can be even slower than fp32. Thus the tensorflow hybrid design.

**Comment by gcp** [comment]
I tried fp16 training on a V100 but I had problems with the converege of the value network, even after re-scaling the backprop gradient (see NVIDIA's papers on why that's needed).

**Comment by ihavnoid** [comment]
Was the policy head the only problem?  What I am trying to do is to cast everything back to fp32 on the 'dual' heads while leaving the residual tower and those parameters at fp16.

**Comment by ihavnoid** [comment]
By the way, is this the nvidia paper you are referring to?

https://devblogs.nvidia.com/parallelforall/mixed-precision-training-deep-neural-networks/

**Comment by gcp** [comment]
Yes, that and the slides to go with it.

I think what you're trying is a good idea (fp16 res tower, fp32 heads).

**Comment by ihavnoid** [comment]
Training the ad8a1d02 dataset for 24 hours, and this is the current status:

`step 132000, policy loss=5.11683 mse=0.0368261 reg=0.285763 (226.404 pos/s)`
`step 132000, training accuracy=16.0938%, mse=0.0652886`

Accuracy seems to be moving around 15~20% since the last 12 hours.  Is this normal?

**Comment by gcp** [comment]
Yes, that sounds about right. The MSE is very low, you're probably overfitting.

**Comment by ihavnoid** [comment]
Okay I thought we should be hitting around 50% accuracy but maybe that's only for the supervised learning data.

By the way, if you are interested, I can try to get this merge-worthy (parameterized fp16/fp32) what do you think?

**Comment by gcp** [comment]
Can always take a look at the code in a pull request.

**Comment by gcp** [comment]
>Okay I thought we should be hitting around 50% accuracy but maybe that's only for the supervised learning data.

Yes. For the current games, we're starting to approach 30%. It slowly creeps up as the moves are more sensible.

**Comment by ihavnoid** [comment]
Code on:

https://github.com/gcp/leela-zero/pull/440

I couldn't make the float32 training code backward-compatible (variable hierarchy is different) so I understand it may not be okay to merge as-is.  Anyway, please have a look.

**Comment by sethtroisi** [comment]
This is supported, closing old issue
