### ISSUE TITLE
kgs-genmove_cleanup w fills own eyes

### ISSUE THREAD

**Issue by Dorus** [leela-zero/leela-zero#344]
In some online plays, like on kgs like [here](http://www.yss-aya.com/cgos/viewer.cgi?19x19/SGF/2017/12/10/326239.sgf) (source [reddit](https://www.reddit.com/r/cbaduk/comments/7ityi6/lz_eebb91_vs_stop09_on_cgos_with_a_twist_at_the/)), Leela Z fills all possible moves and eventually its last eye and dies in an otherwise won game. I've seen this a few times.

I was unable to reproduce this until GoGui started sending "kgs-genmove_cleanup w". Black correctly passes here, but white keeps filling till eventually it dies. This reproduces exactly what was observed in the game above.

**Comment by Uizmp** [comment]
Should Leelaz check who wins the game with Tromp-Taylor rule, when a opponent plays a "pass"?

**Comment by gcp** [comment]
This is what the "-d" option influences: https://github.com/gcp/leela-zero/blob/1894e17d8165b8f88b03f704155400091c07db7b/src/UCTSearch.cpp#L191

In addition, kgs-genmove_cleanup has specific code to not force an eye fill: https://github.com/gcp/leela-zero/blob/1894e17d8165b8f88b03f704155400091c07db7b/src/UCTNode.cpp#L536

**Comment by barrybecker4** [comment]
I am using LeelaWatcher and Leela Zero 0.12 + AutoGTP v14. 
It's fun to watch the games, but I see some strange things in the endgame.
This game was won by white after it captured a big black group, but then play continued.
Black had living groups at the top, bottom, and right. The it starts filling in its own territory, including its eyes! - until white captures all its groups. I can understand why it fills in territory up until it has 2 eyes, but why does it fill one of its remaining 2 eyes? Furthermore, why didn't black resign before this point?
![image](https://user-images.githubusercontent.com/3020163/37104967-daf4b852-21e2-11e8-8b21-8e78c1bd7b9b.png)

**Comment by jkiliani** [comment]
For Leela Zero, a loss is a loss, whether by a half point or 300 points doesn't matter. It (sometimes) fills in its own eyes rather than pass in no resign mode only, since this extends the game and prevents a more immediate loss.

**Comment by barrybecker4** [comment]
I'm pretty sure its not in no-resign mode. I've seen white resign games. I am running with default settings. I started it with 
java -jar e:/projects/LeelaWatcher/build/libs/LeelaWatcher-1.0.2.jar . autogtp.exe

**Comment by roy7** [comment]
A % of games are set to resignation_percent 0 as part of learning. It's like 10% or 20% of them all randomly. I bet if you know the hash of the game you watched and look up the SGF file it'll have -r 0 in the params.
