### ISSUE TITLE
why leelaz reload new network after one move done

### ISSUE THREAD

**Issue by l1t1** [leela-zero/leela-zero#348]
Score: W+Resign
Winner: white
Writing b537503401344dc8a85e1f192408ae35.sgf
Dumping b537503401344dc8a85e1f192408ae35.txt
8 game(s) played in 426 minutes = 3201 seconds/game, 10124 ms/move, last game took 2910 seconds.
curl.exe -F networkhash=1607dbea9c6f8f8e6137b2b167464d4003e5b43c1ec4d792959c6113ef863186 -F clientversion=8 -F sgf=@b537
503401344dc8a85e1f192408ae35.sgf.gz -F trainingdata=@b537503401344dc8a85e1f192408ae35.txt.0.gz http://zero.sjeng.org/sub
mit
Game data bde0cc2cc735455c97abec68dd2643e8bdb1e77d867a4939b2550b2da05ad372 stored in database
Best network hash: 96bf20e75aeb80fff4a68d9d449f73483c8e08021566c1ed574b3b741372aa60
Required client version: 8 (OK)
curl.exe -s -O -J -w %{filename_effective} http://zero.sjeng.org/best-network
Curl filename: 96bf20e75aeb80fff4a68d9d449f73483c8e08021566c1ed574b3b741372aa60.gz
Net filename: 96bf20e75aeb80fff4a68d9d449f73483c8e08021566c1ed574b3b741372aa60
Stopping engine.
./leelaz.exe -r 1 -g -t 1 -q -d -n -m 30 -w 96bf20e75aeb80fff4a68d9d449f73483c8e08021566c1ed574b3b741372aa60 -p 1600 --n
oponder
Engine has started.
Infinite thinking time set.
<b>1 (N9) Best Network has changed: restarting.</b>
Stopping engine.
./leelaz.exe -r 0 -g -t 1 -q -d -n -m 30 -w 96bf20e75aeb80fff4a68d9d449f73483c8e08021566c1ed574b3b741372aa60 -p 1600 --n
oponder
Engine has started.
Infinite thinking time set.
1 (D12) 2 (Q18) 3 (E13) 4 (R3) 5 (K5) 6 (B2) 7 (D2) 8 (M11) 9 (B11) 10 (A6) 11 (P4) 12 (K15) 13 (G2) 14 (O2) 15 (R9) 16

**Comment by marcocalignano** [comment]
IT tells you why

>  Best Network has changed: restarting.

that means the network you are using in your game is not the best anymore hence it starts again with the new one

**Comment by l1t1** [comment]
but the 96bf..gz  is ready when 
Writing b537503401344dc8a85e1f192408ae35.sgf
Dumping b537503401344dc8a85e1f192408ae35.txt
was playing

**Comment by marcocalignano** [comment]
How many game are you running at the same time?

**Comment by l1t1** [comment]
should be one.
my command is :
autogtp -k sga

**Comment by marcocalignano** [comment]
Ok I think it is a bug I will look into it later ( even if with the next release that will be obsolete).

**Comment by l1t1** [comment]
thanks

**Comment by marcocalignano** [comment]
I look into it and it is a flow. This happens only with the thread that download the network and it starts after the first move (so we loose a move on one thread only and only once a new network is downloaded). It is really difficult to fix and after the fix we need to test autogtp again. So since in the next version the handling of the threads is completely different I wouldn't want to fix it. (unless @gcp really wants)
