### ISSUE TITLE
Can you support dual-GPU in TensorFlow?

### ISSUE THREAD

**Issue by bclman** [leela-zero/leela-zero#35]
I use tensorflow.
When training data, I found only one of two GTX1080Ti worked.
One gpu is idle.
Do you have any plan to support dual GPU computing?
![train](https://user-images.githubusercontent.com/32253256/32690136-a48ca6a2-c734-11e7-9ae2-3f8167a836ba.jpg)

**Comment by sethtroisi** [comment]
closing old feature request with no owner.
