### ISSUE TITLE
Questions about future arrangement

### ISSUE THREAD

**Issue by sbbdms** [leela-zero/leela-zero#350]
> How is progress on the 6x128 version? I havn't heard anything about it anymore for some time now. Are we still planning to scale up?

> I haven't done anything regarding this. We had some problems getting 5x64 to learn and the window was modified, so I'm not sure how to properly step up or, or if we should just forget about it and run 5x64 to the end.

I noticed that GCP gave the answer yesterday to the question above.
I think it means that we are just improving an network for testing, meanwhile fix known bugs and confirm that the developments actually make sense. If so:

(1) Will this project be restarted formally, from a totally random network?

If it will be restarted:
(2) When will it happen? From the time that 5x64 network can beat GnuGo 3.9.1 or other stronger programs?
(3) Is the initial network directly 40 blocks? Or still from a small network to 40 blocks, just like the current experiment?

Thanks for answering.

**Comment by zhurak** [comment]
I guess we always can train new network on all games and proceed further with a new one. Or since residual networks are known for its smooth extension we just can add more blocks on top of it. It is not possible to increase number of filters in that way though. 
Anyway I believe that LeelaZero can reach dan level with current network. Then we can train 20 blocks residual NN on dan level games from scratch. In that way we still save its soul -- pure AI without any human knowledge.

**Comment by evanroberts85** [comment]
I wouldn’t be surprised if Deepmind release another paper in the next few months to completly change are approach to deep learning, so it is pretty pointless making any firm plans.

**Comment by roy7** [comment]
> We had some problems getting 5x64 to learn and the window was modified, so I'm not sure how to properly step up or, or if we should just forget about it and run 5x64 to the end.

@gcp The problems with learning with 5x64 could have been from the mutli-threaded MCTS bug making white lose so much? Or maybe some other bug. I suspect 5x64 could actually learn now, after all. If that changes anything.

**Comment by jkiliani** [comment]
5x64 can definitely still go a lot further than the current situation. At least single digit kyu, low dan wouldn't really surprise me though. I guess we'll see when it stalls out, but at that point it may be feasible to simply train a larger network on the existing data and continue to improve it by self play.

**Comment by gcp** [comment]
>The problems with learning with 5x64 could have been from the mutli-threaded MCTS bug making white lose so much?

We fixed a lot of bugs along the way. We can run 5x64 to the end and then still see if we can progress on top of that with a bigger network, or restart.

The advantage of 5x64 is that it will be usable on modest hardware.

**Comment by jkiliani** [comment]
Congratulations on training three winning networks in one day! Did you change anything about how you train lately, or was it coincidence?
