### ISSUE TITLE
Catching Ctrl-C

### ISSUE THREAD

**Issue by marcocalignano** [leela-zero/leela-zero#422]
The last feature I want to do for autogtp is the possibility to interrupt the program save the games and resume them next time we start. Actually the code is all done (still to test) but I do not know how to catch the Ctrl-C signal or any  Kay combination from withing QCoreApplication. 
Anyone can help me? 
The code is in my repository in branch "resume"

**Comment by apetresc** [comment]
For what it's worth, you can catch Ctrl-C (which is `SIGINT`) using the sample code [found here](https://gist.github.com/azadkuh/a2ac6869661ebd3f8588).

**Comment by apetresc** [comment]
I should note though, that having Ctrl-C save the current state to resume later is pretty unconventional - there's already SIGTSTP for that (Ctrl-Z).

The most natural way for Leela-Zero to handle Ctrl-C, in my opinion, is to make the first one set a flag that tells it to stop gracefully after finishing the current unit of work (i.e, game), and the second one abort on the spot. This matches what, for example, (fishnet)[https://github.com/niklasf/fishnet] does.

**Comment by marcocalignano** [comment]
So I-ve tried that code but I did make it work. When the signal is capture I need to call a public function from the object Management like this 
boss->storeGames() ;
But even if I capture the variable in the lambda function IT does not seem to work.

**Comment by marcocalignano** [comment]
On another note does this solution is good also for Windows and Apple?

**Comment by marcocalignano** [comment]
I found something that can works under the MIT license. Is it compatible with GPL3 ?

**Comment by gcp** [comment]
MIT is compatible, yes.

**Comment by marcocalignano** [comment]
So now I can catch the signal Ctrl-Z but it seams that the signal reach also the QProcess where Leela is Working  so the the all program stall. Anyone knows how to mask unix signal in a QProcess or at least put them in a different Process group?

**Comment by marcocalignano** [comment]
I am also thinking if this is worth the effort, because it is a solution done for Unix signals. No Idea how Windows works or even Apple.

**Comment by ljn917** [comment]
Mac is similar to Linux because Mac is Unix. Win is different, but most of the Unix singals do exist in Win for compactibility. Try std::signal.

http://doc.qt.io/qt-5.6/unix-signals.html

https://msdn.microsoft.com/en-us/library/xdkz3x12.aspx

**Comment by marcocalignano** [comment]
Still I have a problem when I issue Ctrl-Z from the console, this signal is sent to all processes: main and the QProcess where Leelaz is running. So if I catch it in main to save the game I have to wait for leelaz to finish the current move, but since leelaz received also Ctrl-Z the Process will never return, and I am stalled.

**Comment by ljn917** [comment]
I think this answer your question.

https://unix.stackexchange.com/questions/225687/what-happens-to-a-multithreaded-linux-process-if-it-gets-a-signal

**Comment by ljn917** [comment]
Basically, the signal can be sent to only one thread or all threads based on different implementation.....

**Comment by marcocalignano** [comment]
It also depend of the version of the OS you are using and basically for Linux above 2.6 a Signal is sent to a process and oll the thread generated from it that usually are inside the process group. So "the implementation" means you have to find a way to do one of these two thing:
put the threads and the process spawn by autogtp into a different process group or mask them from all the signal so when the signal comes it remains pending until the main process of autogtp becomes active. From what I know both these things are not possible with QProcess and QThread. I am not sure how to do the process group changing but I know you can mask pthread from signals. No I dae if boost can help there, but this means rewrite autogtp almost in its entirety and test all over again.

**Comment by ljn917** [comment]
You can try to mask leelaz workers with SIG_IGN and set main to receive the
signal.

On Dec 19, 2017 5:41 PM, "marcocalignano" <notifications@github.com> wrote:

It also depend of the version of the OS you are using and basically for
Linux above 2.6 a Signal is sent to a process and oll the thread generated
from it that usually are inside the process group. So "the implementation"
means you have to find a way to do one of these two thing:
put the threads and the process spawn by autogtp into a different process
group or mask them from all the signal so when the signal comes it remains
pending until the main process of autogtp becomes active. From what I know
both these things are not possible with QProcess and QThread. I am not sure
how to do the process group changing but I know you can mask pthread from
signals. No I dae if boost can help there, but this means rewrite autogtp
almost in its entirety and test all over again.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/gcp/leela-zero/issues/422#issuecomment-352908822>, or mute
the thread

**Comment by qysnn** [comment]
I think it's better to have platform specific code without qt framework to do the job. And as you may already found out, linux system will also handle Ctrl+Z as the switch between background and foreground, so focus on Ctrl+C may be a better idea.

**Comment by killerducky** [comment]
What about something simpler like "q" to quit gracefully and "qq" to quit immediately. First q can print a message to the user about pressing q again. That might be easier and less OS dependent.

**Comment by ljn917** [comment]
Using stdin is cleaner, but I doubt anyone would actually notice the
commands.

**Comment by ljn917** [comment]
@marcocalignano I have not tested QProcess, but here is a toy in std C++. Signal handler is only called once, although there are two child threads. This is what I mean for "different implementations". GCC uses pthread.

```
// g++ sig.cpp -pthread
// Ctrl+C, Ctrl+\

#include <stdio.h>
#include <signal.h>
#include <thread>
#include <mutex>

sig_atomic_t sig = 0;
std::mutex mtx;

void my_handler(int param) {
    printf("my_handler: signal is %d.\n", param);
    fflush(stdout);
    sig = param;
}

void a() {
    while(true) {
        mtx.lock();
        if(sig != 0 && SIGINT == sig) {
            printf("a: signal is %d.\n", sig);
            fflush(stdout);
            sig = 0;
            mtx.unlock();
            return;
        }
        mtx.unlock();
    }
}

void b() {
    while(true) {
        mtx.lock();
        if(sig != 0 && SIGQUIT == sig) {
            printf("b: signal is %d.\n", sig);
            fflush(stdout);
            sig = 0;
            mtx.unlock();
            return;
        }
        mtx.unlock();
    }
}

int main(void) {
    signal(SIGINT, my_handler);
    signal(SIGQUIT, my_handler);
    
    std::thread first(a);
    std::thread second(b);

    first.join();
    second.join();

    return 0;
}
```

**Comment by marcocalignano** [comment]
@ljn917 ok now put an output in each loop inside the  `if(sig != 0 && SIGINT == sig)` block ad an output after the `second.join()` line, run the program and tell me if you can see all three output on you console

**Comment by marcocalignano** [comment]
@ljn917 and your code never returns on Linux 4.13

**Comment by ljn917** [comment]
You need ctrl+c and ctrl+\ for sigint and sigquit to exit the two threads.

**Comment by marcocalignano** [comment]
So I have to define a signal for each thread that I spawn in autogtp.Or even if you use the same signal the user have to press Ctrl-C once for every thread pr process? That means thet even for a "normal" command line 
`./autogtp -g4 `
the user have to press Ctrl-C 9 time if the games are all self-played or 13 time if they are all matches something in between if it is there is a mix of games?
Not a good solution.

**Comment by ljn917** [comment]
I think you need to define a global volatile sig_atomic_t, and set it when
you receive sigint in the handler. Run another loop to monitor the
sig_atomic_t,
if it is set, then emit a qt signal to all workers to broadcast the signal.
I think qt doc in one of my previous post has more methods about this.

**Comment by ljn917** [comment]
http://doc.qt.io/qt-5.6/unix-signals.html

**Comment by marcocalignano** [comment]
I am telling you that I did they but while I emitted the signal all the thread and processes in the Process threads already received the SIGINT signal and are gone so that the join function never return.

**Comment by ljn917** [comment]
Are you talking about my code or autogtp? I have not tested qt yet, it
could behave differently.

On Dec 20, 2017 5:42 AM, "marcocalignano" <notifications@github.com> wrote:

I am telling you that I did they but while I emitted the signal all the
thread and processes in the Process threads already received the SIGINT
signal and are gone so that the join function never return.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/gcp/leela-zero/issues/422#issuecomment-353028991>, or mute
the thread

**Comment by marcocalignano** [comment]
Your code works because you have the mutex if you take the mutex out probably won't work either if you catch the signal only in the main loop. Can you try?

**Comment by ljn917** [comment]
The mutex does not matter at all. I added it to avoid the mess in stdout
while I was testing. I just tested it, removing it works too.

**Comment by marcocalignano** [comment]
Ok now catch the signal in the main loop and tell the thread to quit from there then join them and see if it works.

**Comment by ljn917** [comment]
I guess the Management class needs a deconstructor to unlock the blocking
mutex and join all threads. Maybe the mutex can be removed. Then, we can
add an event loop member function for Management class to wait for sigint
and broadcast the signal.

**Comment by marcocalignano** [comment]
But try that on your code first! Catch the signal in the main function (making a loop) and then tell the threads to quit and join them, remember to put some output on exit of all thread and main program.

**Comment by ljn917** [comment]
I don't know what exactly you want to test... It has worked already.

**Comment by marcocalignano** [comment]
Something like that

```
// g++ sig.cpp -pthread
// Ctrl+C, Ctrl+\

#include <stdio.h>
#include <signal.h>
#include <thread>
#include <mutex>

volatile sig_atomic_t sig = 0;
std::mutex mtx;
bool end = false;
void my_handler(int param) {
    printf("my_handler: signal is %d.\n", param);
    fflush(stdout);
    sig = param;
}

void a() {
    while(!end) {
        mtx.lock();
       printf("a : is working \n");
        mtx.unlock();
    }
}

void b() {
    while(!end) {
        mtx.lock();
        printf("b : is working \n");
        }
        mtx.unlock();
    }
}

int main(void) {
    signal(SIGINT, my_handler);
    signal(SIGQUIT, my_handler);
    
    std::thread first(a);
    std::thread second(b);
    while(true) {
        if(sig != 0 && SIGINT == sig) {
            printf("signal is %d.\n", sig);
            fflush(stdout);
            sig = 0;
            end = true;
    }            
    first.join();
    second.join();
     printf("all thread finished");
    return 0;
}
￼
```

**Comment by ljn917** [comment]
Like this?

```
// g++ sig2.cpp -pthread
// Ctrl+C

#include <stdio.h>
#include <signal.h>
#include <thread>
#include <chrono>

volatile sig_atomic_t sig = 0;
volatile bool end = false;
 
void my_handler(int param) {
    printf("my_handler: signal is %d.\n", param);
    fflush(stdout);
    sig = param;
}

void a() {
    while(!end) {
        printf("a : is working \n");
        std::this_thread::sleep_for(std::chrono::milliseconds(100));
    }
}

void b() {
    while(!end) {
        printf("b : is working \n");
        std::this_thread::sleep_for(std::chrono::milliseconds(100));
    }
}

int main(void) {
    signal(SIGINT, my_handler);
    
    std::thread first(a);
    std::thread second(b);
    
    while(true) {
        if(sig != 0 && SIGINT == sig) {
            printf("main: signal is %d.\n", sig);
            end = true;
            break;
        }
    }
    
    first.join();
    second.join();
    
    printf("main: all thread finished\n");
    
    return 0;
}

```

**Comment by marcocalignano** [comment]
Ok so now change the threads a and b in child processes and see if that works as well!

**Comment by sethtroisi** [comment]
This is checked in :)
