### ISSUE TITLE
 is it possible to show w/b winrates of network in web page?

### ISSUE THREAD

**Issue by l1t1** [leela-zero/leela-zero#428]
so that we know if one of the color is stronger?
for example

Start Date | Network Hashes | Wins(W/b) / Losses | Games | SPRT
-- | -- | -- | -- | --
2017-12-18 23:45 | ce1aa643 VS 0eb8b23b | 257(150/107) : 194 (56.98%) | 451 / 400 | PASS
2017-12-18 21:07 | 5166c094 VS 0eb8b23b | 13(1/12) : 63 (17.11%) | 76 / 400 | fail

btw
whether the server disptch b and w evenly and adjust it when result is  lean?
suppose 200 color black games doesn't return result to server due to error

**Comment by sethtroisi** [comment]
For older models this is tracked on https://cloudygo.com/leela-zero-v1/graphs
