### ISSUE TITLE
How to match the web site link and the sgf file name?

### ISSUE THREAD

**Issue by earthengine** [leela-zero/leela-zero#476]
It looks like the saved game uses a different name than the one used in the server's name. So it is not easy to simply look at the saved games folder and make up a link in the server to the game.

There are two motivations to do so:

* To verify my game is actually uploaded to the server
* To share the game in forums without having to upload the sgf to anywhere

**Comment by WhiteHalmos** [comment]
I think the sgf database is wiped every so often, so I don't this can work for #2. #1 can already be done for your most recently submitted game.

**Comment by l1t1** [comment]
you can view the link in console output

**Comment by earthengine** [comment]
Right, but the console is to verbose. I only look at it when I need to ensure Leela Zero is alive and running.

**Comment by gcp** [comment]
If you want to save your games why not use the -k option?

**Comment by earthengine** [comment]
I use the -k option all the time. And sometimes I picked up some interesting game from there. However, the problem is that there is no easy way to pick the same server copy of that game, so I have to upload to websites like eidogo, then share the link in Reddit. This is why I want to know how to match the saved game with the server copy.
