### ISSUE TITLE
What will be the rating method with anchors?

### ISSUE THREAD

**Issue by isty2e** [leela-zero/leela-zero#480]
So if we want to obtain reasonable Elo ratings without self-bias, it is essential to anchor ratings with, for example, GNUGo 3. Often more than one anchors are essential if the ratings are distributed over a large region.

The question is, how are we going to calculate the rating exactly? For example, it is stated in the AGZ paper that they used the BayesElo rating system, but it is unclear what the prior would be. With a uniform prior the BayesElo rating just reduces to maximum likelihood rating, but I doubt if it is the method DeepMind used. Another thing I tried as the prior is a binomial distribution assuming p=0.5, but the results were not that satisfactory.

This issue shouldn't be urgent for now, but when LZ reaches a certain rating, this can be important in the future.

**Comment by isty2e** [comment]
That is what basically anchoring is. However, the ratings are not necessarily additive: If matches between A, B and C is held, then ΔRating(A-C) is not necessarily ΔRating(A-B) + ΔRating(B-C). Thus to handle multiple matches a rating system should be carefully designed.

**Comment by marcocalignano** [comment]
@isty2e I can provide the matching programs.

**Comment by isty2e** [comment]
That's good, but how to calculate the rating properly is the real question.

**Comment by marcocalignano** [comment]
We could make a tournament with more then two players and the use the Idea I found in here 
https://github.com/FigBug/Multiplayer-ELO

**Comment by isty2e** [comment]
It is calculating the rating in a sequential way, which is a very basic version of doing it. The maximum likelihood method I mentioned is better.

**Comment by killerducky** [comment]
@WhiteHalmos is already running every network on CGOS. I think that should be sufficient. I don't think it's necessary to add infrastructure to autogtp to duplicate this.

**Comment by isty2e** [comment]
@killerducky Well whether it should be included in the autogtp or not is out of my interest. I'm though a bit curious how CGOS ratings can be, and at some time we might need to rate the networks properly (since we have much more games between nets), though not in the near future.

**Comment by sethtroisi** [comment]
No active discussion for >1 year, with newer issue
