### ISSUE TITLE
Leela Zero outside matches

### ISSUE THREAD

**Issue by Marcin1960** [leela-zero/leela-zero#507]
It seems to me that there two components to relative strength of recent networks (in games against other bots or humans).

One is how strong a defeated opponent can be. Now it is at least 1 or 2 dan on KGS.

Second is how weak can be opponent that wins. Now it is no higher than 6 kyu.

The first is the measure how smart Leela Zero really is.  The second shows how vulnerable she is to the bad errors. So she is like a strong player who is absentminded and drunk. :) What do you think?

**Comment by MartinDevelopment** [comment]
It seems like the network likes to do crazy things that don't work, because it cannot see something that works yet.

**Comment by Marcin1960** [comment]
I might try to play LeelaZeroT 509e against KGS bots weaker than 6 kyu. Now LeelaZeroT is playing against 3 dan Hirabot. To see how large is the spread.

**Comment by Marcin1960** [comment]
Can someone tell what difference in strength, pondering option makes?

**Comment by john45678** [comment]
I am a bit confused about LZ rating, Is the AGZ vs LZ graph posted on the spreadsheet on Reddit (https://docs.google.com/spreadsheets/d/1QhYWYQvXBhI5eHJm45fvf97CaV2rRmgrATwVgBFGKoU/htmlview# ) which shows LZ now nearly 2000 Elo accurate.
thanks

**Comment by RavnaBergsndot** [comment]
I think the AGZ rating estimation (the one that's used for comparing to human players) is based on 4 TPUs and 1 minute per move. If we give the current LZ network the same hardware and time constraints, it should be closer to 2000 Elo than what a typical GPU gives.

**Comment by john45678** [comment]
@RavnaBergsndot, now I understand, thanks.

**Comment by grolich** [comment]
Elo measures relative performance, so before we have any tested "anchors" to compare with, there is no direct "link" between LZ's Elo graph and AZ's.

The two graphs (LZ's and AZ's Elo ratings) can't really be superimposed like this until we have an anchor to compare with. It wasn't technically correct to mark it that way.

However, it might be possible soon since it seems we can now play well against gnugo, so I assume there will be a "fixed" version of the graph once the data on this is gathered and used.

**Comment by john45678** [comment]
@grolich, thanks.

**Comment by LetterRip** [comment]
@grolich I think the networks learn the same lessons in the same order and at around the same number of games.  So just the shape of the graph is enough to suggest where Leela Zero's strength is relative to AlphaGo.

**Comment by jkiliani** [comment]
Can the current networks defeat the supervised network best_v1 yet? From the performance against humans and other bots, it seems we're in reach of the supervised network at least, if not already past it.

**Comment by zediir** [comment]
LZ-7fcf3c-t1-p1600 Is 2202 elo on CGOS while LZ-HBest1-t1-p1600 is 2638 so probably not quite there yet.

**Comment by jkiliani** [comment]
Looks like we're about to have a new passer with 58da6176. Would be cool if the 5x64 reinforced learning network could actually beat the 6x128 supervised network, I guess we'll see within a few days whether that happens or it stalls out before.

**Comment by Marcin1960** [comment]
Out of curiosity, I started LeelaZeroT with 9x9 board.

**Comment by Marcin1960** [comment]
KGS / LeelaZeroT / 76347a12 / 1.78M / 32k against 6 dan HiraBot41

**Comment by dzhurak** [comment]
Let it rock!

**Comment by sethtroisi** [comment]
Leela is now very strong and has played a number of outside matches :)
