### ISSUE TITLE
More webpage improvements wanted (backend changes probably induced)

### ISSUE THREAD

**Issue by arnaudgo** [leela-zero/leela-zero#511]
Hello :)

So far the webpage is great, thank you very much for the work already done.

I'm one of those who refreshes it frequently... and so, even if the html tables look ugly in my opinion lol ::o)
This joke apart, let me enlist the improvements I'd like to see and if you think they are meaningful, please make them when you have time :-)

1°) where we read these stats:

"607 clients in past 24 hours, 197 in past hour."
 
I would like to read also the equivalent in terms of performance and more exactly in units of (float32?) loating point /operations per second.
I haven't maturated much the idea of how to calculate the metric but I know that I care a little of how many cients and care a lot of what cumulated performance has been dedicated to LZ client for one unit of time (hour/day). So, I guess it would imply o track not only the number of IPs seen for a duration of time but also how long did the running lasted per GPU type. 
I let you decide if the effort is worth too :) And I guess it is as far as we are interested in keeping on comparing LZ learning with AZ learning. How do LZ distributed computing performance compares and competes with AZ computing performance ?
Then we can correlate the learning speed delta between both with the amount of dedicated computing resources.
Of course, if you already have these indicators, it's already great and showing them on the web page will be just a little enhancement for us :)

2°) Providing full data for Best Network Hashes and Test Matches through a downloadable flat file (CSV-like)

3°) Providing EidoGo / WGo links for all the 100 most recent matches.

Thanks for reading me :)

Arnaud

**Comment by sethtroisi** [comment]
3) is handled.
2) is pretty easy to scrap from the HTML.
1) is harder, sorry.
