### ISSUE TITLE
Perhaps we should try pruning the network?

### ISSUE THREAD

**Issue by LetterRip** [leela-zero/leela-zero#512]
Given that pruned networks can have quite similar performance and significantly faster inference, it might save  lot of GPU cycles if we do pruning each time we find an improved network.

https://github.com/garion9013/impl-pruning-TF

**Comment by isty2e** [comment]
It will definitely reduce the execution time, but I am not sure if it is worth adopting, considering the expected accuracy drop, complication in training, and difficulty of implementation. Without an extensive experiment, I can hardly see it applied in LZ.

**Comment by LetterRip** [comment]
Here is a paper on resnet pruning.

https://arxiv.org/pdf/1608.08710.pdf

**Comment by isty2e** [comment]
I have been aware of the network pruning, and it is often an appealing method indeed. However, I am not sure if the claimed negligible loss in accuracy is transferrable to all applications, especially for LZ. At any rate, for any method to be adopted, a series of experiments are inevitable.

**Comment by LetterRip** [comment]
@isty2e agreed that it isn't necessarily applicable to Go and other games though I don't see why in principle it shouldn't be.

**Comment by barrtgt** [comment]
That would be a good experiment for supervised training. Should only take a couple days to train. I think it would be quite different for zero training where exploration is a big part of the process and pruning too early would impede it. I'm willing to bet the 64 filters are already at capacity as well, considering Deepmind chose to use 256.

**Comment by jjoshua2** [comment]
I think this is something we would do, especially if we trained with a big 20 block like Google did, so it could still be run efficiently by people with a slow GPU or CPU. Or even with the 6x128 one we are planning, at the end, so it could be run more efficiently on a CPU, or maybe even a smartphone.

**Comment by isty2e** [comment]
Sure, this might be the first thing to try in the second run.

@LetterRip Yes, I do think that this is likely to work, especially with MCTS. But someone should do the experiment and it can be not that easy :)

**Comment by Alderi-Tokori** [comment]
To be honest, Alpha Go Zero showed that its pure NN was almost at the AlphaGo Fan Hui level, so you can theoretically have a pro level player with 0 playouts per move (well, 1 playout).

**Comment by jkiliani** [comment]
@Alderi-Tokori True, and from the scaling curves they showed in the AlphaZero paper, it's a realistic assumption that it will scale most at very low playouts. I.e., just 10 playouts versus raw network is likely to already make a big difference, and 100 playouts should still be reasonable even for a large network on a laptop computer as long as the implementation is fast enough (Winograd, batching, caching etc.)

**Comment by isty2e** [comment]
Can someone explain me why the MCTS depth is suddenly mentioned here? I'm not following what's happening here...

**Comment by Alderi-Tokori** [comment]
@isty2e : @jjoshua2 Mentioned that this would be a good in order to run it on slow devices, so I remarked that we could already have a pro level player with no playouts given enough training (which mean it could already run on a potato).

**Comment by isty2e** [comment]
@Alderi-Tokori Oh, thanks. But pruned networks can be helpful for faster self-plays, I think that is the point?

**Comment by Alderi-Tokori** [comment]
@isty2e Ah, fair point.

**Comment by jkiliani** [comment]
Does pruning also reduce the symmetry variance of the neural network, i.e. the expected variance between a position's network evaluation and the evaluation of a rotation/reflection of that position? This could potentially be very useful for applications where few playouts are used, since the MCTS can't average out the neural network's rotational asymmetry in that case.

**Comment by LetterRip** [comment]
@jkiliani it might but I don't think it necessarily would.

**Comment by gcp** [comment]
>https://github.com/garion9013/impl-pruning-TF

Note that this implementation suffers from vastly reduced performance because the pruned network doesn't have a form that can be efficiently computed.

**Comment by gcp** [comment]
>True, and from the scaling curves they showed in the AlphaZero paper, it's a realistic assumption that it will scale most at very low playouts.

This is an argument for using much smaller networks. What is better, do you think? A 20 times bigger network with 1 playout, or a smaller network with 20 playouts?

It's a tradeoff in efficiency and diminishing returns.

As for the topic of this thread: give code, give results, or this is a pointless discussion.

**Comment by ivorget** [comment]
Intel has a library (clDNN) that does pruning and other optimisations automatically and it apparently supports ResNets. It's aimed at their own low/lowish-end graphics cards but might also work on others.
[Introductory whitepaper including some benchmarks](https://software.intel.com/en-us/articles/accelerating-deep-learning-inference-with-intel-processor-graphics)
[clDNN github repo](https://github.com/01org/cldnn)

I haven't actually used it myself but if nobody beats me to it I may try to test it at somestage in the hope of reducing the current LZ turn time of (don't laugh) ~60s on my Intel HD 400.

**Comment by gcp** [comment]
I don't see any evidence that that library supports weight pruning. It talks about "Prunes unused branches in the network" which is something completely different and irrelevant.
