### ISSUE TITLE
High certainty to play a suicide (and bad) move (network 7fcf3c)

### ISSUE THREAD

**Issue by earthengine** [leela-zero/leela-zero#525]
[This bug is now hightly repeatable.](https://github.com/gcp/leela-zero/issues/263)

when playing game 

[http://eidogo.com/#2PNdOQJhQ](http://eidogo.com/#2PNdOQJhQ)

Command line (sabiki):

```
leelaz.exe --gtp -w 7fcf3c160712c9b83837688171d623a269b0485702a04d821afb5ed31ac09a98 -p 100000 --noponder
```

At least in my Windows 10 computer (Nvidia G960) it always plays suicide move H5 at move 298.

`next` snapshot: latest

**Comment by earthengine** [comment]
Log file:

Using 2 thread(s).
RNG seed: 6580014735556307438
Initializing OpenCL
Detected 1 OpenCL platforms
Platform version: OpenCL 1.2 CUDA 9.1.75
Platform profile: FULL_PROFILE
Platform name:    NVIDIA CUDA
Platform vendor:  NVIDIA Corporation
Device ID:     0
Device name:   GeForce GTX 960
Device type:   GPU
Device vendor: NVIDIA Corporation
Device driver: 388.13
Device speed:  1253 MHz
Device cores:  8 CU
Device score:  1112
Selected platform: NVIDIA CUDA
Selected device: GeForce GTX 960
with OpenCL 1.2 capability
Wavefront/Warp size: 32
Max workgroup size: 1024
Max workgroup dimensions: 1024 1024 64 
Detecting residual layers...v1...64 channels...5 blocks
Transferring weights to GPU...done
BLAS Core: Barcelona
>>name
= Leela Zero

>>version
= 0.9

>>protocol_version
= 2

>>list_commands
= protocol_version
name
version
quit
known_command
list_commands
quit
boardsize
clear_board
komi
play
genmove
showboard
undo
final_score
final_status_list
time_settings
time_left
fixed_handicap
place_free_handicap
set_free_handicap
loadsgf
printsgf
kgs-genmove_cleanup
kgs-time_settings
kgs-game_over
heatmap

>>boardsize 19
= 

>>clear_board
= 

>>play W A16
= 

>>play B A13
= 

>>play B A12
= 

>>play B A6
= 

>>play B A5
= 

>>play W A4
= 

>>play W B17
= 

>>play W B16
= 

>>play B B14
= 

>>play B B11
= 

>>play B B10
= 

>>play B B9
= 

>>play W B8
= 

>>play W B7
= 

>>play B B6
= 

>>play W B5
= 

>>play W B4
= 

>>play W C18
= 

>>play W C16
= 

>>play B C15
= 

>>play B C14
= 

>>play B C12
= 

>>play W C11
= 

>>play B C10
= 

>>play B C8
= 

>>play B C7
= 

>>play B C6
= 

>>play B C5
= 

>>play W C4
= 

>>play W D18
= 

>>play W D17
= 

>>play W D15
= 

>>play W D14
= 

>>play B D13
= 

>>play B D12
= 

>>play W D10
= 

>>play B D9
= 

>>play B D8
= 

>>play W D7
= 

>>play W D6
= 

>>play W D5
= 

>>play W D3
= 

>>play B E18
= 

>>play B E17
= 

>>play W E16
= 

>>play B E11
= 

>>play W E10
= 

>>play W E9
= 

>>play W E8
= 

>>play W E7
= 

>>play W E6
= 

>>play B E5
= 

>>play W E4
= 

>>play W E2
= 

>>play W F19
= 

>>play W F18
= 

>>play W F17
= 

>>play W F15
= 

>>play W F14
= 

>>play B F12
= 

>>play W F10
= 

>>play W F9
= 

>>play B F8
= 

>>play W F7
= 

>>play B F6
= 

>>play B F5
= 

>>play B F4
= 

>>play W F3
= 

>>play W F2
= 

>>play B G18
= 

>>play W G17
= 

>>play W G16
= 

>>play W G14
= 

>>play W G13
= 

>>play B G12
= 

>>play W G10
= 

>>play B G9
= 

>>play B G8
= 

>>play B G7
= 

>>play B G6
= 

>>play B G4
= 

>>play W G3
= 

>>play W G1
= 

>>play B H18
= 

>>play B H17
= 

>>play B H16
= 

>>play W H15
= 

>>play W H14
= 

>>play B H13
= 

>>play W H12
= 

>>play W H11
= 

>>play W H10
= 

>>play B H9
= 

>>play W H7
= 

>>play B H6
= 

>>play B H4
= 

>>play W H3
= 

>>play W H2
= 

>>play B H1
= 

>>play B J17
= 

>>play W J16
= 

>>play W J15
= 

>>play B J14
= 

>>play B J13
= 

>>play B J12
= 

>>play B J11
= 

>>play B J10
= 

>>play B J7
= 

>>play B J3
= 

>>play B J2
= 

>>play W K19
= 

>>play W K18
= 

>>play B K17
= 

>>play W K16
= 

>>play W K14
= 

>>play B K13
= 

>>play W K12
= 

>>play B K11
= 

>>play B K10
= 

>>play B K9
= 

>>play B K8
= 

>>play B K6
= 

>>play B K5
= 

>>play B K4
= 

>>play W K3
= 

>>play B K2
= 

>>play B K1
= 

>>play W L18
= 

>>play W L17
= 

>>play W L14
= 

>>play W L13
= 

>>play W L12
= 

>>play B L11
= 

>>play W L10
= 

>>play W L9
= 

>>play B L8
= 

>>play B L7
= 

>>play B L5
= 

>>play B L4
= 

>>play W L3
= 

>>play W L2
= 

>>play W L1
= 

>>play W M19
= 

>>play B M18
= 

>>play B M17
= 

>>play W M16
= 

>>play W M15
= 

>>play W M14
= 

>>play B M13
= 

>>play W M12
= 

>>play W M11
= 

>>play B M10
= 

>>play W M9
= 

>>play W M8
= 

>>play B M6
= 

>>play B M5
= 

>>play W M4
= 

>>play W M3
= 

>>play W M2
= 

>>play B N19
= 

>>play B N17
= 

>>play W N16
= 

>>play W N14
= 

>>play W N12
= 

>>play W N11
= 

>>play B N10
= 

>>play B N9
= 

>>play W N8
= 

>>play B N7
= 

>>play B N6
= 

>>play W N5
= 

>>play W N2
= 

>>play B O18
= 

>>play B O17
= 

>>play W O16
= 

>>play W O15
= 

>>play W O14
= 

>>play W O13
= 

>>play W O12
= 

>>play B O11
= 

>>play B O10
= 

>>play W O9
= 

>>play W O8
= 

>>play B O6
= 

>>play B O5
= 

>>play W O4
= 

>>play B P18
= 

>>play B P16
= 

>>play W P15
= 

>>play B P14
= 

>>play W P13
= 

>>play B P12
= 

>>play B P11
= 

>>play W P10
= 

>>play W P8
= 

>>play B P6
= 

>>play W P5
= 

>>play W P3
= 

>>play W P2
= 

>>play B Q17
= 

>>play B Q15
= 

>>play B Q14
= 

>>play W Q13
= 

>>play B Q12
= 

>>play W Q11
= 

>>play W Q10
= 

>>play W Q9
= 

>>play W Q8
= 

>>play W Q7
= 

>>play B Q6
= 

>>play W Q4
= 

>>play W Q2
= 

>>play B R16
= 

>>play B R15
= 

>>play B R14
= 

>>play W R13
= 

>>play B R12
= 

>>play B R11
= 

>>play W R10
= 

>>play W R9
= 

>>play B R8
= 

>>play W R7
= 

>>play B R6
= 

>>play B R5
= 

>>play B R4
= 

>>play W R3
= 

>>play W R1
= 

>>play B S16
= 

>>play B S13
= 

>>play B S12
= 

>>play W S11
= 

>>play W S10
= 

>>play W S9
= 

>>play B S8
= 

>>play B S7
= 

>>play B S5
= 

>>play W S4
= 

>>play W S3
= 

>>play W S1
= 

>>play B T15
= 

>>play B T14
= 

>>play B T13
= 

>>play B T11
= 

>>play W T10
= 

>>play B T9
= 

>>play B T8
= 

>>play B T6
= 

>>play W T5
= 

>>play W T3
= 

>>boardsize 19
= 

>>clear_board
= 

>>play W A16
= 

>>play B A13
= 

>>play B A12
= 

>>play B A6
= 

>>play B A5
= 

>>play W A4
= 

>>play W B17
= 

>>play W B16
= 

>>play B B14
= 

>>play B B11
= 

>>play B B10
= 

>>play B B9
= 

>>play W B8
= 

>>play W B7
= 

>>play B B6
= 

>>play W B5
= 

>>play W B4
= 

>>play W C18
= 

>>play W C16
= 

>>play B C15
= 

>>play B C14
= 

>>play B C12
= 

>>play W C11
= 

>>play B C10
= 

>>play B C8
= 

>>play B C7
= 

>>play B C6
= 

>>play B C5
= 

>>play W C4
= 

>>play W D18
= 

>>play W D17
= 

>>play W D15
= 

>>play W D14
= 

>>play B D13
= 

>>play B D12
= 

>>play W D10
= 

>>play B D9
= 

>>play B D8
= 

>>play W D7
= 

>>play W D6
= 

>>play W D5
= 

>>play W D3
= 

>>play B E18
= 

>>play B E17
= 

>>play W E16
= 

>>play B E11
= 

>>play W E10
= 

>>play W E9
= 

>>play W E8
= 

>>play W E7
= 

>>play W E6
= 

>>play B E5
= 

>>play W E4
= 

>>play W E2
= 

>>play W F19
= 

>>play W F18
= 

>>play W F17
= 

>>play W F15
= 

>>play W F14
= 

>>play B F12
= 

>>play W F10
= 

>>play W F9
= 

>>play B F8
= 

>>play W F7
= 

>>play B F6
= 

>>play B F5
= 

>>play B F4
= 

>>play W F3
= 

>>play W F2
= 

>>play B G18
= 

>>play W G17
= 

>>play W G16
= 

>>play W G14
= 

>>play W G13
= 

>>play B G12
= 

>>play W G10
= 

>>play B G9
= 

>>play B G8
= 

>>play B G7
= 

>>play B G6
= 

>>play W G5
= 

>>play B G4
= 

>>play W G3
= 

>>play W G1
= 

>>play B H18
= 

>>play B H17
= 

>>play B H16
= 

>>play W H15
= 

>>play W H14
= 

>>play B H13
= 

>>play W H12
= 

>>play W H11
= 

>>play W H10
= 

>>play B H9
= 

>>play W H7
= 

>>play B H6
= 

>>play B H4
= 

>>play W H3
= 

>>play W H2
= 

>>play B H1
= 

>>play B J17
= 

>>play W J16
= 

>>play W J15
= 

>>play B J14
= 

>>play B J13
= 

>>play B J12
= 

>>play B J11
= 

>>play B J10
= 

>>play B J7
= 

>>play W J6
= 

>>play W J5
= 

>>play W J4
= 

>>play B J3
= 

>>play B J2
= 

>>play W K19
= 

>>play W K18
= 

>>play B K17
= 

>>play W K16
= 

>>play W K14
= 

>>play B K13
= 

>>play W K12
= 

>>play B K11
= 

>>play B K10
= 

>>play B K9
= 

>>play B K8
= 

>>play B K6
= 

>>play B K5
= 

>>play B K4
= 

>>play W K3
= 

>>play B K2
= 

>>play B K1
= 

>>play W L18
= 

>>play W L17
= 

>>play W L14
= 

>>play W L13
= 

>>play W L12
= 

>>play B L11
= 

>>play W L10
= 

>>play W L9
= 

>>play B L8
= 

>>play B L7
= 

>>play B L5
= 

>>play B L4
= 

>>play W L3
= 

>>play W L2
= 

>>play W L1
= 

>>play W M19
= 

>>play B M18
= 

>>play B M17
= 

>>play W M16
= 

>>play W M15
= 

>>play W M14
= 

>>play B M13
= 

>>play W M12
= 

>>play W M11
= 

>>play B M10
= 

>>play W M9
= 

>>play W M8
= 

>>play B M6
= 

>>play B M5
= 

>>play W M4
= 

>>play W M3
= 

>>play W M2
= 

>>play B N19
= 

>>play B N17
= 

>>play W N16
= 

>>play W N14
= 

>>play W N12
= 

>>play W N11
= 

>>play B N10
= 

>>play B N9
= 

>>play W N8
= 

>>play B N7
= 

>>play B N6
= 

>>play W N5
= 

>>play W N2
= 

>>play B O18
= 

>>play B O17
= 

>>play W O16
= 

>>play W O15
= 

>>play W O14
= 

>>play W O13
= 

>>play W O12
= 

>>play B O11
= 

>>play B O10
= 

>>play W O9
= 

>>play W O8
= 

>>play B O6
= 

>>play B O5
= 

>>play W O4
= 

>>play B P18
= 

>>play B P16
= 

>>play W P15
= 

>>play B P14
= 

>>play W P13
= 

>>play B P12
= 

>>play B P11
= 

>>play W P10
= 

>>play W P8
= 

>>play B P6
= 

>>play W P5
= 

>>play W P3
= 

>>play W P2
= 

>>play B Q17
= 

>>play B Q15
= 

>>play B Q14
= 

>>play W Q13
= 

>>play B Q12
= 

>>play W Q11
= 

>>play W Q10
= 

>>play W Q9
= 

>>play W Q8
= 

>>play W Q7
= 

>>play B Q6
= 

>>play W Q4
= 

>>play W Q2
= 

>>play B R16
= 

>>play B R15
= 

>>play B R14
= 

>>play W R13
= 

>>play B R12
= 

>>play B R11
= 

>>play W R10
= 

>>play W R9
= 

>>play B R8
= 

>>play W R7
= 

>>play B R6
= 

>>play B R5
= 

>>play B R4
= 

>>play W R3
= 

>>play W R1
= 

>>play B S16
= 

>>play B S13
= 

>>play B S12
= 

>>play W S11
= 

>>play W S10
= 

>>play W S9
= 

>>play B S8
= 

>>play B S7
= 

>>play B S5
= 

>>play W S4
= 

>>play W S3
= 

>>play W S1
= 

>>play B T15
= 

>>play B T14
= 

>>play B T13
= 

>>play B T11
= 

>>play W T10
= 

>>play B T9
= 

>>play B T8
= 

>>play B T6
= 

>>play W T5
= 

>>play W T3
= 

>>genmove W
Thinking at most 50.0 seconds...
NN eval=0.460709
Playouts: 1325, Win: 38.08%, PV: H5 T12 E13 T11 N4 N3 N5 T4 S6 Q5 J4 J1 D11 H1 P7 L19
Playouts: 2706, Win: 37.19%, PV: H5 T12 E13 Q5 J4 N4 T11 T4 S6 T12 E14 T11 E15 D16 F13 D11 F11
Playouts: 4115, Win: 37.61%, PV: H5 T12 Q5 T11 N4 N3 P4 N5 Q3 N4 Q4 T4 S6 J1 J4 H1 M7 E13 E12 D11 F13 E14
Playouts: 5503, Win: 38.22%, PV: H5 T12 Q5 T11 N4 P4 N3 O3 N5 T4 J4 J1 D11 H1 S6 E13 E12 F13 F11 G11 O7 P7 M7
Playouts: 6919, Win: 38.34%, PV: H5 T12 L16 L15 T11 T4 T12 J4 J5 J1 J4 H1 S6 N4 Q5 P4 D11 E13 E12 F13 F11 G11 M7 D4 O7 B15 A14 A15 P7 J18 L19 H19
Playouts: 8326, Win: 37.89%, PV: H5 T12 L16 J4 J5 T11 N4 N3 N5 L15 J4 J1 D11 H1
Playouts: 9744, Win: 37.33%, PV: H5 T12 L16 J4 J5 T11 N4 N3 N5 L15 J4 J1 D11 H1
Playouts: 11154, Win: 37.13%, PV: H5 T12 L16 J4 J5 T11 N4 N3 N5 L15 J4 J1 D11 H1
Playouts: 12547, Win: 36.70%, PV: H5 T12 L16 J4 J5 T11 N4 L15 O3 P4 N3 O2 N5 T4 S6 J1 J4 H1 D11 E13 E12 F13 F11 G11 B15 A15 A14
Playouts: 13939, Win: 36.46%, PV: H5 T12 L16 J4 J5 T11 N4 L15 O3 P4 N3 O2 D11 T4 S6 J1 J4 H1 N5 Q5
Playouts: 15314, Win: 36.30%, PV: H5 T12 L16 J4 J5 T11 N4 L15 O3 P4 N3 O2 D11 T4 S6 J1 J4 H1 N5 Q5
Playouts: 16662, Win: 36.29%, PV: H5 T12 L16 J4 J5 T11 N4 L15 O3 P4 N3 O2 D11 T4 S6 J1 J4 H1 N5 Q5
Playouts: 18056, Win: 36.27%, PV: H5 T12 L16 J4 J5 T11 N4 L15 O3 P4 N3 O2 D11 T4 S6 J1 J4 H1 N5 Q5
Playouts: 19470, Win: 36.28%, PV: H5 T12 L16 J4 J5 T11 N4 L15 O3 P4 N3 O2 D11 T4 S6 J1 J4 H1 N5 Q5
Playouts: 20870, Win: 36.38%, PV: H5 T12 L16 J4 J5 T11 N4 L15 O3 P4 N3 O2 D11 T4 S6 J1 J4 H1 N5 Q5
Playouts: 22262, Win: 36.17%, PV: H5 T12 L16 J4 J5 T11 N4 L15 O3 P4 N3 O2 D11 T4 S6 J1 J4 H1 N5 Q5
Playouts: 23669, Win: 36.11%, PV: H5 T12 L16 J4 J5 T11 N4 L15 O3 P4 N3 O2 D11 T4 S6 J1 J4 H1 N5 Q5
Playouts: 25069, Win: 36.02%, PV: H5 T12 L16 J4 J5 T11 N4 L15 O3 P4 N3 O2 D11 T4 S6 J1 J4 H1 N5 Q5
Playouts: 26463, Win: 35.88%, PV: H5 T12 L16 J4 J5 T11 N4 L15 O3 P4 N3 O2 D11 T4 S6 J1 J4 H1 N5 Q5

  H5 ->   25803 (V: 36.36%) (N:  0.01%) PV: H5 T12 L16 J4 J5 T11 N4 L15 O3 P4 N3 O2 D11 T4 S6 J1 J4 H1 N5 Q5
 L16 ->     474 (V: 35.13%) (N:  4.05%) PV: L16 L15 H5 J4 J5 J1 J4 H1 N4 N3 N5 Q5 S6 T4 T12 D11 E12 F13 E13 E14 L19 B15 A14 A15 M19 D4 M7 O7 P7 G11 P9 F11 C9
  C3 ->     165 (V: 36.07%) (N:  0.15%) PV: C3 D4 H5 T4 S6 J4 J5 J1 J4 H1 N4 N3 N5 Q5 D11 E13
  T4 ->     162 (V: 20.28%) (N: 18.41%) PV: T4 J1 Q5 T5 P4 N4 Q3 T4 S6 Q4 P5
 T12 ->     122 (V: 20.90%) (N: 13.21%) PV: T12 J1 J3 J2 H5 J3 N4 N3 N5 T4 S6 Q5
  Q5 ->      95 (V: 27.73%) (N:  5.73%) PV: Q5 J1 P4 N4 Q3 J3 Q4 H5
 B15 ->      67 (V: 31.88%) (N:  2.00%) PV: B15 J1 A15 T4
 L19 ->      54 (V: 26.96%) (N:  3.45%) PV: L19 J1 M19 T4 S6 Q5 N4 N3 N5 J3 H5 E13 E12
  N4 ->      47 (V: 21.19%) (N:  5.13%) PV: N4 J1 D11 T4 H5 J3 N3 O3 N5
 F11 ->      46 (V: 31.44%) (N:  1.46%) PV: F11 J1 T4 B15 T5 E13 D11
 A15 ->      43 (V: 30.00%) (N:  1.80%) PV: A15 J1 B15 T4 N4 N3 N5 Q5 S6 P7 H5
 E14 ->      39 (V: 31.75%) (N:  1.14%) PV: E14 J1 T4 E13 E12 F13 T5 N4 D11 L19
 J18 ->      39 (V: 31.24%) (N:  1.44%) PV: J18 T4 H5 J4 J5 N4 J4 Q5 S6 T12
  J8 ->      37 (V: 33.61%) (N:  0.61%) PV: J8 T4 H5 J4 J5 J1 J4 H1 N4 N3 N5 Q5 S6 E13 E12 D11 F13 E14
 D11 ->      35 (V: 23.18%) (N:  3.30%) PV: D11 J1 N4 N3 N5 T4 S6 Q5 H5 J3 O7 P7
 B19 ->      30 (V: 33.19%) (N:  0.68%) PV: B19 T4 H5 J4 J5 J1 J4 H1 S6 N4 Q5 P4 D11 E13 E12 F13 F11
 E13 ->      30 (V: 14.43%) (N:  4.78%) PV: E13 J1 T12 T4 S6 Q5 P7 N4
 B13 ->      23 (V: 33.93%) (N:  0.34%) PV: B13 T4 H5 J4 J5 J1 J4 H1 S6 N4 Q5 P4 D11
  C1 ->      22 (V: 33.59%) (N:  0.22%) PV: C1 T4 H5 J4 J5 J1 J4 H1 N4 N3 N5 Q5 S6 T12 D11
  O3 ->      20 (V: 34.93%) (N:  0.16%) PV: O3 J1 N4 P4 N3 O2 D11 T4 S6
  T2 ->      20 (V: 34.05%) (N:  0.20%) PV: T2 T4 H5 J4 J5 J1 J4 H1 D11 N4 Q5 P4 S6 E13
 E19 ->      20 (V: 19.37%) (N:  2.31%) PV: E19 J1 H5 J3 N4 N3 N5 T4 S6 Q5
 F13 ->      17 (V: 14.22%) (N:  2.61%) PV: F13 J1 D11 T4 S6 E13 E12 E14
  K7 ->      15 (V: 36.09%) (N:  0.02%) PV: K7 T4 H5 J4 J5 J1 J4 H1 S6 N4 Q5
  B3 ->      13 (V: 32.61%) (N:  0.29%) PV: B3 J1 A3 C3 B2 C2 B1
  O7 ->      13 (V: 24.51%) (N:  1.13%) PV: O7 T4 S6 J1 P7 Q5 M7
 G19 ->      12 (V: 20.32%) (N:  1.27%) PV: G19 J1 T4 T12 N4 T5 S6 T4
 A14 ->      10 (V: 31.01%) (N:  0.41%) PV: A14 J1 H5 J3 N4 N3 N5 T4 S6
  J9 ->       9 (V: 23.59%) (N:  0.85%) PV: J9 J1 D11 T4 S6 Q5 N4 N3 N5 J3
 G11 ->       9 (V: 18.22%) (N:  1.16%) PV: G11 J1 D11 T4 S6 N4 H5
 T16 ->       8 (V: 28.36%) (N:  0.28%) PV: T16 J1 D11 T4 S6 Q5 P7 N4 O7
  Q1 ->       7 (V: 28.70%) (N:  0.21%) PV: Q1 J1 H5 J3 D11 T4 S6
 A11 ->       7 (V: 27.81%) (N:  0.31%) PV: A11 J1 H5 J3 N4 N3 N5 Q5
 O19 ->       7 (V: 23.92%) (N:  0.64%) PV: O19 T4 S6 J1 H5 J3 N4
 S18 ->       6 (V: 24.77%) (N:  0.31%) PV: S18 J1 D11 T4 S6 Q5 N4
  C2 ->       6 (V: 21.49%) (N:  0.59%) PV: C2 J1 H5 J3
  P7 ->       6 (V: 16.89%) (N:  0.88%) PV: P7 J1 T4 N4 T5
  M7 ->       6 (V: 15.53%) (N:  0.96%) PV: M7 J1 O7 T4 P7 N4
  S6 ->       5 (V: 32.59%) (N:  0.02%) PV: S6 T4 H5 J4 J5
 S19 ->       5 (V: 29.15%) (N:  0.29%) PV: S19 J1 T4 N4 T5 E13
 E12 ->       5 (V: 25.72%) (N:  0.41%) PV: E12 J1 D11 E14 H5 J3
 C19 ->       5 (V: 24.02%) (N:  0.30%) PV: C19 J1 D11 T4 S6 E13
  A2 ->       5 (V: 23.45%) (N:  0.40%) PV: A2 J1 T4 Q5
  A8 ->       5 (V: 23.38%) (N:  0.42%) PV: A8 J1 T4 T12 T5 T11
 A18 ->       5 (V: 22.01%) (N:  0.50%) PV: A18 J1 T4 N4 T5 Q5
  H8 ->       5 (V: 21.92%) (N:  0.47%) PV: H8 J1 T4 L19 T5 N4
  B2 ->       5 (V: 21.30%) (N:  0.59%) PV: B2 C2 H5 J4
  C9 ->       4 (V: 26.25%) (N:  0.05%) PV: C9 T4 S6 J1 N4
 S17 ->       4 (V: 25.10%) (N:  0.32%) PV: S17 J1 D11 E13 E12
 A17 ->       4 (V: 24.97%) (N:  0.26%) PV: A17 J1 T4 N4 T5
  E1 ->       4 (V: 24.29%) (N:  0.28%) PV: E1 J1 D11 E13 E12
 R19 ->       4 (V: 24.06%) (N:  0.25%) PV: R19 J1 D11 J3 H5
  F1 ->       4 (V: 23.88%) (N:  0.34%) PV: F1 J1 T4 L19 T5
 B18 ->       4 (V: 23.60%) (N:  0.36%) PV: B18 J1 T4 N4 T5
  O2 ->       4 (V: 22.61%) (N:  0.23%) PV: O2 J1 N4 N3 N5
 S14 ->       4 (V: 13.09%) (N:  0.55%) PV: S14 J1 T4 E13 E12
 J19 ->       4 (V: 13.01%) (N:  0.73%) PV: J19 J1 T4 L16 T5
 H19 ->       4 (V:  8.73%) (N:  0.94%) PV: H19 J1 D11 E13 E12
  O1 ->       3 (V: 29.89%) (N:  0.18%) PV: O1 J1 T4 J3
 P17 ->       3 (V: 29.77%) (N:  0.01%) PV: P17 T4 S6 J1
 Q19 ->       3 (V: 20.16%) (N:  0.30%) PV: Q19 J1 T4 E13
 B12 ->       3 (V: 19.34%) (N:  0.35%) PV: B12 J1 H5 J3
 C13 ->       3 (V: 17.32%) (N:  0.29%) PV: C13 J1 H5 J3
 K15 ->       3 (V: 15.83%) (N:  0.42%) PV: K15 J1 T4 N4
 Q16 ->       2 (V: 25.44%) (N:  0.00%) PV: Q16 J1 T4
  T1 ->       2 (V: 24.26%) (N:  0.13%) PV: T1 T4 S6
 N18 ->       2 (V: 23.79%) (N:  0.01%) PV: N18 J1 T4
  L6 ->       2 (V: 23.76%) (N:  0.01%) PV: L6 J1 T4
  S2 ->       2 (V: 22.44%) (N:  0.19%) PV: S2 J1 D11
 T17 ->       2 (V: 22.30%) (N:  0.28%) PV: T17 J1 D11
  A1 ->       2 (V: 21.42%) (N:  0.16%) PV: A1 J1 T4
 R17 ->       2 (V: 20.49%) (N:  0.29%) PV: R17 J1 T4
  P1 ->       2 (V: 20.22%) (N:  0.20%) PV: P1 J1 T4
 T19 ->       2 (V: 19.68%) (N:  0.19%) PV: T19 J1 D11
  T7 ->       2 (V: 16.07%) (N:  0.11%) PV: T7 T4 S6
  N3 ->       2 (V: 15.42%) (N:  0.20%) PV: N3 N4 H5
 A19 ->       2 (V: 15.03%) (N:  0.26%) PV: A19 J1 H5
 A10 ->       2 (V: 14.67%) (N:  0.27%) PV: A10 J1 T4
  A3 ->       2 (V: 14.46%) (N:  0.19%) PV: A3 B3 H5
  A9 ->       2 (V: 13.79%) (N:  0.46%) PV: A9 J1 D11
  B1 ->       2 (V: 13.41%) (N:  0.40%) PV: B1 J1 T4
  M1 ->       2 (V: 13.30%) (N:  0.18%) PV: M1 J1 T4
  A7 ->       2 (V: 13.10%) (N:  0.39%) PV: A7 J1 T4
 P19 ->       2 (V: 12.47%) (N:  0.35%) PV: P19 J1 T4
 E15 ->       2 (V: 12.21%) (N:  0.35%) PV: E15 E14 H5
 T18 ->       2 (V: 11.98%) (N:  0.26%) PV: T18 J1 T4
 D19 ->       2 (V: 11.15%) (N:  0.51%) PV: D19 J1 D11
 R18 ->       2 (V: 10.58%) (N:  0.46%) PV: R18 J1 T4
pass ->       2 (V: 10.28%) (N:  0.27%) PV: pass J1 D11
 Q18 ->       2 (V:  9.23%) (N:  0.36%) PV: Q18 J1 T4
  D1 ->       2 (V:  8.77%) (N:  0.38%) PV: D1 J1 T4
 S15 ->       2 (V:  8.43%) (N:  0.32%) PV: S15 J1 D11
 L15 ->       2 (V:  8.21%) (N:  0.51%) PV: L15 L16 H5
  N1 ->       1 (V: 18.92%) (N:  0.13%) PV: N1 J1
  R2 ->       1 (V: 17.22%) (N:  0.15%) PV: R2 J1
  D2 ->       1 (V: 13.95%) (N:  0.29%) PV: D2 C2
27712 visits, 2626155 nodes, 27712 playouts, 554 n/s

= H5

**Comment by earthengine** [comment]
It looks like the logic consider the real suicide H5 as not suicide, but a legal move J1 as suicide.

**Comment by killerducky** [comment]
It's a sabaki bug:
https://github.com/yishn/Sabaki/pull/294

**Comment by earthengine** [comment]
I don't think so. What I can see in the log file is that it never even consider J1, and at move 263 it never consider N5, which is not a suicide, although it jumps into an eye. I think it is leelaz that get confused with what the suicide rule actually means.

**Comment by killerducky** [comment]
Just look at your own logfile, it has at the beginning: 
```
play B A13
play B A12
```

The moves given out of order by Sabaki, but Leela requires the moves to be in order. Please try repeating this from the console and you'll see it works perfectly:

```
leela <options>
loadsgf filename.sgf 298
genmove w

```
You will see it never considers the illegal H5 move.

**Comment by killerducky** [comment]
Looks like he has fixed the issue, he has made a bunch of commits in the last few days so I expect he will make a release soon. Here is the one that fixes this issue:

https://github.com/yishn/Sabaki/pull/316

**Comment by earthengine** [comment]
You are right for the illegal move. But the other concern is still. In the playout, I saw that it consider J1 as a black legal move, not white. In the `genmove w` command, it never consider J1, and J1 appear in an response of subsequent black move. This is still a bug.

**Comment by killerducky** [comment]
Please post your leela command line, the commands you give leela, and the console output.

**Comment by earthengine** [comment]
Never mind. I saw the code for "loadsgf", it says if I pass 298 the actual steps it followed is 297. But I thought I should pass 297 as it is the last move number.

**Comment by earthengine** [comment]
In my opinion, it is better for whatever reason, to allow `genmove` and `play` for two subsequent move of both sides. It should be treated as if there is a pass in the middle.

**Comment by billyswong** [comment]
Allowing `genmove` twice on the same color may be a fine idea, but treating it as if there is a pass in the middle may be bad because there is the case of double-pass to premature win by TT scoring. Treating consecutive moves of the same color like free placement handicap stones may be a more proper method.

**Comment by earthengine** [comment]
@billyswong So this have to be a special kind of pass, which means it is not count as a usual pass, so pass on this situation is not a win.
