### ISSUE TITLE
AutoGTP shows "GPU 0" even for CPU only version

### ISSUE THREAD

**Issue by MaxMaki** [leela-zero/leela-zero#593]
Hi,

I wanted to test running the GPU AutoGTP and the CPU AutoGTP at the same time to maximize unused CPU cores.

But it seems that the CPU AutoGTP launches and uses the GPU as well?

I get the following when launching the CPU only AutoGTP (windows 64-bit)

AutoGTP v11
Using 1 thread(s) for GPU(s).
Starting thread 1 on GPU 0.

Is this correct?

**Comment by marcocalignano** [comment]
@MaxMaki This is only a test output. If you do not use the parameter -u leelaz is started without the option --gpu that means, depending on how you compiled it (I guess), leelaz will use the CPU or the first GPU available.

**Comment by gcp** [comment]
It's basically a small AutoGTP display glitch.

**Comment by MaxMaki** [comment]
Ok, thanks for the info!
