### ISSUE TITLE
FR: Best move for W (or B)

### ISSUE THREAD

**Issue by JDJoe** [leela-zero/leela-zero#612]
Pleas implement: Best move for White (or Black) 

Leela calculates best moves and returns 5 best possible moves 1,2,3,4,5 so it can be shown on the board. 

(for a working example, please see Pachi+GoGui) It's a really helpful tool.

![screenshot_20180108_192315](https://user-images.githubusercontent.com/19360446/34682999-6d47588e-f4a9-11e7-8b31-31c4bf5fcbb3.png)

**Comment by gcp** [comment]
I think those are gogui specific extensions, and gogui is very dead :-/

**Comment by roy7** [comment]
Gogui had a full extendable command system that is pretty cool. When it connects to an engine it will find out what features it supports and offer them in the interface. I sort of forgot all about that but maybe I will look at adding heatmaps for display in gogui for the fun of it.

**Comment by roy7** [comment]
It'd rock if someone added support for gogui extensions into Sabaki.

**Comment by JDJoe** [comment]
> It'd rock if someone added support for gogui extensions into Sabaki.

Yes. This is where I was kinda going with that.

**Comment by killerducky** [comment]
Here are some guis to try that are adding LZ support:
https://github.com/yishn/LeelaSabaki (same author as Sabaki)
https://github.com/pnprog/goreviewpartner

**Comment by pnprog** [comment]
Regarding GoReviewPartner, I pushed the code on github for support for Leela Zero on Monday. It's working fine, but I am still testing it before releasing a Windows version.

**Comment by JDJoe** [comment]
Bump...

**Comment by gcp** [comment]
Are you volunteering to add this?

**Comment by JDJoe** [comment]
> Are you volunteering to add this?

I wish I knew how :)
