### ISSUE TITLE
How strong is 5x64 human trained?

### ISSUE THREAD

**Issue by Yoitsu36** [leela-zero/leela-zero#628]
Currently, we know that human trained 6x128 is around 2600-2700 elo in CGOS, but how strong is the 5x64 version network? would be interesting to compare the current zero one with a human trained one now that the zero is flattening.

**Comment by gcp** [comment]
Train one and find out?

**Comment by Yoitsu36** [comment]
well, i dont really know how to train it nor do i know where to get all the games, was mostly asking in case it already had been done by anyone.

**Comment by zediir** [comment]
@gcp Was going to ask, what dataset did you use to train the supervised net?

**Comment by gcp** [comment]
https://github.com/yenw/computer-go-dataset

All the strong human games from here.

**Comment by jkiliani** [comment]
Is there currently something like a "no promote" flag for submitted matches, that allows testing a network on the distributed infrastructure without it  being promoted if it beat best network? There should be, from the retesting of old networks after distributed testing went live. Could this be used to test best_v1 and other supervised learning nets against current reinforcement learning nets? This may make it much easier for @zediir or anyone else to train a strong supervised net, if supervised learning has the same extreme seesaw in strength  when sampled at different times.

**Comment by zediir** [comment]
If I can be bothered to set up and train it, I was planning on just using the validation qt project to check a couple of the trained networks.

**Comment by CamWagner** [comment]
I got one to maybe 1d, but I didn't test for very long. LeelaZ surpassed it already :)

**Comment by LetterRip** [comment]
@GamWagner - could you make your model available?

**Comment by CamWagner** [comment]
OK give me a few hours and I'll test my models to figure out which one is the strongest, then release here

**Comment by CamWagner** [comment]
Here is the best 5-block net I trained: [leelaz-model-16000.txt](https://github.com/gcp/leela-zero/files/1621420/leelaz-model-16000.txt)

I played 388 400-playout games to test which net I had was the best. This was (probably, iirc) trained starting from network 58da6176 (December 31), on the computer go dataset, including a few AI games, but mostly human games. I stopped training also on December 31.

I tested 2000, 4000, 8000, 16000, 64000, 128000, and 256000 steps against each other. (32000 has somehow disappeared into the void behind the recycle bin). I can't remember which learning rate I used, it was either 0.001 or 0.0001.

I played a few games with 1600 playouts against the current net (46ff4b9 on Jan 10, mind you this is an 11 day difference in training), it won 2/13. Against the 6 block network (5 block having 1600, 6 block having 666 playouts), it won 0/22. I'd be interested to see how it would do against 58da6176, but I've done 423 test matches so far, someone else please do it and report back!

**Comment by pangafu** [comment]
But I remember google is use human game to init net parameters, then use self-play to upgrade network. so can't say current leela zero beat human network. 
If we do self-play on human network, they maybe all can reach same elo.

**Comment by CamWagner** [comment]
Ur right I would like to do self play, unfortunately my dataset didn't include weaker games so it tended not to know about low level mistakes, some self atari, some wrong second line cuts... By starting on the LZ network I thought it might know about the basics so that it learns more.

I'd love to train a human one with self play but I don't have the resources.

**Comment by isty2e** [comment]
The supervised net in the AGZ paper did not undergo any reinforcement learning. Initialization with supervised network + self-play reinforcement learning led to AGM, not the network in Fig. 3, for example.

**Comment by zediir** [comment]
Supervised 5x64 net trained with with TYGEM ~1.5M 9p v. 9p games.

https://drive.google.com/open?id=1S5rpVgOOA-JncjTsNiKIQC7b18qzYMDu

>step 1000000, policy=1.76137 mse=0.196145 reg=0.163062 total=2.70901 (2921.92 pos/s)
>step 1000000, training accuracy=49.1797%, mse=0.198143

Running it against c83e1b locally now.

**Comment by CamWagner** [comment]
@zediir wow that looks really good, much better than anything I could train. How did your training process work?

**Comment by Marcin1960** [comment]
I wonder what would happen if you trained it on high dan games together with low dan and high kyu?

**Comment by Alderi-Tokori** [comment]
>the 1M network won by around 3:1

That is not really statistically significant at all. I've seen nets have 7:0 at first then lose in the end. You need to run more games (a full SPRT test) in order to say if it's really stronger or not.

**Comment by evanroberts85** [comment]
Two numbers between a colon usually indicates a ratio. so around 75% win rate.

**Comment by zediir** [comment]
I neant in the ratio 3:1. Actual played games was around 200

**Comment by zediir** [comment]
```
21 wins, 47 losses
The first net is worse than the second
.\tygm1M v .\c83e1b ( 68 games)
              wins        black       white
.\tygm1M   21 30.88%   11 32.35%   10 29.41%
.\c83e1b   47 69.12%   23 67.65%   24 70.59%
                       34 50.00%   34 50.00%
```

```
37 wins, 61 losses
The first net is worse than the second
.\tygm1M v .\830158 ( 98 games)
              wins        black       white
.\tygm1M   37 37.76%   19 38.00%   18 37.50%
.\830158   61 62.24%   31 62.00%   30 62.50%
                       50 51.02%   48 48.98%
```

```
The first net is better than the second
.\tygm1M v .\7fcf3c ( 111 games)
              wins        black       white
.\tygm1M   73 65.77%   37 64.91%   36 66.67%
.\7fcf3c   38 34.23%   20 35.09%   18 33.33%
                       57 51.35%   54 48.65%
```

```
30 wins, 2 losses
The first net is better than the second
.\tygm1M v .\0c0941 ( 32 games)
              wins        black       white
.\tygm1M   30 93.75%   15 100.00%   15 88.24%
.\0c0941    2  6.25%    0  0.00%    2 11.76%
                       15 46.88%   17 53.13%
```

So somewhere between 830158 and 7fcf3c

**Comment by Alderi-Tokori** [comment]
> A colon rather than a dash between two numbers usually indicates a ratio. so around 75% win rate.

I didn't know that, thank you.

**Comment by zediir** [comment]
40b94c results. Seems like the supervised net is about as strong as the selfplay one was at about where training started to slow down

```
147 wins, 105 losses
The first net is better than the second
.\tygm1M v .\40b94c ( 252 games)
              wins        black       white
.\tygm1M  147 58.33%   73 57.94%   74 58.73%
.\40b94c  105 41.67%   53 42.06%   52 41.27%
                      126 50.00%  126 50.00%
```

**Comment by sethtroisi** [comment]
We have very strong SL and RL nets now. closing >1year old issue
