### ISSUE TITLE
Strange behavior?

### ISSUE THREAD

**Issue by holicst** [leela-zero/leela-zero#653]
Hi,

It looks like all successful networks start fine and then win rate starts to fall. I always get excited when a new network starts to achieve 60% for example and then it always drops and hopefully stays above 50%.

If I'd want to sabotage the project then I'd do it with the distributed test matches. Simply check on the website which network looks promising and then I'd submit only it's games in which it loses. That way it's easy to make them fall below 55% (or whatever the limit is) and it's much simpler than sabotaging the training process itself.

Am I the only one who noticed this (subjective anyway)? Can we make a chart of the win rate of each network over time (or games played) to double check this based on data and not assumptions?

Cheers,
Tamás

**Comment by gcp** [comment]
>It looks like all successful networks start fine

What's your definition of "successful"? One that wins early on? Note that it needs to win early on, because networks that lose early on get an early SPRT termination.

IMHO this is almost certainly purely statistical noise and trying to see patterns in it.

**Comment by holicst** [comment]
Let's say it starts with 58% after 100 or 200 games. I always seem to see a decline. Naturally I know that this might me a false alarm or just a subjective bias. If it is just a few minutes for you to check, I'd recommend to do it.

Maybe an additional logic in the client check would be to compare the winrate from games of each IP address and if it differs radically from the average then consider it sabotage.

**Comment by jkiliani** [comment]
@holicst This would be really difficult to do, because to test this hypothesis you'd basically need to do an SPRT test of games restricted to one subset of clients against another subset. Individual clients tend not to submit that many games for a single match that these results would reach significance levels.

**Comment by gcp** [comment]
>Let's say it starts with 58% after 100 or 200 games.

To illustrate what I mean, it's not possible to see 42% after 100 or 200 games because that will mean an early SPRT termination.

**Comment by gcp** [comment]
>Individual clients tend not to submit that many games for a single match that these results would reach significance levels.

Unless it's a DDOS that also means they can't influence the match result much.

Note that clicking on "vs" on the homepage already allows you to see the submitted match games and results per client. So you can investigate this, if you want.

**Comment by holicst** [comment]
Great, now I'm convinced. If you are not afraid of this then I'm not worried also :)

**Comment by thynson** [comment]
It looks like that such behaviour appears when the new networks wins in less move number, in average, while the old network win in more move number, so the new network advances quickly from the beginning, and then be caught up by the old one as match grows.

**Comment by d7urban** [comment]
Let’s say we ha a network that after many matches settles on 45%, if this network, by chance, gets wins early on and a high win rate, it will settle towards the mean of 45% the more games are played.

**Comment by LetterRip** [comment]
What you are seeing is called regression towards the mean.  A bad or ok network that is lucky at first will start high but over time will lose the expected amount - so will have a steadily decreasing score till it reaches its expected score.  A bad network that gets normal or unlucky results will terminate early.  An ok network that gets ok results will play out till the end.  An ok network that gets unlucky might terminate early or will start bad but always be on the verge of failure till the end.

**Comment by marcocalignano** [comment]
Another (maybe) strange thing is a Black pass on the 1st move. I am using the /next branch with winograd and network , is this normal 0db82470729f053191d66e7c866cbeb7a036fb232ac5524eea62642bf6e7ada3.

**Comment by jkiliani** [comment]
@marcocalignano Should be possible theoretically... even if pass in no longer in the empty board policy priors, it could be selected by Dirichlet noise for one playout. Even without any additional playouts happening, at temperature 1 the pass may then be picked as move, although with a very low probability.

If you saw this happen just once it should be just a fluke. If you see it happening multiple time, it would warrant investigation.

**Comment by jkiliani** [comment]
I just saw something strange:

 {
    "cmd": "selfplay",
    "hash": "c83e1b6e0ffbf8e684f2d8f6261853f14c553b29ee0e70ff6c34e87d28009c43",
    "leelaz_version": "0.10",
    "options": {
        "noise": "true",
        "playouts": "1600",
        "randomcnt": "30",
        "resignation_percent": "0"
    },
    "options_hash": "cf1fad",
    "random_seed": "9452221766682348802",
    "required_client_version": "11"
}

Got new job: selfplay
net: c83e1b6e0ffbf8e684f2d8f6261853f14c553b29ee0e70ff6c34e87d28009c43.
Engine has started.
Infinite thinking time set.
1 (B R4) 2 (W D16) 3 (B D4) 4 (W Q17) 5 (B C17) 6 (W Q15) 7 (B D17) 8 (W C3) 9 (B E16) 10 (W L12) 11 (B P4) 12 (W D3) 13 (B E4) 14 (W C4) 15 (B R14) 16 (W R15) 17 (B R11) 18 (W R9) 19 (B Q14) 20 (W R6) 21 (B P15) 22 (W P14) 23 (B P16) 24 (W S14) 25 (B Q16) 26 (W R16) 27 (B S13) 28 (W P17) 29 (B N16) 30 (W O14) 31 (B N15) 32 (W S15) 33 (B R17) 34 (W R18) 35 (B S17) 36 (W S18) 37 (B T14) 38 (W T17) 39 (B P12) 40 (W N13) 41 (B K16) 42 (W N3) 43 (B O11) 44 (W O7) 45 (B N4) 46 (W M4) 47 (B N5) 48 (W O3) 49 (B P3) 50 (W J4) 51 (B D6) 52 (W D8) 53 (B Q8) 54 (W R8) 55 (B Q7) 56 (W Q9) 57 (B O9) 58 (W P8) 59 (B M8) 60 (W D11) 61 (B G4) 62 (W P9) 63 (B L4) 64 (W M5) 65 (B M3) 66 (W L3) 67 (B M2) 68 (W L2) 69 (B C5) 70 (W M6) 71 (B N6) 72 (W N7) 73 (B M7) 74 (W N2) 75 (B E3) 76 (W D14) 77 (B L6) 78 (W M1) 79 (B M3) 80 (W M2) 81 (B L5) 82 (W M3) 83 (B F14) 84 (W H12) 85 (B F12) 86 (W P2) 87 (B S6) 88 (W S5) 89 (B R5) 90 (W S7) 91 (B Q6) 92 (W T6) 93 (B Q2) 94 (W R2) 95 (B P1) 96 (W N9) 97 (B M10) 98 (W N10) 99 (B N11) 100 (W M9) 101 (B L9) 102 (W N8) 103 (B L11) 104 (W M12) 105 (B M11) 106 (W L8) 107 (B R3) 108 (W K12) 109 (B L7) 110 (W K8) 111 (B K9) 112 (W J8) 113 (B J9) 114 (W J6) 115 (B H8) 116 (W H7) 117 (B G8) 118 (W H15) 119 (B J15) 120 (W H14) 121 (B H16) 122 (W F15) 123 (B E15) 124 (W G16) 125 (B J14) 126 (W J13) 127 (B G17) 128 (W H17) 129 (B J16) 130 (W F17) 131 (B G18) 132 (W E14) 133 (B F16) 134 (W G15) 135 (B D15) 136 (W F13) 137 (B C14) 138 (W C15) 139 (B C16) 140 (W C13) 141 (B B15) 142 (W S2) 143 (B S3) 144 (W O1) 145 (B O2) 146 (W Q13) 147 (B R13) 148 (W P2) 149 (B Q1) 150 (W H18) 151 (B F18) 152 (W M17) 153 (B E13) 154 (W G14) 155 (B N14) 156 (W O13) 157 (B D13) 158 (W L15) 159 (B K18) 160 (W L16) 161 (B F14) 162 (W B8) 163 (B B5) 164 (W C12) 165 (B L17) 166 (W M18) 167 (B G7) 168 (W H5) 169 (B M16) 170 (W K14) 171 (B O17) 172 (W O15) 173 (B N18) 174 (W T2) 175 (B T3) 176 (W K15) 177 (B G13) 178 (W H13) 179 (B L18) 180 (W M19) 181 (B J18) 182 (W J17) 183 (B K17) 184 (W O18) 185 (B N17) 186 (W E2) 187 (B F2) 188 (W D2) 189 (B P18) 190 (W Q18) 191 (B B2) 192 (W B3) 193 (B A3) 194 (W A4) 195 (B A2) 196 (W B4) 197 (B A5) 198 (W F1) 199 (B G2) 200 (W B1) 201 (B O19) 202 (W P5) 203 (B O16) 204 (W M14) 205 (B Q5) 206 (W O4) 207 (B O2) 208 (W C2) 209 (B P6) 210 (W O6) 211 (B J11) 212 (W H11) 213 (B E10) 214 (W F9) 215 (B C9) 216 (W B9) 217 (B C8) 218 (W C7) 219 (B C10) 220 (W D7) 221 (B E9) 222 (W E6) 223 (B F6) 224 (W B10) 225 (B L13) 226 (W C11) 227 (B F10) 228 (W H10) 229 (B H9) 230 (W G10) 231 (B K11) 232 (W G12) 233 (B F13) 234 (W G9) 235 (B F8) 236 (W E8) 237 (B F11) 238 (W G6) 239 (B F5) 240 (W M15) 241 (B N19) 242 (W Q12) 243 (B Q11) 244 (W P13) 245 (B R12) 246 (W Q19) 247 (B L19) 248 (W G1) 249 (B H2) 250 (W J2) 251 (B H1) 252 (W E1) 253 (B B7) 254 (W B6) 255 (B A7) 256 (W A8) 257 (B A6) 258 (W C6) 259 (B D5) 260 (W B13) 261 (B A12) 262 (W A11) 263 (B D9) 264 (W A13) 265 (B E7) 266 (W A14) 267 (B A15) 268 (W J12) 269 (B S9) 270 (W S10) 271 (B R10) 272 (W T9) 273 (B S11) 274 (W S8) 275 (B pass) 276 (W J10) 277 (B K10) 278 (W S9) 279 (B G5) 280 (W H6) 281 (B G3) 282 (W P10) 283 (B P11) 284 (W M17) 285 (B M18) 286 (W P2) 287 (B R1) 288 (W Q3) 289 (B O2) 290 (W R7) 291 (B N1) 292 (W T18) 293 (B O5) 294 (W O1) 295 (B P2) 296 (W P5) 297 (B N1) 298 (W O5) 299 (B O1) 300 (W S1) 301 (B T1) 302 (W M13) 303 (B J7) 304 (W K7) 305 (B K6) 306 (W J7) 307 (B H4) 308 (W J5) 309 (B J3) 310 (W K3) 311 (B H3) 312 (W J1) 313 (B C18) 314 (W B14) 315 (B O8) 316 (W S1) 317 (B O10) 318 (W P7) 319 (B B16) 320 (W resign) Game has ended.
Score: B+Resign 
Winner: black
Stopping engine.
Uploading game: 96a8b830b3644d228886d27fa6641262.sgf for network c83e1b6e0ffbf8e684f2d8f6261853f14c553b29ee0e70ff6c34e87d28009c43
Game data eb8764f6d926a63c76b22e259c46385e627a6899a2dae74991ca1d922df30209 stored in database
9 game(s) (9 self played and 0 matches) played in 301 minutes = 2010 seconds/game, 6457 ms/move, last game took 2107 seconds.

If a client is assigned a r=0 game, how can there be a resignation?

**Comment by roy7** [comment]
Here's the game in question.

http://zero.sjeng.org/view/eb8764f6d926a63c76b22e259c46385e627a6899a2dae74991ca1d922df30209?viewer=wgo

Since @jkiliani is on /next the arguments are in the SGF comments, and -r 0 was definitely sent to leelaz. (At least the side of the match that saved out the SGF file. I assume both sides get an identical argument list.)

**Comment by gcp** [comment]
This was probably regressed by https://github.com/gcp/leela-zero/commit/d0eaa6b512f276f84a231aa915dadcc8f3070f22.

**Comment by gcp** [comment]
I don't see anything immediately wrong, but https://github.com/gcp/leela-zero/commit/d0eaa6b512f276f84a231aa915dadcc8f3070f22#diff-70aab7683fe64f9428b8bc47d1d183c0R167 is sensitive to floating point rounding. So I guess it could resign if the score is very close or essentially 0.

**Comment by roy7** [comment]
I don't see how those changes would fail on resign_pct being 0, but I'm guessing bestscore > resign_threshold or bestscore > handicap_resign_threshold had a situation where bestscore was below zero. Is that possible? In the same way win % can be over 100%.

If so, then should a check be done for resign_pct == 0 return false regardless of bestscore?

**Comment by gcp** [comment]
>if (bestscore > resign_threshold) {

This will fail if the score is exactly 0, the next if will also fail, and at the end we return true = resign.

**Comment by roy7** [comment]
if (resign_threshold == 0) { return false; }

Somewhere early in the function then?

**Comment by gcp** [comment]
Did you not see the commit above? :-)

**Comment by roy7** [comment]
Oh. Oops. :)

**Comment by jkiliani** [comment]
Same thing just happened again, in http://zero.sjeng.org/view/ebf69ef0d90cf2174a5f07415a45305dd6bb7798daa63010acfd6a677adf9d30?viewer=wgo

Once can be a fluke, but twice in a row? It's very possible this issue is widespread among /next clients who include https://github.com/gcp/leela-zero/commit/d0eaa6b512f276f84a231aa915dadcc8f3070f22 but not yet https://github.com/gcp/leela-zero/commit/1e8de8ab01ec82f4fe7d298624cc0a7f0836beda

**Comment by marcocalignano** [comment]
@gdp You could have solved with this:
`if (bestscore >= resign_threshold) `

**Comment by roy7** [comment]
@marcocalignano If bestscore was somehow negative, it's resign. Best to special case 0 directly?

@jkiliani I loaded that 2nd example into leela and:

genmove w
Thinking at most 50.0 seconds...
NN eval=0.000000

So the NN eval was in fact 0 causing the issue.

**Comment by roy7** [comment]
If I undo a lot, the NN eval is basically 1.000000 for black for many moves already. So it must have resigned once the floating point ended up so small it was 0.

**Comment by gcp** [comment]
@marcocalignano I wanted to avoid any issues with the fp comparison, makes sense to special case this out I think.

**Comment by marcocalignano** [comment]
@roy7 since `bestscore` rappresents a probability, if it becomes negative there is a calculation problem in leelaz.

**Comment by gcp** [comment]
IEEE 754 floating point has negative zeroes. (Not sure they are a possible issue here)

**Comment by roy7** [comment]
I didn't go look how NN eval is calculated. I just recall Leela can sometimes have win rates over 100%, so I thought perhaps a losing win rate under 0% might be possible on the other side. :)

**Comment by gcp** [comment]
Regular Leela fiddles with the probabilities a bit, Leela Zero doesn't do that. So @marcocalignano is right that it should be in the [0..1.0] range. I was just a little unsure about those edges.

**Comment by marcocalignano** [comment]
@gcp You get a negative zero only when a really little **negative** number is rounded to zero, and the sign is evaluated only in 1/+0 = +inf or 1/-0 = -inf.
But your solution is good anyway this was only academic (and probably pedantic ;) )

**Comment by OmnipotentEntity** [comment]
For the record:

    #include <iostream>
    #include <cmath>

    int main() {
      const double a = -0.0;
      const double b = 0.0;

      std::cout << "a is " << (std::signbit(a) ? "negative." : "positive.") << std::endl;
      std::cout << "a is " << (a >= b ? "" : "not ") << "greater than or equal to b." << std::endl;
    }

Will print:

> a is negative.  
> a is greater than or equal to b.

**Comment by Marcin1960** [comment]
Leela Zero got cheated :)


[petgo3-JeanPenn.zip](https://github.com/gcp/leela-zero/files/1804050/petgo3-JeanPenn.zip)
