### ISSUE TITLE
Upload failed message after every games. (Curl returned non-zero exit code: 26)

### ISSUE THREAD

**Issue by Dorus** [leela-zero/leela-zero#671]
Since 10.1 i get the following message between all my games:

![afbeelding](https://user-images.githubusercontent.com/4461459/35126294-15f62630-fcad-11e7-9efa-7274feb98dc5.png)

> Upload failed. Curl returned non-zero exit code: 26
> Network connection to server failed.
> NetworkException: Curl returned non-zero exit code 26
> Retrying when next game is finished.

The same error repeats after every game.

Also i have a few strange files in my leela-zero dir:

02f7265f3d614ec7bd8c310d32b97355.txt.0.gz (since 18-1)
02f7265f3d614ec7bd8c310d32b97355.sgf (since 18-1)
curl_saveff3d03861a68436cbfa93a2bbf95840f.bin (since 11-1)
afbac44a9e2544a1bed5a637ce3accf7.txt.0.gz (since 11-1)
afbac44a9e2544a1bed5a637ce3accf7.sgf (since 11-1)

(However, my actual games do seem to get submitted. Possibly only these 2 failed?)

**Comment by roy7** [comment]
26 seems to be a local read error:

> 
> CURLE_READ_ERROR (26)
> 
> There was a problem reading a local file or an error returned by the read callback.

**Comment by marcocalignano** [comment]
@Dorus  Can you read the files in the list or are they corrupted? If not they could be game save with the previous version that autogtp try to send to the server after it sent the last game correctly. (In fast you Game Data ... store in the database. Try to move the file you mention to another directory and check if you get an error message even at the next game upload.

**Comment by Dorus** [comment]
I put every new version in its own directory, so these files can only be from the current version.

All i can think of is i killed leela in some non-standard way: I suspended the process after it finished one game (and did 1-3 moves in the next one) so i could let the other running game finish to close autogtp.

I can read the files, i uploaded a zip here:
[tmp.zip](https://github.com/gcp/leela-zero/files/1644833/tmp.zip)

Going to need 15 minutes for the first game to finish to see if moving the files to a sub directory solves the problem.

**Comment by Dorus** [comment]
It just happened again, 3 new files:

```text
curl_save1e4271e40c974cfebdbd7ac8041e453a.bin
c832511ac57a486e905254cd1d761bb8.sgf
c832511ac57a486e905254cd1d761bb8.txt.0.gz
```

This time I'm 100% sure i didn't mess with suspend process or anything.

**Comment by marcocalignano** [comment]
This happens when autogtp fails to upload a game to the server. After saving it starts another game and at the end try to send them both and delete all the files.

**Comment by Dorus** [comment]
Yes but... it fails to send it every time and it does not delete the file.

So somewhere there i a bug. Either autogtp created invalid data and tried to upload it, or autogtp created invalid data when temporary storing the failed upload data to the disk, or the server is rejecting valid data.

I'm pretty sure my (other) games do upload as i can see them under matches and the recent self play option.

Do i need to upload those 3 files again?

**Comment by marcocalignano** [comment]
`curl_save1e4271e40c974cfebdbd7ac8041e453a.bin` should be just text can you post the content?
Would be also cool if you could give me the output from autogtp the first time you had problem uploading. @roy7 can you look for this game `c832511ac57a486e905254cd1d761bb8.sgf` in the database?

**Comment by roy7** [comment]
The result from server where it says "Game data xxx stored in database" has the hash you'd use in the view selfplay url. Can't search by the local UID that autogtp/leela uses, those aren't stored on server.

**Comment by Dorus** [comment]
The .bin:

```text
c832511ac57a486e905254cd1d761bb8
9
-F networkhash=7fde81e8f671c710fc53be86e4b256cebc4825a652ea925d38270cfe1c86575a 
-F clientversion=13 
-F options_hash=16b7b7 
-F movescount=313 
-F winnercolor=white 
-F random_seed=1609378531 
-F sgf=@c832511ac57a486e905254cd1d761bb8.sgf.gz 
-F trainingdata=@c832511ac57a486e905254cd1d761bb8.txt.0.gz 
http://zero.sjeng.org/submit 
```

> Would be also cool if you could give me the output from autogtp the first time you had problem uploading. 

Yeah i missed that :( I was an hour away from my pc and the error happened right when i left, so it was already scrolled out of the console (even while i have quite a large buffer on it)

**Comment by marcocalignano** [comment]
@Dorus  And if you create your curl command line from the /bin output (`curl -F networkhash=7fde81e8f671c710fc53be86e4b256cebc4825a652ea925d38270cfe1c86575a -F clientversion=13 ...`) Do you get an error?

**Comment by marcocalignano** [comment]
@Dorus now I see the curl command line look for a .gz file your .sgf is not compressed yet. 
Please try the line like the .bin file says and tell me the error. then compress you .sgf file (`gzip c832511ac57a486e905254cd1d761bb8.sgf`) and try again and tell me if the last work please.

**Comment by Dorus** [comment]
Before compressing:
```Text
curl -F networkhash=7fde81e8f671c710fc53be86e4b256cebc4825a652ea925d38270cfe1c86575a -F clientversion=13 -F options_hash=16b7b7 -F movescount=313 -F winnercolor=white -F random_seed=1609378531 -F sgf=@c832511ac57a486e905254cd1d761bb8.sgf.gz -F trainingdata=@c832511ac57a486e905254cd1d761bb8.txt.0.gz http://zero.sjeng.org/submit
Warning: setting file c832511ac57a486e905254cd1d761bb8.sgf.gz  failed!
curl: (26) read function returned funny value
```
After:
```test
curl -F networkhash=7fde81e8f671c710fc53be86e4b256cebc4825a652ea925d38270cfe1c86575a -F clientversion=13 -F options_hash=16b7b7 -F movescount=313 -F winnercolor=white -F random_seed=1609378531 -F sgf=@c832511ac57a486e905254cd1d761bb8.sgf.gz -F trainingdata=@c832511ac57a486e905254cd1d761bb8.txt.0.gz http://zero.sjeng.org/submit
Game data adb121e5b7df3aaebf3e3292de7f8ae4e6474028de5233fff5f2d958a0536b12 stored in database
```

**Comment by roy7** [comment]
It has to be gzip'ed before upload, perhaps there's some sort of race condition that the upload might try to start before gzip completes?

**Comment by Dorus** [comment]
But then there should be a zipped file on my disk and the upload should succeed the next time. Somehow the zip command failed completely.

Sadly all other games so far have gone correctly, so i havn't been able to catch this bug "in the act" so to say :)

**Comment by marcocalignano** [comment]
@Dorus Let's wait to catch this bug in the act, because based on my code the .sgf file should be zipped already before it is sent. No idea why is isn't can you check of it was a gzipfile even if the extension was only .sgf?

**Comment by Dorus** [comment]
[tmp.zip](https://github.com/gcp/leela-zero/files/1650291/tmp.zip)
Plain sgf. I've uploaded all files so you can inspect them yourself if you want :)

Also i'll keep an eye out for it, but only that one out of the last 98 games all wend correctly, so it might take a while before it happens again :(

**Comment by Dorus** [comment]
Update: this has happened again twice since last month. Just today 10 hours ago with LeelaZ 0.12. This time i'm sure LeelaZ was running cleanly and i shut it down cleanly with q+enter yesterday.

However, i still havn't caught autoGTP in the act yet :( It's kinda hard with only 2 events in a month.

**Comment by Dorus** [comment]
Just had 2 more :(

![afbeelding](https://user-images.githubusercontent.com/4461459/37571034-d1562bfa-2af7-11e8-8cb2-27340783adb5.png)

These files are in my leelaZ dir:
![afbeelding](https://user-images.githubusercontent.com/4461459/37571053-0e569986-2af8-11e8-9cd6-68decd86ffbe.png)

[failfails.zip](https://github.com/gcp/leela-zero/files/1823130/failfails.zip)

Sadly i'm hours too late again to spot the error in console.

**Comment by sethtroisi** [comment]
I also had this problem. I'm deleting all my temp games and upload worked again.

**Comment by sethtroisi** [comment]
Look at that handsome poster from 13 months ago with that clever solution :)
---
several versions of the client since this issue, very obsolete
