### ISSUE TITLE
GPU usage

### ISSUE THREAD

**Issue by roy7** [leela-zero/leela-zero#684]
Freshly synced to the github and running /next. With 4 threads and nothing else running on my server, I only seem to use about 30% of the GPU when I load nvidia-smi over and over while LZ is thinking. 

Do I need to use more CPU threads? Or something else I can check into on why so much GPU power is idle?

```
> +-----------------------------------------------------------------------------+
> | NVIDIA-SMI 384.111                Driver Version: 384.111                   |
> |-------------------------------+----------------------+----------------------+
> | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
> | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
> |===============================+======================+======================|
> |   0  GeForce GTX 108...  Off  | 00000000:09:00.0  On |                  N/A |
> | 30%   57C    P2   114W / 300W |    241MiB / 11164MiB |     38%      Default |
> +-------------------------------+----------------------+----------------------+
> 
> +-----------------------------------------------------------------------------+
> | Processes:                                                       GPU Memory |
> |  GPU       PID   Type   Process name                             Usage      |
> |=============================================================================|
> |    0       712      G   /usr/lib/xorg-server/Xorg                     25MiB |
> |    0     21088      G   /usr/lib/xorg-server/Xorg                     33MiB |
> |    0     26659      C   /home/roy/code/leela-zero/src/leelaz         169MiB |
> +-----------------------------------------------------------------------------+

```

**Comment by roy7** [comment]
My settings are

 -w /home/roy/code/leela-zero/src/c83e1b6e0ffbf8e684f2d8f6261853f14c553b29ee0e70ff6c34e87d28009c43 --gtp --lagbuffer 300 --visits=50000 --threads=4 --noponder --logfile=logs/11341124.log

**Comment by roy7** [comment]
My nodes/sec are what I'd expect... so I don't know if nvidia-smi is lying to me, or if I could get a lot more nodes/sec somehow.

> 
> !!!!! zeroslowgtp.js:543             [26659 11341124] 3:50:02 stderr: 50003 visits, 16731420 nodes, 49943 playouts, 1949 n/s
> !!!!! zeroslowgtp.js:543             [26659 11341124] 3:50:28 stderr: 50003 visits, 16583945 nodes, 49817 playouts, 2149 n/s
> !!!!! zeroslowgtp.js:543             [26659 11341124] 3:50:55 stderr: 50003 visits, 16552159 nodes, 49947 playouts, 2116 n/s
> !!!!! zeroslowgtp.js:543             [26659 11341124] 3:51:15 stderr: 50003 visits, 16452955 nodes, 37169 playouts, 2245 n/s
> !!!!! zeroslowgtp.js:543             [26659 11341124] 3:51:46 stderr: 50003 visits, 16380990 nodes, 50003 playouts, 1961 n/s
> !!!!! zeroslowgtp.js:543             [26659 11341124] 3:52:13 stderr: 50003 visits, 16209457 nodes, 49997 playouts, 2167 n/s
> !!!!! zeroslowgtp.js:543             [26659 11341124] 3:52:41 stderr: 50003 visits, 16079009 nodes, 50001 playouts, 2167 n/s
> !!!!! zeroslowgtp.js:543             [26659 11341124] 3:53:00 stderr: 50003 visits, 15975328 nodes, 28627 playouts, 1975 n/s
> !!!!! zeroslowgtp.js:543             [26659 11341124] 3:53:18 stderr: 50003 visits, 15880943 nodes, 27773 playouts, 2075 n/s
> !!!!! zeroslowgtp.js:543             [26659 11341124] 3:53:49 stderr: 48830 visits, 15475620 nodes, 48829 playouts, 1875 n/s
> !!!!! zeroslowgtp.js:543             [26659 11341124] 3:54:17 stderr: 50003 visits, 15786452 nodes, 49920 playouts, 2161 n/s
> !!!!! zeroslowgtp.js:543             [26659 11341124] 3:54:47 stderr: 50003 visits, 15585361 nodes, 46002 playouts, 1888 n/s
> !!!!! zeroslowgtp.js:543             [26659 11341124] 3:55:16 stderr: 50003 visits, 15482748 nodes, 37806 playouts, 1599 n/s
> !!!!! zeroslowgtp.js:543             [26659 11341124] 3:55:28 stderr: 50003 visits, 15414224 nodes, 12128 playouts, 1900 n/s
> !!!!! zeroslowgtp.js:543             [26659 11341124] 3:55:57 stderr: 50003 visits, 15355628 nodes, 49993 playouts, 2065 n/s
> !!!!! zeroslowgtp.js:543             [26659 11341124] 3:56:25 stderr: 50003 visits, 15293833 nodes, 49905 playouts, 2111 n/s
> !!!!! zeroslowgtp.js:543             [26659 11341124] 3:56:52 stderr: 50003 visits, 15133913 nodes, 48367 playouts, 2178 n/s
> !!!!! zeroslowgtp.js:543             [26659 11341124] 3:57:24 stderr: 43130 visits, 12840751 nodes, 42674 playouts, 1639 n/s
> !!!!! zeroslowgtp.js:543             [26659 11341124] 3:57:42 stderr: 50003 visits, 14844208 nodes, 23139 playouts, 1763 n/s
> !!!!! zeroslowgtp.js:543             [26659 11341124] 3:58:04 stderr: 50003 visits, 14796212 nodes, 30698 playouts, 1874 n/s
> !!!!! zeroslowgtp.js:543             [26659 11341124] 3:58:33 stderr: 50003 visits, 14717623 nodes, 49987 playouts, 2016 n/s
> !!!!! zeroslowgtp.js:543             [26659 11341124] 3:59:03 stderr: 50003 visits, 14728580 nodes, 50000 playouts, 2018 n/s

**Comment by gcp** [comment]
If you are using a visit limit, and the opponent plays the expected move along a forced line, the program will be done immediately.

**Comment by roy7** [comment]
Yes but often I'm using my full 25 seconds to think. And while that thinking is happening, nvidia-smi goes from 0% to the 30%-40% range.

**Comment by gcp** [comment]
Probably a combination of small networks and god knows what nvidia-smi is measuring,

**Comment by roy7** [comment]
Is there a more reliable way to check GPU utilization under linux?

**Comment by gcp** [comment]
Not really. GPUs are all vendor magic.

**Comment by killerducky** [comment]
First just try increasing -t threads and see what happens.

**Comment by roy7** [comment]
With 16 threads, it bounces from 10%-40%. nodes/sec are lower. Too much lock contention?

Compare the before/after nodes/sec of 4 threads vs 16 threads.

!!!!! zeroslowgtp.js:543             [26659 11341124] 4:13:01 stderr: 50003 visits, 11585427 nodes, 49374 playouts, 2282 n/s
!!!!! zeroslowgtp.js:543             [26659 11341124] 4:13:27 stderr: 50003 visits, 11484258 nodes, 49806 playouts, 2254 n/s
!!!!! zeroslowgtp.js:543             [26659 11341124] 4:13:52 stderr: 50003 visits, 11386314 nodes, 49675 playouts, 2280 n/s
  zeroslowgtp.js:535             [26859 11341124] 4:13:55 Starting  -w /home/roy/code/leela-zero/src/c83e1b6e0ffbf8e684f2d8f6261853f14c553b29ee0e70ff6c34e87d28009c43 --gtp --lagbuffer 300 --visits=50000 --threads=16 --noponder --logfile=logs/11341124.log
!!!!! zeroslowgtp.js:543             [26859 11341124] 4:14:22 stderr: 35604 visits, 8013678 nodes, 35604 playouts, 1367 n/s
!!!!! zeroslowgtp.js:543             [26859 11341124] 4:14:51 stderr: 33314 visits, 7438487 nodes, 33220 playouts, 1276 n/s
!!!!! zeroslowgtp.js:543             [26859 11341124] 4:15:21 stderr: 33545 visits, 7430095 nodes, 33387 playouts, 1274 n/s

**Comment by roy7** [comment]
> Edit: Generally I think you should expect this version to require more threads to feed the GPU than before. Because there are many GPU optimizations to make it run faster, and the tree reuse change makes the CPU run slower.

@killerducky But adding 12 more cpu cores made my nodes/sec go down about 40%.

**Comment by killerducky** [comment]
Ok thanks for the stats, but now I have no idea what's happening.  :)

**Comment by roy7** [comment]
Ok so doing some tests at command line. Move 1 of a new game, 16 threads seems fine, 2200 nodes/sec. So I loaded in https://online-go.com/api/v1/games/11341124/sgf and then did 'genmove w'. Here's my speed results:

16 threads 1200 n/s
8 threads 1475 n/s
4 threads 1920 n/s
2 threads 2862 n/s
1 thread 2130 n/s

With 2 threads I get max performance, and nvidia-smi lists GPU % at 46-48% firm.

**Comment by roy7** [comment]
I reverted to v0.10.1 to try same test. Had to change --visits to --playouts of course.

16 threads 1461 n/s
8 threads 1530 n/s
4 threads 1990 n/s
2 threads 2596 n/s
1 thread 1971 n/s

**Comment by roy7** [comment]
@killerducky Had me try raising virtual loss to 1000 from 3. This is /next with --playouts 50000.

16 threads 1653 n/s
8 threads 1919 n/s
4 threads 2058 n/s
2 threads 2767 n/s
1 thread 1878 n/s

**Comment by roy7** [comment]
Adding a true multi-threaded benchmark command that does a search off of a complex mid-game board might be useful.

**Comment by ihavnoid** [comment]
I also noticed that it is getting harder to fully utilize GPU.  One of the reasons seems to be due to the OpenCL stack overhead (you know, sending tasks, receiving results) and this seems to be much more severe on Windows.

I think the problem got harder after implementing winograd transformation - even if everything got faster, the GPU utilization itself dropped (maybe a good thing!) because it has more kernel invocations (6 invocations per residual tower, vs. 4 before winograd).  One possible approach to reduce overhead might be grouping multiple network evaluations into a single opencl kernel call, but this has its own problem, too (e.g., needing a lot of threads to be efficient, which may reduce strength by itself)

If we are going to optimize everything for bigger networks (e.g., 20x256) then I saw no problem fully utilizing the GPU, simply because each kernel gets bigger by a lot.  Smaller networks are the problem (e.g., 5x64) and hence I am not sure if it is going to be a real problem we have to solve.

Any thoughts?

**Comment by roy7** [comment]
If people want to work their gpu harder they can just run autogtp -g 2 right? :) Run two games at once.

**Comment by arnaudgo** [comment]
Hello @roy7,

Do you use the Multi-Process Service that may  address the problem od GPU under-utilization you're facing with?

Arnaud

**Comment by roy7** [comment]
If you mean running with -g 2, I can do that and it'll full up the GPU yeah. Doing 1 game at a time doesn't use as much. It isn't a big deal, it just means if a single one of my bots is playing that there is unused GPU power standing by.

**Comment by arnaudgo** [comment]
@roy7 I refer to CUDA MPS: https://docs.nvidia.com/deploy/pdf/CUDA_Multi_Process_Service_Overview.pdf

**Comment by roy7** [comment]
Ah. I know nothing about that at all. :)

**Comment by sethtroisi** [comment]
No active discussion for >1 year, with newer issue
