### ISSUE TITLE
Minor README corrections and clarifications

### ISSUE THREAD

**Issue by barrybecker4** [leela-zero/leela-zero#693]
Some minor README corrections:

- "Wait, what" -> "Wait, what?"
- "deep residual convolutional neural network" -> link to https://blog.waya.ai/deep-residual-learning-9610bb62c355 (this link is somewhat arbitrary, but should give some background about what deep residual networks are and why they are useful)
- "Mastering the Game of Go without Human Knowledge" -> link to https://storage.googleapis.com/deepmind-media/alphago/AlphaGoNaturePaper.pdf
- Under "Gimme the weights", link from "1700 years on commodity hardware" instead of having separate link.
- I won't change anything in "I just want to play right now", but couldn't this section be updated to provide the best weights from the current ongoing training?
- Under "Usage", I think it would be better and more compact just to link from the text instead of writing out the link longhand.
   - For example, "GTP protocol, version 2" would like directly to  https://www.lysator.liu.se/~gunnar/gtp/gtp2-spec-draft2/gtp2-spec.html
   - and "Sabaki" would link to http://sabaki.yichuanshen.de/
- In "Training data format", "1 line with 362 floating point..." -> "1 line with 362 (19x19 + 1) floating point..." just to make it clear where the 362 number comes from.

I'll create a PR

**Comment by tamubun** [comment]
In "Weights format", the inputs are
1)
...
8) Side to move stones at time T=-8  (0 if T<=7)  -> Side to move stones at time T=-7  (0 if T<=6)
... 
16) Other side stones at time T=-8   (0 if T<=7) -> 16) Other side stones at time T=-7   (0 if T<=6)

**Comment by tamubun** [comment]
In "Weights format", the inputs are
1) Side to move stones at time T=0
...
8) Side to move stones at time T=-8 (0 if T<=7) -> 8) Side to move stones at time T=-7 (0 if T<=6)
...
16) Other side stones at time T=-8 (0 if T<=7) -> 16) Other side stones at time T=-7 (0 if T<=6)

**Comment by tamubun** [comment]
In "Weights format", the inputs are
```
1) Side to move stones at time T=0
  ...
8) Side to move stones at time T=-8 (0 if T<=7) -> 8) Side to move stones at time T=-7 (0 if T<=6)
  ...
16) Other side stones at time T=-8 (0 if T<=7) -> 16) Other side stones at time T=-7 (0 if T<=6)

```

**Comment by barrybecker4** [comment]
@tamubun, I think you are saying that I should change 8) and 16) to read like this
8) Side to move stones at time T=-7  (0 if T<=6)
16) Other side stones at time T=-7   (0 if T<=6)
I will make the change, but @gcp should verify that is correct (I don't know).

**Comment by tamubun** [comment]
@barrybecker4 Yes, I want to say:

`8) Side to move stones at time T=-8 (0 if T<=7)`
is incorrect and should be 
`8) Side to move stones at time T=-7 (0 if T<=6)`

And 16) is too. Simply writing down all omitted lines can show the reason.

```
1) Side to move stones at time T=0
2) Side to move stones at time T=-1  (0 if T=0)
3) Side to move stones at time T=-2 (0 if T<=1)
4) Side to move stones at time T=-3 (0 if T<=2)
5) Side to move stones at time T=-4 (0 if T<=3)
6) Side to move stones at time T=-5 (0 if T<=4)
7) Side to move stones at time T=-6 (0 if T<=5)
8) Side to move stones at time T=-7 (0 if T<=6)
```

**Comment by barrybecker4** [comment]
Aha. Thanks for the clarification.

**Comment by alreadydone** [comment]
Isn't this more correct/
```
1) Stones of the side to move at time T
2) Stones of the side to move at time T-1  (0 if T=0)
...
8) Stones of the side to move at time T-7  (0 if T<=6)
9) Stones of the other side at time T
10) Stones of the other side at time T-1   (0 if T=0)
...
16) Stones of the other side at time T-7   (0 if T<=6)
17) All 1 if black is to move, 0 otherwise
18) All 1 if white is to move, 0 otherwise
```

**Comment by alreadydone** [comment]
Also many info in https://github.com/gcp/leela-zero/blob/master/FAQ.md is outdated, e.g. 1000 vs. 1600 playouts. This is linked from http://zero.sjeng.org/ and may confuse people.

**Comment by gcp** [comment]
I pulled most of this, except for the deep residual convolutional networks explanation, which IMHO didn't really help much to clear things up and went off to discuss ResNeXT etc. Maybe there's a better explanation somewhere.

**Comment by sethtroisi** [comment]
No active discussion for >1 year, with multiple updates to README since
