### ISSUE TITLE
Improve error messages in GTP

### ISSUE THREAD

**Issue by barrybecker4** [leela-zero/leela-zero#697]
For many GTP commands, if the user types the wrong thing, it just says "syntax not understood". 
This does not give the user much guidance on what they need to type so that their input will be accepted. There were a few times that I had to go look at the code to figure out what needed to be entered. Most users will not do that. I would like to add a few clarifying words to the error messages as suggested below.
 
- boardsize ->
  "unacceptable size" -> "%d is an unacceptable size.\nOnly a size of 19 is currently supported."
- genmove ->
  "syntax error" -> "You need to specify the color for whom to generate the move.\nFor example, 'genmove white'."
- kgs-genmove_cleanup ->
 "syntax error" -> "You need to specify the color to cleanup.\nFor example, 'kgs-genmove_cleanup white'."
- time-left ->
   "Color in time adjust not understood.\n" -> "Color $s in time adjust not understood.\nAcceptable values are 'b' or 'w'.", color
  "syntax not understood" -> "Syntax not understood. Expected parameters are color time stones"  
- fixed-handicap, place_free_handicap -> 
   "Not a valid number of handicap stones" -> "%d is not a valid number of handicap stones.\nUse a number that is in the range 2 - 9".
- kgs-time_settings ->
   "syntax not understood" -> "%s is not an expected KGS time setting. Try one of 'none', 'absolute', 'canadian', or 'byoyomi'."
- dump_training  
   "syntax not understood" -> "Unexpected winner color: %s.\nSpecify either 'b' or 'w'."
   
Also this block: 
```
     if (!cmdstream.fail()) {
        gtp_printf(id, "");
     } else {
        gtp_fail_printf(id, "syntax not understood");
     }
```
is repeated many times. I will make it a method.
   I'll create a PR shortly.

**Comment by gcp** [comment]
I closed that PR because:

a) GTP is meant to be used between programs, it's not a human UI. If a human uses it, he's likely to be the one developing the engine or the GUI...
b) Some of the changes actually violated the GTP spec.

>There were a few times that I had to go look at the code to figure out what needed to be entered

You should look at the GTP spec.

>Most users will not do that.

I surely hope most people aren't trying to "speak" GTP!

**Comment by barrybecker4** [comment]
I suppose the main use case is machines sending commands, but I thought the improved messages would have been useful for developers, like me, who were trying to test things out from the command line.

**Comment by wctgit** [comment]
Alternatively, perhaps instead you could add some comments/documentation to the source code with descriptions of the commands and/or a link/reference to the GTP specifications, if that would be helpful.

**Comment by sethtroisi** [comment]
closing, no active discussion for >1 year
