### ISSUE TITLE
AutoGTPv13 throws "NetworkException" / "No such file or directory" due to quirk/bug of gzip.exe when run from certain folder paths on Windows 64-bit default release

### ISSUE THREAD

**Issue by wctgit** [leela-zero/leela-zero#712]
_[Edit: This issue has become clarified in the discussion/comments below, which identifies the existence of the gzip.exe quirk/bug.]_

I tried to follow these straightforward instructions from the readmes:
> ## Windows
>
> Head to the Github releases page at https://github.com/gcp/leela-zero/releases, download the latest release, unzip, and launch autogtp.exe. It will connect to the server automatically and do its work in the background, uploading results after each game. You can just close the autogtp window to stop it.

Downloaded leela-zero-0.11-win64.zip. Unzipped it, read this readme:
> Unzip and launch autogtp.exe. ...

From command line, tried `autogtp` command without any arguments. Result:
> C:\bin\leela-zero-0.11-win64>autogtp
> Auto GTP v13
> Using 1 thread(s) for GPU(s).
> Starting tuning process, please wait...
> gzip: 7fde81e8f671c710fc53be86e4b256cebc4825a652ea925d38270cfe1c86575a.gz: No such file or directory
> Net filename: 7fde81e8f671c710fc53be86e4b256cebc4825a652ea925d38270cfe1c86575a
> Network connection to server failed.
> NetworkException: Failed to fetch the network
> Retrying in 30 s.
> gzip: 7fde81e8f671c710fc53be86e4b256cebc4825a652ea925d38270cfe1c86575a.gz: No such file or directory
> Net filename: 7fde81e8f671c710fc53be86e4b256cebc4825a652ea925d38270cfe1c86575a
> Network connection to server failed.
> NetworkException: Failed to fetch the network
> Retrying in 45 s.
> gzip: 7fde81e8f671c710fc53be86e4b256cebc4825a652ea925d38270cfe1c86575a.gz: No such file or directory
> Net filename: 7fde81e8f671c710fc53be86e4b256cebc4825a652ea925d38270cfe1c86575a
> Network connection to server failed.
> NetworkException: Failed to fetch the network
> Retrying in 67 s.
> Maximum number of retries exceeded. Falling back to previous network.

Furthermore, during this process, it **briefly** generates a file named "7fde81e8f671c710fc53be86e4b256cebc4825a652ea925d38270cfe1c86575a.gz", which is available during the tuning process. However, this file is then deleted, very soon after the tuning process, when the attempt to connect fails. I managed to copy the file to see what it was. 

However, when I used 7zip to unzip the file, 7zip issued this error message:
> Unexpected end of data : leelaz-model-1544000.txt

Nevertheless, 7zip did manage to extract a file, 'leelaz-model-1544000.txt', which was 5,224,471 bytes long. See attachments.
[leelaz-model-1544000.txt](https://github.com/gcp/leela-zero/files/1649958/leelaz-model-1544000.txt)
[7fde81e8f671c710fc53be86e4b256cebc4825a652ea925d38270cfe1c86575a.gz](https://github.com/gcp/leela-zero/files/1649961/7fde81e8f671c710fc53be86e4b256cebc4825a652ea925d38270cfe1c86575a.gz)

I tried to manually copy the gz file to the autogtp.exe directory and re-run it. Same result, and the program deleted the file.

I tried to manually copy leelaz-model-1544000.txt to the exe directory and re-run it. Same result, although it does not delete leelaz-model-1544000.txt.

I also noticed that there's another gz file, "ed002cf36a2e33358907b66fecb80b16a1d104d18f7d1813babb1f2d9712916d.gz", which perhaps(?) came from a previous run of autogtp, before I decided to write up this issue. It contains leelaz-model-1520000.txt which is 14,241,115 bytes long. It also gives an 'Unexpected end of data' message when I used 7zip to extract it. See attachments.
[leelaz-model-1520000.txt](https://github.com/gcp/leela-zero/files/1649977/leelaz-model-1520000.txt)
[ed002cf36a2e33358907b66fecb80b16a1d104d18f7d1813babb1f2d9712916d.gz](https://github.com/gcp/leela-zero/files/1649978/ed002cf36a2e33358907b66fecb80b16a1d104d18f7d1813babb1f2d9712916d.gz)

In no cases did the 'Falling back to previous network' seem to do anything. The program simply ended, and back to the command prompt.

No other diagnostic information seems to be available. I have no idea why it would give a "Network connection to server failed" message. My internet is high speed and I have no problem accessing github or anything like that.

At first I thought it might be a firewall issue, silently failing, but a) Windows is supposed to pop up with a message asking whether you want to add an exception to the firewall, whenever an app tries to make an unexpected connection, but this did not occur, b) I manually added an exception anyway, just to be sure, and c) you're probably using http anyways, which I think is allowed through the firewall by default anyway, right?

Hope that helps diagnose the problem. It would be a shame if there are lots of potential Windows users who would like to support the project with Auto GTP, but who simply don't have the background knowledge or patience to file a bug report when something like this happens.

I would suggest adding automated unit tests **and** automated acceptance/build tests to test whether this basic 'right out of the box' functionality works on at least Windows and Mac machines as part of the build process.

I even recommended Leela Zero to Haylee (Hajin Lee, https://www.youtube.com/channel/UCTji1kQNoWIH85dB_Vxka9g/videos). I hope this problem is resolved before she reads my message and tries it out. Otherwise, it may discourage her (and other Go professionals) from trying it out.

At the very least, it would be extremely helpful to include much more informative error messages, and perhaps generate a log file with diagnostic information, so that it doesn't require a former programmer like me to generate a detailed bug report.

**Comment by gcp** [comment]
It sounds like you have some kind of proxy blocking Leela's internet access. There isn't much we or Leela can do to fix that and obviously tests on our side can't detect this.

Patches to improve the CI test coverage are welcome, but the things you talk about are done for a release anyway.

**Comment by wctgit** [comment]
You could add error/warning messages to indicate what the problem is. I doubt there's any kind of proxy, as it's a simple internet connection that all other software on my laptop uses.

**Comment by MaxMaki** [comment]
Do you have a VPN running? I know that on Windows my VPN software blocks Leela without any warning or indication why.

Same can be said for Anti-Virus software. Disable all anti-virus and/or VPN and try?

In case it's some kind of weird file permission (for example a work computer loaded with some kind of security software, or just general windows bugginess) try running the autogtp.exe as administrator as well.

There's hundreads of clients running without problems, so most likely it's a local problem on your computer.

**Comment by gcp** [comment]
>You could add error/warning messages to indicate what the problem is.

Network connection to server failed.
NetworkException: Failed to fetch the network

Is this not clear enough?

**Comment by FFLaguna** [comment]
Working off of what @MaxMaki said, I'm guessing it's related to permissions errors. Try redownloading LZ and run it from a folder that is not C:\bin\. Try something you'll definitely have full permissions to, like the default windows "Downloads" folder, or "Documents", or "Desktop".

**Comment by wctgit** [comment]
No, I have a simple laptop bought from a regular chain store, running basic Windows 10. My internet connection is a run of the mill high speed connection from a major regional ISP. Regular, run of the mill wireless router. Nothing fancy in my machine or setup. Everything else works fine, it's only Auto GTP that has some unknown issue, because there's not enough diagnostic output for me to tell you anything else.

**Comment by FFLaguna** [comment]
Windows does weird things with folder permissions in the C:\ and C:\Program Files directories, for example. Right click and check the security options if you know how to, or else I recommend trying what I suggested above.

**Comment by joseph-ireland** [comment]
The error actually seems to be to do with unzipping the file rather than downloading it: https://github.com/gcp/leela-zero/blob/master/autogtp/Management.cpp#L457

Could probably change that to "Error decompressing network", and add the stderr from the gunzip process.

@wctgit If you want to confirm the error then you can try copying the file where it came from, open a command prompt and run

```
cd C:\bin\leela-zero-0.11-win64
curl.exe -s -O -J -w %{filename_effective} http://zero.sjeng.org/networks/7fde81e8f671c710fc53be86e4b256cebc4825a652ea925d38270cfe1c86575a.gz
gzip.exe -d -q 7fde81e8f671c710fc53be86e4b256cebc4825a652ea925d38270cfe1c86575a.gz
```

then see what the error is.  
Remember this whole project is developed by (talented) volunteers in their limited spare time, so little omissions like this can easily happen. Error checking code is so easy to neglect since most people never see it running.

**Comment by wctgit** [comment]
> @wctgit If you want to confirm the error then you can try copying the file where it came from, ...

I'll try that when I get a chance. Thanks for the idea.

> Remember this whole project is developed by (talented) volunteers in their limited spare time, so little omissions like this can easily happen. 

Oh, don't worry, I know. I'm a former programmer myself.

> Error checking code is so easy to neglect since most people never see it running.

Yep. That's why I try to make detailed bug reports for those times when the errors _are_ visible. Also, my degree was in Human-Computer Interaction, a fancy phrase that basically means I pay attention to 'what it's like to try to use the software' not only for expert users like us programmers, but for everyday users like a typical Go enthusiast or professional player.

I'm really interested to see how far this project can develop its neural net, so I'm writing bug reports with an eye towards getting the software to a point where it "Works like a charm!" right out of the box. That's a really good way to generate user-base enthusiasm and word of mouth spread and adoption.

So, perhaps I may come across as nitpicky, especially to expert users and computer programmers, but the idea is to get the software as usable as possible for a wider (and less 'expert') user-base.

After all, I don't want to wait 1700 years to see the results! ;-) The more the merrier, right? :-)

**Comment by wctgit** [comment]
> @wctgit If you want to confirm the error then you can try copying the file where it came from, open a command prompt and run ... gzip

Indeed, you've nailed it down exactly, thanks! The real culprit is gzip.exe. (Note: For brevity I renamed the file to x.gz.)

It seems that -- for some unknown reason -- when I run this command under the bin folder:
> C:\bin\leela-zero-0.11-win64>gzip.exe -l x.gz
> gzip: x.gz: No such file or directory

However, when I run the identical command under the Downloads folder:
> C:\bin\leela-zero-0.11-win64>cd \Users\me\Downloads\leela-zero-0.11-win64
> 
> C:\Users\me\Downloads\leela-zero-0.11-win64>gzip.exe -l x.gz
>          compressed        uncompressed  ratio uncompressed_name
>             8236023            23664829  65.2% x

This seems to be a quirk of gzip.exe, because I also tested the curl.exe commands you recommended, and it all worked just fine. To put the last nail in the coffin, I went back to the bin folder and tried adding .\ in front of the filename, and ... it worked!

> C:\Users\me\Downloads\leela-zero-0.11-win64>cd \bin\leela-zero-0.11-win64
> 
> C:\bin\leela-zero-0.11-win64>gzip.exe -l .\x.gz
>          compressed        uncompressed  ratio uncompressed_name
>             8236023            23664829  65.2% .\x

I have no idea why gzip would behave differently depending on the current directory, however if you explicitly specify ".\x.gz" rather than just "x.gz", then it works the same way in both locations.

**Comment by marcocalignano** [comment]
I haven't looked at it yet, and autogtp v16 still uses gzip. I guess will come with the autogtp v17

**Comment by sethtroisi** [comment]
seems to have been fixed >6months ago
