### ISSUE TITLE
Include game's start and/or end time of day in SGF comment

### ISSUE THREAD

**Issue by wctgit** [leela-zero/leela-zero#761]
Since many games can be played on the same day, it would be helpful to be able to know the time of day that a game was started and/or ended. I recommend UTC, but perhaps local time is also okay. We can't always rely on the SGF file's operating-system-dependent created or modified dates, since they could be changed/omitted when sharing or otherwise working with the files.

SGF itself (latest version, 4) does not directly support recording of the game's start or end times, therefore, the suggestion is to add them to a game-level comment.

**Comment by gcp** [comment]
What's the point of this?

**Comment by gcp** [comment]
FWIW the server knows the submission time with second accuracy, I believe, due to how mongodb stores data and creates unique ids.

**Comment by wctgit** [comment]
When I download games and browse them in a program such as Sabaki, sometimes I'm interested to know which game was played before or after anothing on a particular day, but that information is not available in the SGF file itself. Also, the same problem when viewing games in the default game viewer in the web browser.

If someone wanted to perform some statistical analysis on SGF files, and doesn't have access to the server's accurate time information, then this level of information detail is lost to them. E.g. they could not produce an accurate graph of games played over a given time period, as they would all be lumped under a single day, presumably at midnight. Basically, if the information is readily available, why not include it? It need not be back-ported to previous games -- although it seems that would actually be possible -- just add the additional info to newly created games.

**Comment by gcp** [comment]
>they could not produce an accurate graph of games played over a given time period, as they would all be lumped under a single day, presumably at midnight

I think this is too vague a use case (again, what's even the point?) to put useless info in the SGF's.

**Comment by odeint** [comment]
> If someone wanted to perform some statistical analysis on SGF files, and doesn't have access to the server's accurate time information, then this level of information detail is lost to them. E.g. they could not produce an accurate graph of games played over a given time period, as they would all be lumped under a single day, presumably at midnight.

Games played by the same network are all fungible (and if they are not, it is because of different client hardware/software, not the time or day). There is no learning (or any change really) happening within a network, so I don't see what there would be to analyse. The number of moves and the network names are already included.

**Comment by wctgit** [comment]
A simple example would be the rate at which games are being played during the day.  Also, there has been recent discussion around fast wins potentially biasing the SPRT. If someone were to try to investigate this issue, then knowing when the games were generated, especially in what order they were received by the server (e.g. using the UTC time of the game) would be useful information.

**Comment by wctgit** [comment]
> I think this is too vague a use case (again, what's even the point?) to put useless info in the SGF's.

By the same token, you could argue that including the date of the game is useless information. The only reason people don't normally record the time of the game in SGF files is because the SGF version 4 is an old file format and doesn't include a property for time. See https://senseis.xmp.net/?SmartGameFormat.
> **Development:** FF[4] is outdated, but has not been replaced by something more recent. Today UTF-8 is standard, not Latin-1. The DT property needs the possibility to indicate a time. The TM property needs a unit. For a (dormant) proposal, see [ext] The SGF Format. 

Which links to a proposal which includes the allowance for the game start time to be recorded within the DT property. See https://homepages.cwi.nl/~aeb/go/misc/sgf.html#details

> DT[value] has as value an ISO standard date, when available. For example DT[1946-07-31]. When less information is available, one can omit day, as in DT[1946-07], and month, as in DT[1946]. When more information is available, one can add the starting time, as in DT[2000-01-01 00:53]. For games played over several days, the dates can be given separated by commas, or by .. or ~ to denote an interval. Such a sequence of dates can be condensed, as in DT[1946-07-31,08-15,16,17]. A Japanese era date is given via the JD property.

It's not like this is a completely out-of-the-blue piece of data to record. Others have noted the missing time information in SGFs also. The time info exists, it could be recorded, it could be useful, and it's not difficult to record it using a C property or GC property.
> Also, this relies on the client's clock being correct.

First, it doesn't have to be perfect. Second, most computers these days are synchronized to 'internet time'. Third, if such level of accuracy is important, then the server itself could use its own time to have a single source of time readings. Fourth, if doing it on the server is onerous, but you still want high accuracy, you can do a quick HTTP request from one of many internet time servers, defaulting to the computer's local time if there's no internet. But really, it doesn't have to be 100% totally accurate. Even some time information would be better than nothing.

**Comment by sethtroisi** [comment]
No active discussion for >1 year
