### ISSUE TITLE
Include the self-play contributor's info (perhaps hashed) in SGF file

### ISSUE THREAD

**Issue by wctgit** [leela-zero/leela-zero#762]
It would be useful/helpful to include some additional information about the contributor of the self-play game and/or the machine/GPU(s) on which the game was played. 

For the contributor's identity, it is in the same spirit as the identity used to determine the link "View your most recent selfplay training game". It would be interesting to see some statistics based on how many unique contributors there are, how many games they've contributed, how fast the typical machine is, what kinds of GPUs are being used, etc.

Hashing can be used to protect privacy. The idea is not to track people or physical machines or locations, only to track the sources of games in a generic way. A person may know their own hash (to track their own contributions, for example), but others will not be able to determine a contributor based on the hash alone.

Example: contributor's GitHub username if available (perhaps hashed), computer's IP or MAC (hashed), which GPU or what type of GPU was used, etc. 

SGF has some potentially useful properties which could help store this information (from http://www.red-bean.com/sgf/properties.html): 
```
US	Name of user (or program) which entered/input the game
SO	Source of game (e.g. book, magazine, AutoGTP contributor or machine info...)
PC	Name of 'place' the game was played (perhaps the machine/GPU info?)
GC	Game Comment (can contain any general info about the game)
C	Generic Comment (already used to store leelaz cmd line options; 
	could also store other info; can have multiple C properites for different purposes)
```
Additional potentially useful SGF properties:
```
GN	Game Name (should actually probably be set to the game hash/filename, 
	as per SGF recommendations)
EV	Event name (could be set to "Leela Zero AutoGTP self-play" or something similar)
RO	Round number of event (could be set to the game number, from 0 to 3185577 currently)
AN	Name of annotator (who knows? Could be useful for something)
```

**Comment by Cabu** [comment]
Hashing IP or MAC doesn't work because the space to search in is too small. It will be 'easy' to check all possible values to find a matching hash. 
For IP there is only 2**64 possibilities, and for MAC there is 24457 x 2**24 possibilities.

**Comment by gcp** [comment]
This won't ever be stored in the SGF for privacy reasons. The server can track some of this in the DB (so it can be stripped when the data is made public).

As you were already explained, it's very easy to get anonymization wrong, too.

In general I would want to avoid storing any kind of information about the clients unless it's absolutely needed.

**Comment by wctgit** [comment]
I can understand that caution, that's reasonable. How about some of the other information I suggested, such as GPU type, and/or some other information about the type of the machine (e.g. CPU vs. GPU, personal computer vs. super-computer, etc.). Again, like the time-info issue, the purpose is for possible future analysis. Also, it provides some personal 'investment' into the project from a contributor's point of view; the idea there to attract and maintain interest from contributors by providing interesting statistics they can browse.

**Comment by gcp** [comment]
Storing hardware info (GPU model, driver version) and (when available) build id would be interesting for reproducible games, see issue #300. But until there is more progress on that, the info doesn't help much.

Again, I prefer to store as little PII data as possible. It's a trade-off between fancy stats pages and respecting user privacy. I know most people long stopped caring but I still care about the latter and for now will err on the side of caution.

**Comment by sethtroisi** [comment]
Thanks for protecting user privacy gcp <3
