### ISSUE TITLE
Stopping on-going self-game when a better network is found

### ISSUE THREAD

**Issue by arnaudgo** [leela-zero/leela-zero#768]
Hi !

it would be nice if all self-games in progress were stopped when a better network is found, don't you think so ?
Very useful when one game lasts many hours and it's only at the very first moves.
It doesn't have to check at each move and I don't have any suggestion on what would be optimal but implementing this seems to me a nice enhancement.

Arnaud

**Comment by Mardak** [comment]
What's the problem with finishing a self-play game that just started a little bit before a new network is found?

**Comment by arnaudgo** [comment]
Hello @Mardak ,

Okay maybe I should have started from this point :) Is there any added value to send a self-play game between weaker networks ?

Arnaud

**Comment by jkiliani** [comment]
@arnaudgo Yes. The training window generally uses games from a number of successive generations of networks, so a game will be used effectively even if it happened to be submitted when that network was already outdated. At the moment, there are still a few games played by c83e1b6e in the window. 5773f44c is far stronger than that, so why do you think a game played by 5773f44c shouldn't be used, if it displaced one from c83e1b6e?

**Comment by tterava** [comment]
As the training speed is limited by the _quantity_ of self-play games submitted, I think it's actually harmful to stop games that are in progress. The difference in playing strength is quite small and the games of the previous best network are still extremely valuable. If we drop those games in the middle we are wasting all the processing power put into the games in progress.

I think the difference is very negligible but changing it would be unnecessary work and probably slightly harmful to the progress.

**Comment by arnaudgo** [comment]
Well,
I have no firm beliefs that they should be dropped, it's only the result of my ignorance :)

 Now, I wonder if it could end one self-game and start a new one while being offline that's to say unable to upload the SGF for the previous self-game and unable to check if there's a better network.

Can it take those actions afterwards? You are allowed to tell me: just read the source to check yourself, it would be legitimate :) Otherwise thanks for answering if you already know, it permits me not making a test myself in real conditions.

Arnaud

**Comment by marcocalignano** [comment]
@arnaudgo autogtp try to upload the game to the server when the game ends. Afterwords it try to get a new job from the server and then download the last best network. If these operations fail it tries few time, then gives up and falls abck to the last self-played game configuration.

**Comment by Marcin1960** [comment]
Perhaps if the gain is high like at least 60%? With 56% I would keep it going for a while, 56% might be still a random result.

**Comment by arnaudgo** [comment]
Thank you very much @marcocalignano :) It can play successively several games offline then, it's not a problem, and upload all past games as soon as the connectivity is recovered :) 

Perfect :) 

Arnaud

**Comment by sethtroisi** [comment]
Fixed somewhere along the line
