### ISSUE TITLE
Top ten networks ratings table.

### ISSUE THREAD

**Issue by john45678** [leela-zero/leela-zero#784]
Could a table be put on zero.sjeng.org, beside the graph showing the top 10 networks ratings. (the graph is hard to see with so many nets together).
thanks.

**Comment by roy7** [comment]
I think I prefer this more though?

https://vega.github.io/vega-lite/examples/interactive_overview_detail.html

**Comment by isty2e** [comment]
@roy7 I tried to plot the LZ data with this "overview and detail" style, but I gave up trying to make vconcat and layers work together.

**Comment by emc2314** [comment]
And could we put several lines showing the **Leela ELO** of other players (which could be estimated once-for-all or dynamically)?
For example, **Ke Jie** is about 16000, **AlphaGo Zero 40 block** is about 21000 according to [this document](https://docs.google.com/spreadsheets/d/1QhYWYQvXBhI5eHJm45fvf97CaV2rRmgrATwVgBFGKoU/).

**Comment by arnaudgo** [comment]
Personnaly I wouldl appreciate being able to toggle the presence of FAIL dots :)

Arnaud

**Comment by Marcin1960** [comment]
@arnaudgo "toggle the presence of FAIL dots :)"

Or even better, turn just dots below 50%

**Comment by sethtroisi** [comment]
Done, also somewhat handled in cloudygo

https://cloudygo.com/leela-zero-v3/eval-graphs
