### ISSUE TITLE
autogtp should use a new line every 10~20 moves

### ISSUE THREAD

**Issue by fcicq** [leela-zero/leela-zero#80]
```
    output << moveNum << " (" << moveDone << ") ";
```

**Comment by fcicq** [comment]
ah. output a timestamp at the beginning or at the end?

**Comment by fcicq** [comment]
\#include <QTime> will be required at the top.

```
void Game::move() {
    QTime ct = QTime::currentTime();
    if (moveNum % 20 == 0) {
      output << endl << "[" << ct.toString() << "] ";
    }
    moveNum++;
```

**Comment by fcicq** [comment]
#74 is related, but I dont count seconds per game...

**Comment by wonderingabout** [comment]
@sethtroisi 

if we want to cleanup the github issues, i think its easier to start with oldest updated issues  : 

https://github.com/leela-zero/leela-zero/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-asc

**Comment by sethtroisi** [comment]
closing issue with no clear owner and >1 year of no progress
