### ISSUE TITLE
Improve autogtp error handling

### ISSUE THREAD

**Issue by killerducky** [leela-zero/leela-zero#839]
I just put an assert(false) in the LZ code to see how autogtp handles it. autogtp just exits with no output to the user to help him know what is wrong.

```
./leelaz -w ~/networks/latest.txt -p 10 --noponder -r 0 

leelaz: /home/aolsen/projects/lz-assert/leela-zero/src/UCTNode.cpp:326: UCTNode* UCTNode::uct_select_child(int): Assertion `false' failed.
Aborted (core dumped)

./autogtp

Got new job: selfplay
net: 66650b159e9da469130453ea5730bd265dc81db00a19e6110ee20fc16597830e.
Engine has started.
Infinite thinking time set.
<program exits silently>
```

Maybe autogtp can capture stdout/stderr in a small buffer, and if leelaz dies, print the last few lines of output?

**Comment by marcocalignano** [comment]
@killerducky can you run the same 'assert failing' binary but with the option `-q`?

**Comment by marcocalignano** [comment]
@killerducky I tried to put some `assert(false)` on the leelaz code (main and UCTNode) but I do not get the error you get and leelaz works normally. Some optimization flags maybe? can you give me a patch?

**Comment by killerducky** [comment]
Make sure you build LZ with -DNDEBUG.

**Comment by sethtroisi** [comment]
closing, solution in last response
