### ISSUE TITLE
Run Leelaz in command line

### ISSUE THREAD

**Issue by optimistman** [leela-zero/leela-zero#846]
How can I run the leelaz by command line in windows? Through gogui or sakabi? I want to do some test on the weights. Thanks!

**Comment by gcp** [comment]
I'm not sure what you are asking?

Do you want to run it on the command line, or under gogui/sabaki? These are like the opposite.

What are you **actually** trying to do?

**Comment by optimistman** [comment]
I want to run it on the command line directly. 
If I run the autogtp, it will call leelaz.exe by the following command line commands (The options was read by adding some print function in leelaz.exe)
".\leelaz.exe -p 1600 -r 1 -m 30 -t 1 -d -n --noponder -s 6189541225801548312 -g -q -w d6f3a68b6ca8c074bd3161cd0da3e8816e8b7bc2d3262cd7c46e81fb9bab2b9b", but if I use the above commands directly in the cmd window, it does NOT work. 

I thought that I can only call leelaz.exe through gogui/sabaki, so I ask whether I have to call leelaz.exe through gogui/sabaki. If I can call it without gogui/sabaki, it's better.

**Comment by MaxMaki** [comment]
Run leelaz.exe -h to get all parameters you can specify.

The important ones are:

-w weightfile (the network you want to run)
-g (GTP, in case you run it with sabaki, but not if you run it on the commandline)
-p number_here (number of playouts, in case you dont want it to think for 50 seconds, but instead specify how many playouts)

if you use -p you also have to specify --noponder

Example for Sabaki:
leelaz.exe -g -p 1600 --noponder -w networkfile

If you run it from the commandline you can type list_commands to get a list of GTP commands, but note that GTP commands aren't really meant to be easy or convenient for people to use.

If i've understood correctly from your post, you want to run two networks against each other?
You could just make two sabaki engines as i mentioned above, or, if you actually want to run a proper match you're better off using Gomill Ringmaster (for example)

**Comment by optimistman** [comment]
@MaxMaki , Thank you for your answer. I don't want to run the leelaz through sabaki interface. I want to run leelaz through command line in cmd windows, so in the next step, I can write a script to automatically test some games between different weights.

But it's OK if I can run leelaz through Sabaki.exe in the cmd windows.

**Comment by nathanloop** [comment]
https://pypi.python.org/pypi/gomill

That's what you're looking for to run network vs network without a gui.

**Comment by chucklu** [comment]
@optimistman  

- Step1

**.\leelaz.exe -g --noponder -t16 --playouts 300 -w E:\Go\leelaz-model-swa-16-128000_quantized_25c231.txt**

- Step2

**list_commands**

then you can use `list_commands` to check what you can do, http://www.gnu.org/software/gnugo/gnugo_19.html
= protocol_version
name
version
quit
known_command
list_commands
boardsize
clear_board
komi
play
genmove
showboard
undo
final_score
final_status_list
time_settings
time_left
fixed_handicap
place_free_handicap
set_free_handicap
loadsgf
printsgf
kgs-genmove_cleanup
kgs-time_settings
kgs-game_over
heatmap


- step3

**play black D4**


- step4

**showboard**



Passes: 0            Black (X) Prisoners: 0
White (O) to move    White (O) Prisoners: 0

   a b c d e f g h j k l m n o p q r s t
19 . . . . . . . . . . . . . . . . . . . 19
18 . . . . . . . . . . . . . . . . . . . 18
17 . . . . . . . . . . . . . . . . . . . 17
16 . . . + . . . . . + . . . . . + . . . 16
15 . . . . . . . . . . . . . . . . . . . 15
14 . . . . . . . . . . . . . . . . . . . 14
13 . . . . . . . . . . . . . . . . . . . 13
12 . . . . . . . . . . . . . . . . . . . 12
11 . . . . . . . . . . . . . . . . . . . 11
10 . . . + . . . . . + . . . . . + . . . 10
 9 . . . . . . . . . . . . . . . . . . .  9
 8 . . . . . . . . . . . . . . . . . . .  8
 7 . . . . . . . . . . . . . . . . . . .  7
 6 . . . . . . . . . . . . . . . . . . .  6
 5 . . . . . . . . . . . . . . . . . . .  5
 4 . . .(X). . . . . + . . . . . + . . .  4
 3 . . . . . . . . . . . . . . . . . . .  3
 2 . . . . . . . . . . . . . . . . . . .  2
 1 . . . . . . . . . . . . . . . . . . .  1
   a b c d e f g h j k l m n o p q r s t

Hash: 68CF0A4D4D44DA46 Ko-Hash: F8DD395FF18CB668

Black time: 00:00:05, 1 stones left
White time: 00:00:05, 1 stones left

- step5

**genmove white**
Thinking at most 4.0 seconds...
NN eval=0.538409
Playouts: 4, Win: 10.32%, PV: Q16 D16 Q4

 Q16 ->       7 (V: 53.49%) (N: 72.84%) PV: Q16 D16 Q4 O17
 D16 ->       3 (V: 53.64%) (N: 10.90%) PV: D16 Q16 Q4
  Q4 ->       3 (V: 53.60%) (N: 11.24%) PV: Q4 Q16 D16
3.1 average depth, 5 max depth
9 non leaf nodes, 1.44 average children
14 visits, 5025 nodes, 13 playouts, 3 n/s

= Q16

- step6

**showboard**


Passes: 0            Black (X) Prisoners: 0
Black (X) to move    White (O) Prisoners: 0

   a b c d e f g h j k l m n o p q r s t
19 . . . . . . . . . . . . . . . . . . . 19
18 . . . . . . . . . . . . . . . . . . . 18
17 . . . . . . . . . . . . . . . . . . . 17
16 . . . + . . . . . + . . . . .(O). . . 16
15 . . . . . . . . . . . . . . . . . . . 15
14 . . . . . . . . . . . . . . . . . . . 14
13 . . . . . . . . . . . . . . . . . . . 13
12 . . . . . . . . . . . . . . . . . . . 12
11 . . . . . . . . . . . . . . . . . . . 11
10 . . . + . . . . . + . . . . . + . . . 10
 9 . . . . . . . . . . . . . . . . . . .  9
 8 . . . . . . . . . . . . . . . . . . .  8
 7 . . . . . . . . . . . . . . . . . . .  7
 6 . . . . . . . . . . . . . . . . . . .  6
 5 . . . . . . . . . . . . . . . . . . .  5
 4 . . . X . . . . . + . . . . . + . . .  4
 3 . . . . . . . . . . . . . . . . . . .  3
 2 . . . . . . . . . . . . . . . . . . .  2
 1 . . . . . . . . . . . . . . . . . . .  1
   a b c d e f g h j k l m n o p q r s t

Hash: B0B4D9E9AE8F3B3F Ko-Hash: 8B6B4136B98AFCDC

Black time: 00:00:05, 1 stones left
White time: 00:00:05, 1 stones left

- step7

**genmove black**
Thinking at most 4.0 seconds...
NN eval=0.465112
Playouts: 18, Win: 25.28%, PV: D16 Q4 O17 F17 O3 F3

 D16 ->      17 (V: 46.41%) (N: 31.42%) PV: D16 Q4 O17 F17 O3 F3
  Q4 ->      12 (V: 46.50%) (N: 31.33%) PV: Q4 D16 C14 C6 R14
 R17 ->      10 (V: 46.39%) (N: 22.82%) PV: R17 R16 Q17 P16 P17 O16
4.4 average depth, 7 max depth
28 non leaf nodes, 1.39 average children
40 visits, 14265 nodes, 33 playouts, 7 n/s

= D16

**Comment by chucklu** [comment]
@optimistman  You can use command `play` and `genmove` to decide how to play it in cmd.
check the syntax of gtp here www.gnu.org/software/gnugo/gnugo_19.html
