### ISSUE TITLE
Error in OpenCL calculation

### ISSUE THREAD

**Issue by marcocalignano** [leela-zero/leela-zero#849]
`*ERROR*: Error in GTP response. Error read 78 'Error in OpenCL calculation: expected 0.013709 got 0.014459 (error=5.471240%)`

This is the first time for me that I get this error. Now I am running the /next (not the lasts commits) branch. The funny thing is that I am running autogtp since two days strait:

`609 game(s) (557 self played and 52 matches) played in 3125 minutes = 307 seconds/game, 934 ms/move, last game took 5339 seconds.`

Now I will take the last next and compile again.

**Comment by mbc44** [comment]
> Microsoft Windows [Version 10.0.14393]
> (c) 2016 Microsoft Corporation. All rights reserved.
> 
> C:\Users\root>cd Downloads
> 
> C:\Users\root\Downloads>cd leela-zero-0.11-win64
> 
> C:\Users\root\Downloads\leela-zero-0.11-win64>autogtp.exe -g 4
> AutoGTP v13
> Using 4 thread(s) for GPU(s).
> Starting tuning process, please wait...
> net: 66650b159e9da469130453ea5730bd265dc81db00a19e6110ee20fc16597830e.
> ./leelaz --tune-only -w 66650b159e9da469130453ea5730bd265dc81db00a19e6110ee20fc16597830e
> Using 2 thread(s).
> RNG seed: 50653094259479878
> Detecting residual layers...v1...128 channels...6 blocks.
> Initializing OpenCL.
> Detected 1 OpenCL platforms.
> Platform version: OpenCL 2.1 AMD-APP (2527.8)
> Platform profile: FULL_PROFILE
> Platform name:    AMD Accelerated Parallel Processing
> Platform vendor:  Advanced Micro Devices, Inc.
> Device ID:     0
> Device name:   Hawaii
> Device type:   GPU
> Device vendor: Advanced Micro Devices, Inc.
> Device driver: 2527.8
> Device speed:  1010 MHz
> Device cores:  44 CU
> Device score:  1121
> Device ID:     1
> Device name:   Intel(R) Xeon(R) CPU E5-1650 v4 @ 3.60GHz
> Device type:   CPU
> Device vendor: GenuineIntel
> Device driver: 2527.8 (sse2,avx)
> Device speed:  3598 MHz
> Device cores:  12 CU
> Device score:  521
> Selected platform: AMD Accelerated Parallel Processing
> Selected device: Hawaii
> with OpenCL 2.1 capability.
> Loaded existing SGEMM tuning.
> Wavefront/Warp size: 64
> Max workgroup size: 256
> Max workgroup dimensions: 1024 1024 1024
> Tuning process finished
> Starting thread 1 on GPU 0
> ...
> ...
> ...
> 1 (B C4) 1 (B R16) 1 (B Q4) 1 (B Q17) 2 (W Q4) *ERROR*: Error in GTP response.
> Error read 81 'Error in OpenCL calculation: expected 2.479579 got 0.419435 (error=491.171967%)
> '
> *ERROR*: Error in GTP response.
> Error read 78 'Update your GPU drivers or reduce the amount of games played simultaneously.
> '
> 2 (W D16) *ERROR*: Error in GTP response.
> Error read 80 'Error in OpenCL calculation: expected 0.912411 got 0.797072 (error=14.470264%)
> '
> *ERROR*: Error in GTP response.
> Error read 78 'Update your GPU drivers or reduce the amount of games played simultaneously.
> '
> 2 (W R4) *ERROR*: Error in GTP response.
> Error read 80 'Error in OpenCL calculation: expected 1.994458 got 1.485479 (error=34.263618%)
> '
> *ERROR*: Error in GTP response.
> Error read 78 'Update your GPU drivers or reduce the amount of games played simultaneously.
> '
> 3 (B C17)
> C:\Users\root\Downloads\leela-zero-0.11-win64>

**Comment by gcp** [comment]
5.5% error is pretty close to the margin we put. Perhaps it could be made a bit bigger. Real errors tend to be very large anyway.

**Comment by marcocalignano** [comment]
Could it be a consequence of  context switching in a busy CPU and the -ffast-math optimization option.

**Comment by gcp** [comment]
Doubtful.
