### ISSUE TITLE
How Leela Zero defeated the Six-Eyed Dragon (Just a fun match to watch)

### ISSUE THREAD

**Issue by wctgit** [leela-zero/leela-zero#852]
No, it didn't _really_ have six eyes; that would be impossible, of course. But I enjoyed watching [66650b15 defeat a recent candidate 18b46808](http://zero.sjeng.org/viewmatch/99978acd8b98641b95f1482b050dc9a4714e8b099f246270e5d42330807f4632?viewer=wgo), and thought you might enjoy it too. White has a potential to make, or connect to, at least six real or potential eyes, but Black systematically prevents, pokes, or pops them leading to a nice epic finale at the end.

Reflections on the game as it relates to the networks: I find it interesting that near the end, White believed it was playing end-game _dame_ moves, and ends up filling several of its own liberties as a result, instead of just playing the saving move at L6. Is White (a fairly weak contender, 18b4) unusually blind to liberties/false-eyes, or is this a common problem even with the recent champion nets? In other words, if the neural nets were swapped near the end, would the better net have spotted the weakness and played L6 to save the dragon? (Or maybe it already knew it was lost, and was playing desperately? To my naive eyes, it appeared it thought the dragon was alive and maybe even thought it was winning until very near the end.)

Was Black (the current champ 666 net) considering the White dragon(s) as a whole, and trying to kill it systematically (as I was guessing/imagining), or was it more so playing locally optimal moves until it finally realized it had the opportunity to kill the whole thing near the very end with L6?

**Comment by wctgit** [comment]
Hmm, looks like it was fighting over a 1/2 point win, so the _dame_ plays do in fact make some kind of 'desperate' sense.

**Comment by sethtroisi** [comment]
Fun game

closing to try and lower issue count to a sane number
