### ISSUE TITLE
"AlphaGo Zero vs. Master with Michael Redmond 9p: Game 5" Review video

### ISSUE THREAD

**Issue by wctgit** [leela-zero/leela-zero#856]
Michael Redmond's commentary and reviews are certainly a major reason I became interested in AlphaGo, and, indeed, in Go in general. After taking a recent break, he has finally put up a new review of Game 5 of the published games between AGZ and AG Master: https://www.youtube.com/watch?v=Sxz1NnMScQQ

Relevance: Aside from being fun/interesting to watch, I post this because Michael Redmond has repeatedly said, on many different occasions and in many different ways, that he would love to have a version of AlphaGo that he can play with, experiment with, study with, learn with, and just generally explore in any way he could. In that spirit, I attempted to post a comment on that video recommending Leela Zero, and linking back to http://zero.sjeng.org/. Unfortunately, I should have de-link-ified the link so it wouldn't trip YouTube's default spam filtering. I subsequently sent a message to the AGA channel's admin asking for the comment to be de-spammed. But presently, it's not publicly viewable yet.

In any case, the point is that Michael Redmond (among other folks, too) is an ideal example of someone who's mainly into Go, but who is also very interested in AlphaGo/AI sufficiently that he might go the extra mile to try Leela Zero and even run Auto GTP. I'm sure that people like him are just the tip of the iceberg: People who may not be as savvy at 'installing' programs the open-source way (of unzipping to a folder and running the binary directly, often from a command line), but who absolutely **would** contribute processing power to the project if only a) they knew the project existed, and b) it was relatively easy enough to set it up to automatically do so.

As for the b) part, I believe this project is already pretty easy to set up, provided the person has more-than-the-population-average knowledge of how to use a computer (aside from encountering some unresolved quirks such as #712). Of course, it could be streamlined further, but someone like Michael Redmond wouldn't let any little install quirks prevent him from having his Zero. Certainly many of the viewers of the AGA channel's review videos on AGZ/AGM by Redmond would be likely to have the minimal know-how to install and run Auto GTP. And the more people running it, the faster that 1700 years of computation will diminish.

So, that just leaves the a) part, which is spreading the word about this project's existence. I'll include the text of my botched comment below as an example of how one might go about letting interested folks know about the existence of Leela Zero. It's nothing special, just an idea:

> For anyone interested in having something like AlphaGo Zero available for their own learning and exploration, there's an open source project called Leela Zero which is designed and trained based on AlphaGo Zero's architecture and training protocol (as described in the AGZ paper by Deep Mind). Use it with any Go GUI which supports GTP (e.g. the open source Sabaki project). You can even help train it on your own computer and watch it climb the ranks at OGS and CGS! Cool, eh?﻿
> 
> Leela Zero progress: http://zero.sjeng.org/
> Leela Zero "Read Me" page: https://github.com/gcp/leela-zero/blob/master/README.md
> Sabaki: http://sabaki.yichuanshen.de/
> Leela Zero on OGS (Royal Zero): https://online-go.com/player/484523/RoyalZero
> CGS Rankings (look for names starting with 'LZ'): http://www.yss-aya.com/cgos/19x19/standings.html

**Comment by l1t1** [comment]
last link is wrong, pls trim %feef

**Comment by wctgit** [comment]
Fixed. Thx. Weird. Guess it was from copying text out of YT comment box.

**Comment by gcp** [comment]
For what it's worth, I've been asked to do a keynote about advances in Computer Go (i.e. Leela Zero) at the European Go Congress this summer, so word will definitely spread among go players.

**Comment by roy7** [comment]
I hope someone makes a video recording for YouTube so we can all check it out. :)

**Comment by jonlave** [comment]
We could start by contacting the big Go YouTubers for promotion: Haylee's World of Go, Nick Sibicky, etc.

**Comment by wctgit** [comment]
Cool, congrats, @gcp! Yay! \(^_^)/  I hope the European Go Congress experience is fun and enjoyable, as well as getting to show Leela Zero to the world! :-D

> We could start by contacting the big Go YouTubers for promotion: Haylee's World of Go, Nick Sibicky, etc.

We could, but if we do, we wouldn't want to come across as spammy (as my attempt may have been, accidentally; oopsy!). I imagine two ways that could be more natural, 1) just mention it organically in the course of a normal conversation/chat/comment-thread/whatever, or 2) more formally as a kind of official announcement (perhaps for a new version release?), posted on someone's blog, for example, and then spread the word about the official announcement, so everyone is spreading the same message. 

1) is more natural and organic, word-of-mouth style, and 2) has a more organized and coherent message, pre-planned and more of a 'marketing' style. Both have their strengths and weaknesses, and luckily they are not mutually exclusive. Even with the 'marketing' approach, though at first glance it may seem 'over-produced', at least it's something people are familiar with and have come to expect as a normal 'way of doing business' (e.g. companies doing press releases, etc.), so while it's more 'organized', it wouldn't necessarily be seen as 'spammy'.

BTW, the AGA's channel actually already has a pretty good list of Go-related channels if you go to https://www.youtube.com/user/USGOWeb/channels

**Comment by marcocalignano** [comment]
I am in contact with Nick Sibicky, and he is not interested in AI for go at the moment. Maybe in the future, he said he will do a video in the future mentioning some project and also Leela zero. 
But Andrew Jackson (@amj) from minigo is a Go teacher friends of nick Sibicky, he also has his own you-tube channel and it is also famous on you-tube (at least in Korea :smile) because he commented the AlphaGo versus Ke Jie games. Maybe he could help with the video.

**Comment by SebastienFaurite** [comment]
Haylee already tweeted about Leela so she is interested. 

@Hajin_lee: The author of Leela is looking for help in computing resources for his open source project https://github.com/gcp/leela-zero that will attempt to emulate AlphaGo Zero.

**Comment by SebastienFaurite** [comment]
https://twitter.com/Hajin_lee/status/931649180266741760

**Comment by wctgit** [comment]
Sweet! I posted a comment to her a little while ago, when I first became acquainted with this project. I wonder if that was what prompted her to look into it! :-D (Of course, I have no way to know.) A tweet from her might spark a lot of interest and get some new AutoGTP volunteers.

Hey, anyone with Twitter (I don't use it, sorry), maybe you could re-tweet her tweet, and/or comment on her tweet (and 'like' it, etc.) to try to promote Leela Zero indirectly via Haylee's tweet? That's likely to have more impact than if you're not already a popular Twitter account, and just posted a tweet yourself.

**Comment by wctgit** [comment]
Oh, no, wait. That's from Nov 2017. Old news. Ignore previous comment.

**Comment by sethtroisi** [comment]
closing, no active discussion for >1 year with subsequent discussions
