### ISSUE TITLE
VS2015 Project files are missing preprocessor defines

### ISSUE THREAD

**Issue by jun63cn** [leela-zero/leela-zero#865]
Thinking at most 4.0 seconds...
genmove w
NN eval=0.487784
Playouts: 4050, Win: 50.90%, PV: Q4 D4 Q16 R17 R16 Q17 P17 P18 O18 O17 P16 N18 Q18 O19 R18 R3 R4 Q3 P3 P2 O2 O3 P4 N2 Q2 O1 R2 S3 S2 O4 C17
0.4s left
Stopping early.

  Q4 ->    2213 (V: 51.17%) (N: 29.54%) PV: Q4 D4 Q16 R17 R16 Q17 P17 P18 O18 O17 P16 N18 Q18 O19 R18 R3 R4 Q3 P3 P2 O2 O3 P4 N2 Q2 O1 R2 S3 S2 O4 C17 D17
 Q16 ->    1525 (V: 50.96%) (N: 24.47%) PV: Q16 Q4 D4 R17 Q17 R16 R15 S15 S14 R14 Q15 S13 S16 T14 S17 C3 C4 D3 E3 E2 F2 F3 E4 G2 D2 F1 C2 O4 C17 D17 C16
  D4 ->    1510 (V: 51.00%) (N: 23.21%) PV: D4 Q4 Q16 R17 Q17 R16 R15 S15 S14 R14 Q15 S13 S16 T14 S17 C3 C4 D3 E3 E2 F2 F3 E4 G2 D2 F1 C2 O4 C17 D17 C16
 C17 ->     166 (V: 50.41%) (N:  4.16%) PV: C17 D17 C16 C15 B15 B14 C14 D15 B13 B16 A14 B17 D4 Q16 Q4 R3 R4 Q3
 R16 ->     122 (V: 50.41%) (N:  3.14%) PV: R16 Q4 D4 C3 D3 C4 C5 B5 B6 C6
  D3 ->      87 (V: 50.66%) (N:  1.83%) PV: D3 Q4 Q16 R17 Q17 R16 R15 S15 S14
  C4 ->      83 (V: 50.32%) (N:  2.14%) PV: C4 Q4 Q16 R17 R16 Q17 P17 P18 O18
  Q3 ->      70 (V: 50.09%) (N:  2.08%) PV: Q3 D4 Q16 R17 Q17 R16 R15 S15
 Q17 ->      68 (V: 49.99%) (N:  2.15%) PV: Q17 Q4 D4 C3 C4 D3 E3 E2 F2
  R4 ->      65 (V: 50.02%) (N:  2.01%) PV: R4 Q16 D4 C3 D3 C4 C5
5909 visits, 2061052 nodes, 5909 playouts, 1641 n/s

= Q4

play B Q16
= 

time_left w 5 1
= 

genmove w
update_root, 2061052 -> 170773 nodes (8.3% reused)
Thinking at most 4.0 seconds...
NN eval=0.484696
2.0s left
Stopping early.

  D4 ->    2477 (V: 51.68%) (N: 71.02%) PV: D4 R3 R4 Q3 P3 P2 O2 O3 P4 N2 Q2 O1 R2 C3 C4 D3 E3 E2 F2 F3 E4 G2 D2 F1 C2 D14 R17 R16 Q17 P17 P18 O18 O17 P16 N18 Q18 O19 R18 D17
  C4 ->     146 (V: 50.70%) (N:  7.32%) PV: C4 R3 Q3 R4 R5 S5 S6 R6 Q5 S7 S4 T6 S3 E3 C17 C16 D17
  D3 ->     116 (V: 51.00%) (N:  4.97%) PV: D3 R3 R4 Q3 P3 P2 O2 O3 P4 N2 Q2 O1 R2 C5 G3 C8 C4 D5
= D4

**Comment by jkiliani** [comment]
Please look if https://github.com/gcp/leela-zero/issues/864 answers your question.

**Comment by jun63cn** [comment]
I  choosed Release x64 build not debug build .

**Comment by gcp** [comment]
The project file for MSVC2015 is missing various defines, compare:
https://github.com/gcp/leela-zero/blob/47ddf38327b80ec5f2303344d1d9c65e25f5a3fb/msvc/VS2017/leela-zero.vcxproj#L194

which is missing in the MSVC2015 dir.

**Comment by sethtroisi** [comment]
closing, no active discussion for >1 year with subsequent issues and PRs
