### ISSUE TITLE
Why Leela Zero Can 't recognize SGF?

### ISSUE THREAD

**Issue by cngoodboy** [leela-zero/leela-zero#869]
I downloaded about 32k personal checkers and wanted to train a human network of 10blocks 192filters. But when I decided to convert to a training file after merging these chess pieces into one, there was a problem:
Then I saw that Leela suggested that only 65 cheats were found without any error messages (the combined chess size was checked). This should be how to solve?

**Comment by wpstmxhs** [comment]
How did you merge all game records into single SGF file?

**Comment by samecos** [comment]
@wpstmxhs   'chess'  ='a board game of strategic skill for two players' .You can say 'WeiQi' instead of 'Game of Go'. Also,learn a  Chinese words by the way.

**Comment by sethtroisi** [comment]
closing, no active discussion for ~1 year with subsequent discussion on other issues
