### ISSUE TITLE
Extremely strong network we accidentally trained

### ISSUE THREAD

**Issue by featurecat** [leela-zero/leela-zero#871]
My friend and I wanted to train a 1d level bot. So we obtained 1.3 million 1d go games (https://github.com/CamWagner/go-dataset). And we trained on them for 3.7 million steps.

Well, we were very surprised that this network is not 1d. It won 34 out of 50 games (68%) against the current best net 5ac1d898! You can check its games on KGS: LzEvalA is 5ac1d898, LzEvalB is our "1d" network.

I am wondering, how is this possible? We only trained on the 1d dataset. The download link is below. Side question: does anyone have any ideas on how to train a 1d network? Haha.

[leelaz-model-3680000.txt](https://github.com/gcp/leela-zero/files/1724645/leelaz-model-3680000.txt)
(edit, corrected the number of wins from 42 to 34. I had the wrong regex.)

**Comment by Eddh** [comment]
The best network is trained on games by the equivalent of a 5D player who don't know ladder, using troll opening, and who is so drunk he should be in a coma.

**Comment by odeint** [comment]
Very strange, since the "HumanBest" networks were usually quite a lot weaker than a somewhat saturated self-taught network of the same size. Pretty amazing that you 6x128 is so good! You're absolutely positive that the binaries (master vs next & several tuned versions) and settings (visits, pondering, etc) are the same for both weights tested?

**Comment by gcp** [comment]
>Anyway, I'm no expert, but there is not only the NN but the tree search in the algorithm. So the NN might be around 1 dan, and the tree search makes it stronger.

That is correct. If you want to have it play at 1 dan level, use --playouts 1.

**Comment by scott-stormer** [comment]
Really makes sense,  1d generally has  an ok sense of shape, and intuition about the important areas to play, but 1d reading is pretty bad.  So that network with more playouts would be like a hypothetical 1d who was much better at reading.

**Comment by jkiliani** [comment]
1 dan at 1 playout is probably stretching it a bit, 5-3 kyu sounds more reasonable. A fit can't be better than the data it fits to after all. You'll probably get the 1 dan level at some low number of playouts, in the 20-100 range. It's interesting that you get a network that's actually stronger than 5ac1 in this way, but maybe the training data has a very good distribution of play styles so the policy priors include all strong moves already and the playouts just have to find the right one?

**Comment by odinAuthor** [comment]
Even the original AG trained on the KGS dataset with a lot of weak dan games. Training on pro level games would lead to just learn correct shape, and no hint whatsoever what to do in unusual shapes, or how to punish overplays and bad moves.

**Comment by gcp** [comment]
(Also it's 7-8 against 5ac1here so not quite the lopsided result mentioned in the OP)

**Comment by CamWagner** [comment]
@gcp your comment made me want to recalculate my results. I used the wrong regex to calculate number of wins. This network won 34/50 games (68%), not 42/50. My bad! :)

**Comment by jthack** [comment]
Is it possible that training a network on the same games can yield different results? @gcp

**Comment by wctgit** [comment]
@jthack I'm pretty sure that training is performed not on whole games at a time, but on single board positions at a time, and these board positions are all randomly shuffled up (from multiple games) to eliminate bias that would be introduced if the training occurred largely on positions from the same game all at once or in a particular order. Therefore, yes, I believe that LZ's training system would produce different results, even starting from the same net and the same set of games. (It's possible that it is controlled with a random seed, however, I'm not sure. If that's the case, then if the same random seed is used, you might get the same results. But you'll have to wait for gcp's answer to know that for sure.)

**Comment by gcp** [comment]
>Is it possible that training a network on the same games can yield different results?

Look at zero.sjeng.org and hover your mouse over the network names.

**Comment by gcp** [comment]
And yes, even with the same amount of steps the shuffling is randomized and the seed is not deterministic.

**Comment by sethtroisi** [comment]
closing, no active discussion for >1 year with subsequent strong models
