### ISSUE TITLE
cuDNN backend?

### ISSUE THREAD

**Issue by Ttl** [leela-zero/leela-zero#875]
Apparently cuDNN licensing was changed some time ago and now the license allows redistributing the binaries and header files. [0] [1]

Is there any other issues with including it? It would be nice to use only OpenCL because cuDNN only runs on nvidia GPUs, but cuDNN should be at least twice as fast and it's hard for me to pass those kind of performance gains.

[0] http://docs.nvidia.com/deeplearning/sdk/cudnn-sla/index.html#distribution

[1] https://github.com/CDLuminate/nvidia-cudnn/issues/1

**Comment by WhiteHalmos** [comment]
This would be awesome!

**Comment by jjoshua2** [comment]
I don't mind signing up and downloading and installing additional binaries. In fact I already signed up. But I need binaries because I don't want to deal with compiling. Does anyone have a windows compile of the next branch?

**Comment by gcp** [comment]
The license is not compatible with Leela Zero's, so any binaries linked with cuDNN can't be legally redistributed.

You would still be able to add source-level support for cuDNN, and it's legal for people to use it on their own machine.

But seriously:

```
During the term of the AGREEMENT and for three (3) years thereafter, you will maintain all usual and proper books and records of account relating to the cuDNN Licensed Software and services provided under the AGREEMENT. During such period and upon written notice to you, NVIDIA or its authorized third party auditors subject to confidentiality obligations will have the right to inspect and audit your Enterprise books and records for the purpose of confirming compliance with the terms of the AGREEMENT.
```

IHMO including such a backend would just be inviting people to break *both* licenses.

**Comment by WhiteHalmos** [comment]
Wow, that's some terribly restraining clauses! :(

**Comment by jkiliani** [comment]
> Edit: And to make it more fun, the license requires you to snitch on anyone who does.

You mean this, right?

```You are responsible for the compliance with the terms and conditions of the AGREEMENT by your Enterprise and Contractors. Any act or omission that, if committed by you, would constitute a breach of the AGREEMENT shall be deemed to constitute a breach of the AGREEMENT if committed by your Enterprise or Contractors. ```

**Comment by gcp** [comment]
No, this part:

``
 You agree to notify NVIDIA in writing of any known or suspected distribution or use of the cuDNN Licensed Software not in compliance with the terms of the AGREEMENT, and to enforce the terms of your agreements with respect to cuDNN Licensed Software you distributed. 
``

**Comment by Ttl** [comment]
Doesn't the license allow dynamic linking to the library and distributing the so/dll file with the program or is the problem with the GPL? AQ distributes cuDNN like that.

I understand though that you don't want to agree to the license because of the other clauses. Is there any issues with compiling against the cuDNN, but requiring the user to drop the so/dll in the leelaz folder?

**Comment by alreadydone** [comment]
I guess it wouldn't be a problem for me to compile and run a cuDNN-enabled version on Big Red II anyway? It already has CUDA/cuDNN 7.5 installed.

**Comment by gcp** [comment]
>Doesn't the license allow dynamic linking to the library and distributing the so/dll file with the program or is the problem with the GPL?

It's both not allowed by the GPL and subject to the above-mentioned limitations: ```The above distributions are subject to the following: ... 3. you must enter into enforceable agreements that pass down terms consistent with the terms set forth in the AGREEMENT"```

>Is there any issues with compiling against the cuDNN, but requiring the user to drop the so/dll in the leelaz folder?

You can't do that without using the .h headers.

**Comment by alreadydone** [comment]
don't completely get the point of this research but it looks relevant: https://research.fb.com/announcing-tensor-comprehensions/

**Comment by Ttl** [comment]
I added cuDNN support but it looks like it's slightly slower than the OpenCL implementation:

```
cuDNN:
 1600 evaluations in  1.84 seconds -> 870 n/s

openCL:
 1600 evaluations in  1.70 seconds -> 942 n/s
```

Tensorflow manages to compute 1100 positions/s with batch size of 1 on my computer and it calculates gradients too so it should be faster than that. However I don't see any obvious issues with the code. 

Code can be found at: https://github.com/Ttl/leela-zero/tree/cudnn

**Comment by gcp** [comment]
What algorithm is it selecting?

**Comment by Ttl** [comment]
Fused Winograd. I tried manually other algorithms and the performed even worse.

**Comment by alreadydone** [comment]
Thank you for your work! However I got some error when compiling (I merged cuDNN support into [this branch](https://github.com/alreadydone/lz/tree/cudnn):

<details>

```
......
CC -I/N/soft/cle5/cuDNN/cudnn-7.5/cuda/include -I. -I/N/u/xu56/BigRed2/openblas/include -I/N/u/xu56/BigRed2 -Wall -Wextra -pipe -O3 -g -ffast-math -flto -march=native -std=c++14 -DNDEBUG -MD -MP -c -o Tuner.o Tuner.cpp
CC -I/N/soft/cle5/cuDNN/cudnn-7.5/cuda/include -I. -I/N/u/xu56/BigRed2/openblas/include -I/N/u/xu56/BigRed2 -Wall -Wextra -pipe -O3 -g -ffast-math -flto -march=native -std=c++14 -DNDEBUG -MD -MP -c -o CuDNN.o CuDNN.cpp
CuDNN.cpp: In member function 'void CuDNN::convolveActivation(net_t*, net_t*, net_t*, net_t*, net_t*, net_t*, size_t, const conv_descriptor&)':
CuDNN.cpp:236:16: error: 'cudnnConvolutionBiasActivationForward' was not declared in this scope
       bufferOut));
                ^
CuDNN.cpp:46:29: note: in definition of macro 'checkCUDNN'
     cudnnStatus_t status = (expression);                     \
                             ^
CuDNN.cpp: In member function 'size_t CuDNN::convolve_init(int, int, int, conv_descriptor&)':
CuDNN.cpp:301:47: error: too many arguments to function 'cudnnStatus_t cudnnSetConvolution2dDescriptor(cudnnConvolutionDescriptor_t, int, int, int, int, int, int, cudnnConvolutionMode_t)'
               /*computeType=*/CUDNN_DATA_FLOAT));
                                               ^
CuDNN.cpp:46:29: note: in definition of macro 'checkCUDNN'
     cudnnStatus_t status = (expression);                     \
                             ^
In file included from CuDNN.h:28:0,
                 from CuDNN.cpp:40:
/N/soft/cle5/cuDNN/cudnn-7.5/cuda/include/cudnn.h:363:27: note: declared here
 cudnnStatus_t CUDNNWINAPI cudnnSetConvolution2dDescriptor(
                           ^
make[1]: *** [CuDNN.o] Error 1
make[1]: Leaving directory `/N/dc2/scratch/xu56/lz12/cudnn/src'
make: *** [default] Error 2
```
</details>

**Comment by Ttl** [comment]
It looks like you are using older version of cuDNN. It should be at least version 6.

You can see the version you are using in top of cudnn.h header file in "/N/soft/cle5/cuDNN/cudnn-7.5/cuda/include/cudnn.h".

**Comment by alreadydone** [comment]
Thanks! The cuDNN on BRII was indeed v5.1 for CUDA 7.5:
#define CUDNN_MAJOR      5
#define CUDNN_MINOR      1
I've now downloaded v6.0 and compilation was successful. However the speed is 623 n/s (cuDNN) vs. 1994 n/s (OpenCL). The tuner doesn't work for cuDNN, right? 
A strange thing is that when I run autogtp, the board from leelaz is displayed and no games are played.

**Comment by gcp** [comment]
>The tuner doesn't work for cuDNN, right?

cuDNN (which relies on cuBLAS) has detailed knowledge of all NVIDIA cards - the tuning is already baked in.

**Comment by Ttl** [comment]
autogtp doesn't work because it tries to run the tuner. leelaz is supposed to quit after the tuning is complete, but cuDNN version doesn't handle "--tune-only" flag correctly.

**Comment by sethtroisi** [comment]
closing, no active discussion for ~1 year with subsequent issues and PRs
