### ISSUE TITLE
a question about training games and elo

### ISSUE THREAD

**Issue by l1t1** [leela-zero/leela-zero#879]
we can see a red fail flag above the blue curve, is it mean that we could get higher eol if accept that nrtwork?

**Comment by l1t1** [comment]
at the x 24000k games

**Comment by odeint** [comment]
6x128 is still improving, so no end-of-life yet. Real EOL will be at 20x256, or possibly 40x256 if we go full AlphaGo Zero.

**Comment by wctgit** [comment]
I think he means Elo, not eol.

**Comment by OmnipotentEntity** [comment]
The red flag is because that particular network actually had an unlucky string of games at the beginning and failed the "early stop" criterion.  However, after it failed, winning games trickled in and reactivated it, and it eventually became the new champion.

**Comment by luigio** [comment]
So is the AlphaZero approach of always using the latest network for training not being used yet?

**Comment by Dorus** [comment]
No, the planning is to first run 6x128 till it stops progressing (for 200k games?), then drop the learning rate.

Only after that, the AZ approuch will be tried.

This is all documented in the other issue about this.

Re: red flag: We play 400 games max, at 400 games to be certain the new network is actually an improvement, you need 220 wins (55%). To have the same certainty at 53% win, you need over 1000 games. We had to draw a line somewhere, if we run all new nets to we are certain they are less than 50% or over 50%, some of them might need thousands of games. At that point it's better to just run a few thousand new self play games, train a new network, and let that one promote at over 55% instead.

**Comment by luigio** [comment]
> No, the planning is to first run 6x128 till it stops progressing (for 200k games?), then drop the learning rate.
>
> Only after that, the AZ approach will be tried.
>
> This is all documented in the other issue about this.

Thanks. Which issue are you referring to? I'm browsing by name but nothing seems related to this.

**Comment by jkiliani** [comment]
> Thanks. Which issue are you referring to? I'm browsing by name but nothing seems related to this.

https://github.com/gcp/leela-zero/issues/591

**Comment by sethtroisi** [comment]
closing, no active discussion for ~1 year with subsequent issues and PRs
