### ISSUE TITLE
Performance boost from latest release 0.12

### ISSUE THREAD

**Issue by wctgit** [leela-zero/leela-zero#892]
Just upgraded to the latest release recently. Game moves used to take about 7000-7500 ms/move and now take 5340 ms/move: roughly 25-30% decrease in time/move, or inversely, 30-40% increase in speed. Just thought I'd offer that little data point. What kinds of performance improvements is everyone else getting? Are there any results known from the server side of things, like overall increase in #games/client/time? Average boost in performance per client? Etc.?

Also, does the FPU change mean that the same nets are now playing stronger moves overall, hence producing better quality training games?

**Comment by bjiyxo** [comment]
Can you post your computer configuration? 7000-7500 is awesome!

**Comment by wctgit** [comment]
Is it? That's basically 7 to 7.5 seconds per move. Now down to about 5 s/move. I'm guessing that's average or maybe even worse than average, since it's a run of the mill laptop.

<details>
<summary>Abbreviated first game run specs</summary>

```
AutoGTP v14
Using 1 thread(s) for GPU(s).
Starting tuning process, please wait...
Net filename: 0fb68ccfbc643947bcac23c0aad4b9e43cfaa84cc01fe5da85ce06e843fabec5
net: 0fb68ccfbc643947bcac23c0aad4b9e43cfaa84cc01fe5da85ce06e843fabec5.
./leelaz --tune-only -w 0fb68ccfbc643947bcac23c0aad4b9e43cfaa84cc01fe5da85ce06e843fabec5
Using 2 thread(s).
RNG seed: 10601305187162615856
Detecting residual layers...v1...128 channels...6 blocks.
Initializing OpenCL.
Detected 2 OpenCL platforms.
Platform version: OpenCL 1.2 CUDA 8.0.0
Platform profile: FULL_PROFILE
Platform name:    NVIDIA CUDA
Platform vendor:  NVIDIA Corporation
Device ID:     0
Device name:   GeForce 940MX
Device type:   GPU
Device vendor: NVIDIA Corporation
Device driver: 376.54
Device speed:  860 MHz
Device cores:  4 CU
Device score:  1112
Platform version: OpenCL 2.1
Platform profile: FULL_PROFILE
Platform name:    Intel(R) OpenCL
Platform vendor:  Intel(R) Corporation
Device ID:     1
Device name:   Intel(R) HD Graphics 620
Device type:   GPU
Device vendor: Intel(R) Corporation
Device driver: 21.20.16.4534
Device speed:  1000 MHz
Device cores:  24 CU
Device score:  621
Device ID:     2
Device name:   Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
Device type:   CPU
Device vendor: Intel(R) Corporation
Device driver: 6.6.0.359
Device speed:  2500 MHz
Device cores:  4 CU
Device score:  521
Selected platform: NVIDIA CUDA
Selected device: GeForce 940MX
with OpenCL 1.2 capability.

Started OpenCL SGEMM tuner.
Will try 578 valid configurations.
...
Tuning process finished
Starting thread 1 on GPU 0
{
    "cmd": "selfplay",
    "hash": "0fb68ccfbc643947bcac23c0aad4b9e43cfaa84cc01fe5da85ce06e843fabec5",
    "leelaz_version": "0.10",
    "options": {
        "noise": "true",
        "playouts": "1600",
        "randomcnt": "30",
        "resignation_percent": "0"
    },
    "options_hash": "cf1fad",
    "random_seed": "11905756602153114965",
    "required_client_version": "11"
}

Got new job: selfplay
net: 0fb68ccfbc643947bcac23c0aad4b9e43cfaa84cc01fe5da85ce06e843fabec5.
Engine has started.
Infinite thinking time set.
1 (B D17) ... 308 (W pass) 309 (B pass) Game has ended.
Score: W+4.5
Winner: white
```

Uploading game: 3907f5be444e44fd8461cd5f56cc8d9b.sgf for network 0fb68ccfbc643947bcac23c0aad4b9e43cfaa84cc01fe5da85ce06e843fabec5
Game data 48f50d8b51f64b23a4b63d0599a0d8cf0c34e7d28aa4206bcf7936b07f31db52 stored in database
1 game(s) (1 self played and 0 matches) played in 27 minutes = 1638 seconds/game, **5300 ms/move**, last game took 1636 seconds.
</details>

**Comment by Ka-zam** [comment]
I'm getting something similar and then a further 30% going to Linux as compared to the pre-built Windows binaries.

I still have a project to rebuild OpenBLAS on Linux and see if that makes a difference on my Ryzen 1700 system.

**Comment by Dorus** [comment]
yeah, i had similar gains, from 3250 to 2350 ms/move, so about 30-40% faster.

**Comment by jonlave** [comment]
Since updating from last night, this is the latest stats for me:

267 game(s) (238 self played and 29 matches) played in 961 minutes = 216 seconds/game, 719 ms/move, last game took 422 seconds.

Before:
It was closer to 1130 ms/move = 36.4 % time improvement

Over the weekend, I had built next branch from source and was getting 630 ms/move, so I may try that again for better performance.

autogp -g 2

Machine:
CPU: Ryzen 1800X 3.6 GHz
GPU: Geforce GTX 1080 Ti

**Comment by gcp** [comment]
>Also, does the FPU change mean that the same nets are now playing stronger moves overall, hence producing better quality training games?

Yes.

**Comment by wctgit** [comment]
Okay, thx for that info.

**Comment by sethtroisi** [comment]
closing, no active discussion for ~1 year
