### ISSUE TITLE
what is the purpose of .vs directory in leela-zero-0.12-win64.zip file?

### ISSUE THREAD

**Issue by l1t1** [leela-zero/leela-zero#902]
It seems a directory of visual studio, but there is only one file in it.

**Comment by wctgit** [comment]
I'm guessing it's a VisualStudio version control folder, perhaps accidentally not ignored.

**Comment by gcp** [comment]
Yes, bit surprised how that got there.

**Comment by l1t1** [comment]
so I can delete it safely.

**Comment by gcp** [comment]
Yes.
