### ISSUE TITLE
Slack/Mattermost channels for informal discussions

### ISSUE THREAD

**Issue by arnaudgo** [leela-zero/leela-zero#913]
Hello,

What about opening Slack or Mattermost channels (-users,-dev,...) for informal discussions about LZ ?

Arnaud

**Comment by arnaudgo** [comment]
This would be a way to get notified of a new release, a new promoted network, a new match..
This also can be a good way to improve feedback loop.
And of course, it can be for support, for technical exchange, or whatever.

**Comment by OmnipotentEntity** [comment]
Well, I've set up a discord server, if anyone wants to use it. https://discord.gg/cA2dekV

**Comment by arnaudgo** [comment]
Great! I will join :)
