### ISSUE TITLE
A 9x9 version of leela-zero

### ISSUE THREAD

**Issue by ihavnoid** [leela-zero/leela-zero#926]
In case there are people interested, I created a 9x9 fork of leela-zero:

https://github.com/ihavnoid/leelaz-ninenine

The goal is to try and study ideas without having to buy/hire thousands of servers.  As a learning experience, I am trying to create a superhuman 9x9 network only using my PC with two GPUs. Both self-play and training are done in a single machine.

**Comment by jkiliani** [comment]
Is this similar to @Alderi-Tokori's 9x9 fork? What you're doing sounds very similar to his project...

**Comment by ihavnoid** [comment]
Interesting... Never knew there was another fork :)

**Comment by jkiliani** [comment]
Actually he did make his code available, just not as a branch, in https://github.com/gcp/leela-zero/issues/863. Also, he reports a lot of his methods and results, so this might interest you.

**Comment by Alderi-Tokori** [comment]
@ihavnoid Hey that's great, yup I've also been working on a 9x9 experiment for a while, but have been too lazy to actually do a fork / make a PR. As @jkiliani said, I've detailed a lot of my choices in the linked thread, and I'm currently backtracking to compare the rate of progression of the network with and without FPU reduction.

One thing to mention though, apparently my net getting up to 9d at that time was actually probably a fluke (a 7d that was actually not that good lost a few ranked against it and pushed it to 9d), at the time (and that is stil pretty much the case), it was more probably a strong 7d ~ weak 8d.

Regardless, the main difference between my experiment and Leelaz/AGZ is the fact I'm only using the latest net's games to train a new net instead of using a fixed-size window, so if you're planning on following their method to the letter, it will be interesting to compare the rate of progression and plateaus of both methods.

**Comment by roy7** [comment]
It'd be nice if @Alderi-Tokori could get all of his 9x9 custom stuff merged and based on using a config setting, so you and others interested in 9x9 can be on same code base as everyone else. ;)

**Comment by Alderi-Tokori** [comment]
@roy7 Actually doing that right now, it will be ready in an hour or two

**Comment by Alderi-Tokori** [comment]
Done! https://github.com/gcp/leela-zero/pull/928

**Comment by ThomasCabaret** [comment]
@Alderi-Tokori Hi, I am interested by the whole training framework you design/setup for your 9x9 version. (anything you did automatized to monitor etc...)
For the record I have compiled this years ago:
http://www.goproblems.com/12825?psetid=12759999
It more or less the "full perfect game tree solution" for go on 7x7. (for which the mathematical komi is 9)
It may be interesting to see how close to this a self trained network goes (and not that much long I guess given the really small board size). 
It can also give two points in the curve "game required for top level  by  board size"

**Comment by Alderi-Tokori** [comment]
Hi @ThomasCabaret , sorry to disappoint you, but I haven't automated anything, I basically manually run a training session once per day when I have more than 25~30k games generated, and promote the created net if it wins its match against the current best. I agree that for 7x7 it should be relatively fast to get a good result, but it's still going to take at least a month to get a top level net.

**Comment by ihavnoid** [comment]
I have been running the whole flow automated for the last 10 days.  Involving my desktop PC and a Google cloud GPU instance (K80) whenever preemptive instances are available.  The first couple of days were a disaster - there was a bug in my code which dumped the data incorrectly (winner recorded as losing, loser recorded as winner) and hence nothing was making proper progress.

Once that was fixed and everything was re-started, I got a sort of reasonably-playing 128x10 network in a week.

One tweak I made was that I took a slightly different approach of generating training data.  The thing is that learning early moves rely on a sensible late-move judgement. Without a good late-move evaluation, the good early move will not get rewarded and the bad move will not get punished on the training data.  Hence, I skipped the first N moves (N is a random number from 0 to 80) and then collected the endgame only.  The skipped moves were only played with very few playouts (10~30 randomly) to speed up the selfplay.  All other moves were tested with 400 playouts (picked 400 because the board is... roughly 1/4).

As the endgame nets got reasonable, I reduced the range of skips to 0~60, 0~40, 0~20, and then no skip at all.  Same for resign percent - initially there is no point having a nonzero resignation percent as the net doesn't understand the concept of winning and losing.  Initially started with zero resignation, and as the net learns more, I started increasing the resignation percent randomly.

I didn't evaluate the nets to see which one to use for data generation - the latest net is always being used.  Training is done using the latest 25k self-play games - the 25k window is an automated moving window where new data is added and old data is thrown out periodically.

Once I get a reasonable net, I am going to restart and experiment what can accelerate training - e.g., training other types of NN outputs (e.g., whether a stone was alive or dead eventually) or other NN architecture tweaks if possible.  It's just for learning new things so I won't really bound myself to particular ideas. :)

**Comment by barrtgt** [comment]
If you can't think of anything to try, window sizes and their affects might be worth investigating.

**Comment by sethtroisi** [comment]
closing older issue with no active discussion

**Comment by albertcity** [comment]
> Done! #928

@Alderi-Tokori Hello! I am looking for a pretrained 9x9 model, and it will be used as baseline in our paper. Can I get any help from you? tks :)

**Comment by Alderi-Tokori** [comment]
Hi @albertcity, if you're looking for the strongest 9x9 net available *period*, then I think the latest kataGo net is the current strongest on 9x9 (it can play on any board size, actually). If you really want my 9x9 leelaz net, here is the latest one, it ranked around 22nd on CGOS at the time so it was still a bit far from the top: https://drive.google.com/drive/folders/1c7DvKOtdeLiyuDlU-wCu548oYPkc9GDX?usp=sharing (it's the leelaz-9x9-2018_07_14 file)

Bear in mind those are old models, I have no idea if they're still compatible with the current leelaz code, but if they're not, there is the src.rar archive with the old leelaz source code.

**Comment by albertcity** [comment]
@Alderi-Tokori Thanks a lot! I will look into kataGo, too. Thanks for your advice
