### ISSUE TITLE
a question about pause-resume

### ISSUE THREAD

**Issue by l1t1** [leela-zero/leela-zero#927]
I paused a game at last Sat, and resume it on this Mon, I found it runs successful.
but the weight file has changed, does it effect the training games as the game are mixed two weights?

**Comment by l1t1** [comment]
<pre>
D:\tool\leela12>autogtp -k sga
AutoGTP v14
Using 1 thread(s) for GPU(s).
Starting tuning process, please wait...
Net filename: 9ac646d7e0e237bc8ba77896fa97cc0b4fd8d71f6e9ee4daeb37008dd6ca0cff
net: 9ac646d7e0e237bc8ba77896fa97cc0b4fd8d71f6e9ee4daeb37008dd6ca0cff.
./leelaz --tune-only -w 9ac646d7e0e237bc8ba77896fa97cc0b4fd8d71f6e9ee4daeb37008dd6ca0cff
Using 2 thread(s).
RNG seed: 9977447250707900944
Detecting residual layers...v1...128 channels...6 blocks.
Initializing OpenCL.
Detected 1 OpenCL platforms.
Platform version: OpenCL 1.2 CUDA 8.0.0
Platform profile: FULL_PROFILE
Platform name:    NVIDIA CUDA
Platform vendor:  NVIDIA Corporation
Device ID:     0
Device name:   GeForce GT 730
Device type:   GPU
Device vendor: NVIDIA Corporation
Device driver: 376.62
Device speed:  901 MHz
Device cores:  2 CU
Device score:  1112
Selected platform: NVIDIA CUDA
Selected device: GeForce GT 730
with OpenCL 1.2 capability.
Loaded existing SGEMM tuning.
Tuning process finished
Starting thread 1 on GPU 0
Got previously stored file
Engine has started.
Infinite thinking time set.
Loading 47d7ed13406149bdb6b7ddb480437cb6.sgf
Loading 47d7ed13406149bdb6b7ddb480437cb6.train
195 (B N11) 196 (W O12) 197 (B O13) 198 (W P12) 199 (B L19) 200 (W S8) 201 (B E6) 202 (W N17) 203 (B T8) 204 (W S9) 205
(B E15) 206 (W C13) 207 (B C15) 208 (W M19) 209 (B D13) 210 (W A12) 211 (B B14) 212 (W O16) 213 (B O15) 214 (W K19) 215
(B K18) 216 (W L18) 217 (B H15) 218 (W J13) 219 (B R2) 220 (W S2) 221 (B O2) 222 (W K13) 223 (B L13) 224 (W Q2) 225 (B K
14) 226 (W H14) 227 (B J14) 228 (W H13) 229 (B J16) 230 (W E3) 231 (B F4) 232 (W J17) 233 (B H18) 234 (W Q19) 235 (B R19
)
</pre>

**Comment by l1t1** [comment]
Score: W+Resign
Winner: white
Uploading game: 5586a9ecc84d4657a1b9da52b7b9933c.sgf for network af9ce63c14d564dc43acc4affc3f8b86d25c29ffb1d10913f2a1ef5
63ed51804
Game data 5e42f6cc5800c46fcab5ea2f4bd8a25026ad8a96ac294523ca235c700b45df2b stored in database

**Comment by jkiliani** [comment]
When the best network changed when you resume a paused game, it will still finish that game first. Afterward, a new game will be started with the new best net.

**Comment by Dorus** [comment]
Tuning uses the current best, but the resumed game will use the old best. So i guess what happened is you got a new net for tuning, but the old net was used till the ongoing game was completed.

**Comment by jkiliani** [comment]
Hmm this sounds like it could potentially cause a crash when people resume a saved game at the time the network filters are changed during a bootstrap...

**Comment by marcocalignano** [comment]
@jkiliani why?

**Comment by jkiliani** [comment]
If the tuning is done for one number of filters at startup, but the game played using a different number, would that not cause instability?

**Comment by marcocalignano** [comment]
No leelaz check the tuning file at the moment the network is loaded adn if it does not find a value for the filter number in the network starts tuning again.
