### ISSUE TITLE
Appveyor build artifacts

### ISSUE THREAD

**Issue by jkiliani** [leela-zero/leela-zero#938]
Maybe this is a newbie question, but I noticed that while the Appveyor configuration on Leela Chess produces a Windows .exe file as a build artifact, in Leela Zero it isn't configured to do so. Is there a reason for this? I found it very convenient as a way to update from /next branch without a compilation environment on Windows.

**Comment by bood** [comment]
Yes, it is doable, main problem according to @gcp now is that the OpenBLAS on nuget is not the latest, possible solution is to compile a latest version and upload to github files.

I don't have a windows environment unfortunately. Some help can be used here.

**Comment by jpturcotte** [comment]
I see a lot of people asking about Windows binaries of pending PRs. I do not know about OpenBLAS, but is it still an issue? Because Appveyor artifacts would be very useful for testing.
