### ISSUE TITLE
a gui for leela zero

### ISSUE THREAD

**Issue by l1t1** [leela-zero/leela-zero#947]
https://github.com/CamWagner/lizzie
![screenshot](https://user-images.githubusercontent.com/23301704/36773738-157786e6-1c96-11e8-9c76-b01935149ae2.png)

**Comment by l1t1** [comment]
create a.bat file as D:\jre1.8.0_152\bin\java -jar lizzie.jar . leelaz.exe -w network

copy attachment & drop Postfix .zip to leelaz directory and rename the network file as "network"

then run a.bat
[Lizzie.jar.zip](https://github.com/gcp/leela-zero/files/1767053/Lizzie.jar.zip)

**Comment by kris-computer-go** [comment]
Works fine with 256x20 network by Antti Korhonen
https://drive.google.com/file/d/1PSyfsDvXmtIrhUx4Gf6x7mGzDtwe4npr

**Comment by tychota** [comment]
Would like the UNIX (mac / linux) version :)
Is this plan for it to support autogtp too (see https://github.com/fsparv/LeelaWatcher/blob/master/src/main/java/leelawatcher/parser/AutoGtpOutputParser.java).

**Comment by higherdim** [comment]
That's cool. Thanks!
