### ISSUE TITLE
Is it possible to use LIME with LeelaZ?

### ISSUE THREAD

**Issue by Hersmunch** [leela-zero/leela-zero#976]
From https://github.com/marcotcr/lime:
> This project is about explaining what machine learning classifiers (or models) are doing. At the moment, we support explaining individual predictions for text classifiers or classifiers that act on tables (numpy arrays of numerical or categorical data) or images, with a package called lime (short for local interpretable model-agnostic explanations). Lime is based on the work presented in [this paper](http://www.kdd.org/kdd2016/papers/files/rfp0573-ribeiroA.pdf) (bibtex here for citation).
> Lime is able to explain any black box classifier, with two or more classes. All we require is that the classifier implements a function that takes in raw text or a numpy array and outputs a probability for each class. Support for scikit-learn classifiers is built-in.

I'm wondering if something similar to the [example in the image tutorial](https://marcotcr.github.io/lime/tutorials/Tutorial%20-%20images.html) can be done for a board position, showing areas of the board or groups of stones (including from board history inputs) that support or don't support any  move (policy) and the predicted winner (value). In the example below it is shown to be "explaining prediction of 'Cat' in pros and cons":
![GitHub Logo](https://raw.githubusercontent.com/marcotcr/lime/master/doc/images/images.png)

Another way it might be useful is through reviewing explanations (see paper sections 6.2-6.4), looking to see whether particular inputs are useful/not useful or being used when they obviously shouldn't be. In our case, insight into how much of the history inputs are useful or whether they are being used unnecessarily. If we are to start another run of LZ then doing this beforehand (using networks of all strengths) might allow for evidence based optimisation, rather than trying several things blind.

Anyway, I'm not really set up or knowledgeable enough to give it a go myself but am willing to start learning if others suggest it might actually be worthwhile. Of course, if anyone thinks it is possible and  fancies giving it a go, please do!

**Comment by Kiv** [comment]
The author has a new algorithm out that is supposedly superior to LIME. I haven't tried it yet but it looks interesting:

https://github.com/marcotcr/anchor

**Comment by alreadydone** [comment]
something new: https://distill.pub/2018/building-blocks/

**Comment by Eddh** [comment]
lightvector seems to have something nice to analyze what NN are doing https://github.com/lightvector/GoNN

**Comment by bellau** [comment]
IMO, lime is not easily usable due to "History planes".

**Comment by Hersmunch** [comment]
Would you mind explaining why you think that?
I believe it would be possible to only present the current plane to LIME to analyse and handle how the history would be changed. However if that is done then it wouldn’t be able to help us understand whether the history planes are important or being “misused”.
I’m not sure what the effect would be of using or somehow not using impossible states but my guess is that using them should help LIME with its analysis.

My main concern is that I think it needs (all?) the data that was used to train the network. As far as I know we don’t record which positions were actually used out of all the logged data. Plus it’ll be huge and take a while for explaining just one input (based upon what is said about the example image above).

**Comment by sethtroisi** [comment]
closing, no active discussion for ~1 year with subsequent issues and PRs.

The Minigo team did a little work looking at activations.
