### ISSUE TITLE
UCTSearch Tree memory optimizations

### ISSUE THREAD

**Issue by sethtroisi** [leela-zero/leela-zero#980]
There have been several attempts to reduce the memory usage of the UCTSearch tree.
I'm not sure what the correct approach is anymore and wanted to vet the other developer's opinions.

At a high level there have been three approaches

1. **expandable** originally written by @ywrt (https://github.com/gcp/leela-zero/pull/574) and shepherded by @sethtroisi (https://github.com/gcp/leela-zero/pull/887)
2. **edges** written by @WhiteHalmos (https://github.com/gcp/leela-zero/pull/878)
3. **trimmed** suggested by @GCP (https://github.com/gcp/leela-zero/issues/956#issuecomment-369914185) and coded by @sethtroisi ([source](https://github.com/gcp/leela-zero/compare/next...sethtroisi:v__small_node_simple?expand=1))

All three approaches reduce memory usage (trimmed by ~80%, expandable by ~70%, edges by ~30%) but with some downsides (trimmed requires an occasional 2nd pass to re-add children, expandable is highly complex bug-prone, edges is only the smallest memory reduction) more on this latter.

I think I'd benefit (as well as everyone else) in defining what the goals are right now
1. Allowing deeper search (AKA much larger MAX_TREE_SIZE) for long time control games / analysis
2. Decreasing self-play client requirements
3. Ability to experiment with various UCT / MCTS ideas

---
**Description of the changes**

**expandable nodes**: Currently when a leaf node is expanded we create one child UCTNode (~60 bytes) for each legal child move (~250 average). **expandable** change store the children's data (6 bytes of move + score) in a vector until `uct_select_child` tries to select a child for play_simulation and then expands them on demand. The compact memory format is close to the max theoretical saving and strongly enables Goal 1 and 2. The cost here is the code is highly complex and will slow any future development and experimentation in UCTNode as well as possibly introducing race-conditions for multi-threaded search.

**edges**: Instead of expanding each child to a full UCTNode (~60 bytes) expand a partial data structure (~16 bytes) and only do the rest of the expansion on demand. This change is much less risky than expandable because expansion is more cleanly handled. The downside is the saving maybe isn't large enough to justify the change when the other options exist.

**trimmed**: Suggested by @GCP, this approach is based on the idea that after the first couple of moves we rarely expand anything but the top policy node so throw away the children that aren't likely to be explored. Initial testing shows savings upwards of 90% but comes with a small performance hit from re-evaluate the ~0.2% of nodes where scores were trimmed but are now needed. This change is the smallest amount of code and might add in Goal 3 of causing more metrics and research into the shape of the tree.

---
**Data**

See https://github.com/gcp/leela-zero/pull/887 for specific details

* 1M visits, 500K playouts with tree reuse (which would take ~3 minutes on a fast GPU) would be possible.
* On self-play clients, using 1600 playouts, memory usage would be reduced from 600 MB below 300MB

---
my opinion at this point

Goal 1 enables better bots and super powerful teaching tools, which is an important milestone in the future. My highest priority right now is to discover all the bugs in leela-zero and to not introduce more. Having worked on **expandable** idea for two weeks and discovered a handful of bugs I'm scared that I (or someone later) will break search in some non-obvious way.

I like **trimmed**, while it feels uglier to throw away data that might be needed in practice it's a HUGE memory saving and the amount of time required to re-calculate the trimmed nodes is tiny (<0.2% of nodes have to be reevaluated). In addition this comes with knobs that can be tuned and I like additional power user parameters.

I'm just now wondering if **edges** and **trimmed** could be combined but this will take another several days to code and test and I'd appreciate input from others before I spent another week on this.

**Comment by gcp** [comment]
One thing to consider is that it would be very nice to have an approach that scales. With this I mean that you can keep the program running and the moves will keep getting stronger, even if you have limited memory. This means at some point a GC pass is needed [1] that operates similarly to the trimmed proposal, and there's no way around needing a kind of re-expansion.

[1] This could have been avoided by storing the nodes in a TTable instead of a tree structure in the first place, but that might add a lot of complication too. A lot of the (SMP) code assumes the nodes can never change underneath it, which is more problematic in that approach. Also, this means a GC-pass must stop the SMP search, which isn't going to be nice either.

**Comment by gcp** [comment]
Looking at your "trimmed" implementation, the reliance on depth seems problematic to me, and maybe the source of some complexity. Would it not make more sense to trigger on visits?

You can calculate when the exploration term of an unvisited node with a P(s,a) <= than the current best would be higher than the current UCT value, and re-expand in that case.

This is obviously very wasteful early on, which is why I suggested postponing till MAX_TREE_SIZE / something.

**Comment by gcp** [comment]
>A lot of the (SMP) code assumes the nodes can never change underneath it, which is more problematic in that approach. 

To be fair, that's mostly a concern because we assume m_children never changes. In a TTable based approach, m_children is computed per thread, and not stored anywhere. (But the whole idea is a significant design change)

**Comment by gcp** [comment]
Braindumping a bit now, but including a "currently active CPUs in this tree" var in the nodes would allow on-line GC to work (wait, that's m_virtual_loss_count, right?), assuming uct_select_edge does not descend or iterate the children if it cannot obtain a node lock.

**Comment by WhiteHalmos** [comment]
Great summary! I agree with your sentiment that trimming is the definite winner in memory consumption, trading with a few re-expansions later isn't a big problem since vastly lower memory usage will already result in a slight speed gain, and if it's done near the memory limit it will only be better than stopping evaluations.

Personally I like your idea of using edges for a general memory gain and using trimming when we are near the memory limit.

A dynamic memory limit or node/edge limit (that could be a command line arg) would work better. That way we do not hamper those with more RAM and can support those with less RAM on 64-bit.

**Comment by marcocalignano** [comment]
I was wondering if was possible to write search that goes deep first.
So you have a parameter that tell the depth, each search sort the root children and expand the best one, sort the new expanded children and expand the best one, and so on till the max_depth is reached. The we go back a level and expand the second best. when the max_depth is reached, we go back again and again. If we tune max_depth properly we can expand few branches but with the wanted depth. and the we can trim the others.

**Comment by marcocalignano** [comment]
@sethtroisi you have to get the max_depth right to be able to go deeper in better branches but also be able to explore more branches in the thinking time.

**Comment by WhiteHalmos** [comment]
I feel that we should not depart too far from the way MCTS is run in published research papers. Tuning values that the papers aren't specified is one thing, while swapping out the algorithms is another entirely different proposition.

**Comment by WhiteHalmos** [comment]
Here is trimming with 0.001 threshold. I output the lowest best-child (returned by uct_select_child)'s policy which in this case was `0.00709`. I included estimated playouts here so you can see approx. when the min-best-policy actually drops.
```
make -j4 leelaz && ./leelaz -w w --benchmark -v100000 -s1
Thinking at most 2678400.0 seconds...                   
NN eval=0.518894            
0.23671 < 10000.00000       
0.16292 < 0.23671           
0.13855 < 0.16292           
0.10854 < 0.13855           
0.10021 < 0.10854           
0.08646 < 0.10021           
0.07800 < 0.08646           
0.07511 < 0.07800           
0.05457 < 0.07511           
0.05448 < 0.05457           
0.01292 < 0.05448           
Playouts: 8213, Win: 51.50%, PV: D4 R4 D16 C17 D17 C16 C15 B15 B14 C14 D15 B13 B16 A14 B17 C3 D3 C4 C5 B5 B6 C6 D5 B7 B4 A6 B3 O4 R17 Q17 R16                           
Playouts: 17160, Win: 51.52%, PV: D4 R4 D16 C17 D17 C16 C15 B15 B14 C14 D15 B13 B16 A14 B17 C3 D3 C4 C5 B5 B6 C6 D5 B7 B4 A6 B3 O4 R17 Q17 R16 R15 S15 S14 R14 Q15      
0.00748 < 0.01292
Playouts: 26765, Win: 51.53%, PV: D4 R4 D16 C17 D17 C16 C15 B15 B14 C14 D15 B13 B16 A14 B17 C3 D3 C4 C5 B5 B6 C6
 D5 B7 B4 A6 B3 O4 R17 Q17 R16 R15 S15 S14 R14 Q15 S13 S16 T14 S17                                              Playouts: 36368, Win: 51.53%, PV: D4 R4 D16 C17 D17 C16 C15 B15 B14 C14 D15 B13 B16 A14 B17 C3 D3 C4 C5 B5 B6 C6
 D5 B7 B4 A6 B3 O4 R17 Q17 R16 R15 S15 S14 R14 Q15 S13 S16 T14 S17 M3 D6 Q4 Q5                                  
Playouts: 46160, Win: 51.53%, PV: D4 R4 D16 C17 D17 C16 C15 B15 B14 C14 D15 B13 B16 A14 B17 C3 D3 C4 C5 B5 B6 C6
 D5 B7 B4 A6 B3 O4 R17 Q17 R16 R15 S15 S14 R14 Q15 S13 S16 T14 S17 M3 D6 Q4 Q5 Q3 R3                            Playouts: 56073, Win: 51.54%, PV: D4 R4 D16 C17 D17 C16 C15 B15 B14 C14 D15 B13 B16 A14 B17 C3 D3 C4 C5 B5 B6 C6
 D5 B7 B4 A6 B3 O4 R17 Q17 R16 R15 S15 S14 R14 Q15 S13 S16 T14 S17 M3 D6 Q4 Q5 Q3 R3 R2 R6                      Playouts: 65733, Win: 51.54%, PV: D4 R4 D16 C17 D17 C16 C15 B15 B14 C14 D15 B13 B16 A14 B17 C3 D3 C4 C5 B5 B6 C6
 D5 B7 B4 A6 B3 O4 R17 Q17 R16 R15 S15 S14 R14 Q15 S13 S16 T14 S17 M3 D6 Q4 Q5 Q3 R3 R2 R6 P2                   Playouts: 75405, Win: 51.54%, PV: D4 C3 C4 D3 E3 E2 F2 F3 E4 G2 D2 F1 C2 Q3 D16 C17 D17 C16 C15 B15 B14 C14 D15
B13 B16 A14 B17 Q6 R17 Q17 R16 R15 S15 S14 R14 Q15 S13 S16 T14 S17 K3 N3 G5 J4                                  Playouts: 84635, Win: 51.54%, PV: D4 C3 C4 D3 E3 E2 F2 F3 E4 G2 D2 F1 C2 Q3 D16 C17 D17 C16 C15 B15 B14 C14 D15
B13 B16 A14 B17 Q6 R17 Q17 R16 R15 S15 S14 R14 Q15 S13 S16 T14 S17 K3 N3 G5 J4                                  
0.00709 < 0.00748
Playouts: 93718, Win: 51.55%, PV: D4 C3 C4 D3 E3 E2 F2 F3 E4 G2 D2 F1 C2 Q3 D16 C17 D17 C16 C15 B15 B14 C14 D15 
B13 B16 A14 B17 Q6 R17 Q17 R16 R15 S15 S14 R14 Q15 S13 S16 T14 S17 K3 N3 G4 H3                                  
 
  D4 ->   21512 (V: 51.51%) (N: 23.67%) PV: D4 C3 C4 D3 E3 E2 F2 F3 E4 G2 D2 F1 C2 Q3 D16 C17 D17 C16 C15 B15 B14 C14 D15 B13 B16 A14 B17 Q6 R17 Q17 R16 R15 S15 S14 R14 Q15 S13 S16 T14 S17 K3 N3 G4 H3                        
  C4 ->   14061 (V: 51.60%) (N: 10.02%) PV: C4 R4 D16 C17 D17 C16 C15 B15 B14 C14 D15 B13 B16 A14 B17 E3 D6 O4 R17 Q17 R16 R15 S15 S14 R14 Q15 S13 S16 T14 S17 H3 L3 F4 C3 B3 B2 D3 C2 D4                                       
  D3 ->   12644 (V: 51.61%) (N:  8.65%) PV: D3 D17 Q4 R3 R4 Q3 P3 P2 O2 O3 P4 N2 Q2 O1 R2 C5 F4 D14 R17 R16 Q17 
P17 P18 O18 O17 P16 N18 Q18 O19 R18 C8 C11 D6 C3 C2 D4 B3 E3                                                    
 D16 ->   11514 (V: 51.48%) (N: 13.86%) PV: D16 D4 Q4 C17 C16 D17 E17 E18 F18 F17 E16 G18 D18 F19 C18 R3 R4 Q3 P3 P2 O2 O3 P4 N2 Q2 O1 R2 O17 C3 D3 C4 C5 B5 B6 C6 D5 B7 B4 A6 B3 G15 J16 D6 C10 S15                            
  Q4 ->   10348 (V: 51.52%) (N: 10.85%) PV: Q4 D4 D16 C17 C16 D17 E17 E18 F18 F17 E16 G18 D18 F19 C18 R3 R4 Q3 P3 P2 O2 O3 P4 N2 Q2 O1 R2 O17 C3 D3 C4 C5 B5 B6 C6 D5 B7 B4 A6 B3 G15 J16 D6 C10 S15                            
 D17 ->   10195 (V: 51.59%) (N:  7.80%) PV: D17 C4 Q4 R3 Q3 R4 R5 S5 S6 R6 Q5 S7 S4 T6 S3 C15 F16 F4 R17 R16 Q17 P17 P18 O18 O17 P16 N18 Q18 O19 R18 O16 C12 H3 H17     
 C16 ->    7318 (V: 51.52%) (N:  7.51%) PV: C16 R4 D4 C3 D3 C4 C5 B5 B6 C6 D5 B7 B4 A6 B3 E17 D14 O4 R17 Q17 R16 R15 S15 S14 R14 Q15 S13 S16 T14 S17 M3 H17 Q4 Q5 Q3    
  R4 ->    5980 (V: 51.55%) (N:  5.45%) PV: R4 D17 D4 C3 C4 D3 E3 E2 F2 F3 E4 G2 D2 F1 C2 P3 Q6 D14 R17 R16 Q17 
P17 P18 O18 O17 P16 N18 Q18 O19 R18 C12 R8 D16 E16 C16 C17 B17 F17 B15 P7 P6 O7                                 
  Q3 ->    5888 (V: 51.55%) (N:  5.46%) PV: Q3 D17 D4 C3 C4 D3 E3 E2 F2 F3 E4 G2 D2 F1 C2 R5 O4 D14 R17 R16 Q17 
O17 P17 P16 O18 S17 S18 N18 O16 N17 S16 S15             
 R17 ->     539 (V: 51.18%) (N:  1.29%) PV: R17 Q17 R16 R15 S15 S14 R14 Q15 S13 S16 T14 S17 D4 D17 R4 C3 C4     
20.6 average depth, 54 max depth                        
81502 non leaf nodes, 1.23 average children              
100000 visits, 519002 nodes, 99999 playouts, 939 n/s
```
Here is the same without trimming.
```
make -j4 leelaz && ./leelaz -w w --benchmark -v100000 -s1
Thinking at most 2678400.0 seconds...                   
NN eval=0.518894            
0.23671 < 10000.00000       
0.16292 < 0.23671           
0.13855 < 0.16292           
0.10854 < 0.13855           
0.10021 < 0.10854           
0.08646 < 0.10021           
0.07800 < 0.08646           
0.07511 < 0.07800           
0.05457 < 0.07511           
0.05448 < 0.05457           
0.01292 < 0.05448           
Playouts: 7855, Win: 51.50%, PV: D4 R4 D16 C17 D17 C16 C15 B15 B14 C14 D15 B13 B16 A14 B17 C3 D3 C4 C5 B5 B6 C6 D5 B7 B4 A6 B3 O4 R17       
Playouts: 16242, Win: 51.52%, PV: D4 R4 D16 C17 D17 C16 C15 B15 B14 C14 D15 B13 B16 A14 B17 C3 D3 C4 C5 B5 B6 C6 D5 B7 B4 A6 B3 O4 R17 Q17 R16 R15 S15 S14 R14 Q15      
0.00748 < 0.01292
Playouts: 25143, Win: 51.53%, PV: D4 R4 D16 C17 D17 C16 C15 B15 B14 C14 D15 B13 B16 A14 B17 C3 D3 C4 C5 B5 B6 C6
 D5 B7 B4 A6 B3 O4 R17 Q17 R16 R15 S15 S14 R14 Q15 S13 S16                                                      Playouts: 34154, Win: 51.53%, PV: D4 R4 D16 C17 D17 C16 C15 B15 B14 C14 D15 B13 B16 A14 B17 C3 D3 C4 C5 B5 B6 C6
 D5 B7 B4 A6 B3 O4 R17 Q17 R16 R15 S15 S14 R14 Q15 S13 S16 T14 S17 M3 D6 Q4                                     Playouts: 43185, Win: 51.53%, PV: D4 R4 D16 C17 D17 C16 C15 B15 B14 C14 D15 B13 B16 A14 B17 C3 D3 C4 C5 B5 B6 C6
 D5 B7 B4 A6 B3 O4 R17 Q17 R16 R15 S15 S14 R14 Q15 S13 S16 T14 S17 M3 D6 Q4 Q5 Q3                               
Playouts: 52244, Win: 51.54%, PV: D4 R4 D16 C17 D17 C16 C15 B15 B14 C14 D15 B13 B16 A14 B17 C3 D3 C4 C5 B5 B6 C6
 D5 B7 B4 A6 B3 O4 R17 Q17 R16 R15 S15 S14 R14 Q15 S13 S16 T14 S17 M3 D6 Q4 Q5 Q3 R3 R2                         Playouts: 61236, Win: 51.54%, PV: D4 R4 D16 C17 D17 C16 C15 B15 B14 C14 D15 B13 B16 A14 B17 C3 D3 C4 C5 B5 B6 C6
 D5 B7 B4 A6 B3 O4 R17 Q17 R16 R15 S15 S14 R14 Q15 S13 S16 T14 S17 M3 D6 Q4 Q5 Q3 R3 R2 R6 P2                   Playouts: 70068, Win: 51.54%, PV: D4 C3 C4 D3 E3 E2 F2 F3 E4 G2 D2 F1 C2 Q3 D16 C17 D17 C16 C15 B15 B14 C14 D15 
B13 B16 A14 B17 Q6 R17 Q17 R16 R15 S15 S14 R14 Q15 S13 S16 T14 S17 K3 N3 G5 J4                                  Playouts: 78814, Win: 51.54%, PV: D4 C3 C4 D3 E3 E2 F2 F3 E4 G2 D2 F1 C2 Q3 D16 C17 D17 C16 C15 B15 B14 C14 D15
B13 B16 A14 B17 Q6 R17 Q17 R16 R15 S15 S14 R14 Q15 S13 S16 T14 S17 K3 N3 G5 J4                                  Playouts: 87399, Win: 51.55%, PV: D4 C3 C4 D3 E3 E2 F2 F3 E4 G2 D2 F1 C2 Q3 D16 C17 D17 C16 C15 B15 B14 C14 D15
B13 B16 A14 B17 Q6 R17 Q17 R16 R15 S15 S14 R14 Q15 S13 S16 T14 S17 K3 N3 G4 H3                                  
0.00709 < 0.00748
Playouts: 96361, Win: 51.55%, PV: D4 C3 C4 D3 E3 E2 F2 F3 E4 G2 D2 F1 C2 Q3 D16 C17 D17 C16 C15 B15 B14 C14 D15 
B13 B16 A14 B17 Q6 R17 Q17 R16 R15 S15 S14 R14 Q15 S13 S16 T14 S17 K3 N3 G4 H3                                  

  D4 ->   21512 (V: 51.51%) (N: 23.67%) PV: D4 C3 C4 D3 E3 E2 F2 F3 E4 G2 D2 F1 C2 Q3 D16 C17 D17 C16 C15 B15 B14 C14 D15 B13 B16 A14 B17 Q6 R17 Q17 R16 R15 S15 S14 R14 Q15 S13 S16 T14 S17 K3 N3 G4 H3                        
  C4 ->   14061 (V: 51.60%) (N: 10.02%) PV: C4 R4 D16 C17 D17 C16 C15 B15 B14 C14 D15 B13 B16 A14 B17 E3 D6 O4 R17 Q17 R16 R15 S15 S14 R14 Q15 S13 S16 T14 S17 H3 L3 F4 C3 B3 B2 D3 C2 D4                                       
  D3 ->   12644 (V: 51.61%) (N:  8.65%) PV: D3 D17 Q4 R3 R4 Q3 P3 P2 O2 O3 P4 N2 Q2 O1 R2 C5 F4 D14 R17 R16 Q17 
P17 P18 O18 O17 P16 N18 Q18 O19 R18 C8 C11 D6 C3 C2 D4 B3 E3                                                    
 D16 ->   11514 (V: 51.48%) (N: 13.86%) PV: D16 D4 Q4 C17 C16 D17 E17 E18 F18 F17 E16 G18 D18 F19 C18 R3 R4 Q3 P3 P2 O2 O3 P4 N2 Q2 O1 R2 O17 C3 D3 C4 C5 B5 B6 C6 D5 B7 B4 A6 B3 G15 J16 D6 C10 S15                            
  Q4 ->   10348 (V: 51.52%) (N: 10.85%) PV: Q4 D4 D16 C17 C16 D17 E17 E18 F18 F17 E16 G18 D18 F19 C18 R3 R4 Q3 P3 P2 O2 O3 P4 N2 Q2 O1 R2 O17 C3 D3 C4 C5 B5 B6 C6 D5 B7 B4 A6 B3 G15 J16 D6 C10 S15                            
 D17 ->   10195 (V: 51.59%) (N:  7.80%) PV: D17 C4 Q4 R3 Q3 R4 R5 S5 S6 R6 Q5 S7 S4 T6 S3 C15 F16 F4 R17 R16 Q17 P17 P18 O18 O17 P16 N18 Q18 O19 R18 O16 C12 H3 H17     
 C16 ->    7318 (V: 51.52%) (N:  7.51%) PV: C16 R4 D4 C3 D3 C4 C5 B5 B6 C6 D5 B7 B4 A6 B3 E17 D14 O4 R17 Q17 R16 R15 S15 S14 R14 Q15 S13 S16 T14 S17 M3 H17 Q4 Q5 Q3    
  R4 ->    5980 (V: 51.55%) (N:  5.45%) PV: R4 D17 D4 C3 C4 D3 E3 E2 F2 F3 E4 G2 D2 F1 C2 P3 Q6 D14 R17 R16 Q17 
P17 P18 O18 O17 P16 N18 Q18 O19 R18 C12 R8 D16 E16 C16 C17 B17 F17 B15 P7 P6 O7                                 
  Q3 ->    5888 (V: 51.55%) (N:  5.46%) PV: Q3 D17 D4 C3 C4 D3 E3 E2 F2 F3 E4 G2 D2 F1 C2 R5 O4 D14 R17 R16 Q17 
O17 P17 P16 O18 S17 S18 N18 O16 N17 S16 S15             
 R17 ->     539 (V: 51.18%) (N:  1.29%) PV: R17 Q17 R16 R15 S15 S14 R14 Q15 S13 S16 T14 S17 D4 D17 R4 C3 C4     
18.7 average depth, 54 max depth                        
81502 non leaf nodes, 1.23 average children              
100000 visits, 34342918 nodes, 99999 playouts, 871 n/s
```
This is a 7% performance increase by using 98.5% fewer nodes with the exact same output.

**Comment by WhiteHalmos** [comment]
With a random game (trimming off):
```
make -j4 leelaz && /usr/bin/time -v ./leelaz -w w -g -v3200 -d --noponder -r10 -m30 -n -p0 -s1 -t1
```
Lowest is: `0.00002 < 0.00003`
No randomness:
```
make -j4 leelaz && /usr/bin/time -v ./leelaz -w w -g -v3200 -d --noponder -r10 -m0 -p0 -s1 -t1
```
Lowest is: `0.0000553 < 0.0000687`

**Comment by WhiteHalmos** [comment]
Unfortunately lowest is `0.0000009 < 0.0000019` for no randomness, 32000 visits.
```
make -j4 leelaz && /usr/bin/time -v ./leelaz -w w -g -v32000 -d --noponder -r10 -m0 -p0 -s1 -t1
```

**Comment by gcp** [comment]
It seems the behavior of UCT actually makes it impossible to make a "safe" version with trimming unless re-expansion is added.

https://github.com/gcp/leela-zero/pull/1049#issuecomment-375293614

**Comment by gcp** [comment]
Test implementation of on-line trimming:

 #1076

**Comment by TFiFiE** [comment]
[Memory Bounded Monte Carlo Tree Search](https://aaai.org/ocs/index.php/AIIDE/AIIDE17/paper/view/15856)

**Comment by sethtroisi** [comment]
This was fixed in some pull that I weirdly can't find

also related: https://github.com/leela-zero/leela-zero/pull/1082

**Comment by alreadydone** [comment]
https://github.com/leela-zero/leela-zero/pull/1097

**Comment by sethtroisi** [comment]
thanks @alreadydone
