### ISSUE TITLE
Drop stored game while resuming if best network changed?

### ISSUE THREAD

**Issue by thynson** [leela-zero/leela-zero#987]
Just found one [game](http://zero.sjeng.org/view/ae3b8928995af4e7f60d9bcd556add325edc2fabd6434da7fca6a3ae2f79315c?viewer=wgo) uploaded just a few minutes ago, using weight 9ac646d7 which is very old.

**Comment by jgkwok** [comment]
Data is data. As long as it's appropriately labelled, it's probably better to keep it. I believe self-play games are the most expensive part of this project. Would be a shame to throw it away.
