### ISSUE TITLE
zero.sjeng.org - small suggestions

### ISSUE THREAD

**Issue by kris-computer-go** [leela-zero/leela-zero#999]
It would be nice if instead Original strength graph (Mostly obsolete) one could see a magnification of the last fraction of the main graph (like 10 times bigger for example with last 500.000 games)
Also on the table of Best Network Hashes one more column is needed: ELO ranking.
And please keep all the list of Best Network Hashes, not only last 100.

Just my wishes

**Comment by oni-link** [comment]
> It would be nice if instead Original strength graph (Mostly obsolete) one could see a magnification of the last fraction of the main graph (like 10 times bigger for example with last 500.000 games)

Try http://zero.sjeng.org/view/player/elotest.html

**Comment by alreadydone** [comment]
Good suggestions. The last one has been raised before (and working on?).
https://github.com/gcp/leela-zero/issues/412#issuecomment-367608695

2018年3月8日 12:45，"kris-computer-go" <notifications@github.com>写道：

**Comment by kris-computer-go** [comment]
@oni-link http://zero.sjeng.org/view/player/elotest.html
Yes thank you
However I think x-axis should be 5 or 10 times bigger (not every 100 ELO but every 10) to see more clearly

**Comment by oni-link** [comment]
> However I think x-axis should be 5 or 10 times bigger (not every 100 ELO but every 10) to see more clearly

Did you try and use the mouse wheel to zoom in?

**Comment by jkiliani** [comment]
Zooming with the mouse wheel works fine, the only difficulty I have with http://zero.sjeng.org/view/player/elotest.html is that the horizontal and vertical scales are hard linked, and it's not possible to change that proportionality.

**Comment by roy7** [comment]
By popular demand network list is now all networks not just the last 100.

**Comment by roy7** [comment]
http://zero.sjeng.org/static/elotest.html

I changed the default scale to something closer to current data and it looks okay atm. It's possible we could change that scale # on the fly with, say, total # of games so it'll always look right long-term.

I'm sure this can be done better, I'm not all that experienced with vega-lite, but here's all of the scale options. https://vega.github.io/vega-lite/docs/scale.html

**Comment by jkiliani** [comment]
The new scale is way better, thanks!

**Comment by gcp** [comment]
Note that there is an issue tracker for the server too! 

https://github.com/gcp/leela-zero-server/issues

**Comment by barrybecker4** [comment]
It would be nice to have an annotated vertical line at the places where a new network was introduced.

**Comment by roy7** [comment]
If someone has handy game counts for each block size I should be able to do that.

**Comment by sethtroisi** [comment]
This is done
